### ISSUE TITLE
Standby complains "Receive advertisement timeout" and keeps trying to become primary

### ISSUE THREAD

**Issue by geotransformer** [acassen/keepalived#2217] opened 2022-10-22 01:14 UTC
**Describe the bug**
1> Standby keepalived complains "Receive advertisement timeout" and tries to become primary. Looks like brain split.
2> Primary keepalived shows the following log
Wed Oct 19 00:20:36 2022: Track script chk_xxxx_healthy is already running, expect idle - skipping run

**To Reproduce**
Dont know what happened

Found the following discussion before
https://groups.io/g/keepalived-users/topic/master_instance_briefly_stops/75373214

**Expected behavior**

Complete switchover if there is any issue on primary keepalived side. 

**Keepalived version**
```
keepalived-2.0.20
```

**Distro (please complete the following information):**
 - Name: [Ubuntu]
 - Version: [18.04]
 - Architecture: [container]

**Details of any containerisation or hosted service (e.g. AWS)**
Docker & Kubernetes & Calico

**Configuration file:**
```
Node-1
vrrp_script chk_xxxx22_healthy {   
    script "/usr/local/bin/chk_xxxx22_healthy 2222 3333"
    interval 1       
    rise 1            
    fall 1           
    init_fail       
}
vrrp_instance xxxx22 {
    state BACKUP
    interface ens01
    virtual_router_id 253
    priority 99
    advert_int 1
   
    virtual_ipaddress {
               10.192.1.138/24 brd 10.192.1.255 dev ens01
               172.57.189.215/32 brd 172.57.189.215 dev ens02
               172.57.201.221/32 brd 172.57.201.221 dev ens03
    }
    track_script {
       chk_xxxx22_healthy
    }
    track_interface      
        ens05     
        ens04    
        ens03     
        ens02    
        ens01  
    }
}
```

**Notify and track scripts**
```
chk_xxxx22_healthy  script
   
#!/bin/bash
  
if [ -z "$1" ]
  then
    exit 1
fi

for var in "$@"
do
    </dev/tcp/127.0.0.1/$var
    if [ $? -ne 0 ]; then
     exit 1
    fi
done
```

**System Log entries**
```
Node-1 (priority 99):

===========Partial logs=============
**Mon Oct 10 22:03:18 2022: (xxxx22) Receive advertisement timeout**
Mon Oct 10 22:03:18 2022: (xxxx22) Entering MASTER STATE
Mon Oct 10 22:03:18 2022: (xxxx22) setting VIPs.
Mon Oct 10 22:03:18 2022: (xxxx22) Sending/queueing gratuitous ARPs on ens01 for 10.192.1.138
Mon Oct 10 22:03:18 2022: (xxxx22) Sending/queueing gratuitous ARPs on ens02 for 172.57.189.215
Mon Oct 10 22:03:18 2022: (xxxx22) Sending/queueing gratuitous ARPs on ens03 for 172.57.201.221
Mon Oct 10 22:03:18 2022: (xxxx22) Master received advert from 10.192.1.43 with higher priority 100, ours 99
Mon Oct 10 22:03:18 2022: (xxxx22) Entering BACKUP STATE
Mon Oct 10 22:03:18 2022: (xxxx22) removing VIPs.

Mon Oct 10 22:03:25 2022: (xxxx22) Receive advertisement timeout**
Mon Oct 10 22:03:25 2022: (xxxx22) Entering MASTER STATE
Mon Oct 10 22:03:25 2022: (xxxx22) setting VIPs.
Mon Oct 10 22:03:25 2022: (xxxx22) Sending/queueing gratuitous ARPs on ens01 for 10.192.1.138
Mon Oct 10 22:03:25 2022: (xxxx22) Sending/queueing gratuitous ARPs on ens02 for 172.57.189.215
Mon Oct 10 22:03:25 2022: (xxxx22) Sending/queueing gratuitous ARPs on ens03 for 172.57.201.221

**Mon Oct 10 22:03:25 2022: (yyyyy22) Receive advertisement timeout**
Mon Oct 10 22:03:25 2022: (yyyyy22) Entering MASTER STATE
Mon Oct 10 22:03:25 2022: (yyyyy22) setting VIPs.
Mon Oct 10 22:03:25 2022: (yyyyy22) Sending/queueing gratuitous ARPs on ens04 for 10.192.1.140
Mon Oct 10 22:03:25 2022: (yyyyy22) Sending/queueing gratuitous ARPs on ens05 for 10.211.219.181
Mon Oct 10 22:03:25 2022: (yyyyy22) Sending/queueing gratuitous ARPs on ens06 for 10.211.220.55


Node-2 (priority 100)

===========Partial logs=============
Mon Oct 10 22:03:18 2022: Track script chk_yyyyy22_healthy is already running, expect idle - skipping run
Mon Oct 10 22:03:18 2022: Track script chk_xxxx22_healthy is already running, expect idle - skipping run**
Mon Oct 10 22:03:18 2022: (xxxx22) Received advert from 10.192.1.42 with lower priority 99, ours 100, forcing new election
Mon Oct 10 22:03:18 2022: (xxxx22) Sending/queueing gratuitous ARPs on ens01 for 10.192.1.138
Mon Oct 10 22:03:18 2022: (xxxx22) Sending/queueing gratuitous ARPs on ens02 for 172.57.189.215
Mon Oct 10 22:03:18 2022: (xxxx22) Sending/queueing gratuitous ARPs on ens03 for 172.57.201.221
Mon Oct 10 22:03:26 2022: Track script chk_xxxx22_healthy is already running, expect idle - skipping run
Mon Oct 10 22:03:26 2022: (xxxx22) Received advert from 10.192.1.42 with lower priority 99, ours 100, forcing new election
Mon Oct 10 22:03:26 2022: (xxxx22) Sending/queueing gratuitous ARPs on ens01 for 10.192.1.138
Mon Oct 10 22:03:26 2022: (xxxx22) Sending/queueing gratuitous ARPs on ens02 for 172.57.189.215
Mon Oct 10 22:03:26 2022: (xxxx22) Sending/queueing gratuitous ARPs on ens03 for 172.57.201.221
Mon Oct 10 22:03:26 2022: (yyyyy22) Received advert from 10.192.1.42 with lower priority 99, ours 100, forcing new election
Mon Oct 10 22:03:26 2022: (yyyyy22) Sending/queueing gratuitous ARPs on ens04 for 10.192.1.140
Mon Oct 10 22:03:26 2022: (yyyyy22) Sending/queueing gratuitous ARPs on ens05 for 10.211.219.181
Mon Oct 10 22:03:26 2022: (yyyyy22) Sending/queueing gratuitous ARPs on ens06 for 10.211.220.55
Mon Oct 10 22:03:28 2022: (xxxx22) Sending/queueing gratuitous ARPs on ens01 for 10.192.1.138
Mon Oct 10 22:03:28 2022: (xxxx22) Sending/queueing gratuitous ARPs on ens02 for 172.57.189.215
Mon Oct 10 22:03:28 2022: (xxxx22) Sending/queueing gratuitous ARPs on ens03 for 172.57.201.221
Mon Oct 10 22:03:33 2022: (xxxx22) Sending/queueing gratuitous ARPs on ens01 for 10.192.1.138
Mon Oct 10 22:03:33 2022: (xxxx22) Sending/queueing gratuitous ARPs on ens02 for 172.57.189.215
Mon Oct 10 22:03:33 2022: (xxxx22) Sending/queueing gratuitous ARPs on ens03 for 172.57.201.221
```

**Did keepalived coredump?**
```
If so, can you please provide a stacktrace from the coredump, using gdb.
```

**Additional context**
There are about 8 VRRPs groups in keepalived container

**Comment by pqarmitage** [comment] 2022-10-22 10:12
Should the first line of the configuration be: `vrrp_script chk_xxxx22_healthy {`?

The groups.io discussion you link to above was caused by internal state information and stats (triggered by SIGUSR1 and SIGUSR2) being written to files, and those files being on slow storage, in that case network storage, and opening one of the files took some time, which blocked keepalived. This doesn't look like the cause of your problem.

What the message `Track script chk_xxxx22_healthy is already running, expect idle - skipping run` means is that the previous run of the script hasn't yet completed. Since that happened for chk_yyyyy22_healthy at the same time, and also Node-1 timed out receiving adverts, i.e. in your case it didn't receive an advert for 3 + (256 - 99)/256 seconds, it looks as though something happened on Node-2 that stopped processes running at that time.

There are configuration options that will allow you to increase the execution priority of keepalived (see the groups.io discussion for more information) that might help if some higher priority process was hogging the system, but otherwise it seems to be something happening in Node-2 that is stopping processes running.

**Comment by pqarmitage** [comment] 2022-12-09 13:40
Closing due to no update for over 6 weeks.

**Closed by pqarmitage** 2022-12-09 13:40 UTC

**Comment by nabiladoui** [comment] 2023-03-02 15:12
The same issue is observed in our setup as well.
node-2 (higher priority) suddenly stops sending adverts, prompting node-1 to go MASTER.
also the same track script behavior is observed :

Thu Mar  2 04:51:50 2023: Track script chk_seppims2_port is already running, expect idle - skipping run
Thu Mar  2 04:51:50 2023: Track script chk_nrfims2_port is already running, expect idle - skipping run
Thu Mar  2 04:35:15 2023: Track script chk_udpims2_port is already running, expect idle - skipping run
Thu Mar  2 04:35:15 2023: Track script chk_seppims2_port is already running, expect idle - skipping run
Thu Mar  2 04:20:15 2023: Track script chk_n4sxi21_port is already running, expect idle - skipping run
Thu Mar  2 04:20:14 2023: Track script chk_grvip29_port is already running, expect idle - skipping run

Does vrrp_script execution affect sending the advertisement ?

**Comment by cesarthr** [comment] 2023-05-22 15:36
Hello guys,
We're having the same issue too.

Any ideas?
At the mac address level we didn't find problems in the network that justify the timeout pointing by keepalived.

Server Master: ACCDDLPRFE001
IPv4 Address: 181.47.254.193
IPv6 Address: 2800:810:100:b::3
Priority: 100

Server Backup: ACCDDLPRFE002
IPv4 Address: 181.47.254.194
IPv6 Address: 2800:810:100:b::4
Priority: 99

IPV4 VIP 181.47.254.195
IPV6 VIP 2800:810:100:b::5
Advert_int 1

---

keepalived version
Keepalived v2.1.5 (07/13,2020)

---

Distro
- Name: Debian
- Version: 11.6
- Architecture: virtual machine

---

Details
VMware vCenter / VMware esxi 7.0.3, VMware-toolbox 11.2.5.26209 (build-17337674)

--------------------------
Configuration file Master:
--------------------------

global_defs {
   router_id ACCDDLPRFE001
   enable_script_security
}

vrrp_script chk_dnsdist {
  script "/usr/bin/pgrep dnsdist"
  interval 1
  weight 2
  rise 2
  fall 2
}

vrrp_instance VI_4 {
    interface eth0
    state MASTER
    virtual_router_id 37
    priority 100
    advert_int 1
    unicast_src_ip 181.47.254.193
    unicast_peer {
        181.47.254.194
    }

    authentication {
       auth_type PASS
       auth_pass MDkwNTgx
   }

    virtual_ipaddress {
        181.47.254.195/28 dev eth0
    }

    track_script {
        chk_dnsdist
    }
}

vrrp_instance VI_6 {
    interface eth0
    state MASTER
    virtual_router_id 31
    priority 100
    advert_int 1
    unicast_src_ip 2800:810:100:b::3
    unicast_peer {
        2800:810:100:b::4
    }

    virtual_ipaddress {
        2800:810:100:b::5/64 dev eth0
    }

    track_script {
        chk_dnsdist
    }
}

----------------------
backup logs:

May 22 11:04:19 ACCDDLPRFE002 systemd[1]: Started Keepalive Daemon (LVS and VRRP).
May 22 11:04:19 ACCDDLPRFE002 Keepalived_vrrp[1891189]: Assigned address 181.47.254.194 for interface eth0
May 22 11:04:19 ACCDDLPRFE002 Keepalived_vrrp[1891189]: Assigned address fe80::250:56ff:fea1:1a52 for interface eth0
May 22 11:04:19 ACCDDLPRFE002 Keepalived_vrrp[1891189]: Registering gratuitous ARP shared channel
May 22 11:04:19 ACCDDLPRFE002 Keepalived_vrrp[1891189]: Registering gratuitous NDISC shared channel
May 22 11:04:19 ACCDDLPRFE002 Keepalived_vrrp[1891189]: (VI_4) removing VIPs.
May 22 11:04:19 ACCDDLPRFE002 Keepalived_vrrp[1891189]: (VI_6) removing VIPs.
May 22 11:04:19 ACCDDLPRFE002 Keepalived_vrrp[1891189]: (VI_4) Entering BACKUP STATE (init)
May 22 11:04:19 ACCDDLPRFE002 Keepalived_vrrp[1891189]: (VI_6) Entering BACKUP STATE (init)
May 22 11:04:19 ACCDDLPRFE002 Keepalived_vrrp[1891189]: VRRP sockpool: [ifindex(  2), family(IPv4), proto(112), fd(13,14), unicast, address(181.47.254.194)]
May 22 11:04:19 ACCDDLPRFE002 Keepalived_vrrp[1891189]: VRRP sockpool: [ifindex(  2), family(IPv6), proto(112), fd(15,16), unicast, address(2800:810:100:b::4)]
May 22 11:04:19 ACCDDLPRFE002 Keepalived_vrrp[1891189]: VRRP_Script(chk_dnsdist) succeeded
May 22 11:04:19 ACCDDLPRFE002 Keepalived_vrrp[1891189]: (VI_4) Changing effective priority from 99 to 101
May 22 11:04:19 ACCDDLPRFE002 Keepalived_vrrp[1891189]: (VI_6) Changing effective priority from 99 to 101
May 22 11:04:23 ACCDDLPRFE002 Keepalived_vrrp[1891189]: (VI_4) Receive advertisement timeout
May 22 11:04:23 ACCDDLPRFE002 Keepalived_vrrp[1891189]: (VI_4) Entering MASTER STATE
May 22 11:04:23 ACCDDLPRFE002 Keepalived_vrrp[1891189]: (VI_4) setting VIPs.
May 22 11:04:23 ACCDDLPRFE002 Keepalived_vrrp[1891189]: (VI_4) Sending/queueing gratuitous ARPs on eth0 for 181.47.254.195
May 22 11:04:23 ACCDDLPRFE002 Keepalived_vrrp[1891189]: Sending gratuitous ARP on eth0 for 181.47.254.195
May 22 11:04:23 ACCDDLPRFE002 Keepalived_vrrp[1891189]: Sending gratuitous ARP on eth0 for 181.47.254.195
May 22 11:04:23 ACCDDLPRFE002 Keepalived_vrrp[1891189]: Sending gratuitous ARP on eth0 for 181.47.254.195
May 22 11:04:23 ACCDDLPRFE002 Keepalived_vrrp[1891189]: Sending gratuitous ARP on eth0 for 181.47.254.195
May 22 11:04:23 ACCDDLPRFE002 Keepalived_vrrp[1891189]: Sending gratuitous ARP on eth0 for 181.47.254.195

--------------
master logs:

May 22 11:08:08 ACCDDLPRFE001 Keepalived[2683141]: Starting Keepalived v2.1.5 (07/13,2020)
May 22 11:08:08 ACCDDLPRFE001 Keepalived_vrrp[2683142]: (VI_4) Entering BACKUP STATE (init)
May 22 11:08:08 ACCDDLPRFE001 Keepalived_vrrp[2683142]: (VI_6) Entering BACKUP STATE (init)
May 22 11:08:08 ACCDDLPRFE001 Keepalived_vrrp[2683142]: VRRP_Script(chk_dnsdist) succeeded
May 22 11:08:08 ACCDDLPRFE001 Keepalived_vrrp[2683142]: (VI_4) Changing effective priority from 100 to 102
May 22 11:08:08 ACCDDLPRFE001 Keepalived_vrrp[2683142]: (VI_6) Changing effective priority from 100 to 102
May 22 11:08:08 ACCDDLPRFE001 Keepalived[2683141]: Printing parent data for process(2683141) on signal
May 22 11:08:08 ACCDDLPRFE001 Keepalived_vrrp[2683142]: Printing VRRP stats for process(2683142) on signal
May 22 11:08:08 ACCDDLPRFE001 Keepalived_vrrp[2683142]: Printing VRRP data for process(2683142) on signal
May 22 11:08:08 ACCDDLPRFE001 Keepalived_vrrp[2683142]: (VI_6) received lower priority (101) advert from 2800:810:100:b::4 - discarding
May 22 11:08:09 ACCDDLPRFE001 Keepalived_vrrp[2683142]: (VI_6) received lower priority (101) advert from 2800:810:100:b::4 - discarding
May 22 11:08:10 ACCDDLPRFE001 Keepalived_vrrp[2683142]: (VI_6) received lower priority (101) advert from 2800:810:100:b::4 - discarding
May 22 11:08:11 ACCDDLPRFE001 Keepalived_vrrp[2683142]: (VI_6) received lower priority (101) advert from 2800:810:100:b::4 - discarding
May 22 11:08:11 ACCDDLPRFE001 Keepalived_vrrp[2683142]: (VI_4) Entering MASTER STATE
May 22 11:08:11 ACCDDLPRFE001 Keepalived_vrrp[2683142]: (VI_6) Entering MASTER STATE
May 22 11:08:11 ACCDDLPRFE001 Keepalived_vrrp[2683142]: (VI_6) using locally configured advertisement interval (1000 milli-sec)
May 22 11:08:13 ACCDDLPRFE001 Keepalived[2683141]: Printing parent data for process(2683141) on signal
May 22 11:08:13 ACCDDLPRFE001 Keepalived_vrrp[2683142]: Printing VRRP stats for process(2683142) on signal
May 22 11:08:13 ACCDDLPRFE001 Keepalived_vrrp[2683142]: Printing VRRP data for process(2683142) on signal
May 22 11:08:18 ACCDDLPRFE001 Keepalived[2683141]: Printing parent data for process(2683141) on signal
May 22 11:08:18 ACCDDLPRFE001 Keepalived_vrrp[2683142]: Printing VRRP data for process(2683142) on signal
May 22 11:08:18 ACCDDLPRFE001 Keepalived_vrrp[2683142]: Printing VRRP stats for process(2683142) on signal


Thank you
