### ISSUE TITLE
unable to ping the failover IP once it is moved from machine A to machine B

### ISSUE THREAD

**Issue by shettypriy** [acassen/keepalived#1768] opened 2020-10-30 07:01 UTC
I have configured two debian10 machines where I have installed haproxy and keepalived on each of the machines. Also, failover IP is configured on both the servers on the network interface. When I stop the haproxy service on machine A the failover IP is moved from machine A to machine B network interface. However, when I try to ping the failover IP which is moved to machine B from another machine , say machine C, there is no response. It says 'Unable to connect to remote host: Connection timed out' when a telnet is done. Also,I am unable to ping to that failover IP from other machine(machine C). Failover IPs of both the machines are whitelisted in UFW firewall. Could you anyone help me on this

**Comment by pqarmitage** [comment] 2020-10-30 09:24
This is a duplicate of #1769.

**Closed by pqarmitage** 2020-10-30 09:24 UTC
