### ISSUE TITLE
主备_master-master、master-backup

### ISSUE THREAD

**Issue by gxki** [acassen/keepalived#1398] opened 2019-09-30 08:24 UTC
### 版本
2.0.6
### 发生问题
配置keepalived.conf后，和网络成功案例配置的一样，出现浮点飘移失败情况
### 失败情况
主state  MASTER
备state  BACKUP
浮点IP飘移失败
### 成功情况
主state  MASTER
备state  MASTER
### 希望
恳请各位大牛可以给些指导，什么原因，谢谢

**Comment by pqarmitage** [comment] 2019-09-30 11:32
@gxki Unfortunately I cannot understand what is written above, and consequently have no idea what the issue is.

**Comment by pqarmitage** [comment] 2019-10-02 09:03
Using Google translate I get:

**Title**
Active and standby _master-master, master-backup

**Version**
2.0.6

**Problem**
After configuring keepalived.conf, as in the case of the network success story, floating-point drift failure occurs.

**Failure situation**

Main state MASTER
Prepare state BACKUP
Floating point IP drift failed

**Success**

Main state MASTER
Prepare state MASTER

**hope**

I ask you to give some guidance to the big cow, what reason, thank you

**Comment by pqarmitage** [comment] 2019-10-02 09:08
I am guessing that this question is about why both keepalived instances can be in master state.

The reason that two keepalived instances both end up in master state is that the lower priority instance is, for some reason, not receiving the adverts sent by the master instance. This could be due to the virtual router IDs not matching in the two configurations; the two systems using network interfaces that aren't in the same multicast domain; or more generally due to a network configuration/setup such that the lower priority system is not receiving the adverts sent by the higher priority system (this can often happen when using containers or in an AWS or other hosted environment).

**Comment by pqarmitage** [comment] 2019-10-09 08:42
Closing due to no update for over a week. @gxki if you are still having issues please update this issue report and we can re-open it if necessary.

**Closed by pqarmitage** 2019-10-09 08:42 UTC
Labels: Further information needed
