### ISSUE TITLE
systemd detection with option with-init=SYSV OpenWrt

### ISSUE THREAD

**Issue by ja-pa** [acassen/keepalived#1188] opened 2019-03-27 16:13 UTC
Hi,
I'm trying to cross compile keepalived version **2.0.14** for OpenWrt but it fails on systemd check (since OpenWrt) doesn't support that.

Since configuration option is set to --with-init = SYSV

I keep getting this "Error" from version **2.0.12.**
Version **2.0.10** is compiled on OpenWRT without a problem.
For reference, here is OpenWrt Makefile for keepalived with used configuration https://github.com/openwrt/packages/blob/master/net/keepalived/Makefile#L56
 

Build error (related to systemd )
```
configure: loading site script /home/cznic/data/src/openwrt_master_omnia/turris-build/build/include/site/arm
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-openwrt-linux-strip... arm-openwrt-linux-muslgnueabi-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking pkg-config is at least version 0.9.0... yes
Package systemd was not found in the pkg-config search path.
Perhaps you should add the directory containing `systemd.pc'
to the PKG_CONFIG_PATH environment variable
No package 'systemd' found
```

**Comment by pqarmitage** [comment] 2019-03-27 23:33
If appears to be `PKG_PROG_PKG_CONFIG` that is failing.

See https://askubuntu.com/questions/468661/how-to-fix-pkg-prog-pkg-config-command-not-found-error

Are you building from a tarball or from a clone from github? If you are using a tarball, it may be that the generated configure won't work on your system. Can you try cloning keepalived from github, then execute `./build_setup; configure --with-init=SYSV` and see if that works.

**Comment by pqarmitage** [comment] 2019-03-28 16:07
So that I can try and reproduce the problem, can you provide details of what distro and version you are attempting to build keepalived on.

Out of interest, why do you disable libipset? keepalived's use of iptables will be more efficient if ipsets are used. You might benefit from specifying `--disable-libipset-dynamic` though if you use ipsets.

Also, disabling libnl means that keepalived cannot use IPVS with IPv6. Is there a reason fir disabling libnl?

**Comment by BKPepe** [comment] 2019-03-29 12:58
CC: @feckert, who is the maintainer of keepalived in OpenWrt.

**Comment by feckert** [comment] 2019-03-29 13:04
I have added this to OpenWrt a view minutes ago
https://github.com/openwrt/packages/pull/8536

**Comment by BKPepe** [comment] 2019-03-29 13:06
I'm aware of it, but I thought it would be good to ping you about it. Because developers of keepalived are curious about other things, which in Makefile there are disabled libipset and so on. ;-)

**Comment by feckert** [comment] 2019-03-29 13:21
> Out of interest, why do you disable libipset? keepalived's use of iptables will be more efficient if ipsets are used. You might benefit from specifying --disable-libipset-dynamic though if you use ipsets.

Because in OpenWrt we updated libipset to a new version this was not compatible at that time to the old keepalived version 2.0.7 see https://github.com/openwrt/packages/commit/d33a4c492460e6b6b1de5a71a7f09c989ab44fdf#diff-8ada53a0982d851e47876a53b4cdd033
But I will do a build if this is now fixed.

> Also, disabling libnl means that keepalived cannot use IPVS with IPv6. Is there a reason fir disabling libnl?

The reason is that @stintel 
https://github.com/openwrt/packages/commit/ffa10121311d1dbeea6d7644df10a35ca903ffb6#diff-8ada53a0982d851e47876a53b4cdd033 die removed this because the build failed. What could we do to add this again so we get IPVS on IPv6.

**Comment by stintel** [comment] 2019-03-29 13:36
@feckert just add it as a hard dependency?

**Comment by pqarmitage** [comment] 2019-03-29 14:11
From [debian bug 884798](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884798) it appears that autotools is not cross-compile safe. I will need to investigate this further.

**Comment by pqarmitage** [comment] 2019-03-29 14:20
@feckert keepalived commit b7a98f92 added support for libipset version 7.

Regarding libnl, assuming it is version 3, keepalived wants libnl3, libnl-route-3 and libnl-genl-3.

**Comment by feckert** [comment] 2019-03-29 14:25
> @feckert keepalived commit b7a98f9 added support for libipset version 7.

thanks for feedback I have added this again and it works on my buildsystem I will update the PR on OpenWrt

**Comment by pqarmitage** [comment] 2019-03-29 16:13
@ja-pa I can now reproduce the Package systemd was not found ... problem. I will investigate further.

However, @feckert  has submitted [openwrt pull request 8536](https://github.com/openwrt/packages/pull/8536) which updates keepalived to 2.0.14 and successfully builds. I wonder what the difference is?

**Comment by feckert** [comment] 2019-03-29 16:50
I have to say as I know that I also had the problem at first. Then it s gone. Let me look at the next week If I have forgotten to push a patch that I have made to fix this.

**Comment by pqarmitage** [comment] 2019-03-29 17:13
@feckert I think it might relate to you having systemd.pc available in the pkg-config search path in the build environment whereas I haven't.

**Comment by feckert** [comment] 2019-03-29 17:16
I think this should only be evaluated if systemd init selected

**Comment by pqarmitage** [comment] 2019-03-29 17:27
@feckert I agree with your comment above. I'm working on a patch now.

**Comment by pqarmitage** [comment] 2019-03-30 13:35
Commit 393db4a resolves this issue.

The attached patch [001-fix-systemd.patch.gz](https://github.com/acassen/keepalived/files/3025489/001-fix-systemd.patch.gz) should be unzipped and placed in the feeds/packages/net/keepalived/patches directory (which will need to be created) of the openwrt tree until keepalived's next release.

**Closed by pqarmitage** 2019-03-30 13:35 UTC
