### ISSUE TITLE
vrrp child process hangs

### ISSUE THREAD

**Issue by gccli** [acassen/keepalived#1093] opened 2018-12-29 09:51 UTC
My check script like following, when the script timeout, make vrrp child process  hang

vrrp_script chk_service {
    script "/opt/csmp/bin/ha-check.py service"
    interval 6
    timeout 3
    fall 3
    rise 1
    user root
}

/var/log/message
Dec 29 16:50:29 xxxx-master Keepalived_vrrp[11745]: Child (PID 26108) failed to terminate after kill

![image](https://user-images.githubusercontent.com/5126626/50536658-a05b1d00-0b91-11e9-8fdd-a13f7b518097.png)

![image](https://user-images.githubusercontent.com/5126626/50536674-d0a2bb80-0b91-11e9-8f32-5bcbb66424c3.png)

**Comment by pqarmitage** [comment] 2018-12-29 11:58
@gccli Could you please provide the output of `keepalived -v`. I need to know exactly what version of the code you are running, since line 1250 in scheduler.c in the latest version of the code is a comment.

When the vrrp child process hangs, is it looping consuming CPU time, or is it doing nothing?

When an rb node is not inserted in an rb tree, __rb_parent_color is a pointer to the node itself; 93844291918976 = 0x5559d3af1c80, so __parent->rb_left == __parent == __parent->rb_left->rb_left, which I don't think is right (I don't think rb_left or rb_right should point to the node itself, but I will need to check).

**Comment by gccli** [comment] 2018-12-30 03:43
> @gccli Could you please provide the output of `keepalived -v`. I need to know exactly what version of the code you are running, since line 1250 in scheduler.c in the latest version of the code is a comment.

Yes, I download latest version from http://www.keepalived.org/download.html
```
keepalived -v
Keepalived v2.0.10 (11/12,2018)

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 3.10.0
Running on Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-snmp-reply-v3-for-v2 --with-init=systemd --with-kernel-dir=/lib/modules/3.10.0-957.1.3.el7/build build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic LDFLAGS=-Wl,-z,relro 

Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING
```

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RT SCHED_RESET_ON_FORK

> 
> When the vrrp child process hangs, is it looping consuming CPU time, or is it doing nothing?
Yes, cpu usage 100%

> 
> When an rb node is not inserted in an rb tree, __rb_parent_color is a pointer to the node itself; 93844291918976 = 0x5559d3af1c80, so __parent->rb_left == __parent == __parent->rb_left->rb_left, which I don't think is right (I don't think rb_left or rb_right should point to the node itself, but I will need to check).

The rb_insert_sort fall into endless loop

**Comment by pqarmitage** [comment] 2018-12-30 13:38
The output `Keepalived v2.0.10 (12/26,2018), git commit u25-181-g6fcd77d+` appears to suggest that you the code version you are using is 181 commits after tag u25, that the latest git commit is 6fcd77d, and that there are subsequent local modifications that haven't been committed. Not only does upstream not have a tag u25, but also I cannot find commit 6fcd77d. Do you have any local modifications to the code, and any local commits?

You haven't mentioned whether the problem is reproducible or not, but since you say you have compiled with the -g option, I assume you can reproduce it. At the moment I am not clear how ha-check.py is not terminating within 2 seconds after being sent a SIGKILL, but by the time a further SIGKILL is sent the process has disappeared (it may be that we are not detecting child termination properly in the event of a timeout). It would be really helpful if you could post a copy of the ha-check.py script, and also explain what is causing it not to complete within 3 seconds. It will greatly assist in identifying the cause of the problem if I can reproduce it.

**Comment by pqarmitage** [comment] 2018-12-30 15:03
@gccli I can now reproduce this problem, so will work on providing a fix for it.

**Comment by pqarmitage** [comment] 2018-12-30 17:56
Commit a577fa0 resolves this issue. The problem was that child process threads use two RB trees, one for the timeout and the other for the PID of the child process. When a child thread was timing out, the thread wasn't being removed from the PID RB tree, causing subsequent corruption of the tree.

**Closed by pqarmitage** 2018-12-30 17:56 UTC
