### ISSUE TITLE
keepalive error

### ISSUE THREAD

**Issue by imrahuldevopser** [acassen/keepalived#2198] opened 2022-09-13 10:55 UTC
keepalived is running but output not showing..

global_defs {
        router_id LVS_DEVEL
}

vrrp_instance VI_1 {
        state MASTER
        interface eth0
        virtual_router_id 51
        priority 100
        virtual_ipaddress {
                192.168.2.18 dev eth0
        virtual_routes {
                0.0.0.0/0 gw 192.168.2.255 dev eth0
        }
}

**Comment by pqarmitage** [comment] 2022-09-13 12:07
I'm very sorry, but I don't understand what the problem is. Does this configuration relate to issue #2197? If so, could you please post the above information to that issue and close this issue. Otherwise could you please explain what is the problem you are experiencing.

Also, can you please provide the information we request in the `Bug Report` template at https://github.com/acassen/keepalived/issues/new/choose.

**Comment by imrahuldevopser** [comment] 2022-09-13 12:30
> I'm very sorry, but I don't understand what the problem is. Does this configuration relate to issue #2197? If so, could you please post the above information to that issue and close this issue. Otherwise could you please explain what is the problem you are experiencing.
> 
> Also, can you please provide the information we request in the `Bug Report` template at https://github.com/acassen/keepalived/issues/new/choose.

Sep 13 11:56:18 ip-172-31-32-186 Keepalived[16003]: NOTICE: setting config option max_auto_priority should result in better keepalived performance
Sep 13 11:56:18 ip-172-31-32-186 Keepalived[16003]: Starting VRRP child process, pid=16004
Sep 13 11:56:18 ip-172-31-32-186 Keepalived_vrrp[16004]: (/etc/keepalived/keepalived.conf: Line 12) VRRP parsed invalid IP virtual_routes. skipping IP...
Sep 13 11:56:18 ip-172-31-32-186 Keepalived_vrrp[16004]: (/etc/keepalived/keepalived.conf: Line 12) VRRP parsed invalid IP {. skipping IP...
Sep 13 11:56:18 ip-172-31-32-186 Keepalived_vrrp[16004]: (/etc/keepalived/keepalived.conf: Line 13) Unknown configuration entry 'gw' for ip address - ignoring
Sep 13 11:56:18 ip-172-31-32-186 Keepalived_vrrp[16004]: (/etc/keepalived/keepalived.conf: Line 13) Unknown configuration entry '192.168.2.255' for ip addres>
Sep 13 11:56:18 ip-172-31-32-186 Keepalived_vrrp[16004]: There are 1 missing '}'s or extra '{'s
Sep 13 11:56:18 ip-172-31-32-186 Keepalived[16003]: Startup complete
Sep 13 11:56:18 ip-172-31-32-186 Keepalived_vrrp[16004]: (VI_1) Entering BACKUP STATE (init)
Sep 13 11:56:21 ip-172-31-32-186 Keepalived_vrrp[16004]: (VI_1) Entering MASTER STATE

**Comment by pqarmitage** [comment] 2022-09-13 12:56
As the logs state: ` There are 1 missing '}'s or extra '{'s`

Your configuration, with indentation, is:
```
global_defs {
    router_id LVS_DEVEL
}

vrrp_instance VI_1 {
    state MASTER
    interface eth0
    virtual_router_id 51
    priority 100
    virtual_ipaddress {
        192.168.2.18 dev eth0
    virtual_routes {
        0.0.0.0/0 gw 192.168.2.255 dev eth0
    }
}
```

As you can see, there is a missing '}' at the end of the `virtual_ipaddress` block. The configuration should be:
```
global_defs {
    router_id LVS_DEVEL
}

vrrp_instance VI_1 {
    state MASTER
    interface eth0
    virtual_router_id 51
    priority 100
    virtual_ipaddress {
        192.168.2.18 dev eth0
    }                         # Add '}' here
    virtual_routes {
        0.0.0.0/0 gw 192.168.2.255 dev eth0
    }
}
```

'gw' is also deprecated in the virtual_route, and it would be better to change it to `via`.

Whilst I don't know the subnet mask that you are using for the subnet that includes 192.168.2.xxx, if it is /24, then the address specified for the router is a broadcast address which will cause problems.

**Closed by pqarmitage** 2022-09-13 12:56 UTC

**Comment by imrahuldevopser** [comment] 2022-09-13 13:06
Sep 13 13:04:45 ip-172-31-32-186 Keepalived[16800]: NOTICE: setting config option max_auto_priority should result in better keepalived performance
Sep 13 13:04:45 ip-172-31-32-186 Keepalived[16800]: Starting VRRP child process, pid=16801
Sep 13 13:04:45 ip-172-31-32-186 systemd[1]: keepalived.service: Got notification message from PID 16801, but reception only permitted for main PID 16800
Sep 13 13:04:45 ip-172-31-32-186 Keepalived_vrrp[16801]: (/etc/keepalived/keepalived.conf: Line 14) "gw" for routes is deprecated. Please use "via"
Sep 13 13:04:45 ip-172-31-32-186 Keepalived_vrrp[16801]: (/etc/keepalived/keepalived.conf: Line 14) VRRP parsed invalid IP 192.168.2.1/24. skipping IP...
Sep 13 13:04:45 ip-172-31-32-186 Keepalived_vrrp[16801]: (/etc/keepalived/keepalived.conf: Line 14) invalid route via address 192.168.2.1/24
Sep 13 13:04:45 ip-172-31-32-186 Keepalived[16800]: Startup complete
Sep 13 13:04:45 ip-172-31-32-186 systemd[1]: Started Keepalive Daemon (LVS and VRRP).
Sep 13 13:04:45 ip-172-31-32-186 Keepalived_vrrp[16801]: (VI_1) Entering BACKUP STATE (init)
Sep 13 13:04:48 ip-172-31-32-186 Keepalived_vrrp[16801]: (VI_1) Entering MASTER STATE
root@ip-172-31-32-186:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc fq_codel state UP group default qlen 1000
    link/ether 02:3f:b2:1a:9d:f0 brd ff:ff:ff:ff:ff:ff
    inet 172.31.32.186/20 metric 100 brd 172.31.47.255 scope global dynamic eth0
       valid_lft 2034sec preferred_lft 2034sec
    inet 192.168.2.18/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::3f:b2ff:fe1a:9df0/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by pqarmitage** [comment] 2022-09-13 13:45
If appears you have changed the virtual_routes block to:
 ```
   virtual_routes {
        0.0.0.0/0 gw 192.168.2.1/24 dev eth0
    }
```
The gateway is not a subnet, it is the address of the router. If the address of your router is 192.168.2.1, then the virtual_routes block should be:
```
    virtual_routes {
        0.0.0.0/0 via 192.168.2.1 dev eth0      # note change of 'gw' to 'via'
    }
```

If the subnet is 192.168.2.0/24 and 192.168.2.255 is the broadcast address, then you will need to change the virtual_ipaddress block to:
```
virtual_ipaddress {
        192.168.2.18/24 brd + dev eth0
    }
```
If you already have an address in the 192.168.2.0/24 subnet configured on eth0, then you can keep the virtual_ipaddress block as you already have it (i.e. without a submet mask), but the `ip a` output you show above appears to show that you don't already have another address in the 192.168.2.0/24 subnet configured. From the `ip a` output above, you appear to have already added the `/24` to the virtual_ipaddress block, but you haven't added `brd +` and so the broadcast address defaults to 192.168.2.0 which is unconventional.

**Comment by imrahuldevopser** [comment] 2022-09-14 10:24
× keepalived.service - LVS and VRRP High Availability Monitor
     Loaded: loaded (/lib/systemd/system/keepalived.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-09-14 15:52:00 IST; 22s ago
       Docs: man:keepalived(8)
             man:keepalived.conf(5)
             man:genhash(1)
             https://keepalived.org
    Process: 751719 ExecStart=/usr/local/sbin/keepalived $KEEPALIVED_OPTIONS (code=exited, status=6)
        CPU: 2ms

Sep 14 15:52:00 ll-edge2 Keepalived[751719]: Starting Keepalived v2.2.7 (01/16,2022)
Sep 14 15:52:00 ll-edge2 Keepalived[751719]: WARNING - keepalived was built for newer Linux 5.15.46, running on Linux 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022
Sep 14 15:52:00 ll-edge2 systemd[1]: keepalived.service: Control process exited, code=exited, status=6/NOTCONFIGURED
Sep 14 15:52:00 ll-edge2 Keepalived[751719]: Command line: '/usr/local/sbin/keepalived' '-D'
Sep 14 15:52:00 ll-edge2 systemd[1]: keepalived.service: Failed with result 'exit-code'.
Sep 14 15:52:00 ll-edge2 Keepalived[751719]: WARNING - using deprecated default config file '/etc/keepalived/keepalived.conf' - please move to '/usr/local/etc/keepalived/keepalived.conf'
Sep 14 15:52:00 ll-edge2 Keepalived[751719]: Configuration file '/etc/keepalived/keepalived.conf' is not a regular non-executable file - skipping
Sep 14 15:52:00 ll-edge2 Keepalived[751719]: CPU usage (self/children) user: 0.002372/0.000000 system: 0.000000/0.000000
Sep 14 15:52:00 ll-edge2 Keepalived[751719]: Stopped Keepalived v2.2.7 (01/16,2022)
Sep 14 15:52:00 ll-edge2 systemd[1]: Failed to start LVS and VRRP High Availability Monitor.

**Comment by imrahuldevopser** [comment] 2022-09-14 10:25
keepalived.conf file

global_defs {
   router_id LVS_DEVEL
}

vrrp_instance VI_1 {
        state BACKUP
        interface ens18
        virtual_router_id 51
        priority 99
        virtual_ipaddress {
        192.168.17.18/24 brd + dev ens18
        }
        virtual_routes {
        0.0.0.0/0 via 192.168.17.1 dev ens18
        }
}

**Comment by pqarmitage** [comment] 2022-09-14 11:29
@imrahuldevopser When you report an issue, can you please state what the problem is that you are experiencing. You keep not doing so and so I am having to guess at what your problem is, and sometimes, such as when you originally raised the issue I couldn't determine what the problem was.

Once again, the keepalived logs describe the problem - `Configuration file '/etc/keepalived/keepalived.conf' is not a regular non-executable file - skipping`. Run `ls -l /etc/keepalived/keepalived/conf` and you should see the problem. The file might have execute permission, it might be a fifo etc etc. For problems like these, if you can't understand what the problem is it is simplest to look at the source code. In the root of the source tree run `grep "is not a regular" $(find . -name "*.c")`. It outputs:
```
./lib/parser.c:		file_config_error(INCLUDE_R, "Configuration file '%s' is not a regular non-executable file - skipping", file_name);
./keepalived/trackers/track_file.c:				/* It is not a regular file */
./keepalived/trackers/track_file.c:
```
so look at lib/parser.c and search for "is not a regular". You will see the following code:
```
        /* Make sure what we have opened is a regular file, and not for example a directory or executable */
        if (stat(file_name, &stb) ||
            !S_ISREG(stb.st_mode) ||
            (stb.st_mode & (S_IXUSR | S_IXGRP | S_IXOTH))) {
                file_config_error(INCLUDE_R, "Configuration file '%s' is not a regular non-executable file - skipping", file_name);
                return false;
        }
```
from which the problem should be even clearer.
