### ISSUE TITLE
keepalived failover

### ISSUE THREAD

**Issue by davidone** [acassen/keepalived#1076] opened 2018-11-29 21:08 UTC
I am trying to have a active/passive haproxy pair for tcp (!http) traffic; I have the following setup:

1 vm - haproxy1 with haproxy and keepalived
1 vm - haproxy2 with haproxy and keepalived
1 vm - webserver with nginx serving a 10G file.bin
1 host - a windows 10 laptop with hyper-v and wsl

(all hosts are ubuntu 18.04.1)

haproxy[12] have three network interfaces:
- eth2: external (haproxy1: 172.18.18.2/28, haproxy2: 172.18.18.3/28)
- eth1: internal (haproxy1: 192.168.1.1/24, haproxy2: 192.168.1.2/24)
- eth0: cross (haproxy: 192.168.0.1/24, haproxy2: 192.168.0.2/24), used for multicast traffic

webserver only one:
- eth0: internal (192.168.1.3/24)

the three networks are created within hyper-v itself (all the network interfaces have the 'MAC address spoofing' option enabled in Hyper-V).

vip on external network is: 172.18.18.10

sysctls on haproxy[12]:
```
# keepalived
net.ipv4.ip_nonlocal_bind = 1
```

This is the haproxy configuration file:
```
global
  log /dev/log  local0
  log /dev/log  local1 notice
  chroot /var/lib/haproxy
  stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
  stats timeout 30s
  user haproxy
  group haproxy
  daemon

defaults
  log   global
  option        dontlognull
  timeout connect 50000
  timeout client  50000
  timeout server  50000
  option redispatch

listen stats-ui
  bind 0.0.0.0:8080
  mode http
  stats enable
  stats realm Haproxy\ Statistics
  stats uri /haproxy_stats

listen dev-service
  bind 172.18.18.10:80
  mode tcp
  balance roundrobin
  server webserver 192.168.1.3:80 check
```

This is the keepalived config file:
```
global_defs {
   script_user root
   enable_script_security
   lvs_sync_daemon eth0 VI_1
   router_id HAPROXY1
}

vrrp_script chk_haproxy {
   script "/usr/bin/pgrep haproxy"
   interval 2
}

vrrp_instance VI_1 {
   interface eth0
   state MASTER       # BACKUP on haproxy2
   nopreempt
   advert_int 1
   virtual_router_id 51
   priority 200        # 100 on haproxy1
   virtual_ipaddress {
       172.18.18.10 dev eth2
   }
   track_script {
       chk_haproxy
   }
}
```

So far so good:
```
$ wget --no-proxy http://172.18.18.10/file.bin
--2018-11-29 20:52:33--  http://172.18.18.10/file.bin
Connecting to 172.18.18.10:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10240000000 (9.5G) [application/octet-stream]
Saving to: ‘file.bin’

file.bin                        1%[             ] 172.21M  32.5MB/s    eta 5m 2s
^C
$
```
To simulate a failover, I stop keepalived on haproxy1 and I'm expecting to see the wget
continuing downloading the file; I see haproxy2 becoming MASTER after stopping keepalived on haproxy1 but unfortunately after the switch wget is not downloading anymore:
```
$ wget --no-proxy http://172.18.18.10/file.bin
--2018-11-29 20:57:04--  http://172.18.18.10/file.bin
Connecting to 172.18.18.10:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10240000000 (9.5G) [application/octet-stream]
Saving to: ‘file.bin.1’

file.bin.1                      4%[=>         ] 484.40M  --.-KB/s    eta 14m 18
^C
$
```
If I try and relaunch wget, it works.

What am I missing here?

Apologies if this is not the right place for this question, but I only found two mailing lists (announce and dev) on keepalived website that I don't think are the right place for this.

Thanks in advance,
d.

**Comment by pqarmitage** [comment] 2018-11-30 12:05
The problem is that when the wget process connects, it establishes a tcp connection to 172.18.18.10 on haproxy1, and haproxy1 establishes a tcp connection from 192.168.1.1 to 192.168.1.3. When keepalived is stopped on haproxy1 and haproxy2 takes over ip address 172.18.18.10, haproxy2 doesn't know anything about the two tcp connections that were established on haproxy1, and consequently although haproxy2 now receives data from the client 172.18.18.10 at the ip level, it doesn't have a corresponding tcp connection established and so the data is dropped. Likewise, the server 192.168.1.3 is still trying to send data back to the wget client to 192.168.1.1 but haproxy1 no longer has ip address 172.18.18.10, and so the TCP connection in haproxy1 between 172.18.18.10 and the client is broken and data cannot be forwarded.

When you run wget again, the client establishes a new tcp connection to 172.18.18.10, this time on haproxy2, and data can be passed again.

**Comment by davidone** [comment] 2018-11-30 12:15
Shouldn't:
```
lvs_sync_daemon eth0 VI_1
```
taking care of syncing the forwarding table from MASTER -> BACKUP?

I understand that from a webserver point of view the new connection comes from a different IP address, I tried having a VIP to be used when haproxy[12] contacts the backend, it didn't work but I'll paste the config as well.

**Comment by pqarmitage** [comment] 2018-11-30 12:33
I _think_ the lvs_sync_daemon only forwards the LVS (IPVS) mappings, and you are not using virtual_servers within your keepalived configuration.

The problem is that the TCP connections that are established initially are between the client and haproxy1 and between haproxy1 and the webserver. When keepalived is stopped on haproxy1, and the 172.18.18.10 and 192.168.1.10 ip addresses are removed, any TCP sessions to/from those addresses will be terminated. The haproxy process in haproxy2 simply cannot have those same TCP connections established as well, and so the file transfer cannot continue.

**Comment by davidone** [comment] 2018-11-30 12:37
Uhm, OK.

Is there any other way I can achieve what I'm trying to do (seamlessy switch the master role to a backup node without impacting any reconnections on the client side)?

**Comment by pqarmitage** [comment] 2018-11-30 12:57
Using NAT should be sufficient, along with using conntrackd. Both haproxy1 and haproxy2 should NAT 172.18.18.10 to 192.168.1.3. You don't need to use the haproxy program.

**Comment by davidone** [comment] 2018-11-30 13:39
Thanks but what if I have many backends?

**Comment by pqarmitage** [comment] 2018-11-30 14:16
Ah, that's a different problem. :)

The solution would be to use the LVS/IPVS functionionality of keepalived, but with some additional IP addresses.

Suppose you now have 4 web servers, web0 (192.168.1.3), web1 (192.168.1.4), web2 (192.168.1.5) and web3 (192.168.1.6). You need to assign a second IP address to each of them, let's say 192.168.2.3/24, 192.168.2.4/24 etc.

Your keepalived config now needs to become:
```
global_defs {
   script_user root
   enable_script_security
   lvs_sync_daemon eth0 VI_1
@haproxy1   router_id HAPROXY1   # See below for explanation of @haproxy1
@haproxy2   router_id HAPROXY2
}

vrrp_instance VI_1 {
   interface eth0
#   state MASTER                              # unnecessary
   nopreempt
   vrrp_version 3                                 # (optional) This is the current version of VRRP
   advert_int 1                                     # with VRRP version 3 this can be reduced as low as 0.01 seconds
   virtual_router_id 51
@haproxy1   priority 200
@haproxy2   priority 180                   # higher priorities produce faster failover times
   vrrp_garp_master_delay 1

   use_vmac                                       # Ensures correct MAC address used, and will be used by the master

   virtual_ipaddress {
       172.18.18.10 dev eth2
       192.168.2.10/24 dev eth1            # note this is on the new subnetwork and the subnet mask is needed since the network isn't otherwise defined on this system
   }
}

virtual_server 172.18.18.10 80 {
        delay_loop 6
        lb_algo lc
        lb_kind NAT
        protocol TCP
        timeout 10

        real_server 192.168.2.3 80 {
            weight 1
            TCP_CHECK {
                connect_timeout 10
                connect_port    80
            }
        }
        real_server 192.168.2.4 80 {
            weight 1
            TCP_CHECK {
                connect_timeout 10
                connect_port    80
            }
        }
        real_server 192.168.2.5 80 {
            weight 1
            TCP_CHECK {
                connect_timeout 10
                connect_port    80
            }
        }
        real_server 192.168.2.6 80 {
            weight 1
            TCP_CHECK {
                connect_timeout 10
                connect_port    80
            }
        }
}
```

If the hostnames of haproxy1 and haproxy2 are `haproxy1.domainname` and `haproxy2.domainname` then the above config file will work on both of them without changes. Alternatively, if your hostnames are host1.domainname and host2,domainname, replace `@haproxy1` etc with `@host1` etc, or specify `-i haproxy1` or `-i haproxy2` as command line options for keepalived. This way you only need 1 config file that works on both systems. The lvs_sync_daemon will propogate the necessary IPVS information for haproxy2 to be able to take over.

The reason for adding the 192.168.2.0/24 addresses is to ensure that the virtual IP address 192.168.2.10 is used as the NAT source address by IPVS. When keepalived on haproxy1 stops and haproxy2 takes over as master, the web servers will still be able to communicate, since they will have the remote IP address as 192.168.2.10.

I think you don't need conntrackd for this to work.

**Comment by davidone** [comment] 2018-11-30 16:47
@pqarmitage that's a very interesting answer, will take few days to work on that.

Very thanks,
d.

**Comment by davidone** [comment] 2018-12-03 15:43
I tried your suggestion, unfortunately it doesn't work. The client is always stuck at:
```
$ wget --no-proxy http://172.18.18.10/file.bin
--2018-12-03 15:41:21--  http://172.18.18.10/file.bin
Connecting to 172.18.18.10:80... failed: Resource temporarily unavailable.
Retrying.
```

Does this involve any iptables NAT or other config?

Thanks,
d.

**Comment by davidone** [comment] 2018-12-06 08:34
Any hint?

**Comment by pqarmitage** [comment] 2018-12-06 08:39
Can you try the wget command on the web server itself, using the added local address, e.g. 192.168.2.3 - it might be that the web server isn't listening on that address.

It would also be helpful if you could try running tcpdump to see what is happening to the packets from wget.

**Comment by davidone** [comment] 2018-12-06 12:13
A couple of updates. I am using Ubuntu 18.04 and keepalived from Ubuntu's repos is still at 1.39. I manually compiled a 2.0.10 version (to have vrrp_version 3).; nothing has changed after that.
I added a masquerade postrouting iptables chain with:
```
iptables --flush
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
```

and it's now working properly.

I can easily switch from one host to the other and the wget isn't dropping the connection / stopping at all.

Tbh I don't know why, but when I try to switch back to the previous MASTER node (issuing a service keepalived stop on the haproxy2 node), wget drops the connection and when it tries again it works.
Is there any timeout issue? I can see that the sync threads are working, so cannot understand what's so special in switching from haproxy2 to haproxy1.

In the meanwhile thanks for your support in this.

**Comment by pqarmitage** [comment] 2018-12-06 13:36
Many thanks for the update, and I'm glad something is now working for you.

In the ipvsadm(3) man page, it states:
_As  masquerading  is used as the forwarding mechanism in this example, the default route of the real servers must be set to the linux director, which will need to be configured to forward and masquerade packets. This can be achieved using the following commands:_
       _echo "1" > /proc/sys/net/ipv4/ip_forward_

so that might explain why the iptables masquerade entry is needed.

The issue regarding switching back from haproxy2 to haproxy1 could be due to the way the sync daemon works. Alexandre can probably help here since he was involved in writing IPVS. We you stop keepalived on haproxy1, the sync daemon stops running. When keepalived starts again on haproxy1, it starts the sync daemon on haproxy1 again, and if it hasn't fully resynchronised by the time it takes takes over as VRRP master,the connection tracking information might not be available.

As an experiment you could try removing the lvs_sync_daemon configuration from keepalived and run two sync daemons on each of haproxy1 and haproxy2, using two different sync_ids, so that you have say a master on ha_proxy1 and a backup on ha_proxy2 using sync_id 1, and a backup on ha_proxy1 and a master on haproxy2 using sync_id 2.  Run the sync daemons before you run keepalived, and leave the running when you stop and restart keepalived.

**Comment by davidone** [comment] 2018-12-06 14:32
Actually I made it working using conntrackd.

This is my keepalived.conf:
```
global_defs {
    script_user root
    enable_script_security
    lvs_sync_daemon eth0 VI_1
@haproxy1   router_id HAPROXY1
@haproxy2   router_id HAPROXY2
}

vrrp_instance VI_1 {
    interface eth0
    advert_int 1
    virtual_router_id 51
@haproxy1   priority 200
@haproxy2   priority 180
    use_vmac

    virtual_ipaddress {
        172.18.18.10 dev eth2
        192.168.2.10/28 dev eth1
    }

    notify_master "/etc/conntrackd/primary-backup.sh primary"
    notify_backup "/etc/conntrackd/primary-backup.sh backup"
    notify_fault "/etc/conntrackd/primary-backup.sh fault"
}

virtual_server 172.18.18.10 80 {
    delay_loop 6
    lb_algo lc
    lb_kind NAT
    protocol TCP

    real_server 192.168.2.3 80 {
    weight 1
        TCP_CHECK {
            connect_timeout 10
            connect_port    80
        }
    }
}
```

where /etc/conntrackd/primary-backup.sh comes from /usr/share/doc/conntrackd/examples/sync/primary-backup.sh.

iptables rules are (/etc/iptables/rules.v4:
```
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A PREROUTING -i eth2 -p tcp --dport 80 -j DNAT --to 192.168.2.3:80
-A POSTROUTING -o eth1 -j MASQUERADE
COMMIT

*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
```

Now I'm able to switch between haproxy1 and haproxy2 properly.

Thanks for your help, I hope this can help others too.

**Comment by pqarmitage** [comment] 2019-06-18 10:32
Closing due to no outstanding action and no update for 6 months.

**Closed by pqarmitage** 2019-06-18 10:32 UTC
