### ISSUE TITLE
Keepalived dies with bigger configurations on a reload.

### ISSUE THREAD

**Issue by VigneshSP94** [acassen/keepalived#2318] opened 2023-07-04 16:34 UTC
**Describe the bug**
Reloading keepalived with high number of VIPs and backends kills keepalived.

**To Reproduce**
Any steps necessary to reproduce the behaviour:
Have high number of listeners
```
root@ipvs:~# ipvsadm -Ln | grep TCP | wc -l
2284
```
Have high number of backend for listeners
```
root@ipvs:~# ipvsadm -Ln | grep Tunnel | wc -l
37298
```
Make changes to your keepalived conf, like changing bunch of backend servers weight from 0 to 10.
Reload keepalived.

**Expected behavior**
Keepalived should complete the reload and run without exiting the process.

**Keepalived version**
Had this issue on two different kernels
```
Keepalived v2.2.4 (08/21,2021)

Copyright(C) 2001-2021 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.4.73
Running on Linux 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020
Distro: Ubuntu 20.04 LTS

configure options:

Config options:  LIBIPSET_DYNAMIC NFTABLES LVS VRRP VRRP_AUTH VRRP_VMAC OLD_CHKSUM_COMPAT INIT=systemd

System options:  VSYSLOG MEMFD_CREATE IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA IPTABLES NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_IPVLAN IFLA_LINK_NETNSID GLOB_BRACE GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE VRF SO_MARK
```
```
Keepalived v2.2.4 (08/21,2021)

Copyright(C) 2001-2021 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.4.73
Running on Linux 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020
Distro: Ubuntu 20.04 LTS

configure options:

Config options:  LIBIPSET_DYNAMIC NFTABLES LVS VRRP VRRP_AUTH VRRP_VMAC OLD_CHKSUM_COMPAT INIT=systemd

System options:  VSYSLOG MEMFD_CREATE IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA IPTABLES NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_IPVLAN IFLA_LINK_NETNSID GLOB_BRACE GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE VRF SO_MARK
```

**Distro (please complete the following information):**
 - Name: Ubuntu
 - Version: 20
 - Architecture: x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
On premise baremetal.

**Configuration file:**
Its a configuration with 2000+ listeners, I will attach a snip but all listeners are identical.
```
virtual_server 100.0.0.1 80 {
        delay_loop 3
        lvs_sched mh
        mh-port
        mh-fallback
        lvs_method TUN
        protocol TCP
        real_server x.x.x.x 80 {
                weight 10
                HTTP_GET {
                        url {
                                path "/static/hostname"
                                status_code 200
                        }
                        connect_ip x.x.x.
                        connect_port 80
                        connect_timeout 2
                }
        }
        .
        .
        .
}
.
.
.
.
```

**Notify and track scripts**
```
None
```

**System Log entries**
We have this agent that runs every 30 seconds to fetch updated keepalived configs and iptables rules, runs reloading of interface and reload keepalived and sets new iptables rules.

```
Jun 28 16:11:30 ipvs systemd[1]: Started update agent.
Jun 28 16:11:40 ipvs systemd[1]: Reloading Keepalive Daemon (LVS).
Jun 28 16:11:40 ipvs systemd[1]: Reloaded Keepalive Daemon (LVS).
Jun 28 16:11:51 ipvs systemd-journald[548]: Suppressed 25326 messages from keepalived.service
Jun 28 16:11:51 ipvs Keepalived_healthcheckers[3915017]: Activating healthchecker for service [x.x.x.x]:tcp:80 for VS [x.x.x.x]:tcp:80
Jun 28 16:11:51 ipvs Keepalived_healthcheckers[3915017]: Activating healthchecker for service [x.x.x.x]:tcp:80 for VS [x.x.x.x]:tcp:80
Jun 28 16:11:51 ipvs Keepalived_healthcheckers[3915017]: Activating healthchecker for service [x.x.x.x]:tcp:80 for VS [x.x.x.x]:tcp:80
Jun 28 16:11:51 ipvs Keepalived_healthcheckers[3915017]: Activating healthchecker for service [x.x.x.x]:tcp:80 for VS [x.x.x.x]:tcp:80
Jun 28 16:11:51 ipvs Keepalived_healthcheckers[3915017]: Activating healthchecker for service [x.x.x.x]:tcp:80 for VS [x.x.x.x]:tcp:80
Jun 28 16:11:51 ipvs Keepalived_healthcheckers[3915017]: Activating healthchecker for service [x.x.x.x]:tcp:80 for VS [x.x.x.x]:tcp:80
.
.
.
No confirmation logs for the healthcheck being successful
```

Again the agent is started
```
Jun 28 16:12:00 ipvs systemd[1]: Started update agent
#systemd tried to reload keepalived but just prints keepalived is inactive
Jun 28 16:12:10 ipvs systemd[1]: Keepalive Daemon (LVS) is not active.
Jun 28 16:12:18 ipvs systemd[1]: keepalived.service: Succeeded. # looks like keepalived exited with 0 status
Jun 28 16:12:18 ipvs systemd[1]: keepalived.service: Scheduled restart job, restart counter is at 1. # systemd restarts it
```

I added `-D` switch to the keepalived start and tried to reproduce this issue, I was able to hit the issue, but didn't get any clarity on what could have caused this.
This is the logs when I reproduced the issue.
```
Jul 04 11:15:09 ipvs systemd[1]: Reloading Keepalive Daemon (LVS).
Jul 04 11:15:09 ipvs Keepalived[2094153]: Reloading ...
Jul 04 11:15:09 ipvs Keepalived[2094153]: Opening file '/etc/keepalived/keepalived.conf'.
Jul 04 11:15:09 ipvs systemd[1]: Reloaded Keepalive Daemon (LVS).
Jul 04 11:15:09 ipvs Keepalived[2094153]: Configuration file /etc/keepalived/keepalived.conf
Jul 04 11:15:09 ipvs Keepalived[2094153]: Opening file 'conf/file'.
Jul 04 11:15:10 ipvs Keepalived[2094153]: Opening file 'another/conffile'.
Jul 04 11:17:33 ipvs systemd[1]: Reloading Keepalive Daemon (LVS).
Jul 04 11:17:33 ipvs Keepalived[2094153]: Reload already in progress, request queued
Jul 04 11:17:33 ipvs systemd[1]: Reloaded Keepalive Daemon (LVS).
Jul 04 11:18:04 ipvs systemd[1]: Stopping Keepalive Daemon (LVS)...
Jul 04 11:18:14 ipvs Keepalived[2094153]: Stopping
Jul 04 11:18:19 ipvs Keepalived[2094153]: checker process failed to die - forcing termination
Jul 04 11:18:19 ipvs Keepalived[2094153]: CPU usage (self/children) user: 1.771966/0.000000 system: 0.059863/0.000000
Jul 04 11:18:19 ipvs Keepalived[2094153]: Stopped Keepalived v2.2.4 (08/21,2021)
Jul 04 11:18:19 ipvs systemd[1]: keepalived.service: Succeeded.
Jul 04 11:18:19 ipvs systemd[1]: Stopped Keepalive Daemon (LVS).
Jul 04 11:18:52 ipvs systemd[1]: Starting Keepalive Daemon (LVS)...
Jul 04 11:18:52 ipvs Keepalived[2103340]: Starting Keepalived v2.2.4 (08/21,2021)
```

**Did keepalived coredump?**
```
No
```

**Additional context**

**Comment by pqarmitage** [comment] 2023-07-04 17:26
@VigneshSP94 Please can you provide your full configuration files, and a precise description of what is being changed before keepalived reloads, or configuration files before they are changed for the reload and the files after they are changed. It would also be helpful to see your keepalived.service file. This is the only way that we can test what is happening and attempt to provide a resolution. You can either attach a compressed tar file, or email it directly to me (see various commits for my email address) if you prefer not to post it publicly.

```
Jul 04 11:17:33 ipvs systemd[1]: Reloading Keepalive Daemon (LVS).
Jul 04 11:17:33 ipvs Keepalived[2094153]: Reload already in progress, request queued
Jul 04 11:17:33 ipvs systemd[1]: Reloaded Keepalive Daemon (LVS).
Jul 04 11:18:04 ipvs systemd[1]: Stopping Keepalive Daemon (LVS)...
Jul 04 11:18:14 ipvs Keepalived[2094153]: Stopping
Jul 04 11:18:19 ipvs Keepalived[2094153]: checker process failed to die - forcing termination
```
looks interesting. It appears that systemd is for some reason deciding to stop keepalived (at 11:18:04). It then takes 10 seconds before keepalived logs that it is stopping (which it should do as soon as it receives the signal to stop). keepalived then signals the child processes to stop, and then the keepalived IPVS (checker) process doesn't terminate within 5 seconds.

How busy is your system, is their plenty of spare memory and CPU time?

**Comment by VigneshSP94** [comment] 2023-07-05 06:51
@pqarmitage thanks for your response.

Our systems are of 16cores, plenty of CPU always free. But during this reload, at 16:12~ UTC, one core spiked to 100%.
![image](https://github.com/acassen/keepalived/assets/24570763/d45da8b8-2cd6-4372-9c96-0b5db77c9856)

When I try to reproduce this, I can see one core to spike during reloads, but it just stops with 1 core and other cores are free.

```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
1850806 root      20   0  173144 166348   2644 R 100.0   0.5   9:50.48 keepalived
```

can keepalived use only one CPU? 

systemd unit file for keepalived

```
# /etc/systemd/system/keepalived.service
[Unit]
Description = Keepalive Daemon (LVS)
After = syslog.target network-online.target
Wants = network-online.target
ConditionFileNotEmpty = /etc/keepalived/keepalived.conf

[Service]
LimitNOFILE = 40960
Type = forking
ExecStart = /usr/local/sbin/keepalived
ExecReload = /bin/kill -HUP $MAINPID
ExecStop = /usr/bin/vtysh -f '/etc/frr/stop_advertise_vip.conf'
ExecStop = /bin/sleep 10
KillMode = process
Restart = always

[Install]
WantedBy = multi-user.target

# /etc/systemd/system/keepalived.service.d/ipvsadm-set.conf
[Service]
ExecStartPost=/sbin/ipvsadm --set 30 10 300
```

I have emailed the tar file has before the change, after the change and diff between both.

**Comment by pqarmitage** [comment] 2023-07-05 11:20
Many thanks for the additional info.

The keepalived processes are single threaded, so each process can only run on one CPU at a time. Since all your configuration is IPVS, that means that keepalived will essentially only use one CPU.

I note from the log entries above:
```
Jul 04 11:15:09 ipvs Keepalived[2094153]: Opening file 'conf/file'.
Jul 04 11:15:10 ipvs Keepalived[2094153]: Opening file 'another/conffile'.
```
which imply that `/etc/keepalived/keepalived.conf` has some include statements, but there are none in the configs you have posted above. Could you please clarify the situation and are there any other config files involved?

**Comment by VigneshSP94** [comment] 2023-07-05 16:49
@pqarmitage sorry, the keepalived.conf has only one include statement that points it to the directory of the file I posted here and it has only one file.

```
root@ipvs:~# cat /etc/keepalived/keepalived.conf
include /etc/keepalived/configs/*
```

**Comment by pqarmitage** [comment] 2023-07-05 17:46
I have converted all the x.x.x.x in your config to IP addresses and can load the configuration. It seems to take about 3 seconds for keepalived to startup with your configuration, but about 83 seconds to reload. 45 seconds after starting the reload I see a message
`systemd[1]: keepalived.service: Reload operation timed out. Killing reload process.`
and I expect you are experiencing the same when keepalived reloads the configuration.

To see how long the reload is taking, run:
`while [ 1 ]; do systemctl status keepalived | grep Active: ; sleep 1; done`

On my test system `grep Timeout /etc/systemd/system.conf` shows
```
#DefaultTimeoutStartSec=45s
#DefaultTimeoutStopSec=45s
#DefaultTimeoutAbortSec=
#DefaultDeviceTimeoutSec=45s
```
which matches the 45 seconds I observe before the systemd reload timeout message occurs. I assume that the DefaultTimeoutStartSec applies to reloads as well, but that is a guess. You could add a line `TimeoutStartSec=90`(or whatever value is sufficient to cover the reload time you observe) in your keepalived service file and see if that stops keepalived being killed.

I am sure your next question will be why does keepalived take so long to reload. The reason is that keepalived has to compare the old config and the new config, work out the changes, and then update the IPVS configuration to match those changes. Your configuration being so large means that there are rather a lot of comparisons to make. I will however have a look to see if there is some way that it can be speeded up.

**Comment by VigneshSP94** [comment] 2023-07-07 03:58
@pqarmitage thank you, I will test this in my lab and update here. Is there any benchmark values available on what is the maximum number of listeners or backend servers keepalived can handle efficiently?

**Comment by pqarmitage** [comment] 2023-07-07 06:33
In essence, all the time is spent in `clear_diff_services()` (well, all but about 0.3 seconds). After further testing it appears that virtually all the time is spent in `migrate_checkers()`, so the number of listeners or backend servers does not appear to be the issue, but rather the number of checkers. I will investigate further.

**Comment by pqarmitage** [comment] 2023-07-07 10:05
@VigneshSP94 I am just testing some code that reduces the reload time by about 95%, so reduces 100 seconds to 5 seconds. It needs some further testing, especially to ensure that there are no regressions, but this will probably be the best solution to your problem.

**Comment by pqarmitage** [comment] 2023-07-07 20:36
@VigneshSP94 With the code optimisations I have made, with your configuration that for me was taking 130 seconds when all parts of the reload process were taken into account, is reduced to less that 3 milli-seconds, reducing the reload time by about 99.77%. This will completely resolve your issue.

I also discovered that checkers that had failed before a reload where no longer marked as failed after the reload and the real servers were re-enabled after the reload until the checkers failed again. With the forthcoming update, checkers that have failed prior to the reload will still be marked as failed after the reload.

I still need to do a bit of further testing, butt will push the changes soon.

**Comment by pqarmitage** [comment] 2023-07-09 10:44
@VigneshSP94 Commit [238bf17](https://github.com/acassen/keepalived/pull/2320/commits/238bf177e096d2a14137f4e187089a7e6a901c69) resolves the issue for me. For me it reduces the reload time using your configurations from 132 seconds to 0.24 seconds, a reduction of 99.8%.

The commit does not apply to keepalived v2.2.4 so you will need to update to the current HEAD of the master branch.

If you add
```
global_defs {
        lvs_flush_on_stop VS
}
```
to your configuration, it will speed up removing virtual servers, particularly when keepalived is shutting down. If nothing else on your system updates the IPVS configuration, then you can omit the `VS` after `lvs_flush_on_stop`.

**Closed by pqarmitage** 2023-07-09 10:44 UTC

**Comment by VigneshSP94** [comment] 2023-07-10 06:30
@pqarmitage my apologies for commenting on this closed issue. I don't see systemd timeout being kicked in.

```
Jul 10 06:03:11 ipvs systemd[1]: Reloaded Keepalive Daemon (LVS).
Jul 10 06:03:11 ipvs Keepalived[3144243]: Reload already in progress, request queued
Jul 10 06:03:11 ipvs systemd[1]: Reloading Keepalive Daemon (LVS).
Jul 10 05:17:48 ipvs systemd[1]: Reloaded Keepalive Daemon (LVS).
Jul 10 05:17:48 ipvs Keepalived[3144243]: Reload already in progress, request queued
Jul 10 05:17:48 ipvs systemd[1]: Reloading Keepalive Daemon (LVS).
Jul 10 05:09:34 ipvs Keepalived[3144243]: Opening file 'some/more/keepalived.conf'.
Jul 10 05:09:33 ipvs Keepalived[3144243]: Opening file 'some/more/keepalived-more.conf'.
Jul 10 05:09:33 ipvs Keepalived[3144243]: Configuration file some/keepalived.conf
Jul 10 05:09:33 ipvs Keepalived[3144243]: Opening file 'some/keepalived.conf'.
Jul 10 05:09:33 ipvs systemd[1]: Reloaded Keepalive Daemon (LVS).
Jul 10 05:09:33 ipvs Keepalived[3144243]: Reloading ...
Jul 10 05:09:33 ipvs systemd[1]: Reloading Keepalive Daemon (LVS).
Jul 10 05:08:48 ipvs Keepalived_healthcheckers[3144244]: Set open file limit to 164641:164641.
Jul 10 05:08:48 ipvs Keepalived_healthcheckers[3144244]: Reinitializing ipvs
Jul 10 05:08:48 ipvs Keepalived[3144243]: Reload complete
Jul 10 05:08:44 ipvs Keepalived_healthcheckers[3144244]: Reloading
```

I see one reload is complete, and the next reload says already a reload is in progress but systemd considers the reload to be complete, same for the next to next. Is there any timeout for reloads within keepalived?

the timeout values in my test system is 90s

```
root@ipvs:~# grep Timeout /etc/systemd/system.conf
#DefaultTimeoutStartSec=90s
#DefaultTimeoutStopSec=90s
#DefaultTimeoutAbortSec=
```

should I try the commit you mentioned anyway and test this?

**Comment by pqarmitage** [comment] 2023-07-10 07:00
@VigneshSP94 Yes, please try the commit referred to above; I hope that it will resolve your issue.

The `Jul 04 11:15:09 ipvs systemd[1]: Reloaded Keepalive Daemon (LVS).` messages I think are logged by systemd once it has sent the reload signal to keepalived, and not when keepalived notifies systemd that it has completed the reload. If you run `while [ 1 ]; do systemctl status keepalived; sleep 1; done` after requesting keepalived to reload you should see that it shows keepalived reloading for quite a while before it returns to the normal state.

I think the `Jul 10 05:17:48 ipvs Keepalived[3144243]: Reload already in progress, request queued` messages are a separate issue, but may be resolved by the above commit.

It was the `Jul 04 11:18:04 ipvs systemd[1]: Stopping Keepalive Daemon (LVS)...` message that indicated the systemd timeout.

**Comment by VigneshSP94** [comment] 2023-07-10 08:18
ok I will patch this and run for a while, thank you again for the response.

**Comment by VigneshSP94** [comment] 2023-07-14 08:47
@pqarmitage I am testing the latest patch now. I'm just trying to understand how systemd timeout will apply here? Because when we reload through systemd, it sends HUP to the keepalived main process to initiates reload and considers reload to be done? the `clear_diff_services()` is started once the HUP signal is received. How can systemd track the time it takes for `clear_diff_services()` to complete and kill the process if it exceeds the timeout value?

Sorry, I'm asking because I'm unable to reproduce this issue consistently.

**Comment by pqarmitage** [comment] 2023-07-14 10:08
When keepalived receives SIGHUP, it sends "RELOADING=1" to systemd, which tells systemd that keepalived is reloading. Once all the child processes have completed reloading, the keepalived parent process then sends "READY=1\nMAINPID=..." to systemd (see lib/systemdc.c for the code).

You can see the effects of this using the old code. Running `while [ 1 ]; do systemctl status keepalived | grep Active: ; sleep 1; done`
I get the following output
```
Active: active (running) since Fri 2023-07-14 10:43:11 BST; 50s ago
     Active: active (running) since Fri 2023-07-14 10:43:11 BST; 51s ago
     Active: active (running) since Fri 2023-07-14 10:43:11 BST; 52s ago
     Active: active (running) since Fri 2023-07-14 10:43:11 BST; 53s ago
     Active: reloading (reload-notify) since Fri 2023-07-14 10:43:11 BST; 54s ago
     Active: reloading (reload-notify) since Fri 2023-07-14 10:43:11 BST; 55s ago
     Active: reloading (reload-notify) since Fri 2023-07-14 10:43:11 BST; 56s ago
     Active: reloading (reload-notify) since Fri 2023-07-14 10:43:11 BST; 57s ago
     Active: reloading (reload-notify) since Fri 2023-07-14 10:43:11 BST; 58s ago
...
     Active: reloading (reload-notify) since Fri 2023-07-14 10:43:11 BST; 2min 42s ago
     Active: reloading (reload-notify) since Fri 2023-07-14 10:43:11 BST; 2min 43s ago
     Active: reloading (reload-notify) since Fri 2023-07-14 10:43:11 BST; 2min 44s ago
     Active: active (running) since Fri 2023-07-14 10:43:11 BST; 2min 45s ago
     Active: active (running) since Fri 2023-07-14 10:43:11 BST; 2min 46s ago
     Active: active (running) since Fri 2023-07-14 10:43:11 BST; 2min 47s ago
```
I fact on my test system, the checker process still runs at or near 100% CPU for another 25 seconds after systemd reports that keepalived is in the active state again. This is because `free_check_data()` is called after the checker process notifies the parent process that it has reloaded and `free_check_data()` was taking 25 seconds or so due to it using the checkers_queue.

So systemd is aware that keepalived is reloading, from 10:44:05 (54 secs after 10:43:11) until 10:45:56, and at 10:44:50 in my logs I have a message `keepalived.service: Reload operation timed out. Killing reload process.`. I get the same message 45 seconds later (at 10:45:35) as well.

With the new code, because the reload is now so fast, I don't see any `reloading (reload-notify)` output when running the while loop above and reloading keepalived.

**Comment by VigneshSP94** [comment] 2023-07-14 10:24
Thank you for the explanation. Did you use the same systemd unit file configuration that I posted or a different one? Because in my test systems, it is never in reloading state when I run 

`while [ 1 ]; do systemctl status keepalived | grep Active: ; sleep 1; done`

**Comment by pqarmitage** [comment] 2023-07-14 11:12
I used the systemd unit file that is part of Fedora 38:
```
[Unit]
Description=LVS and VRRP High Availability Monitor
After=network-online.target syslog.target
Wants=network-online.target

[Service]
Type=notify
NotifyAccess=all
PIDFile=/run/keepalived.pid
KillMode=process
EnvironmentFile=-/etc/sysconfig/keepalived
ExecStart=/usr/sbin/keepalived --dont-fork $KEEPALIVED_OPTIONS
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target
```
Looking at the systemd.service(5) man page suggests that you need `Type=notify` for what I described to work.

**Comment by VigneshSP94** [comment] 2023-07-19 09:27
@pqarmitage thank you for the systemd file.

I noticed you tested with notify. is notify the preferred type instead of forking?  my service type is of `Type=Forking`.

As per systemd doc, only [notify](https://www.freedesktop.org/software/systemd/man/sd_notify.html#:~:text=RELOADING%3D1-,Tells,-the%20service%20manager) will use the socket to communicate to the systemd about the status reload.

I was able to reproduce the issue with the steps you provided with notify but not with forking. Could there be more to this issue than systemd timeout? I'm keep testing this in my lab, just want to know your thoughts.

**Comment by VigneshSP94** [comment] 2023-07-25 03:17
@pqarmitage Could you kindly take a moment to review my last comment this issue? thank you.

**Comment by pqarmitage** [comment] 2023-07-25 11:39
@VigneshSP94 Apologies for not replying sooner; I was away for a week on holiday.

`Type=notify`provides better integration with systemd that `Type=forking`; it means that systemd knows when keepalived starts and finishes reloading, and `systemctl status keepalived` will show the reload in progress. My recommendation is to use `Type=notify` for the better integration with systemd.

`I was able to reproduce the issue with the steps you provided with notify but not with forking.` - were you using the unpatched code or patched code for this?

There is certainly an issue with the unpatched code due to the length of time it takes to reload with your configuration. I think you need to use the patched code. I am not aware of any further issue that should cause a systemd timeout.

**Comment by VigneshSP94** [comment] 2023-08-03 13:38
@pqarmitage thank you for confirming.

I cloned the master and compiled it.

```
Keepalived v2.2.8 (07/26,2023), git commit v2.2.8-33-g4c5f0057

Copyright(C) 2001-2023 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.4.73
Running on Linux 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020
Distro: Ubuntu 20.04 LTS

configure options:

Config options:  LIBIPSET_DYNAMIC NFTABLES LVS VRRP VRRP_AUTH VRRP_VMAC OLD_CHKSUM_COMPAT INIT=systemd

System options:  VSYSLOG MEMFD_CREATE IPV6_MULTICAST_ALL IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA IPTABLES NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_IPVLAN IFLA_LINK_NETNSID GLOB_BRACE GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE VRF SO_MARK

```
Type forking
with the 2.2.8
```
Aug 03 11:06:01 ipvs Keepalived[2743313]: Reload complete
Aug 03 11:04:24 ipvs Keepalived_healthcheckers[2743314]: Reloading
Aug 03 11:03:22 ipvs systemd[1]: Reloaded  Keepalive Daemon (LVS).
Aug 03 11:03:22 ipvs Keepalived[2743313]: Reloading ...
Aug 03 11:03:22 ipvs systemd[1]: Reloading  Keepalive Daemon (LVS).
```

with 2.2.4
```
Aug 03 11:14:10 ipvs Keepalived[2756109]: Reload complete
Aug 03 11:12:59 ipvs Keepalived_healthcheckers[2756110]: Reloading
Aug 03 11:12:29 ipvs systemd[1]: Reloaded  Keepalive Daemon (LVS).
Aug 03 11:12:29 ipvs Keepalived[2756109]: Reloading ...
Aug 03 11:12:29 ipvs systemd[1]: Reloading  Keepalive Daemon (LVS).
```

not a lot of difference between the reload timing.

Type notify won't even start the process as timeout hits way before.

this is with ~25k real servers and 2k virtual servers.

I saw reload timing was very low in the logs you posted, is there anything else I should take into consideration about configuration?
