### ISSUE TITLE
keepalived lost track of an entire VS despite reloads

### ISSUE THREAD

**Issue by pierrecdn** [acassen/keepalived#1904] opened 2021-05-17 10:59 UTC
**Describe the bug**
Using keepalived 2.2.2 and IPVS setup, we ended up at some point with a correct configuration but no change reflected on ipvs anymore, for a given VS.

**To Reproduce**
This is a long-running thing. The only thing I can tell is that we maintain a relatively high pressure on reload events (up to 1 each 15s) and that our config is quite large. Also, we've seen a specific log output for the VS (see `System log entries` section)

**Expected behavior**
A reload should align with what is present in the config file.

**Keepalived version**
Noticed in 2.2.1 and 2.2.2.
Here's the output for 2.2.2:
```
Keepalived v2.2.2 (03/05,2021)

Copyright(C) 2001-2021 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.10.20
Running on Linux 5.10.32-1.el7.x86_64 #1 SMP Fri Apr 23 12:01:09 UTC 2021
Distro: CentOS Linux 7 (Core)

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-vrrp --enable-sha1 --enable-regex :--enable-dump-threads} --with-init=systemd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu target_alias=:--enable-dump-threads} PKG_CONFIG_PATH=/opt/rh/devtoolset-9/root/usr/lib64/pkgconfig::/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld

Config options:  LVS REGEX OLD_CHKSUM_COMPAT INIT=systemd

System options:  VSYSLOG LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE GLOB_BRACE GLOB_ALTDIRFUNC SO_MARK

```

**Distro (please complete the following information):**
 - Name: CentOS
 - Version: 7.9
 - Architecture: x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
No, bare-metal.

**Configuration file:**
An extract of this VS config (they are all very similar)
```
# Consul-based health-check
$HEALTHCHECK_DEFINITION=\
    HTTP_GET { \
        connect_ip ${CHECK_IP} \
        connect_port 8500 \
        url { \
            path /v1/agent/health/service/name/${SERVICE_NAME}?format=text \
            status_code 200 429 \
        } \
    }


$VS_NAME=foo-bar
virtual_server_group ${VS_NAME} {
    <VIP1-IPv4> 80
    <VIP1-IPv4> 443
    <VIP1-IPv6> 80
    <VIP1-IPv6> 443
}
virtual_server group ${VS_NAME} {
    $VS_COMMON_OPTIONS
    protocol tcp
    lvs_method TUN type ipip
    lvs_sched mh
    delay_loop 10
    connect_timeout 10
    retry 3
    warmup 5
    real_server 192.0.2.1 {
        weight 2
        $CHECK_IP=192.0.2.1
        $HEALTHCHECK_DEFINITION
    }
    real_server 192.0.2.2 {
        weight 2
        $CHECK_IP=192.0.2.2
        $HEALTHCHECK_DEFINITION
    }
    real_server 192.0.2.3 {
        weight 2
        $CHECK_IP=192.0.2.3
        $HEALTHCHECK_DEFINITION
    }
}
```

**Notify and track scripts**
None

**System Log entries**
This thing has been observed for the service which then disappeared:
```
May 16 18:37:28 lb-l401-par Keepalived_healthcheckers_lvs[4787]: service [192.0.2.2]:tcp:0 no longer exist
May 16 18:37:28 lb-l401-par Keepalived_healthcheckers_lvs[4787]: Removing service [192.0.2.2]:tcp:0 from VS [foo-bar]:0
May 16 18:37:28 lb-l401-par Keepalived_healthcheckers_lvs[4787]: IPVS cmd IP_VS_SO_SET_DELDEST(1160) error: No such destination(2)
May 16 18:37:28 lb-l401-par Keepalived_healthcheckers_lvs[4787]: IPVS cmd IP_VS_SO_SET_DELDEST(1160) error: No such destination(2)
May 16 18:37:28 lb-l401-par Keepalived_healthcheckers_lvs[4787]: IPVS cmd IP_VS_SO_SET_DELDEST(1160) error: No such destination(2)
May 16 18:37:28 lb-l401-par Keepalived_healthcheckers_lvs[4787]: IPVS cmd IP_VS_SO_SET_DELDEST(1160) error: No such destination(2)
```

**Did keepalived coredump?**
No

**Additional context**

**Comment by pqarmitage** [comment] 2021-05-17 12:06
@pierrecdn This is going to be really difficult to track down what was happening here. To start with I will need to see the complete configuration, since there may be some strange interaction between different parts of the configuration. I will also need to see the full keepalived logs from the time when keepalived started, in case there is anything else logged which may not seem to be obviously related but somehow has an impact. Were there any IP_VS_SO_SET_ADDDEST errors logged at any time?

Am I correct in guessing that the log entries shown above were written when the configuration was being reloaded? Could you please also describe the sort of changes that are being made to the configuration when it is reloaded.

Other than a bug in keepalived (which I am not ruling out but I am not aware of an issue like this) the only possibilities that I can think of are:
i) Something else deleted the RSs from the VS before a new configuration removed them
ii) There is some duplication in the configuration.

**Comment by pierrecdn** [comment] 2021-05-17 16:22
> To start with I will need to see the complete configuration, since there may be some strange interaction between different parts of the configuration. I will also need to see the full keepalived logs from the time when keepalived started, in case there is anything else logged which may not seem to be obviously related but somehow has an impact.

I can provide all of this by email. Is it OK for you?

>Were there any IP_VS_SO_SET_ADDDEST errors logged at any time?

Yes, and that may be a good lead:
```
May 16 17:58:34 lb-l401-par Keepalived_healthcheckers_lvs[4787]: IPVS cmd IP_VS_SO_SET_ADDDEST(1159) error: Destination already exists(17)
May 16 17:58:34 lb-l401-par Keepalived_healthcheckers_lvs[4787]: IPVS cmd IP_VS_SO_SET_ADDDEST(1159) error: Destination already exists(17)
May 16 17:58:34 lb-l401-par Keepalived_healthcheckers_lvs[4787]: IPVS cmd IP_VS_SO_SET_ADDDEST(1159) error: Destination already exists(17)
May 16 17:58:34 lb-l401-par Keepalived_healthcheckers_lvs[4787]: IPVS cmd IP_VS_SO_SET_ADDDEST(1159) error: Destination already exists(17)
```

> Am I correct in guessing that the log entries shown above were written when the configuration was being reloaded? 

Yes, but this is actually printed after the `Reload complete` message.

> Could you please also describe the sort of changes that are being made to the configuration when it is reloaded.

Very often it is creating or deleting a VS or updating its definition (most of the time, a different VS than the one that went into this weird state). To be sure that keepalived runtime is aligned with the intention, a reload is requested by our automation software.

**Comment by pqarmitage** [comment] 2021-05-17 17:22
@pierrecdn Providing the information by email is fine for me. You can find my email address in any of my commits.

Since you are getting the IP_VS_SO_SET_ADDDEST Destination already exists errors, that means that the RS is already configured when keepalived is attempting to add it again. When keepalived attempts to remove the RS, since (I am guessing) it was configured twice, it attempts to remove it twice, and the second time fails.

**Comment by pqarmitage** [comment] 2021-05-17 17:24
I should add that keepalived does not check that there is no duplication of VSs and RSs in the config. I have thought about doing that but decided it is not worth it. Perhaps if keepalived gets the `Destination already exists` error it should check if there is any duplication in the configuration.

**Comment by pqarmitage** [comment] 2021-05-19 09:11
@pierrecdn The "Reload complete" message is logged by the parent process, once all the child processes (VRRP, Healthhecker_lvs and BFD) have completed reading the configuration file(s). If keepalived is being run as a keepalived service and the service type is `notify`, then the parent process also notifies systemd that the reload is complete, in the sense that it is then safe to modify the configuration file(s) again (anyone using automated updating of the keepalived configuration file(s) should really be using this feature).

The child processes really do most of their reload work after they have completed reading the configuration files (e.g. adding new VS/RS and deleting removed VS/RS), and so it is to be expected (if a bit confusing) that the "Reload complete" message is logged before the IP_VS_SO_SET_DELDEST messages.

**Comment by pierrecdn** [comment] 2021-05-19 14:29
Unfortunately I've no logs anymore, the server was reimaged in between.
From what I'm seeing, I've no duplication in my config that could explain all of this.

> the service type is notify, then the parent process also notifies systemd that the reload is complete, in the sense that it is then safe to modify the configuration file(s) again (anyone using automated updating of the keepalived configuration file(s) should really be using this feature).

I understand you recommend to move to this method. Indeed, my current setup make use of `Type=forking`.

**Comment by pqarmitage** [comment] 2021-05-19 15:06
@pierrecdn It would still be very helpful to have a copy of your configuration so that I can try running it myself to try and reproduce the problem.

**Comment by pqarmitage** [comment] 2021-05-26 08:16
@pierrecdn I haven't been able to find anything wrong with the configuration you provided, nor have I found a way to reproduce the problem, other than by having a duplicate RS in the configuration.

I have merged commit a0f9bd1 which will include with `IPVS cmd IP_VS_SO_SET_DELDEST` etc error log entries the details of the virtual server and real server.

You state that you are reloading the configuration up to once every 15 seconds. Is it possible for two reloads to occur within a few milli-seconds of each other? If so it is possible for one reload to interfere with the previous one unless the service file uses `Type=notify` and you also initiate the reload by running `systemctl reload keepalived`.

A further possibility to help track down this problem would be to save copies of the configuration before and after each reload when a problem occurs, and also keepalived's internal state (/etc/keepalived_check.data that is generated by sending SIGUSR1 to the keepalived parent process). If I produce a patch to do this would you be happy to run with it until there is another occurrence of the problem?

**Comment by pierrecdn** [comment] 2021-05-31 08:02
> I have merged commit a0f9bd1 which will include with IPVS cmd IP_VS_SO_SET_DELDEST etc error log entries the details of the virtual server and real server.

Thanks, I'll keep you aware if I'm seeing such a case.

> You state that you are reloading the configuration up to once every 15 seconds. Is it possible for two reloads to occur within a few milli-seconds of each other?

No, we've seen that this was very error-prone in the past, so we keep track of reload needs and do them at once, maximum every 15 seconds.

> If so it is possible for one reload to interfere with the previous one unless the service file uses Type=notify and you also initiate the reload by running systemctl reload keepalived.

As said, indeed it is not using `Type=notify` for now. I'll move to this soon.

> A further possibility to help track down this problem would be to save copies of the configuration before and after each reload when a problem occurs, and also keepalived's internal state (/etc/keepalived_check.data that is generated by sending SIGUSR1 to the keepalived parent process). If I produce a patch to do this would you be happy to run with it until there is another occurrence of the problem?

Sure I can!

**Comment by pqarmitage** [comment] 2021-06-06 14:55
@pierrecdn Apologies for the delay in producing the patch, but it is now attached. The code in the patch is not elegant, but it should be sufficient for this issue.

The patched code will create a directory called dumps in the same directory as your keepalived.conf config file. In the dumps directory it will save a copy of the configuration at startup and after each reload. The checker process will also dump its internal state before and after each reload. The file names in the dumps directory will include the pid of the process writing the file and a sequence number (the config file written when keepalived starts will have a different pid to the one used for reloads).

It will be important to preserve all the keepalived syslog entries, so that what is logged can be matched against the dumps of keepalived's internal state.

Once you are running the patched keepalived, you will need to monitor for the problem occurring, and then save the system logs and the contents of the dumps directory, and we can then have a look at all the data to see what is happening.

[save_config_dump.patch.txt](https://github.com/acassen/keepalived/files/6604353/save_config_dump.patch.txt)

**Comment by pqarmitage** [comment] 2021-06-23 12:45
@pierrecdn Is there any update on this?

**Comment by pqarmitage** [comment] 2021-07-26 08:34
Closing due to no response for over 1 month. It is most likely that the problem was due to a duplicate real server in the configuration.

If this problem recurs and there is more information available we can reopen this issue.

**Closed by pqarmitage** 2021-07-26 08:34 UTC

**Comment by pierrecdn** [comment] 2021-08-16 08:25
Sorry for that, I left for quite a while and then didn't notice recent activity.
I'm seeing that you've embedded this patch into 2.2.3 as part of #1960. I'll give a try to this version with `config_save_dir`.

**Comment by pierrecdn** [comment] 2021-08-16 08:56
I got a few issue at doing so (compiling), logged https://github.com/acassen/keepalived/issues/1965
