### ISSUE TITLE
Keepalived_vrrp exited due to segmentation fault (SIGSEGV)

### ISSUE THREAD

**Issue by ambiadnb** [acassen/keepalived#1867] opened 2021-03-04 09:38 UTC
Hi,

I need help with an issue I have with a keepalived vrrp instance.
When I start the service via systemctl it immediately exits and restarts the process again. This happens over and over.
I already googled for the issue, but unfortunately didn't find anything. Also the error message in the log states that I should report a bug here on github.

This is the log entry I get:
**/var/log/messages**
```
Mar  4 10:08:43 tftphost1 Keepalived[39362]: Keepalived_vrrp exited due to segmentation fault (SIGSEGV).
Mar  4 10:08:43 tftphost1 Keepalived[39362]:   Please report a bug at https://github.com/acassen/keepalived/issues
Mar  4 10:08:43 tftphost1 Keepalived[39362]:   and include this log from when keepalived started, a description
Mar  4 10:08:43 tftphost1 Keepalived[39362]:   of what happened before the crash, your configuration file and the details below.
Mar  4 10:08:43 tftphost1 Keepalived[39362]:   Also provide the output of keepalived -v, what Linux distro and version
Mar  4 10:08:43 tftphost1 Keepalived[39362]:   you are running on, and whether keepalived is being run in a container or VM.
Mar  4 10:08:43 tftphost1 Keepalived[39362]:   A failure to provide all this information may mean the crash cannot be investigated.
Mar  4 10:08:43 tftphost1 Keepalived[39362]:   If you are able to provide a stack backtrace with gdb that would really help.
Mar  4 10:08:43 tftphost1 Keepalived[39362]:   Source version 2.0.10 
Mar  4 10:08:43 tftphost1 Keepalived[39362]:   Built with kernel headers for Linux 4.18.0
Mar  4 10:08:43 tftphost1 Keepalived[39362]:   Running on Linux 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021
Mar  4 10:08:43 tftphost1 Keepalived[39362]:   Command line: '/usr/sbin/keepalived' '-D'
Mar  4 10:08:43 tftphost1 Keepalived[39362]:   configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix=
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                      --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                      --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                      --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                      --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                      --infodir=/usr/share/info --disable-libiptc --disable-ipset --enable-snmp
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                      --enable-snmp-rfc --enable-sha1 --with-init=systemd
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                      build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                      PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                      -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                      -fexceptions -fstack-protector-strong -grecord-gcc-switches
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                      -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                      -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                      -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                      LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
Mar  4 10:08:43 tftphost1 Keepalived[39362]:   Config options: LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                   SNMP_RFCV2 SNMP_RFCV3
Mar  4 10:08:43 tftphost1 Keepalived[39362]:   System options: PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF LIBNL3 RTA_ENCAP
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                   RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                   RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                   RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                   FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                   LWTUNNEL_ENCAP_ILA LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                   IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                   SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT
Mar  4 10:08:43 tftphost1 Keepalived[39362]:                   SCHED_RESET_ON_FORK
Mar  4 10:08:43 tftphost1 Keepalived[39362]: VRRP child process(39594) died: Respawning
Mar  4 10:08:43 tftphost1 Keepalived[39362]: Starting VRRP child process, pid=39595
Mar  4 10:08:43 tftphost1 Keepalived_vrrp[39595]: Registering Kernel netlink reflector
Mar  4 10:08:43 tftphost1 Keepalived_vrrp[39595]: Registering Kernel netlink command channel
Mar  4 10:08:43 tftphost1 Keepalived_vrrp[39595]: Opening file '/etc/keepalived/keepalived.conf'.
```

Additional system info:

**Keepalived version**
```
Keepalived v2.0.10 (11/12,2018)

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.18.0
Running on Linux 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-libiptc --disable-ipset --enable-snmp --enable-snmp-rfc --enable-sha1 --with-init=systemd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld

Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK
```

**Distro:**
 - Name: CentOS
 - Version: 8.3.2011
 - Architecture: x86_64
 - Kernel: Linux 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021

The host where I am trying to run keepalived is a CentOS LXD container running on an Ubuntu 20.04.2 physical machine. Therefore the Ubuntu kernel with CentOS. 
The LXD version I am using is: 4.0.4

**Configuration file:**
```
! Configuration File for keepalived

global_defs {
    router_id tftphost1
    enable_script_security
}

vrrp_script chk_ping_gw {
    script "/bin/ping 192.198.100.1 -c1"
    interval 3
    fall 3
    rise 2
}

vrrp_instance TFTP_VIP_1 {
    state MASTER
    interface eth2.210
    virtual_router_id 10
    priority 101
    advert_int 2
    authentication {
        auth_type PASS
        auth_pass <some password>
    }

    virtual_ipaddress {
        192.198.100.8 dev eth2.210
    }

    track_script {
        chk_ping_gw
    }
    
    track_interface {
        eth2.210
    }

    unicast_src_ip 192.198.100.4
    unicast_peer {
      192.198.100.5
    }
}

```

Any help would be much appreciated.
Thank you

**Comment by pqarmitage** [comment] 2021-03-04 11:58
@ambiadnb Are you able to try running the configuration on the CentOS system to see whether that segfaults or not? I have run your configuration on RHEL8.3 using the RHEL keepalived, which has the same output for `keepalived -v` as you have, and it runs without a problem, although I wasn't running it .

I suspect the problem relates to running a CentOS build of keepalived on a Ubuntu system, but exactly what the problem is I do not know. My guess would be some library incompatibility.

The only way I can see of moving this forward is if you can get a coredump when keepalived segfaults, and then use gdb to produce a stack backtrace with all the keepalived symbols (doing that on CentOS would mean having the keepalived-debuginfo package installed). It might be that if you are able to copy the coredump file to a CentOS 8.3 system that running gdb would produce a meaningful stack backtrace.

**Comment by pqarmitage** [comment] 2021-03-19 07:50
Closing due to no response for over 2 weeks. If further information is provided we can reopen this issue.

**Closed** 2021-03-19 07:50 UTC
