### ISSUE TITLE
Keepalived requires two restarts

### ISSUE THREAD

**Issue by jzielke-nli** [acassen/keepalived#715] opened 2017-12-14 10:18 UTC
Restarting keepalived on Ubuntu 16.04 behaves weird on restarting using systemctl.

When using systemctl restart keepalived once:

````
● keepalived.service - LSB: Starts keepalived
   Loaded: loaded (/etc/init.d/keepalived; bad; vendor preset: enabled)
   Active: active (running) since Thu 2017-12-14 11:12:42 CET; 755ms ago
     Docs: man:systemd-sysv-generator(8)
  Process: 7375 ExecStop=/etc/init.d/keepalived stop (code=exited, status=0/SUCCESS)
  Process: 7383 ExecStart=/etc/init.d/keepalived start (code=exited, status=0/SUCCESS)
    Tasks: 2
   Memory: 540.0K
      CPU: 6ms
   CGroup: /system.slice/keepalived.service
           ├─7185 /usr/sbin/keepalived
           └─7187 /usr/sbin/keepalived

Dec 14 11:12:42 *************** systemd[1]: Stopped LSB: Starts keepalived.
Dec 14 11:12:42 *************** systemd[1]: Starting LSB: Starts keepalived...
Dec 14 11:12:42 *************** keepalived[7383]:  * Starting keepalived keepalived
Dec 14 11:12:42 *************** keepalived[7383]:    ...fail!
Dec 14 11:12:42 *************** systemd[1]: Started LSB: Starts keepalived.
````

When Issuing the same command again:

````
● keepalived.service - LSB: Starts keepalived
   Loaded: loaded (/etc/init.d/keepalived; bad; vendor preset: enabled)
   Active: active (running) since Thu 2017-12-14 11:13:14 CET; 780ms ago
     Docs: man:systemd-sysv-generator(8)
  Process: 7395 ExecStop=/etc/init.d/keepalived stop (code=exited, status=0/SUCCESS)
  Process: 7405 ExecStart=/etc/init.d/keepalived start (code=exited, status=0/SUCCESS)
    Tasks: 3
   Memory: 792.0K
      CPU: 15ms
   CGroup: /system.slice/keepalived.service
           ├─7414 /usr/sbin/keepalived
           ├─7415 /usr/sbin/keepalived
           └─7416 /usr/sbin/keepalived

Dec 14 11:13:14 *************** Keepalived_healthcheckers[7415]: Using LinkWatch kernel netlink reflector...
Dec 14 11:13:14 *************** Keepalived_vrrp[7416]: Registering Kernel netlink reflector
Dec 14 11:13:14 *************** Keepalived_vrrp[7416]: Registering Kernel netlink command channel
Dec 14 11:13:14 *************** Keepalived_vrrp[7416]: Registering gratuitous ARP shared channel
Dec 14 11:13:14 *************** Keepalived_vrrp[7416]: Opening file '/etc/keepalived/keepalived.conf'.
Dec 14 11:13:14 *************** Keepalived_vrrp[7416]: Using LinkWatch kernel netlink reflector...
Dec 14 11:13:14 *************** Keepalived_vrrp[7416]: VRRP_Script(chk_haproxy) succeeded
Dec 14 11:13:14 *************** Keepalived_vrrp[7416]: VRRP_Instance(*************** ) Transition to MASTER STATE
Dec 14 11:13:14 *************** Keepalived_vrrp[7416]: VRRP_Instance(*************** ) Received higher prio advert 103
Dec 14 11:13:14 *************** Keepalived_vrrp[7416]: VRRP_Instance(*************** ) Entering BACKUP STATE
````

When using systemctl stop and systemctl start seperately it works fine.

**Comment by pqarmitage** [comment] 2017-12-14 19:22
I have tried this on my Ubuntu 16.04.3 virtual machine and `systemctl restart keepalived` doesn't exhibit this problem for me.

It looks to me as though you have an old version of either keepalived or the service initialisation system installed.

It appears to me that systemctl is using the old systemd LSB scripts to control keepalived.

If I run `/etc/init.d/keepalived start` etc I get the message `[ok] Starting keepalived (via systemctl): keepalived.service`
and `systemctl status keepalived`has the line
`Process: 7034 ExecStart=/usr/sbin/keepalived $DAEMON_ARGS (code=exited, status=0/SUCCESS)`
whereas you have
`Process: 7383 ExecStart=/etc/init.d/keepalived start (code=exited, status=0/SUCCESS)`
so you are using systemd LSB scripts whereas my system is using systemctl scripts.

Looking at what is happening on your system in more detail, it appears that you have
```
  Process: 7375 ExecStop=/etc/init.d/keepalived stop (code=exited, status=0/SUCCESS)
  Process: 7383 ExecStart=/etc/init.d/keepalived start (code=exited, status=0/SUCCESS)
```
and two keepalived processes running with PIDs 7185 and 7187 which are older PIDs that the ExecStop and ExecStart processes. I think the ExecStop process hasn't successfully stopped all the old keepalived processes, and as a consequence starting the new keepalived fails. It may be that by the time you run `systemctl start` a second time there has been time for the old keepalived processes to terminate and so the new keepalived starts successfully. Likewise, when you do `systemctl stop` followed by `systemctl start`, enough time has elapsed after the stop that keepalived has fully terminated and so the start is then successful.

In `/etc/init.d/keepalived` on my system, there is a 1 second delay between stopping keepalived and starting it again. It may be that you either need to add such a delay or extend it.

This appears to be a ubuntu problem with the service start/stop activities. I would suggest you upgrade to the latest versions and if you still have a problem report it to ubuntu keepalived support.

I have the following package versions installed:
keepalived 1:1.2.19-1ubuntu0.2
systemd 229-4ubuntu21
initscripts 2.88dsf-59.3ubuntu2

BTW, keepalived v1.2.19 is very old. Ubuntu has a snap package of keepalived that is kept up-to-date, and is currently keepalived v1.3.9 git commit 19b0b98 which I committed 6 hours ago.

**Comment by pqarmitage** [comment] 2018-01-18 10:46
Closing due to no response for over 1 month.

**Comment by jzielke-nli** [comment] 2018-01-18 10:50
Sorry for the delay. Projects jept me busy.

Installed Keepalived is 1.2.23~ubuntu16.04.1. Since keepalived normally works fine with any other service under ubuntu I think it's more a problem of keepalived not signaling correctly when being shutdown or not. It shouldn't be ubuntu's fault if old pids get stuck.

**Comment by jzielke-nli** [comment] 2018-01-18 10:53
Sorry for the delay. Projects kept me busy.

Installed Keepalived is 1.2.23~ubuntu16.04.1 which is the latest stable from keepalived's ppa. Since systemd normally works fine with any other service under ubuntu I think it's more a problem of keepalived not signaling correctly when being shutdown or not. It shouldn't be ubuntu's fault if old pids get stuck.

We need keepalived for production so running latest commits without any stability testing is out of question.

Please reopen issue.

**Comment by pqarmitage** [comment] 2018-01-19 12:43
@jzielke-nli The script `/etc/init.d/keepalived` that was being run with your restarts shown above cannot be expected to work reliably. For a restart it executes the following:
```
  restart)
        log_action_begin_msg "Restarting $DESC" "$NAME"

        start-stop-daemon --stop --quiet --pidfile \
                /var/run/$NAME.pid --exec $DAEMON || true
       sleep 1
       if start-stop-daemon --start --quiet --pidfile \
               /var/run/$NAME.pid --exec $DAEMON -- $DAEMON_ARGS; then
               log_end_msg 0
        else
                log_end_msg 1
        fi
       ;;
```
The problem is that the script does not wait for keepalived to terminate, but rather does `sleep 1`. This is never a good sign, since it cannot guarantee that keepalived has terminated. In fact, keepalived takes in excess of 1 second to terminate, since it itself does a `sleep(1);` during the shutdown process in order to increase the likelihood of IGMP leave group messages being sent.

The problem you have been experiencing lies with `/etc/init.d/keepalived` which is a file in the debian directory of the ubuntu source, and hence is provided by ubuntu/debian.

I suggest you file a bug report against Ubuntu requesting that they fix their init script.

**Closed by pqarmitage** 2018-01-19 12:43 UTC
