### ISSUE TITLE
Check script always fails

### ISSUE THREAD

**Issue by Montbuet** [acassen/keepalived#1984] opened 2021-08-30 13:32 UTC
**Describe the bug**
Keepalived fail to execute script and commands like:
```
script "/bin/systemctl status nfs-server"
```
Systemctl status keepalived returns "unable to access script /bin/systemctl"

When embedded in a bash script and logged to /tmp/log:
```
++Systemctl is-active nfs-server.servie
Failed to get D-Bus connection : Permission denied
```

**To Reproduce**
Centos 7.9.2009 in virtualbox
install keepaliveD
My script: (sorry can't copy/past from the VM)
[https://ibb.co/LJ9tT80](url)

**Expected behavior**
It should works

**Keepalived version**
(again sry for not being able to copy/paste)
[https://ibb.co/2PRN2wf](url)

**Distro (please complete the following information):**
Centos 7.9.2009 64 x86

**Details of any containerisation or hosted service (e.g. AWS)**
Virtual Box

**Configuration file:**
[https://ibb.co/9rWMDWp](url)

**Notify and track scripts**
[https://ibb.co/LJ9tT80](url)

**System Log entries**
...

**Did keepalived coredump?**
no

**Additional context**

**Comment by pqarmitage** [comment] 2021-08-30 14:10
I'm not clear what you mean by:
`Systemctl status keepalived returns "unable to access script /bin/systemctl"`

Does this mean that if you execute `systemctl status keepalived`, then you get the message `unable to access script /bin/systemctl`?

Your configuration shows a track_script entry `ping_check`, but that script is not defined in your configuration. You also have a notify script configured but you have not provided details of that.

Can you please provide copies of the keepalived system log entries. That may give as a clue about what is happening.

**Comment by Montbuet** [comment] 2021-08-30 14:27
> I'm not clear what you mean by:
> `Systemctl status keepalived returns "unable to access script /bin/systemctl"`
> 
> Does this mean that if you execute `systemctl status keepalived`, then you get the message `unable to access script /bin/systemctl`?
> 
> Your configuration shows a track_script entry `ping_check`, but that script is not defined in your configuration. You also have a notify script configured but you have not provided details of that.
> 
> Can you please provide copies of the keepalived system log entries. That may give as a clue about what is happening.

Hi @pqarmitage and ty for you answer.
Sorry for clarity issue, forget about ping_check it is not relevant, used for testing and forgot to remove it from my screen.
Here is what returns "service keepalived status -l" when using "script "/bin/systemctl status nfs-server" in check_nfs script:
https://ibb.co/WzpVqKV

Here is the notify.sh script:
https://ibb.co/zH6wbMr

Note: The exact same configuration seems to be working on another centos machine which is hosted elsewhere. I think that this issue is related with these local virtual machines. (both centos 7)

**Comment by pqarmitage** [comment] 2021-08-30 14:55
I have run your configuration in a CentOS 7 VM (albeit not VirtualBox, but that will make no difference). In fact, being in a VM makes no difference in this case.

The problem is caused by SELinux permissions. If you execute `setenforce permissive` before starting keepalived, then it can run the script without any problems (both "/usr/local/sbin/check_nfs.sh" and "/bin/systemctl status nfs-server"work). If while keepalived is running you execute `setenforce enforcing`, then keepalived stops being able to execute the script.

I don't know how, on CentOS 7, you go about working out what SELinux permissions you need to add to allow keepalived to execute either the script or /bin/systemctl. I know on Fedora the system log will tell you what commands to grant permission for what has been denied by SELinux.

I am sorry we can't help with resolving your SELinux policy issues, but that is outside the scope of the keepalived project. You will need to raise this with the relevant SELinux policy maintainers if you cannot resolve the issue yourself. It might we worth looking at current Fedora SELinux policies is respect of keepalived; I have in the past requested additional permissions for keepalived to allow it to do things such as execute scripts.

**Closed by pqarmitage** 2021-08-30 14:55 UTC

**Comment by Montbuet** [comment] 2021-08-30 15:02
Alright, `setenforce permissive` was an easy fix, thank you very much ! :)
