### ISSUE TITLE
Status Always be `backup` after start in Version 2.1.5

### ISSUE THREAD

**Issue by 79U** [acassen/keepalived#1804] opened 2020-12-08 10:52 UTC
**Describe the bug**
 Entering BACKUP STATE  (init)
```
Dec  8 18:32:05 localhost Keepalived[2873451]: Reloading ...
Dec  8 18:32:05 localhost Keepalived[2873451]: Opening file '/usr/local/keepalived/etc/keepalived.conf'.
Dec  8 18:32:05 localhost Keepalived[2873451]: Reloading ...
Dec  8 18:32:05 localhost Keepalived[2873451]: Opening file '/usr/local/keepalived/etc/keepalived.conf'.
Dec  8 18:32:05 localhost Keepalived[2873451]: Reloading ...
Dec  8 18:32:05 localhost Keepalived[2873451]: Opening file '/usr/local/keepalived/etc/keepalived.conf'.
Dec  8 18:32:05 localhost Keepalived[2873451]: Reloading ...
Dec  8 18:32:05 localhost Keepalived[2873451]: Opening file '/usr/local/keepalived/etc/keepalived.conf'.
Dec  8 18:32:05 localhost Keepalived[2873451]: Reloading ...
Dec  8 18:32:05 localhost Keepalived[2873451]: Opening file '/usr/local/keepalived/etc/keepalived.conf'.
Dec  8 18:32:05 localhost Keepalived[2873451]: Reloading ...
Dec  8 18:32:05 localhost Keepalived[2873451]: Opening file '/usr/local/keepalived/etc/keepalived.conf'.
Dec  8 18:32:05 localhost Keepalived[2873451]: Reloading ...
Dec  8 18:32:05 localhost Keepalived[2873451]: Opening file '/usr/local/keepalived/etc/keepalived.conf'.
Dec  8 18:32:05 localhost Keepalived[2873451]: Reloading ...
Dec  8 18:32:05 localhost Keepalived[2873451]: Opening file '/usr/local/keepalived/etc/keepalived.conf'.
Dec  8 18:32:05 localhost Keepalived[2873451]: Reloading ...
Dec  8 18:32:05 localhost Keepalived[2873451]: Opening file '/usr/local/keepalived/etc/keepalived.conf'.

```

**To Reproduce**
```
keepalived.conf

vrrp_instance v4 {
    state MASTER
    priority 100
    interface bond0
    use_vmac vrrp.v4
    vmac_xmit_base
    version 2
    nopreempt    # this parameter make so sense in result
    ......

vrrp_sync_group gv4 {
    group { 
        v4
        v6
    }

    track_script {
        chk_lb 
    }

    notify_master "script.sh master"
    notify_backup "script.sh  backup"
    notify_fault  "script.sh  fault"       
    ...
    # The program will be in dead loop when there were `reload` in these scripts.
}
```

**Keepalived version**
```
Keepalived v2.1.5 (07/13,2020)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 2.6.32
Running on Linux 3.18.27.linux #1 SMP Thu Mar 3 01:59:07 CST 2016

configure options: --prefix=/usr/local/keepalived.2.1.5 --disable-snmp --enable-strict-config-checks

Config options:  STRICT_CONFIG LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV6_ADVANCED_API LIBNL3 IP_MULTICAST_ALL NET_LINUX_IF_H_COLLISION NET_LINUX_IF_ETHER_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK VRRP_VMAC CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC GLOB_BRACE SO_MARK SCHED_RESET_ON_FORK
```

**Distro (please complete the following information):**
 - Name [ centos 6.5]
 - Version [keepalived 2.1.5]
 - Architecture [e.g. x86_64]

**Comment by pqarmitage** [comment] 2020-12-08 11:25
@79U Could you please explain what is meant by:
     `nopreempt    # this parameter make so sense in result`
and particularly
     `# The program will be in dead loop when there were `reload` in these scripts`

Can you please provide your full keepalived configuration and the scripts, so that we can test it. Does the vrrp process produce any logs during the reloads?

**Comment by 79U** [comment] 2020-12-08 15:14
`nopreempt # this parameter make so sense in result`

Sorry, wrong description;

This problem

The state of VRRP_instance is master. Why is keepalived initialized to backup in preemption mode, as shown in logs


log:
```
Dec  8 22:39:15 localhost Keepalived[1888537]: Starting Keepalived v2.1.5 (07/13,2020)
Dec  8 22:39:15 localhost Keepalived[1888537]: Running on Linux 3.18.27.linux #1 SMP Thu Mar 3 01:59:07 CST 2016 (built for Linux 2.6.32)
Dec  8 22:39:15 localhost Keepalived[1888537]: Command line: '/usr/local/keepalived/sbin/keepalived' '-D' '-f'
Dec  8 22:39:15 localhost Keepalived[1888537]:               '/usr/local/keepalived/etc/keepalived.conf'
Dec  8 22:39:15 localhost Keepalived[1888537]: Opening file '/usr/local/keepalived/etc/keepalived.conf'.
Dec  8 22:39:15 localhost Keepalived[1888537]: Opening file '/usr/local/keepalived/etc/vserver.conf'.
Dec  8 22:39:15 localhost Keepalived[1888538]: Starting Healthcheck child process, pid=1888539
Dec  8 22:39:15 localhost Keepalived[1888538]: Starting VRRP child process, pid=1888540
Dec  8 22:39:15 localhost Keepalived_healthcheckers[1888539]: Opening file '/usr/local/keepalived/etc/keepalived.conf'.
Dec  8 22:39:15 localhost Keepalived_healthcheckers[1888539]: Opening file '/usr/local/keepalived/etc/vserver.conf'.
Dec  8 22:39:15 localhost Keepalived_healthcheckers[1888539]: Initializing ipvs
Dec  8 22:39:15 localhost Keepalived_healthcheckers[1888539]: Gained quorum 1+0=1 <= 108 for VS FWM 11
Dec  8 22:39:15 localhost Keepalived_healthcheckers[1888539]: Activating healthchecker for service [x.x.x.x]:none:0 for VS FWM 11
Dec  8 22:39:15 localhost Keepalived_healthcheckers[1888539]: Activating healthchecker for service [x.x.x.x]:none:0 for VS FWM 11
Dec  8 22:39:15 localhost Keepalived_healthcheckers[1888539]: Activating healthchecker for service [x.x.x.x]:none:0 for VS FWM 11
Dec  8 22:39:15 localhost Keepalived_vrrp[1888540]: Registering Kernel netlink reflector
Dec  8 22:39:15 localhost Keepalived_vrrp[1888540]: Registering Kernel netlink command channel
Dec  8 22:39:15 localhost Keepalived_vrrp[1888540]: Opening file '/usr/local/keepalived/etc/keepalived.conf'.
Dec  8 22:39:15 localhost Keepalived_vrrp[1888540]: Opening file '/usr/local/keepalived/etc/virtual_server.conf'.
Dec  8 22:39:15 localhost Keepalived_vrrp[1888540]: Assigned address x.x.x.x for interface bond0
Dec  8 22:39:15 localhost Keepalived_vrrp[1888540]: Assigned address x::x::x::x for interface bond0
Dec  8 22:39:15 localhost Keepalived_vrrp[1888540]: (v4): Success creating VMAC interface vrrp.v4
Dec  8 22:39:15 localhost Keepalived_vrrp[1888540]: Registering gratuitous ARP shared channel
Dec  8 22:39:15 localhost Keepalived_vrrp[1888540]: VRRP sockpool: [ifindex(  6), family(IPv4), proto(112), fd(11,12)]
Dec  8 22:39:15 localhost Keepalived_vrrp[1888540]: VRRP_Script(chk_lb) succeeded
Dec  8 22:39:15 localhost Keepalived_vrrp[1888540]: (v4) Entering BACKUP STATE
Dec  8 22:39:16 localhost Keepalived_healthcheckers[1888539]: Remote Web server [x.x.x.x]:none:0 succeed on service.
Dec  8 22:39:17 localhost Keepalived_healthcheckers[1888539]: Remote Web server [x.x.x.x]:none:0 succeed on service.
Dec  8 22:39:18 localhost Keepalived_healthcheckers[1888539]: Remote Web server [x.x.x.x]:none:0 succeed on service.

```

conf:

```

# cat /usr/local/keepalived/etc/keepalived.conf 

! Configuration File for keepalived

global_defs {
    router_id  LB

      ......

}


vrrp_script chk_lb {
    script "/usr/local/keepalived/bin/check.sh check"
    interval 3
    timeout 2
}


vrrp_instance v4{
    state MASTER
    priority 100
    interface bond0
    use_vmac vrrp.v4
    vmac_xmit_base
    advert_int 3
    version 2
    virtual_router_id 93
    authentication {
        auth_type  xxxxxx
        auth_pass xxxxxx
    }

    track_script {
        chk_lb
    }

    notify_master "/usr/local/keepalived/bin/to_master.sh master"
    notify_backup "/usr/local/keepalived/bin/to_backup.sh backup"
    notify_fault  "/usr/local/keepalived/bin/to_fault.sh fault"

    virtual_ipaddress {
        x.x.x.x
    }
}

include /usr/local/keepalived/etc/vserver.conf
```

`The program will be in dead loop when there were reload in these scripts`

Sorry, wrong description;

This problem

`vrrp_sync_group`  -->   `track_script`  /   `notify_master`  /  `notify_backup`  /  `notify_fulat`  /  `notify`   In these configuration items, if reload Keepalived exists in the script being executed, keepalived will loop forever and be reloaded at run time

conf:

```
vrrp_script chk_lb {
    script  "script.sh check"
    interval 3 
    timeout 2
}

vrrp_sync_group gv4 {
    group { 
        v4
        v6
    }

    track_script {
        chk_lb 
    }

    notify_master "script.sh master"
    notify_backup "script.sh  backup"
    notify_fault  "script.sh  fault"       
}

vrrp_instance v4{
    state MASTER
    priority 100
    interface bond0
    use_vmac vrrp.v4
    vmac_xmit_base
    advert_int 3
    version 2
    virtual_router_id 93
    authentication {
        auth_type  xxxxxx
        auth_pass xxxxxx
    }
    virtual_ipaddress {
        x.x.x.x
    }
}

vrrp_instance v6{
    state MASTER
    priority 100
    interface bond0
    use_vmac vrrp.v6
    vmac_xmit_base
    advert_int 3
    version 2
    virtual_router_id 94

    virtual_ipaddress {
        x:x::x:x::x
    }
}

```
script.sh 

```
to_master() {
     kill -HUP $(cat /run/keepalived.pid)      
}

to_backup() {
     kill -HUP $(cat /run/keepalived.pid)      
}

to_fault() {
     kill -HUP $(cat /run/keepalived.pid)      
}

to_check() {
     kill -HUP $(cat /run/keepalived.pid)     
}

case $1 in 
     check)
          to_check
           ;;
     master)
          to_master
           ;;
     backup)
          to_backup
           ;;
     fault)
          to_fault
           ;;
      *)
           echo
           ;;
esac
```

Keepalived turns on and goes to unlimited Reload; 

To_master can contain reload keepalived, but nothing else

**Comment by pqarmitage** [comment] 2020-12-09 17:37
I think there are two issues here.

> 1. Why does the VRRP instance start in backup mode, even when the configuration has `state MASTER`?

This is to ensure that there isn't a VRRP protocol violation. A VRRP instance can only go straight to master if its priority is 255 (known as the address owner). If the priority is less than 255, it is possible for there to be a higher priority master, so the VRRP instance starting up has to listen for at least one advert period to ensure that there isn't a higher priority master, so it starts in backup state.

As the keepalived.conf(5) man page states:
```
        vrrp_instance <STRING> {
           # Initial state, MASTER|BACKUP
           # As soon as the other machine(s) come up,
           # an election will be held and the machine
           # with the highest priority will become MASTER.
           # So the entry here doesn't matter a whole lot.
           state MASTER
```
What `state MASTER` does is, if the priority of the VRRP instance is 255 the VRRP instance will transition to master immediately everything is configured; otherwise it will wait for 3 advert intervals plus a bit before transitioning to master.

> 2. keepalived loops reloading

I note that your script.sh does not have an exit statement at the end, and so the exit code returned to keepalived may not be reliably. It would be a good idea to add `exit 0` at the end of the script.

What your configuration and script appears to be doing is reloading keepalived every three seconds, and also reloading keepalived on every state change. While I agree that keepalived shouldn't enter a tight loop of reloading, as it appears to be, we most certainly would not support repeatedly reloading like this. If you can explain why you are doing this, it may be that we can suggest a better alternative. 

`state MASTER` and `nopreempt` are contradictory since a VRRP instance cannot become master without preempting if there is already a VRRP instance running; indeed keepalived logs an error if both are configured.

**Comment by 79U** [comment] 2020-12-10 04:42
I'm sorry.

There are two problems here.

I thought the two questions were related,

So I posed a question

Question 1：

There is only one instance of VRRP, the preemption mode, the first to keep alive by starting

Start the 2.1.5 configuration with 1.4.5, 1.4.5 will add the LVS configuration after entering the Mster state, however, 2.1.5 is initialized to become a backup and remove lv configuration, because no broadcast is received to switch to master, you can compare the 1.4.5 and 2.1.5 logs

conf
```
# cat /usr/local/keepalived/etc/keepalived.conf 

! Configuration File for keepalived

global_defs {
    router_id  LB

      ......

}


vrrp_script chk_lb {
    script "/usr/local/keepalived/bin/check.sh check"
    interval 3
    timeout 2
}


vrrp_instance v4{
    state MASTER
    priority 100
    interface bond0
    use_vmac vrrp.v4
    vmac_xmit_base
    advert_int 3
    version 2
    virtual_router_id 93
    authentication {
        auth_type  xxxxxx
        auth_pass xxxxxx
    }

    track_script {
        chk_lb
    }

    notify_master "/usr/local/keepalived/bin/to_master.sh master"
    notify_backup "/usr/local/keepalived/bin/to_backup.sh backup"
    notify_fault  "/usr/local/keepalived/bin/to_fault.sh fault"

    virtual_ipaddress {
        x.x.x.x
    }
}

include /usr/local/keepalived/etc/vserver.conf
```

1.4.5
```
Dec 10 11:44:50 localhost Keepalived[2500793]: Starting Keepalived v1.4.5 (05/26,2018)
Dec 10 11:44:50 localhost Keepalived[2500793]: Running on Linux 3.18.27.linux #1 SMP Thu Mar 3 01:59:07 CST 2016 (built for Linux 2.6.32)
Dec 10 11:44:50 localhost Keepalived[2500793]: Opening file '/usr/local/keepalived/etc/keepalived.conf'.
Dec 10 11:44:50 localhost Keepalived[2500793]: Opening file '/usr/local/keepalived/etc/vserver.conf'.
Dec 10 11:44:50 localhost Keepalived[2500794]: Starting Healthcheck child process, pid=2500795
Dec 10 11:44:50 localhost Keepalived[2500794]: Starting VRRP child process, pid=2500796
Dec 10 11:44:50 localhost Keepalived_healthcheckers[2500795]: Opening file '/usr/local/keepalived/etc/keepalived.conf'.
Dec 10 11:44:50 localhost Keepalived_healthcheckers[2500795]: Opening file '/usr/local/keepalived/etc/virtual_server.conf'.
Dec 10 11:44:50 localhost Keepalived_healthcheckers[2500795]: Initializing ipvs
Dec 10 11:44:50 localhost Keepalived_healthcheckers[2500795]: Gained quorum 1+0=1 <= 108 for VS FWM 11
Dec 10 11:44:50 localhost Keepalived_healthcheckers[2500795]: Activating healthchecker for service [x.x.x.x]:none:0 for VS FWM 11
Dec 10 11:44:50 localhost Keepalived_healthcheckers[2500795]: Activating healthchecker for service [x.x.x.x]:none:0 for VS FWM 11
Dec 10 11:44:50 localhost Keepalived_healthcheckers[2500795]: Activating healthchecker for service [x.x.x.x]:none:0 for VS FWM 11
Dec 10 11:44:50 localhost Keepalived_healthcheckers[2500795]: Activating healthchecker for service [x.x.x.x]:none:0 for VS FWM 11
Dec 10 11:44:50 localhost Keepalived_healthcheckers[2500795]: Activating healthchecker for service [x.x.x.x]:none:0 for VS FWM 11
Dec 10 11:44:50 localhost Keepalived_vrrp[2500796]: Registering Kernel netlink reflector
Dec 10 11:44:50 localhost Keepalived_vrrp[2500796]: Registering Kernel netlink command channel
Dec 10 11:44:50 localhost Keepalived_vrrp[2500796]: Registering gratuitous ARP shared channel
Dec 10 11:44:50 localhost Keepalived_vrrp[2500796]: Opening file '/usr/local/keepalived/etc/keepalived.conf'.
Dec 10 11:44:50 localhost Keepalived_vrrp[2500796]: Opening file '/usr/local/keepalived/etc/vserver.conf'.
Dec 10 11:44:50 localhost Keepalived_vrrp[2500796]: vmac: Success creating VMAC interface vrrp.v4 for vrrp_instance v4
Dec 10 11:44:50 localhost Keepalived_vrrp[2500796]: Using LinkWatch kernel netlink reflector...
Dec 10 11:44:50 localhost Keepalived_vrrp[2500796]: VRRP sockpool: [ifindex(6), proto(112), unicast(0), fd(10,11)]
Dec 10 11:44:50 localhost Keepalived_vrrp[2500796]: VRRP_Script(chk_lb) succeeded
Dec 10 11:44:53 localhost Keepalived_vrrp[2500796]: VRRP_Instance(v4) Transition to MASTER STATE
Dec 10 11:44:56 localhost Keepalived_vrrp[2500796]: VRRP_Instance(v4) Entering MASTER STATE
Dec 10 11:44:56 localhost Keepalived_vrrp[2500796]: VRRP_Instance(v4) setting protocol VIPs.
Dec 10 11:44:56 localhost Keepalived_vrrp[2500796]: Sending gratuitous ARP on vrrp.v4 for x.x.x.x
Dec 10 11:44:56 localhost Keepalived_vrrp[2500796]: VRRP_Instance(v4) Sending/queueing gratuitous ARPs on vrrp.v4 for x.x.x.x
Dec 10 11:44:56 localhost Keepalived_vrrp[2500796]: VRRP_Instance(v4) Sending/queueing gratuitous ARPs on vrrp.v4 for x.x.x.x
```

Question 2：

Double instance,the preemption mode, the first to keep alive by starting

There is' exit 0 'in the script, but I thought this configuration was not necessary at the beginning, so I am very sorry that I did not show it. There is no 'reload keepalived' in the 'to_check' function, but I found there was' reload keepalived 'in the' notify 'script. I added 'reload keepalived' to 'to_check' alone and checked to see if 'track_script' exists in 'reload keepalived', but it still does.

I wanted to add 'reload keepalived' to the script 'notify' to reload the configuration and refresh 'LVS' when 'keealived' failed, because the script I was executing would change some of the configuration

In the same configuration, 'state MASTER Priority 255' does not appear to reload the configuration at startup, 'prioity' does not equal '255' to cycle the configuration file, 'state BACKUP' also cycles the configuration file

conf 

```
vrrp_script chk_lb {
    script  "script.sh check"
    interval 3 
    timeout 2
}

vrrp_sync_group gv4 {
    group { 
        v4
        v6
    }

    track_script {
        chk_lb 
    }

    notify_master "script.sh master"
    notify_backup "script.sh  backup"
    notify_fault  "script.sh  fault"       
}

vrrp_instance v4{
    state MASTER
    priority 100
    interface bond0
    use_vmac vrrp.v4
    vmac_xmit_base
    advert_int 3
    version 2
    virtual_router_id 93
    authentication {
        auth_type  xxxxxx
        auth_pass xxxxxx
    }
    virtual_ipaddress {
        x.x.x.x
    }
}

vrrp_instance v6{
    state MASTER
    priority 100
    interface bond0
    use_vmac vrrp.v6
    vmac_xmit_base
    advert_int 3
    version 3
    virtual_router_id 94

    virtual_ipaddress {
        x:x::x:x::x
    }
}
```
script.sh
```
to_master() {
     kill -HUP $(cat /run/keepalived.pid)   
     exit0    
}

to_backup() {
     kill -HUP $(cat /run/keepalived.pid)      
     exit0 
}

to_fault() {
     kill -HUP $(cat /run/keepalived.pid)  
     exit0    
}

to_check() {
     ...
     exit0 
}

case $1 in 
     check)
          to_check
           ;;
     master)
          to_master
           ;;
     backup)
          to_backup
           ;;
     fault)
          to_fault
           ;;
      *)
           echo
           ;;
esac
```

**Comment by 79U** [comment] 2020-12-10 04:55
```
state MASTER and nopreempt are contradictory since a VRRP instance cannot become master without preempting if there is already a VRRP instance running; indeed keepalived logs an error if both are configured.
```

I did not configure 'nopreempt'. I tried to configure both instances as' nopreempt ', but the configuration file was still cycled;

My main purpose is to configure two or more instances, instance synchronization, now the problem is that if 'reload keepalived' occurs in the 'notify' script, the configuration files will be reloaded.

**Comment by pqarmitage** [comment] 2020-12-10 10:13
@79U I am now totally confused about what you are trying to achieve, what your problems are, and what your configuration is; we seem to have a moving target here in respect of both problems, configurations and scripts.

You have now introduced a new issue related to LVS, but you have not provided any LVS configuration (i.e. the /usr/local/keepalived/etc/vserver.conf file, and it also seems to have disappeared from the latest keepalived configuration file you have posted). Also, you are comparing the logs using 1.4.5 and 2.1.5, but it appears that the configurations are different since a different number of healthcheckers are activated.

The script.sh you have provided is now significantly different from the one you originally provided, and I suspect that neither of them is what you are actually using.

I think we need to start again. Can you please provide all of the actual configuration files and scripts you are using, with the only edits being to hide IP addresses and passwords (if the same IP address is used in different parts of you configuration, e.g. as VIPs and virtual server addresses, then that needs to be shown). Can you please also provide a clear description of what keepalived is doing that you don't think it should do, and what you think it should be doing.

It indeed can be helpful to provide log file extracts to demonstrate what you are saying, but, for example, you have stated above `Start the 2.1.5 configuration with 1.4.5, 1.4.5 will add the LVS configuration after entering the Mster state` and provide the log entries for this, but the log entries do not show anything about the LVS configuration being added after the vrrp instance enters master state.

Unfortunately, if you cannot provide the information I have requested, I can't see how we are going to be able to help you resolve your problem(s).

**Comment by 79U** [comment] 2020-12-10 11:29
I'm really sorry that I didn't think it through. I sorted out the configuration files and scripts. This is how it is used. You can replace the IP configuration and test it

conf:

```
! Configuration File for keepalived

global_defs {
    router_id LB
    max_auto_priority -1
    vrrp_version 2
    script_user root
    lvs_flush
    enable_script_security
}

vrrp_script chk_lb {
    script "/usr/local/keepalived/bin/script.sh to_check"
    interval 3
    timeout 2
}

vrrp_sync_group  sgroup {
    group { 
        v4
        v6
    }

    track_script {
        chk_lb 
    }

    notify_master "/usr/local/keepalived/bin/script.sh to_master"
    notify_backup "/usr/local/keepalived/bin/script.sh to_backup"
    notify_fault  "/usr/local/keepalived/bin/script.sh to_fault"

}

vrrp_instance v4 {
    state BACKUP
    priority 80
    interface bond0
    use_vmac vrrp.v4
    vmac_xmit_base
    version 2
    advert_int 3
    virtual_router_id 93

    authentication {
        auth_type  PASS
        auth_pass keepalivedpass
    }

    virtual_ipaddress {
        1.1.1.1
    }
}

vrrp_instance v6 {
    state BACKUP
    priority 80
    interface bond0
    use_vmac vrrp.v6
    vmac_xmit_base
    advert_int 3
    version 3
    virtual_router_id 94

    virtual_ipaddress {
        fe80::3/64

    }
}


virtual_server fwmark 11 {
    virtualhost localhost
    delay_loop 2
    lvs_sched  wrr
    lvs_method DR
    connect_timeout 6
    real_server 1.1.1.2 0 {
        weight 12
        retry 3
        delay_before_retry 3
        HTTP_GET {
            url {
                path /test
                status_code 200
            }
            connect_port 80
        }
    }
    real_server 1.1.1.3 0 {
        weight 24
        retry 3
        delay_before_retry 3
        HTTP_GET {
            url {
                path /test
                status_code 200
            }
            connect_port 80
        }
    } 
   
}


virtual_server fwmark 12 {
    virtualhost localhost
    delay_loop 2
    lvs_sched  wrr
    lvs_method DR
    connect_timeout 6
    real_server x:x::1 0 {
        weight 12
        retry 3
        delay_before_retry 3
        HTTP_GET {
            url {
                path /test
                status_code 200
            }
            connect_port 80
        }
    }
    real_server x:x::2 0 {
        weight 24
        retry 3
        delay_before_retry 3
        HTTP_GET {
            url {
                path /test
                status_code 200
            }
            connect_port 80
        }
    }
}



```

script.sh

```
to_master() {
     kill -HUP $(cat /run/keepalived.pid)   
     exit0    
}

to_backup() {
     kill -HUP $(cat /run/keepalived.pid)      
     exit0 
}

to_fault() {
     kill -HUP $(cat /run/keepalived.pid)  
     exit0    
}

to_check() {
     exit0 
}

case $1 in 
     to_check)
          to_check
           ;;
     to_master)
          to_master
           ;;
     to_backup)
          to_backup
           ;;
     to_fault)
          to_fault
           ;;
      *)
           echo
           ;;
esac
```

**Comment by pqarmitage** [comment] 2020-12-10 11:45
@79U many thanks for the complete configuration and script, although the script doesn't look quite right with `exit0`; should this be `exit 0`?

I am sorry to ask you to do this, but I am confused about what the issues you are experiencing are, so I don't know what I need to be looking at. To help me out, could you please describe exactly what the issues are that we need to look at.

**Comment by 79U** [comment] 2020-12-10 12:48
> @ 79U非常感谢您提供完整的配置和脚本，尽管使用脚本看起来不太合适`exit0`；应该是`exit 0`吗？
> 
> 很抱歉要求您这样做，但是对于您遇到的问题感到困惑，所以我不知道我需要看什么。为了帮助我，请您确切描述我们需要研究的问题。

That's right, `exit  0 `, `exit0` was an error when you pasted it, so you ignore it, sorry!!

Problems encountered:

With this configuration, when 'keepalived 2.1.5' is started, the program is thrown into a dead loop that reloads the "keepalived.conf" configuration file

**Comment by 79U** [comment] 2020-12-15 02:50
> @ 79U非常感谢您提供完整的配置和脚本，尽管使用脚本看起来不太合适`exit0`；应该是`exit 0`吗？
> 
> 很抱歉要求您这样做，但是对于您遇到的问题感到困惑，所以我不知道我需要看什么。为了帮助我，请您准确描述我们需要研究的问题。

Hello, have you tested the problem? @pqarmitage

**Comment by pqarmitage** [comment] 2020-12-15 15:44
Commit 6c8b51c resolves the issue. It was caused by sync group notifies being sent after a reload if the sync group was in fault or backup state. In your case, since a notify was sent when keepalived started up to say the sync group was in backup state, your script then restarted keepalived, causing another notify, ... . The commit now means that a sync group notify is not sent if the state is the same before and after the reload.

I think what you are doing is probably not safe to rely on. It is not good practice to reload keepalived just in case the configuration has changed; you should be reloading keepalived as part of the process of changing the configuration, so that keepalived is only reloaded if the configuration has changed.

**Closed by pqarmitage** 2020-12-15 15:44 UTC

**Comment by 79U** [comment] 2020-12-16 04:09
Thank you very much for your patience to answer and solve the problem
