### ISSUE TITLE
"daemon is already running" in container

### ISSUE THREAD

**Issue by xieyanker** [acassen/keepalived#1527] opened 2020-03-28 08:32 UTC
My keepalived is started in container, which is controlled by k8s static pod. However, I found it will get abnormal sometimes. The main reason is `daemon is already running`  as follows:

```shell
Starting Keepalived v1.2.24 (02/14,2019)
Opening file '/etc/keepalived/keepalived.conf'.
daemon is already running
```

I don't know how to repeat it at present. It will be not ready unitl I remove the `/var/run/keepalived.pid` file from the host node.

In fact, I mount the `/var/run/keepalived.pid` file from container to host node. I don't know whether it has some bad influences. And I also wonder how to avoid this issue, does it  will work if I add a command to clear pid file at the start of the image?

**Comment by pqarmitage** [comment] 2020-03-28 09:49
The `daemon is already running` means that the pid file `/run/keepalived.pid` exists and there is a process running whose pid matches the pid in the pid file. I presume that the container is run with its own PID namespace, and so the PID of the keepalived process running in the container is always the same.

The problem is occurring because you are shutting down the container without stopping keepalived first; this results in the pid file not being deleted by keepalived, and hence it is found when the container is restarted.

The best solution is to make sure that keepalived is shutdown before the container is stopped, but it would also be sensible to delete the /run/keepalived.pid file when the container starts up.

BTW, the version of keepalived you are running is **VERY** old, and you would benefit from upgrading to a recent version such as v2.0.20.

**Comment by xieyanker** [comment] 2020-03-30 06:13
@pqarmitage Thanks for your reply!

I have used the keepalived version `v2.0.20` for my latest environment.

As far as I know, `/var/run/keepalived.pid` should be a file. However, in fact, it became a directory when the wrong happened. Is there any reasonable explanation for this phenomenon?

Also, I wonder what is the role of the `/var/run/keepalived.pid`, why it need be defined in the keealived parameter. By my test, if there is a `keepalived` container process is running, and I delete the file `/var/run/keepalived.pid`, it will also be fialed when I start a new  `keepalived` container.

I'm very confusing about this.

**Comment by pqarmitage** [comment] 2020-03-30 07:29
You state you have used v2.0.20 for you latest environment, but the docker output suggests you are still running v1.2.24.

I cannot see any reason why keepalived would create `/var/run/keepalived/pid` as a directory, although it is possible that having something like `net_namespace keepalived.pid` in your configuration file could cause keepalived to create `/var/run/keepalived/pid` as a directory.

I am not clear what you mean by:
`Also, I wonder what is the role of the /var/run/keepalived.pid, why it need be defined in the keealived parameter`.
There is a command line option `-p` to specify the PID file, but generally it doesn't need to be used. The only reason I know of for using it would be if you wanted to run more than one instance of keepalived on a system, so as to ensure that each instance used a different PID file.

I do not understand what the docker command outputs are attempting to demonstrate.

**Comment by xieyanker** [comment] 2020-03-30 08:23
Sorry I didn't describe it clearly!

I have some different environments, the latest version of keepalived  which I deploy is v2.0.20, and the output which my print is a old version.

My main trouble is `/var/run/keepalived/pid` became a directory. I don't know why, but it cause the `daemon is already running` error. 

I repeat it as follows:

1. stop keeepalived and clear all related keepalvied containers
2. rm -rf /var/run/keepalived.pid
3. mkdir /var/run/keepalived.pid
4. start keeepalived contianer

we will the error:
```shell
root@mgt01:~# docker ps -a|grep keepalived
89e6d35373f1        9ab22f9b4bef                                                    "/usr/sbin/keepalive…"   11 seconds ago      Exited (0) 9 seconds ago                        k8s_keepalived_keepalived-mgt01_kube-system_82297178c0c553126b8de0f85b15db0f_1
b7caacd530ad        docker.inspur.com:5000/library/cke/kubernetes/pause-amd64:3.1   "/pause"                 12 seconds ago      Up 11 seconds                                   k8s_POD_keepalived-mgt01_kube-system_82297178c0c553126b8de0f85b15db0f_0
root@mgt01:~# docker logs 89e6d35373f1
Starting Keepalived v1.2.24 (02/14,2019)
Opening file '/etc/keepalived/keepalived.conf'.
Error reading pid file /var/run/keepalived.pid
daemon is already running
```

And I try add the command `rm -rf /var/run/keepalived.pid` at the beginning of start container, it will be no problem. I'm just describing this phenomenon, and add the command `rm -rf /var/run/keepalived.pid` works for me. And I think what I still need to solve is why it became a directory.

**Comment by pqarmitage** [comment] 2020-03-30 09:10
It looks to me as though the reason `/var/run/keepalived.pid` is created as a directory is due to the command numbered 3 above: `mkdir /var/run/keepalived.pid`.

**Comment by xieyanker** [comment] 2020-03-30 09:39
emm~. it is created by myself, not the actual error occurred. By the way, why the error shows `daemon is already running` when it is a directory, shouldn't it be other prompts?

**Comment by pqarmitage** [comment] 2020-03-30 10:52
I think that when the relevant code was written it wasn't anticipated that someone would create a directory in /var/run (or /run) with the name of the keepalived pidfile; yes, the code could be improved but is it worthwhile for such an edge case?

It appears from your comment above that if you remove the `/var/run/keepalived.pid` directory that you have created, keepalived runs without a problem, so I think we can now close this issue.

**Closed by pqarmitage** 2020-03-30 10:52 UTC
