### ISSUE TITLE
vrrp_script fails if script contains any privileged commands

### ISSUE THREAD

**Issue by narasago** [acassen/keepalived#1376] opened 2019-08-16 10:41 UTC
**Describe the bug**
With the status check script checking the status of a service hosted by one of the kubernetes pod and failure of the service should result in failover of the VIPs by keepalived. It doesn't happen, the IPs will not get moved to the other node. The unprivileged command execution will always return non-zero exit code when keepalived executes the script.

**To Reproduce**
Add a script with following content:
"kubectl get pod | grep -q <existing-pod>
exit $?"
 This will return 0 when executed manually and returns 1 when keepalived executes the same.

**Expected behavior**
The script execution should be successful and the system should try to get back to either BACKUP or MASTER state, based on the keepalived configuration on that node.

**Keepalived version**
Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

**Distro (please complete the following information):**
 - Fedora
 - 7.6

**Details of any containerisation or hosted service (e.g. AWS)**
NA

**Configuration file:**
! Configuration File for keepalived
global_defs {
    script_user root
}

vrrp_script chk_service {           # Requires keepalived-1.3.5
    script "killall -0 keepalived"  # cheaper than pidof
    interval 2                      # check every 2 seconds
    weight 2                       # add 2 points of prio if OK
}

vrrp_script chk_nginx {
   script "/sbin/runuser -l root -c '/usr/libexec/keepalived/chk_nginx.sh -no-vip-check'"
   interval 2
   fall 2
   rise 4
}

vrrp_instance unify_lvs_service1 {
    priority 98
    advert_int 1
    authentication {
        auth_pass 1111
        auth_type PASS
    }
    state BACKUP
    interface eth2
    track_interface {
      eth1
      eth2
    }
    nopreempt
    virtual_ipaddress {
        x.x.x.x dev eth2
        y.y.y.y dev eth1
    }
    virtual_ipaddress_excluded {
       ipv6_address1  dev eth2
       ipv6_address2 dev eth1
    }
    virtual_router_id 51
    track_script {
       chk_nginx
       chk_service
    }
    notify_master "/usr/libexec/keepalived/script1.sh"
    notify_backup "/usr/libexec/keepalived/script2.sh"
    notify_fault "/usr/libexec/keepalived/script2.sh"
}

**Notify and track scripts**
#!/bin/bash
kubectl get pod | grep -q <existing-pod>
exit $?

**System Log entries**
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived[12528]: Starting Healthcheck child process, pid=12529
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived[12528]: Starting VRRP child process, pid=12530
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived_healthcheckers[12529]: Opening file '/etc/keepalived/keepalived.conf'.
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived_healthcheckers[12529]: Opening file '/opt/bcmt/config/keepalived/place_holder.conf'.
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived_vrrp[12530]: Registering Kernel netlink reflector
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived_vrrp[12530]: Registering Kernel netlink command channel
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived_vrrp[12530]: Registering gratuitous ARP shared channel
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived_vrrp[12530]: Opening file '/etc/keepalived/keepalived.conf'.
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived_vrrp[12530]: Opening file '/opt/bcmt/config/keepalived/place_holder.conf'.
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived_vrrp[12530]: WARNING - script `killall` resolved by path search to `/usr/bin/killall`. Please specify full path.
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived_vrrp[12530]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived_vrrp[12530]: VRRP_Instance(unify_lvs_service1) removing protocol VIPs.
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived_vrrp[12530]: VRRP_Instance(unify_lvs_service1) removing protocol E-VIPs.
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived_vrrp[12530]: Using LinkWatch kernel netlink reflector...
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived_vrrp[12530]: VRRP_Instance(unify_lvs_service1) Entering BACKUP STATE
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived_vrrp[12530]: VRRP sockpool: [ifindex(4), proto(112), unicast(0), fd(10,11)]
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived_vrrp[12530]: VRRP_Script(chk_service) succeeded
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived_vrrp[12530]: /root/test.sh exited with status 1
Aug 16 09:15:10 ovsp0035-edge-1 Keepalived_vrrp[12530]: VRRP_Instance(unify_lvs_service1) Now in FAULT state
Aug 16 09:15:11 ovsp0035-edge-1 Keepalived_vrrp[12530]: VRRP_Instance(unify_lvs_service1) Changing effective priority from 50 to 52
Aug 16 09:15:12 ovsp0035-edge-1 Keepalived_vrrp[12530]: /root/test.sh exited with status 1
Aug 16 09:15:14 ovsp0035-edge-1 Keepalived_vrrp[12530]: /root/test.sh exited with status 1

**Comment by pqarmitage** [comment] 2019-08-16 11:05
@narasago Could you please clarify the following:

- The log shows /root/test.sh being executed, but the keepalived configuration doesn't have that script
- As I said in issue #1371 the chk_service script is pointless
- What is the purpose of using /sbin/runuser - it just seems to add complexity?
- The man page for runuser states: `For backward compatibility, runuser defaults to not change the current directory and to only set the environment variables  HOME  and SHELL`. This presumably means that the PATH environment is not set. How are you configuring the test script to be executed - is test.sh being invoked via runuser? If it is you have not specified a full path for kubectl, and so presumably it is not found.
- Why is keepalived logging `Opening file '/opt/bcmt/config/keepalived/place_holder.conf'`? It doesn't appear to be in the configuration.
- What is 7.6 after Fedora in distro?

**Comment by narasago** [comment] 2019-08-19 04:14
Please find the comments below:
1. The log shows /root/test.sh being executed, but the keepalived configuration doesn't have that script
[Ans]: The configuration is changed with new script for trying out. But, the content of the script is same in /root/test.sh as well.
2. What is the purpose of using /sbin/runuser - it just seems to add complexity?
[Ans]: Without this, keepalived is not able to execute the script containing kubectl commands. The script without runuser exits always with exit code 1. Which is the main reason why this issue is raised.
3. Why is keepalived logging Opening file '/opt/bcmt/config/keepalived/place_holder.conf'? It doesn't appear to be in the configuration.
[Ans]: For easier interpretation by you, I have consolidated the content of place_holder.conf and pasted it here.
4. What is 7.6 after Fedora in distro?
[Ans]: Do you mean VERSION="7.6 (Maipo)"?

**Comment by pqarmitage** [comment] 2019-08-21 09:09
@narasago 

1. Keepalived version 1.3.5 is very old. Please upgrade to a recent version, e.g. 2.0.18. Very many issues have been resolved since v1.3.5.
2. In order for us to attempt to track down the cause of the issues you are experiencing, you need to provide the exact configuration files that produce the problem you are experiencing and the logs that you have provided, otherwise we simply do not know what we are looking at. If any simplification is then needed we can do it, but at least we know what we are diagnosing.
3. I don't think this is important at this stage, but are you running RHEL 7 (Maipo) or Fedora (? version 19).

At the moment I suspect the problem you are experiencing is because you are not specifying a full path name for kubectl in the notify and track scripts, but that is just a guess.

For further ideas regarding problems running scripts, please look at the closed issues; there are many issues there dealing with scripts reported as not running, and what the potential problems and solutions are, including suggestions to help diagnose the problems.

**Comment by pqarmitage** [comment] 2019-09-13 11:40
Closing due to no update for over 3 weeks.

If the problem is still unresolved, please update this issue report, and the issue can be reopened.

**Closed by pqarmitage** 2019-09-13 11:40 UTC
