### ISSUE TITLE
Implement rise and fall for vrrp_instance too

### ISSUE THREAD

**Issue by charlesgoyard** [acassen/keepalived#421] opened 2016-09-13 07:48 UTC
Hi,
please add support for "rise" and "fall" logic in vrrp_instance blocks, just like in vrrp_script.

This is useful for noisy environments like public cloud.

Example:
```
vrrp_instance VIP_1 {
    interface eth1
    virtual_router_id 10
    priority 101
    rise 1
    fall 3
    [...]
```
Thanks a lot for keepalived !

**Comment by pqarmitage** [comment] 2016-09-27 09:29
Can you confirm that what you are asking for essentially is that keepalived should be more tolerant of missing adverts in a "noisy" environment, and so should not trigger transitions between backup and master so readily.

If my understanding is correct, then `fall` won't work. If it is intended to mean how many higher priority adverts a master must receive before it falls to backup, and we are assuming a noisy/lossy environment, then how would a backup instance know when the master had dropped back to backup, since it wouldn't know how many adverts the master had received (a way around this would be for the master to send a priority 0 advert (or presumably several of them) when it transitions to backup, but that would be a change to the VRRP protocol, and in any event sending more than one priority 0 advert would cause mayhem). As soon as a master receives a higher priority advert, it must transition to backup since the higher priority advert means that another, higher priority instance, is taking over as master.

My interpretation of the `rise` parameter is it would be for telling a backup instance how long it should take, presumably in terms of adverts not received, before it should transition to master, thereby making it more tolerant of missed adverts. Any change from three advert intervals during which no advert is received would be contrary to the VRRP specification, but in practice I can see no reason why, if all participating instances are working with the same value, it wouldn't work to use a higher value for missed adverts; the downside is that after a master fails, there would be a longer delay before the new master takes over.

Could you please confirm whether my understanding of this is correct, and if not could you please describe what it is you are wanting.

**Comment by charlesgoyard** [comment] 2016-09-27 13:13
Hi,

> Can you confirm that what you are asking for essentially is that keepalived should be more tolerant of missing adverts in a "noisy" environment, and so should not trigger transitions between backup and master so readily.
> My interpretation of the rise parameter is it would be for telling a backup instance how long it should take, presumably in terms of adverts not received, before it should transition to master, thereby making it more tolerant of missed adverts.

Yes, that's definitely what I mean. You are also right the _fall_ concept does not apply here.

However, what do you mean by "_Any change from three advert intervals during which no advert is received would be contrary to the VRRP specification_" ? What I observed is that one missed advert yields a takeover, with no means to increase that number. Did I overlooked something ?

Thanks,
Charles

**Comment by pqarmitage** [comment] 2016-09-27 19:32
The way the VRRP protocol works is that a backup router should transition to master as soon as it hasn't received an advert for _3 * adver_int + (256 - priority)* adver_int / 256_, where adver_int is the advertisement interval, in other words somewhere between 3 and 4 adver_ints since it last received an advert, and the higher the priority the sooner after 3 * adver int than a lower priority instance. Also, if a backup instance receives a priority 0 advert (which is sent by a master router when it is being taken down administratively), then a backup will transition to master (providing it has received no other advert of higher priority than itself) _(256 - priority) * adver_int / 256_ after the priority 0 adver.

The only exception to this is if a VRRP instance is the address owner (this is equivalent to priority = 255), then it will transition to master as soon as it comes up. Keepalived has another possibility where if a vrrp instance is configured with _state MASTER_, then at startup it will transition to master after 1 adver_int, but this should only be configured on the highest priority instance, and if nopreempt is not set, and so this simply speeds the transition to master of the router at startup, and this will have no effect once a router is running as backup.

The only reason I can think of as to why an instance would transition to master after 1 adver_int is if the instances are using VRRPv2 and the backup router were configured with an adver_int about 1/3 of that configured on the other router, but this would be a configuration error (for VRRPv3 the adver_int is sent in the adverts, and backup routers are expected to use that, which is fine so long as the adver_intervals configured in the configuration files don't differ too wildly).

So essentially, I cannot think of any reason why a backup once it has started running as backup should transition to master after missing only one advert. So far as I can see that would be a bug.

I'm not sure that it makes any difference, but what version of keepalived are you running? Could you try running your tests again, using the `-D` option with keepalived, so see if you can get the problem to happen again. Perhaps we might then be able to see something from the logs, in conjunction with the configuration files.

**Comment by charlesgoyard** [comment] 2016-09-27 20:41
Hi, thanks for your insight. With my parameters I should get 3.6 lost adverts before takeover.
I'll run additional tests tomorrow at work and post the timed results here along with the configuration files.
For instance I'm running keepalived 1.2.13 from Debian Jessie.

**Comment by charlesgoyard** [comment] 2016-09-28 12:12
Hi,
I tried with both 1.2.13 and 1.2.23 and get the same results. I could observe the "miss 3 adverts before switching" behavior, thought.

In my setup, I have hostA and hostB, advert_int is 10 seconds.

I tried with the four following means of breaking the link :
- block vrrp with an iptables rule for 12 seconds
- disconnect the NIC from vsphere for 12 seconds
- ifconfig eth0 down ; sleep 12 ; ifconfig eth0 up
- kill -9 keepalived for 12 seconds

The interesting part is 30 seconds after the last advert hostA sends :
13:03:39.03696 IP 10.200.40.23 > 10.200.40.21: VRRPv2  Advertisement prio 100 intvl 10s
13:03:39.037238 IP 10.200.40.21 > 10.200.40.23: VRRPv2 Advertisement prio 101 intvl 10s

The problems does not seem to lie in lost packets after all: the drop of one or two adverts (iptables method) recovers ok. It more looks like a "distributed race condition" where the backup takes over the master right when the master recovers.

Finally, maybe a not-so-bad solution would be to have an additional configurable timebox tolerance of a few milliseconds for receiving adverts ?

In any case, that's not a bug in keepalived, it seems to behave as expected.

Here are some logs (the hosts have 3 ethernet interfaces, nevermind eth1 and eth2):

```
################
HostA
################

== keepalived.conf ==

global_defs {
notification_email {

    x@y.com
    }
    notification_email_from z@y.com
    smtp_server mail.y.com
    smtp_connect_timeout 30

    router_id "test - hostA"
}

vrrp_instance VIP_1 {
    interface eth0
    virtual_router_id 12
    priority 101         # 101 on master, 100 on backup
    smtp_alert
    advert_int 10
    unicast_src_ip 10.200.40.21
        unicast_peer {
        10.200.40.23
    }

    authentication {
        auth_type PASS
        auth_pass sidtest
    }
    virtual_ipaddress {
        10.200.40.12
    }
}
root@hostA:~# date ; pkill -9 keepalived ; sleep 12 ; date ; keepalived -D
13:03:09 ## killed keepalived
13:03:21 ## restarted keepalived

== keepalived.log ==

13:03:21 hostA Keepalived[1657]: Starting Keepalived v1.2.23 (07/21,2016)
13:03:21 hostA Keepalived[1657]: Remove a zombie pid file /var/run/keepalived.pid
13:03:21 hostA Keepalived[1657]: Remove a zombie pid file /var/run/vrrp.pid
13:03:21 hostA Keepalived[1657]: Remove a zombie pid file /var/run/checkers.pid
13:03:21 hostA Keepalived[1658]: Starting Healthcheck child process, pid=1659
13:03:21 hostA Keepalived[1658]: Starting VRRP child process, pid=1660
13:03:21 hostA Keepalived_vrrp[1660]: Netlink reflector reports IP 10.200.40.21 added
13:03:21 hostA Keepalived_vrrp[1660]: Netlink reflector reports IP 10.200.40.12 added
13:03:21 hostA Keepalived_vrrp[1660]: Netlink reflector reports IP 10.200.105.21 added
13:03:21 hostA Keepalived_vrrp[1660]: Netlink reflector reports IP 10.200.188.21 added
13:03:21 hostA Keepalived_vrrp[1660]: Netlink reflector reports IP fe80::250:56ff:fe80:e0a0 added
13:03:21 hostA Keepalived_vrrp[1660]: Netlink reflector reports IP fe80::250:56ff:fe80:3dc1 added
13:03:21 hostA Keepalived_vrrp[1660]: Netlink reflector reports IP fe80::250:56ff:fe80:9168 added
13:03:21 hostA Keepalived_vrrp[1660]: Registering Kernel netlink reflector
13:03:21 hostA Keepalived_vrrp[1660]: Registering Kernel netlink command channel
13:03:21 hostA Keepalived_vrrp[1660]: Registering gratuitous ARP shared channel
13:03:21 hostA Keepalived_vrrp[1660]: Unable to load ipset library
13:03:21 hostA Keepalived_vrrp[1660]: Unable to initialise ipsets
13:03:21 hostA Keepalived_vrrp[1660]: Opening file '/etc/keepalived/keepalived.conf'.
13:03:21 hostA Keepalived_healthcheckers[1659]: Initializing ipvs 2.6
13:03:21 hostA Keepalived_healthcheckers[1659]: Netlink reflector reports IP 10.200.40.21 added
13:03:21 hostA Keepalived_vrrp[1660]: VRRP_Instance(VIP_1) removing protocol VIPs.
13:03:21 hostA Keepalived_healthcheckers[1659]: Netlink reflector reports IP 10.200.40.12 added
13:03:21 hostA Keepalived_healthcheckers[1659]: Netlink reflector reports IP 10.200.105.21 added
13:03:21 hostA Keepalived_healthcheckers[1659]: Netlink reflector reports IP 10.200.188.21 added
13:03:21 hostA Keepalived_healthcheckers[1659]: Netlink reflector reports IP fe80::250:56ff:fe80:e0a0 added
13:03:21 hostA Keepalived_healthcheckers[1659]: Netlink reflector reports IP fe80::250:56ff:fe80:3dc1 added
13:03:21 hostA Keepalived_healthcheckers[1659]: Netlink reflector reports IP fe80::250:56ff:fe80:9168 added
13:03:21 hostA Keepalived_vrrp[1660]: Using LinkWatch kernel netlink reflector...
13:03:21 hostA Keepalived_vrrp[1660]: VRRP_Instance(VIP_1) Entering BACKUP STATE
13:03:21 hostA Keepalived_healthcheckers[1659]: Registering Kernel netlink reflector
13:03:21 hostA Keepalived_vrrp[1660]: VRRP sockpool: [ifindex(2), proto(112), unicast(1), fd(10,11)]
13:03:21 hostA Keepalived_healthcheckers[1659]: Registering Kernel netlink command channel
13:03:21 hostA Keepalived_healthcheckers[1659]: Opening file '/etc/keepalived/keepalived.conf'.
13:03:21 hostA Keepalived_vrrp[1660]: Remote SMTP server [10.x.x.x]:25 connected.
13:03:21 hostA Keepalived_healthcheckers[1659]: Using LinkWatch kernel netlink reflector...
13:03:21 hostA Keepalived_vrrp[1660]: SMTP alert successfully sent.
13:03:38 hostA Keepalived_vrrp[1660]: VRRP_Instance(VIP_1) forcing a new MASTER election
13:03:48 hostA Keepalived_vrrp[1660]: VRRP_Instance(VIP_1) Transition to MASTER STATE
13:03:58 hostA Keepalived_vrrp[1660]: VRRP_Instance(VIP_1) Entering MASTER STATE
13:03:58 hostA Keepalived_vrrp[1660]: VRRP_Instance(VIP_1) setting protocol VIPs.
13:03:58 hostA Keepalived_vrrp[1660]: Sending gratuitous ARP on eth0 for 10.200.40.12
13:03:58 hostA Keepalived_vrrp[1660]: VRRP_Instance(VIP_1) Sending/queueing gratuitous ARPs on eth0 for 10.200.40.12
13:03:58 hostA Keepalived_vrrp[1660]: Sending gratuitous ARP on eth0 for 10.200.40.12
13:03:58 hostA Keepalived_vrrp[1660]: Sending gratuitous ARP on eth0 for 10.200.40.12
13:03:58 hostA Keepalived_vrrp[1660]: Sending gratuitous ARP on eth0 for 10.200.40.12
13:03:58 hostA Keepalived_vrrp[1660]: Sending gratuitous ARP on eth0 for 10.200.40.12
13:03:58 hostA Keepalived_vrrp[1660]: Remote SMTP server [10.175.20.1]:25 connected.
13:03:59 hostA Keepalived_vrrp[1660]: SMTP alert successfully sent.
13:04:03 hostA Keepalived_vrrp[1660]: Sending gratuitous ARP on eth0 for 10.200.40.12
13:04:03 hostA Keepalived_vrrp[1660]: VRRP_Instance(VIP_1) Sending/queueing gratuitous ARPs on eth0 for 10.200.40.12
13:04:03 hostA Keepalived_vrrp[1660]: Sending gratuitous ARP on eth0 for 10.200.40.12
13:04:03 hostA Keepalived_vrrp[1660]: Sending gratuitous ARP on eth0 for 10.200.40.12
13:04:03 hostA Keepalived_vrrp[1660]: Sending gratuitous ARP on eth0 for 10.200.40.12
13:04:03 hostA Keepalived_vrrp[1660]: Sending gratuitous ARP on eth0 for 10.200.40.12

###############
HostB
###############

== keepalived.conf ==

global_defs {
notification_email {

    x@y.com
    }
    notification_email_from z@y.com
    smtp_server mail.y.com
    smtp_connect_timeout 30

    router_id "test - hostB"
}

vrrp_instance VIP_1 {
    interface eth0
    virtual_router_id 12
    priority 100         # 101 on master, 100 on backup
    smtp_alert
    advert_int 10
    unicast_src_ip 10.200.40.23
        unicast_peer {
        10.200.40.21
    }

    authentication {
        auth_type PASS
        auth_pass sidtest
    }
    virtual_ipaddress {
        10.200.40.12
    }
}

== tcpdump output ==

13:03:08.426669 IP 10.200.40.21 > 10.200.40.23: VRRPv2, Advertisement, vrid 12, prio 101, authtype simple, intvl 10s, length 20 # before keepalived on hostA has been killed
13:03:39.036962 IP 10.200.40.23 > 10.200.40.21: VRRPv2, Advertisement, vrid 12, prio 100, authtype simple, intvl 10s, length 20 # after + 30 seconds, hostB sends an advert
13:03:39.037238 IP 10.200.40.21 > 10.200.40.23: VRRPv2, Advertisement, vrid 12, prio 101, authtype simple, intvl 10s, length 20 # after + 30 seconds
13:03:49.037943 IP 10.200.40.21 > 10.200.40.23: VRRPv2, Advertisement, vrid 12, prio 101, authtype simple, intvl 10s, length 20

== keepalived.log ==

13:03:39 hostB Keepalived_vrrp[1186]: VRRP_Instance(VIP_1) Transition to MASTER STATE
13:03:39 hostB Keepalived_vrrp[1186]: VRRP_Instance(VIP_1) Received higher prio advert 101
13:03:39 hostB Keepalived_vrrp[1186]: VRRP_Instance(VIP_1) Entering BACKUP STATE
13:03:39 hostB Keepalived_vrrp[1186]: Remote SMTP server [10.x.x.x]:25 connected.
13:03:39 hostB Keepalived_vrrp[1186]: SMTP alert successfully sent.

```

Thanks for your help,
Charles

**Comment by pqarmitage** [comment] 2016-09-28 13:28
Just one minor point from your logs, and this has nothing to do with the issue here. The following lines:
```
13:03:21 hostA Keepalived_vrrp[1660]: Unable to load ipset library
13:03:21 hostA Keepalived_vrrp[1660]: Unable to initialise ipsets
```
indicate that you are building keepalived with the ipset development libraries, but you don't have the runtime library libipset.so installed. It would be helpful it you could check what is happening there, in case I have got the dynamic loading of the libipset.so library wrong.

Back to the main issue.
You said: _Finally, maybe a not-so-bad solution would be to have an additional configurable timebox tolerance of a few milliseconds for receiving adverts ?_ In effect the configurable timebox exists. If you look at how the down timer is calculated (see my second post above), the calculation incorporates the priority of the instance. So as you have it configured, the down timers are:
Host A: 3 * 10 + (256-101) * 10 /256 = 36.09375 seconds
Host B: 3 * 10 + (256-100) * 10 /256 = 36.05469 seconds
and these times are very similar, so it is quite possible that with different workloads on the two systems, the sequence of events may not be consistent.

If, on the other hand, you configured Host A with priority 200, the down timers would be:
Host A: 3 * 10 + (256-200) * 10 /256 = 32.1875 seconds
Host B: 3 * 10 + (256-100) * 10 /256 = 36.05469 seconds
and so the sequence of events should be much more predictable.

You also state:
```
The interesting part is 30 seconds after the last advert hostA sends :
13:03:39.03696 IP 10.200.40.23 > 10.200.40.21: VRRPv2 Advertisement prio 100 intvl 10s
13:03:39.037238 IP 10.200.40.21 > 10.200.40.23: VRRPv2 Advertisement prio 101 intvl 10s
```
I'm guessing this is when hostA has been blocked from sending by iptables, and hence the network link between hostA and hostB is working fine. What is happening is that hostB eventually times out (I hope 36 seconds after the last advert from host A), and host A then sends an advert with its priority of 100. hostB then receives that advert (I assume the iptables entry you added only stopped hostA sending or hostB receiving), sees it is of lower priority, and so sends an advert itself, since it is a higher priority.

The logs
```
13:03:21 hostA Keepalived_vrrp[1660]: VRRP_Instance(VIP_1) Entering BACKUP STATE
.
.
.
13:03:38 hostA Keepalived_vrrp[1660]: VRRP_Instance(VIP_1) forcing a new MASTER election
13:03:48 hostA Keepalived_vrrp[1660]: VRRP_Instance(VIP_1) Transition to MASTER STATE
13:03:58 hostA Keepalived_vrrp[1660]: VRRP_Instance(VIP_1) Entering MASTER STATE
13:03:58 hostA Keepalived_vrrp[1660]: VRRP_Instance(VIP_1) setting protocol VIPs.
```
are quite interesting. Presumable hostB sent an advert at 13:03:28, which for some reason host A missed. At 13:03:38 hostA is in backup mode and receives a lower priority advert, so it forces a new election by sending a higher priority advert. At 13:03:48 it starts its transition to MASTER, and then a further 10 seconds later it completes the transition and becomes master.

This isn't how the VRRP protocol is supposed to work. If a lower priority advert is received by a backup instance, it should just be ignored, and so its master down timer isn't reset. Eventually the down timer should expire, and then the backup router becomes master. I'm currently working on this and various other aspects of the timings of transitions between backup and master, which will in many cases speed up the transitions.

**Comment by charlesgoyard** [comment] 2016-09-28 16:40
Hi,
as of the ipsets library, it's installed but linked at compilation, so the dlopen should not take place at all I guess :
```
ldd /usr/sbin/keepalived 
	libipset.so.3 => /lib/x86_64-linux-gnu/libipset.so.3 (0x00007f92aaa91000)
```

As of router advert priority goes, I tried with 50 on backup and 200 on master and get the exact same timing. So maybe there's something to dig with that respect.

> What is happening is that hostB eventually times out (I hope 36 seconds after the last advert from host A)

From the logs it timeouts at 30 seconds, not 36, whatever the priorities are. Strange.

**Comment by pqarmitage** [comment] 2016-09-29 14:31
ipsets being linked at compile time is an error on my part from when I changed the build system to use automake; I accidentally added in -lipset. I've merged a commit to resolve this, and I've also added a commit to report a reason for why dlopen failed, which is the cause of the `Unable to load ipset library` error message. I know this is a separate issue, but it would be good to resolve it as well. Are you in a position to build the latest git sources, and test it? Do you think it would be better to open another issue for this problem?

Regarding the 30 seconds, with v1.2.23 I'm seeing the same as you (I actually had a delay of 30.609955 seconds). v1.2.24 is behaving the same, as is my latest development version, so I'll have a look at this a

**Comment by charlesgoyard** [comment] 2016-09-29 15:21
Hi, for ipset, that seems to work with latest git (thought I tested on Arch, not Debian) ! It's not linked anymore, is correctly loaded when found, and I get a nice error message when missing:
`Keepalived_vrrp[20650]: Unable to load ipset library - libipset.so: cannot open shared object file: No such file or directory`

Back to the main topic, I'm glad you get the same timing too :). So is it a confirmed bug ?

Thank you for your help.

**Comment by pqarmitage** [comment] 2016-09-29 18:27
Yes, I confirm it is a bug.

What I was finding strange was that I am currently doing some development in this area, and I knew I wasn't having the same issue. What I have now discovered is that it works as expected if using VRRPv3, but not with VRRPv2, so it you add `version 3` in the vrrp_instance blocks, you should get the right timings.

I'll have a look at this later, and push a fix once I have resolved it.

**Comment by charlesgoyard** [comment] 2016-09-29 18:35
Hi, using VRRPv3 is a totally doable in my setup, thanks a lot for the workaround. Will try that tomorrow.
Looking forward for the bugfix, I'm glad I could (somehow) help to improve keepalived ;).
Thank you very much for taking the time to look around my issue.

**Comment by pqarmitage** [comment] 2016-09-30 08:52
It turns out it is a bug in by understanding!

For VRRPv3 the down timer is indeed `3 * adver_int + (256 - priority)* adver_int / 256`, but for VRRPv2 it is `3 * adver_int + (256 - priority) / 256`. So for priority 101 the down timer is 3.0605468 and for priority 100 it is 3.0609375, meaning that the difference between the timers is 0.3907ms. It is probably this small difference that accounts for inconsistent behaviour. Changing the priorities to have a larger difference between them should result in more consistent behaviour.

Are you happy that everything is resolved now? 

Many thanks for your input on this, and at least we have resolved an issue in the build system that I wasn't aware existed.

**Comment by charlesgoyard** [comment] 2016-09-30 14:42
Hi, I could get VRRPv3 working, but I'm not 100% sure it solves the timing problems in all situations.
I will do further testing next week and report here.
Thanks !

**Comment by pqarmitage** [comment] 2016-10-18 09:57
Closing due to no further update.

If you have any further updates, please add you comments and request that this issue be reopened.

**Closed by pqarmitage** 2016-10-18 09:57 UTC

**Comment by charlesgoyard** [comment] 2016-10-18 17:51
Hi, sorry for not giving updates in a timely manner !
VRRPv3 seems to solve my problem. Thanks for all your help !
