### ISSUE TITLE
VMAC interface is not created for the second vlan interface in a non-default vrf of vrrp group

### ISSUE THREAD

**Issue by arulkumar9690** [acassen/keepalived#1554] opened 2020-04-22 19:16 UTC
**Describe the bug**
when we configure a vlan [ X ] in non-default namespace [VRF1] associated to VRRP group [1] and assign a virtual address[ x.x.x.x ] - VMAC interface is created successfully. But VMAC interface is not created if we configure another vlan [ Y ] in same non-default namespace [VRF1] associated to same VRRP group [1] and virtual address [y.y.y.y]

Following logs are observed while configuring vlan [Y]
Apr 12 23:51:38 1230 Keepalived_vrrp_1[4870]: Reloading
Apr 12 23:51:38 1230 Keepalived_vrrp_1[4870]: Opening file '/etc/keepalived/keepalived.VRF001.conf'.
Apr 12 23:51:38 1230 Keepalived_vrrp_1[4870]: (br10_v4_1) Found matching interface br10.v257
Apr 12 23:51:38 1230 Keepalived_vrrp_1[4870]: (br11_v4_1) Found matching interface br10.v257
Apr 12 23:51:38 1230 Keepalived_vrrp_1[4870]: (br11_v4_1) vmac name mismatch br11.v257 <=> br10.v257; changing to br10.v257.
Apr 12 23:51:38 1230 Keepalived_vrrp_1[4870]: (br11_v4_1) Entering BACKUP STATE (init)
Apr 12 23:51:41 1230 Keepalived_vrrp_1[4870]: (br11_v4_1) Entering MASTER STATE
Apr 12 23:51:41 1230 Keepalived_vrrp_1[4870]: (br11_v4_1) using locally configured advertisement interval (1000 milli-sec)

**To Reproduce**
Create a non-default namespace [VRF001].
Create 2 vlan's [vlan 10, vlan 11]
Associate vlan 10 and vlan 11 to non-default namespace [VRF001].
Configure vrrp group 1 on both vlan 10 and vlan 11
Configure virtual address on vlan 10 and vlan 11

**Expected behavior**
VMAC interfaces br10.v257 and br11.v257 is to be created.

**Keepalived version**
root@OS10:~# keepalived -v
Keepalived v2.0.19 (04/17,2020), git commit integration_good_build_4169+

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.9.168
Running on Linux 4.9.189 #1 SMP Debian 4.9.189-3+deb9u2

configure options: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --with-kernel-dir=debian/ --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-dbus --enable-json --enable-bfd build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fdebug-prefix-map=/mnt/build/open-source-keepalived=. -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-z,relro CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2

Config options:  NFTABLES LVS VRRP VRRP_AUTH JSON BFD OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV RTA_VIA FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK
root@OS10:~#

**Distro (please complete the following information):**
 - Name [e.g. Fedora, Ubuntu]
 - Version [e.g. 29]
 - Architecture [e.g. x86_64]

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details

**Configuration file:**
A full copy of the configuration file, obfuscated if necessary to protect passwords and IP addresses

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
Full keepalived system log entries from when keepalived started

**Did keepalived coredump?**
If so, can you please provide a stacktrace from the coredump, using gdb.

**Additional context**
Issue is present in both vrrp v4 and v6.

Non-Default Namespace - ip link show
7: br10.v257@if44: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 00:00:5e:00:01:01 brd ff:ff:ff:ff:ff:ff link-netnsid 0
46: v-br10@if44: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 90:b1:1c:f4:a3:c6 brd ff:ff:ff:ff:ff:ff link-netnsid 0
47: v-br11@if45: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 90:b1:1c:f4:a3:c6 brd ff:ff:ff:ff:ff:ff link-netnsid 0

[keepalived_VRF001_conf.txt](https://github.com/acassen/keepalived/files/4518546/keepalived_VRF001_conf.txt)

[journalctl-logs.txt](https://github.com/acassen/keepalived/files/4518533/journalctl-logs.txt)

**Comment by pqarmitage** [comment] 2020-04-23 08:41
Does this only occur if you reload keepalived with br11_v4_1 added to the configuration, or does the problem also occur if you start keepalived with the full configuration?

**Comment by pqarmitage** [comment] 2020-04-23 10:18
@arulkumar9690 Can you please post the output of `ip -d link show` in both the default namespace and the VRF1 namespace.

v-br10 and v-br11 are created with different parent interfaces, but they have the same mac address. br10.v257's parent interface is the parent of v-br10 rather than v-br10, which would normally suggest that v-br10 is a macvlan interface. Anyway, the `ip -d link show` outputs will enable me to configure interfaces that match what you are doing. At the moment I can't reproduce the problem.

**Comment by arulkumar9690** [comment] 2020-04-25 03:23
Behavior is observed in both the scenarios. If we reload keepalived with br11_v4_1 added to the configuration and when we start keepalived with fill configuration.

**ip -d link show (default namespace)**

68: br10: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether f4:38:e6:51:3a:0f brd ff:ff:ff:ff:ff:ff promiscuity 2
    bridge forward_delay 1500 hello_time 200 max_age 2000 ageing_time 540000 stp_state 0 priority 32768 vlan_filtering 0 vlan_protocol 802.1Q bridge_id 8000.f4:38:e6:51:3a:f designated_root 8000.f4:38:e6:51:3a:f root_port 0 root_path_cost 0 topology_change 0 topology_change_detected 0 hello_timer    0.00 tcn_timer    0.00 topology_change_timer    0.00 gc_timer 3209.76 vlan_default_pvid 1 group_fwd_mask 0 group_address 01:80:c2:00:00:00 mcast_snooping 0 mcast_router 1 mcast_query_use_ifaddr 0 mcast_querier 0 mcast_hash_elasticity 4 mcast_hash_max 512 mcast_last_member_count 2 mcast_startup_query_count 2 mcast_last_member_interval 100 mcast_membership_interval 26000 mcast_querier_interval 25500 mcast_query_interval 12500 mcast_query_response_interval 1000 mcast_startup_query_interval 3124 nf_call_iptables 0 nf_call_ip6tables 0 nf_call_arptables 0 addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
69: br11: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether f4:38:e6:51:3a:0f brd ff:ff:ff:ff:ff:ff promiscuity 2
    bridge forward_delay 1500 hello_time 200 max_age 2000 ageing_time 540000 stp_state 0 priority 32768 vlan_filtering 0 vlan_protocol 802.1Q bridge_id 8000.f4:38:e6:51:3a:f designated_root 8000.f4:38:e6:51:3a:f root_port 0 root_path_cost 0 topology_change 0 topology_change_detected 0 hello_timer    0.00 tcn_timer    0.00 topology_change_timer    0.00 gc_timer 3209.76 vlan_default_pvid 1 group_fwd_mask 0 group_address 01:80:c2:00:00:00 mcast_snooping 0 mcast_router 1 mcast_query_use_ifaddr 0 mcast_querier 0 mcast_hash_elasticity 4 mcast_hash_max 512 mcast_last_member_count 2 mcast_startup_query_count 2 mcast_last_member_interval 100 mcast_membership_interval 26000 mcast_querier_interval 25500 mcast_query_interval 12500 mcast_query_response_interval 1000 mcast_startup_query_interval 3124 nf_call_iptables 0 nf_call_ip6tables 0 nf_call_arptables 0 addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
72: e101-051-0.10@e101-051-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br10 state UP mode DEFAULT group default qlen 1000
    link/ether f4:38:e6:51:39:7f brd ff:ff:ff:ff:ff:ff promiscuity 1
    vlan protocol 802.1Q id 10 <REORDER_HDR>
    bridge_slave state forwarding priority 32 cost 100 hairpin off guard off root_block off fastleave off learning on flood on port_id 0x8001 port_no 0x1 designated_port 32769 designated_cost 0 designated_bridge 8000.f4:38:e6:51:3a:f designated_root 8000.f4:38:e6:51:3a:f hold_timer    0.00 message_age_timer    0.00 forward_delay_timer    0.00 topology_change_ack 0 config_pending 0 proxy_arp off proxy_arp_wifi off mcast_router 1 mcast_fast_leave off mcast_flood on addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
73: e101-051-0.11@e101-051-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br11 state UP mode DEFAULT group default qlen 1000
    link/ether f4:38:e6:51:39:7f brd ff:ff:ff:ff:ff:ff promiscuity 1
    vlan protocol 802.1Q id 11 <REORDER_HDR>
    bridge_slave state forwarding priority 32 cost 100 hairpin off guard off root_block off fastleave off learning on flood on port_id 0x8001 port_no 0x1 designated_port 32769 designated_cost 0 designated_bridge 8000.f4:38:e6:51:3a:f designated_root 8000.f4:38:e6:51:3a:f hold_timer    0.00 message_age_timer    0.00 forward_delay_timer    0.00 topology_change_ack 0 config_pending 0 proxy_arp off proxy_arp_wifi off mcast_router 1 mcast_fast_leave off mcast_flood on addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535



**ip -d link show ( non-default namespace )**

7: br10.v257@if68: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 00:00:5e:00:01:01 brd ff:ff:ff:ff:ff:ff link-netnsid 0 promiscuity 0
    macvlan mode private addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
70: v-br11@if69: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether f4:38:e6:51:3a:12 brd ff:ff:ff:ff:ff:ff link-netnsid 0 promiscuity 0
    macvlan mode bridge addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
71: v-br10@if68: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether f4:38:e6:51:3a:12 brd ff:ff:ff:ff:ff:ff link-netnsid 0 promiscuity 0
    macvlan mode bridge addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535

**Comment by pqarmitage** [comment] 2020-04-25 19:49
The interfaces v-br10 and v-br11 and macvlans rather than vlans, and this is fundamental to the issue.

This issue is resolved by commit ac7f279.

**Closed by pqarmitage** 2020-04-25 19:49 UTC
