### ISSUE TITLE
How to use sync connections in keepalived

### ISSUE THREAD

**Issue by igroost** [acassen/keepalived#1819] opened 2020-12-18 17:27 UTC
Hello.

Tell me how we can use contact synchronization between IPVS. In the configuration, I found the lvs_sync_daemon parameter, I included it in the config in the form of lvs_sync_daemon eth0, but the synchronization of conects does not occur. At the same time, if before starting keepalived I start ipvsadm via ipvsadm --start-daemon=master --mcast-interface=eth0 and on the second ipvs ipvsadm --start-daemon=backup --mcast-interface=eth0 everything works. i tried to specify in the configuration forcibly with the indication of syncid, judging by the documentation, contact synchronization will occur on those ipvs pairs where syncids match, but even with the explicit indication of syncid, synchronization does not occur.

```
global_defs {
      router_id IPVS-TEST-203
      lvs_timeouts tcp 3600 tcpfin 720 udp 300
      lvs_sync_daemon eth0
      notification_email {
      asvintsov@uma.tech
                      }
      notification_email_from ipvs-test-203.o2@zxz.su
      smtp_server 91.207.59.201
      smtp_connect_timeout 30
      smtp_alert_checker off
            }
```

```
Keepalived v2.1.5 (11/25,2020), git commit v2.1.5-210-gedd68ac+

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.4.40
Running on Linux 5.4.40-17.1.x86_64 #1 SMP Tue Sep 22 17:51:06 UTC 2020
Distro: CentOS Linux 7 (Core)

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-snmp --enable-snmp-rfc --enable-vrrp --disable-vrrp-auth --disable-iptables --with-init=systemd --enable-regex --enable-regex-timers --enable-checker-debug --enable-regex-debug --enable-log-file build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic LDFLAGS=-Wl,-z,relro 

Config options:  LVS REGEX REGEX_DEBUG VRRP OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 FILE_LOGGING LOG_FILE_APPEND CHECKER_DEBUG

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK
```

```
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: ------< Global definitions >------
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: Network namespace = (default)
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: Network namespace ipvs = (main namespace)
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: Router ID = IPVS-TEST-203
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: Smtp server = 91.207.59.201
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: Smtp server port = 25
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: Smtp HELO name = ipvs-test-203.o2.zxz.su
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: Smtp server connection timeout = 30
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: Email notification from = ipvs-test-203.o2@zxz.su
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: Email notification to:
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]:   asvintsov@uma.tech
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: Default smtp_alert = unset
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: Default smtp_alert_vrrp = unset
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: Default smtp_alert_checker = off
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: Checkers log all failures = false
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: No test config before reload
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: Dynamic interfaces = false
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: LVS TCP timeout = 3600
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: LVS TCP FIN timeout = 720
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: LVS TCP timeout = 300
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: LVS syncd interface = eth0
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: LVS syncd syncid = 0
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: LVS flush = false
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: LVS flush on stop = disabled
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: VRRP notify priority changes = false
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: VRRP IPv4 mcast group = 224.0.0.18
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: VRRP IPv6 mcast group = ff02::12
Dec 18 17:55:07 ipvs-test-203 Keepalived_healthcheckers[5449]: Gratuitous ARP delay = 5
```

Also, I understand correctly that the keepalived lvs_sync_daemon specified in the config is functionally similar to running ipvsadm with the parameters --start-daemon=master --mcast-interface=eth0

**Comment by pqarmitage** [comment] 2020-12-19 14:34
Starting with your last question, ipvs (or LVS) is implemented in the Linux kernel. ipvsadm is the main utility for configuring ipvs in the kernel, but keepalived also configures ipvs in the kernel. Whether the ipvs configuration is set up by ipvsadm or by keepalived, you end up with exactly the same result.  So your statement `Also, I understand correctly that the keepalived lvs_sync_daemon specified in the config is functionally similar to running ipvsadm ...` is not really correct; what would be correct to say is `Also, I understand correctly that the keepalived lvs_sync_daemon specified in the config is **identical** to running ipvsadm ...`.

Actually, specifying `lvs_sync_daemon eth0` in the keepalived config is exactly the same as executing:
```
ipvsadm with the parameters --start-daemon=master --mcast-interface=eth0
ipvsadm with the parameters --start-daemon=backup --mcast-interface=eth0
```
Yes, it runs both master and backup sync daemons, so that the node(s) that are backups for this node can also be masters with this node being a backup for them.

Consider the following configuration:
```
global_defs {
      lvs_sync_daemon eth0
}

vrrp_instance VI_1 {
    interface eth1
    virtual_router_id 251
    version 3
@nodeA    priority 240
@nodeB    priority 220
@nodeC    priority 200
    advert_int 1
    use_vmac
    virtual_ipaddress {
      10.2.0.101/32
    }
}

vrrp_instance VI_2 {
    interface eth1
    virtual_router_id 252
    version 3
@nodeA    priority 200
@nodeB    priority 240
@nodeC    priority 220
    advert_int 1
    use_vmac
    virtual_ipaddress {
      10.2.0.102/32
    }
}

vrrp_instance VI_3 {
    interface eth1
    virtual_router_id 253
    version 3
@nodeA    priority 220
@nodeB    priority 200
@nodeC    priority 240
    advert_int 1
    use_vmac
    virtual_ipaddress {
      10.2.0.103/32
    }
}

virtual_server 10.2.0.101 80      {
        lvs_sched sh
        lvs_method TUN
        protocol TCP

        real_server 10.1.57.100 80 {
        }
}

virtual_server 10.2.0.102 80      {
        lvs_sched sh
        lvs_method TUN
        protocol TCP

        real_server 10.1.57.105 80 {
        }
}

virtual_server 10.2.0.103 80      {
        lvs_sched sh
        lvs_method TUN
        protocol TCP

        real_server 10.1.57.110 80 {
        }
}
```
Under normal circumstances each node will be master for one vrrp instance, so nodeA will have ip address 10.2.0.101, node B 10.2.0.102 etc. Node A will therefore only receive packets addresses to 10.2.0.101, etc, and so on nodeA only virtual_server 10.2.0.101 80 will be active. Since all nodes are running the IPVS sync daemon in both master and backup modes, all nodes will be aware of all IPVS connections. Now suppose nodeA fails, nodeB will take over as VRRP master for 10.2.0.101 and the IPVS connection synchronisation will mean that nodeB has connection entries for the connections that nodeA was handling.

Likewise, either of nodeB or nodeC could now fail and the other will take over as VRRP master, all its virtual servers will be active since all VRRP instances will be in master state, and the node will have all the connection entries in its table.

Your keepalived configuration for the lvs-sync_daemon is correct, and I have tested it and it works fine. You will need to either run a keepalived with matching configuration on the system where you want the backup sync daemon to be running (so that keepalived can start the sync daemons), or you will need to manually configure the backup sync daemon using ipvsadm on the other system.

**Closed by pqarmitage** 2020-12-19 14:34 UTC

**Comment by igroost** [comment] 2020-12-19 22:44
@pqarmitage But in my configuration there is no vrrp_instance section, as I understand it is mandatory and without it synchronization will not work, i.e. it is not enough to specify only the lvs_sync_daemon option in the configuration?

**Comment by pqarmitage** [comment] 2020-12-20 10:01
@igroost It depends what you what to achieve. I merely gave an example above of what someone might want to do to try and help give an understanding of how it can be used.

However, I am not sure I can see how using keepalived to set up the lvs sync daemon without having VRRP instances can be useful.

**Comment by igroost** [comment] 2020-12-20 10:29
@pqarmitage We use two separate servers running keepalived with an identical configuration, for fault tolerance. We want to enable only session synchronization, without using the VRRP functionality, so that when we work on one keepalived, the sessions already installed to it will continue to work on the other because they will be synchronized. i tried enabling synchronization only by running ipvsadm --start-daemon=master --mcast-interface=eth0 before running keepalived and everything works. But if I just specify lvs_sync_daemon eth0 in the keepalived config, then no session synchronization occurs.

I believe that it is better to do all the settings in one place, i.e. in the keepalived config, than to separately enable synchronization via the ipvsadm startup parameters.

**Comment by pqarmitage** [comment] 2020-12-20 12:48
I agree it is better to do all the configuration in one place and that is why keepalived has the option for configuring the sync daemons.

Since your configuration looks correct and also since it works for me, it is rather difficult for me to suggest why it is not working on your systems.

It would be useful to see the output of `ipvsadm -L --daemon` when keepalived is running, and to see the output from both systems.

Also, after a connection is established via a virtual service, it would be worth looking at the output of
```
cat /proc/net/ip_vs_conn
cat /proc/net/ip_vs_conn_sync
```
on both systems.

If none of the above identifies where the problem is, then I would start using wireshark or tcpdump to look at what traffic is being passed between the systems.

**Comment by igroost** [comment] 2020-12-21 10:14
@pqarmitage Thanks for the information, tomorrow I will try to check what the command outputs from both systems show.

**Comment by igroost** [comment] 2020-12-21 23:53
@pqarmitage It looks like we have a problem with multicast passing between keepalived servers in different data centers, I previously started it this way. I started two servers with keepalived in one data center and synchronization of sessions only when specifying the option lvs_sync_daemon eth0 works, I see sessions both in the output of ipvsadm-lnc and in the outputs of cat /proc/net/ip_vs_conn, cat /proc/net/ip_vs_conn_sync. Please tell me how you can diagnose problems in the case of using such a scheme? In tcpdump, as I understand it, we can see multicast traffic in the outputs of cat /proc/net/ip_vs_conn*, but here I do not really understand the output and how it can be used, as well as information about sync_id for example can be found in the logs. Also I don't really understand what is useful and how to interpret the output 
# ipvsadm -l --daemon
master sync daemon (mcast=eth0, syncid=0)
backup sync daemon (mcast=eth0, syncid=0)
because in the working and non-working case, it was the same.

**Comment by pqarmitage** [comment] 2020-12-22 17:19
Since you are seeing
```
# ipvsadm -l --daemon
master sync daemon (mcast=eth0, syncid=0)
backup sync daemon (mcast=eth0, syncid=0)
```
when you are running with keepalived with `lvs_sync_daemon eth0` configured, it means that keepalived is doing what it is supposed to do; once keepalived has configured the kernel as above, then it is the kernel that now sends the synchronisation messages.

If you use a network monitor, e.g. wireshark ot tcpdump, you will see udp traffic being sent to the multicast address 224.0.0.81 port 8848, and these are the IPVS synchronisation messages; you should also see that the TTL of the packets is 1.

The reason it is working in one data centre and not when you are split between 2 data centres is almost certainly due to the traffic being multicast. If you set up two servers with keepalived in the same data centre and one in a remote data centre, you will see that connection information is synchronised between the two servers in the same data centre, but the one in the remote data centre does not get updated. That will prove that keepalived is setting up synchronisation properly, and the issue is related to passing traffic to the second data centre.

The solution to this depends on your network architecture between the two data centres. Do the data centres operate as a single layer 2 domain, or is there routing between the domains (layer 3)? Also, if your two data centres are operating as a single layer 2 domain, is there configuration in the network devices connecting the data centres which controls what multicast traffic is passed between the two data centres? If, on the other hand, you are routing between the two data centres, then you would also need to have multicast routing configured, and PIM running between the routers. Further, in this latter case, you would need to specify the TTL in the `lvs_sync_daemon` statement, since the default TTL is 1, which means that multicast routing would not forward the sync packets.

**Comment by igroost** [comment] 2021-01-13 11:01
@pqarmitage 

Tell me, why is the value different in the output of ipvsadm when the syncid is explicitly configured in the keepalived configuration?

```
# less /var/log/keepalived.log | grep syncid
Jan 13 13:07:06 ipvs-test-103 Keepalived_healthcheckers[4247]: LVS syncd syncid = 1

# cat /etc/keepalived/keepalived.conf | grep syncid
      lvs_sync_daemon eth0 syncid 1

# ipvsadm -l --daemon
master sync daemon (mcast=eth0, syncid=0)
backup sync daemon (mcast=eth0, syncid=0)
```

**Comment by pqarmitage** [comment] 2021-01-13 11:28
@igroost `grep syncid /var/log/keepalived.log` should also show
`LVS syncd vrrp name = syncid`
and you don't have a VRRP instance named `syncid`.

You should see log messages:
`(Line nn) Please use keyword "id" before lvs_sync_daemon syncid value`
and
`Unable to find vrrp instance syncid for lvs_syncd - clearing lvs_syncd config`
in your log files.

The keepalived.conf(5) man page states that the keyword to specify the syncid is `id`, not `syncid`.

**Comment by igroost** [comment] 2021-01-14 11:33
@pqarmitage To summarize and check that I understand everything correctly.

To enable synchronization minimally, it is enough to specify in the configuration keepalived lvs_sync_daemon eth0 id 1. After that, within one L2 segment, on keepalived with matching syncids, session synchronization will begin.

If the vps servers are located in different L2 segments, then you must also specify the TTL value in the keepalived configuration

You can enable session synchronization with two dogs directly via ipvsadm and in the keepalived config, but the configuration specified in keepalived takes precedence.

You can check which sessions are synchronized via 
cat /proc/net/ip_vs_conn_sync. Synced sessions can be identified by the SYNC value in the Origin column. If the Origin capital is listed as LOCAL then the sessions were originally installed with the current lvs

In the output of cat /proc/net/ip_vs_conn, you can view all sessions on lvs installed directly with it, as well as synchronized ones.

Tell me what will happen if two lvs are running the same VIP that customers are accessing. In this case, each lvs will send synchronized information about sessions to the neighboring one, i.e. each lvs will have a database of its own (installed sessions with it) + synchronized sessions with other lvs?

**Comment by pqarmitage** [comment] 2021-01-18 08:18
@igroost The minimum that is required to enable synchronization is `lvs_sync_daemon eth0`, and this will use id 0. If you want to use a different id, then that must be specified.

If your servers are in different L2 segments, then not only will you have to increase the TTL, as you say, but you will also need to ensure that you have multicast routing appropriately set up.

I am not sure what you mean by `two dogs`, but it you are using keepalived to configure IPVS, then it is best not to use ipvsadm to configure IPVS.

You are right in respect of /proc/net/ip_vs_conn_sync.

If two systems are both running IPVS with the same virtual servers are configured, then the synchronization information will be updated as you indicate. However, since there is a time delay before synchronization information is sent, it will probably be necessary (except possibly for UDP) for each connection to use the same system unless one of the systems fails.

Please note that apart from the very first question above, these questions are IPVS questions and not keepalived questions, and should be sent to an IPVS email list.

**Comment by CallMeKangSir** [comment] 2021-08-16 11:03
> @igroost The minimum that is required to enable synchronization is `lvs_sync_daemon eth0`, and this will use id 0. If you want to use a different id, then that must be specified.
> 
> If your servers are in different L2 segments, then not only will you have to increase the TTL, as you say, but you will also need to ensure that you have multicast routing appropriately set up.
> 
> I am not sure what you mean by `two dogs`, but it you are using keepalived to configure IPVS, then it is best not to use ipvsadm to configure IPVS.
> 
> You are right in respect of /proc/net/ip_vs_conn_sync.
> 
> If two systems are both running IPVS with the same virtual servers are configured, then the synchronization information will be updated as you indicate. However, since there is a time delay before synchronization information is sent, it will probably be necessary (except possibly for UDP) for each connection to use the same system unless one of the systems fails.
> 
> Please note that apart from the very first question above, these questions are IPVS questions and not keepalived questions, and should be sent to an IPVS email list.

@pqarmitage I get the same problem for firewall reason,but when i add port 8848,the back machine get the info only when connection closed.
[admin@BJCA-device ~]$ sudo ipvsadm -L -n -c
IPVS connection entries
pro expire state       source             virtual            destination
TCP 02:00  FIN_WAIT    192.168.220.8:15707 192.168.136.246:8000 192.168.136.114:8000
TCP 01:01  FIN_WAIT    192.168.220.8:15616 192.168.136.246:8000 192.168.136.114:8000
