### ISSUE TITLE
when node's bond up from down,cause keepalived sent gratious arp use wrong mac address

### ISSUE THREAD

**Issue by jamesWsg** [acassen/keepalived#1112] opened 2019-01-25 09:09 UTC
**environment**
I have two node (ubuntu14.04) as node1(hostname is 218) ，node2(hostname is 228)，detail info add in the last

 **reproduce step**

1, vrrp config: node1 and node2 state are all BACKUP,but node1 have high priority.deail info add in the last
2, ifdown node1's bond1,you can see VIP(172.17.73.77) switch to node2,and client can receive the gratious arp from node2's mac adrress(00:e0:ed:40:3f:86)
3, then ifup node1's bond1,you can see VIP(172.17.73.77) switch to node1, although client receive the gratious arp ,but in wrong mac (b6:66:23:ef:76:a7),the captured gratious arp packet as following

```
command: tcpdump -e -i bond1 arp 

09:01:39.580054 b6:66:23:ef:76:a7 (oui Unknown) > Broadcast, ethertype ARP (0x0806), length 60: Request who-has 172.17.73.77 (Broadcast) tell 172.17.73.77, length 46
09:01:40.780243 b6:66:23:ef:76:a7 (oui Unknown) > Broadcast, ethertype ARP (0x0806), length 60: Request who-has 172.17.73.77 (Broadcast) tell 172.17.73.77, length 46
09:01:41.980373 b6:66:23:ef:76:a7 (oui Unknown) > Broadcast, ethertype ARP (0x0806), length 60: Request who-has 172.17.73.77 (Broadcast) tell 172.17.73.77, length 46
09:01:43.180640 b6:66:23:ef:76:a7 (oui Unknown) > Broadcast, ethertype ARP (0x0806), length 60: Request who-has 172.17.73.77 (Broadcast) tell 172.17.73.77, length 46
09:01:44.380785 b6:66:23:ef:76:a7 (oui Unknown) > Broadcast, ethertype ARP (0x0806), length 60: Request who-has 172.17.73.77 (Broadcast) tell 172.17.73.77, length 46
09:01:45.580925 b6:66:23:ef:76:a7 (oui Unknown) > Broadcast, ethertype ARP (0x0806), length 60: Request who-has 172.17.73.77 (Bro
```
the probelm is step 3,the expected gratious arp is use the node1's bond1 mac(00:e0:ed:40:3f:84),but the actual mac does not exist. so the client lost connection to VIP（172.17.73.77），until you restart the
node1's keepalived.

i have test many times,found the mac is different every time.(i thought the mac is generate by keepalived or bond).
As a comparison,i delete bond1,direct use NIC. do as before steps,did not have the above problem. at first,i doubt the bond boot process cause this probblem, so i add the preempt_delay in vrrp_config,but it does not have effect.
so now i thought the keepalived may not cooperate well with bond . 
any help would be very appreciate. thanks very much

**node detail info**

1，node1 and node2 info
```
##node1:
bond1 have one NIC，bond mode is active-backup
root@218:~# ip add |grep bond1
3: enp3s0f0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond1 state UP group default qlen 1000
17: bond1: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    inet 172.17.73.37/22 brd 172.17.75.255 scope global bond1
    inet 172.17.73.77/22 scope global secondary bond1
root@218:~# cat /proc/net/bonding/bond1
Ethernet Channel Bonding Driver: v3.7.1 (April 27, 2011)

Bonding Mode: fault-tolerance (active-backup)
Primary Slave: None
Currently Active Slave: enp3s0f0
MII Status: up
MII Polling Interval (ms): 100
Up Delay (ms): 0
Down Delay (ms): 0

Slave Interface: enp3s0f0
MII Status: up
Speed: 10000 Mbps
Duplex: full
Link Failure Count: 0
Permanent HW addr: 00:e0:ed:40:3f:84
Slave queue ID: 0
root@218:~# 


## node2:
root@228:~# ip add |grep bond1
3: enp3s0f0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond1 state UP group default qlen 1000
7: bond1: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    inet 172.17.73.39/22 brd 172.17.75.255 scope global bond1
root@228:~# cat /proc/net/bonding/bond1 
Ethernet Channel Bonding Driver: v3.7.1 (April 27, 2011)

Bonding Mode: fault-tolerance (active-backup)
Primary Slave: None
Currently Active Slave: enp3s0f0
MII Status: up
MII Polling Interval (ms): 100
Up Delay (ms): 0
Down Delay (ms): 0

Slave Interface: enp3s0f0
MII Status: up
Speed: 10000 Mbps
Duplex: full
Link Failure Count: 0
Permanent HW addr: 00:e0:ed:40:3f:86
Slave queue ID: 0
root@228:~# 


```
2，node1 and node2 vrrp config

```
##node1
root@218:~# cat /etc/keepalived/keepalived.conf 
global_defs {
   vrrp_version 3
   vrrp_garp_master_refresh 1
}

vrrp_instance VRRP1 {
   state BACKUP
   interface bond1
   virtual_router_id 1
    priority 3
    preempt_delay 60
    advert_int 0.4
    track_interface {
        bond0
    }
    authentication {
        auth_type PASS
        auth_pass 1066
    }
    virtual_ipaddress {
        172.17.73.77/22
    }
}
root@218:~# 


##node2
root@228:~# cat /etc/keepalived/keepalived.conf 
global_defs {
   vrrp_version 3
   vrrp_garp_master_refresh 1
}

vrrp_instance VRRP1 {
   state BACKUP
   interface bond1
   virtual_router_id 1
    priority 2
    preempt_delay 60
    advert_int 0.4
    track_interface {
        bond0
    }
    authentication {
        auth_type PASS
        auth_pass 1066
    }
    virtual_ipaddress {
        172.17.73.77/22
    }
}
root@228:~# 
```

**Comment by pqarmitage** [comment] 2019-01-28 23:57
I have discovered what is happening now.

When a bond interface is created, it is assigned a random MAC address. When the first real interface is added to the bond interface (ip link set IF master BOND_IF), the bond interface inherits the MAC address of the real interface. When subsequent interfaces are added to the bond interface, they inherit the MAC address from the bond interface (in other words the MAC address of the first interface added to the bond interface).

The problem is that keepalived does not update the MAC address of an interface when it changes; it only updates the MAC address when it sees an interface being created. The reason the gratuitous ARP messages are being sent from b6:66:23:ef:76:a7 is that the new bond0 interface is assigned the MAC b6:66:23:ef:76:a7 when it is created, but keepalived doesn't update the MAC address when the real interfaces are assigned to the bond interface.

I will work on producing a patch to resolve this.

**Comment by pqarmitage** [comment] 2019-01-29 13:16
Commit 322679c resolves this issue, and updates the MAC address used by keepalived when the address changes.

**Closed by pqarmitage** 2019-01-29 13:16 UTC
