### ISSUE TITLE
How can I heat upgrade keepalived to new version?

### ISSUE THREAD

**Issue by UnknowSelf** [acassen/keepalived#1341] opened 2019-06-28 07:21 UTC
I use keepalived-1.3.5.  I upgrade keepalived to new version, and excute kill -HUP keepalived process, but the new version keepalived not worked.
I excute kill -9 keepalived process, the master transimit to slave.
So, How can I heat upgrade keepalived to new version and no switch between master and slave?
@pqarmitage
@acassen 
@vincentbernat
@andriyanov

**Comment by andriyanov** [comment] 2019-06-28 07:40
kill -HUP just re-reads config, not upgrades to a new version.
You can't change software version without restart and master re-election.

**Comment by pqarmitage** [comment] 2019-06-28 08:44
This is a duplicate of issue #1294.

**Closed by pqarmitage** 2019-06-28 08:44 UTC
