### ISSUE TITLE
SIGSEGV on service restart (version 2.0.15)

### ISSUE THREAD

**Issue by MikhaylovOA** [acassen/keepalived#1239] opened 2019-04-25 10:47 UTC
**Describe the bug**
If enable_dbus is specified in global_defs keepalived exits with SIGSEGV in a loop.

**To Reproduce**
1. Write keepalived.conf as below;
2. Reboot or restart service

**Keepalived version**
1. Binary was built from sources which have the git commit 3ebf2a0.
2. 
```
root@gw:~# keepalived -v
Keepalived v2.0.15 (unknown)

Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.9.144
Running on Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2+st1 (2018-11-16)

configure options: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --enable-dbus --enable-log-file --enable-snmp-vrrp --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-json --with-init=systemd build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fdebug-prefix-map=/root/build/keepalived/keepalived-2.0.15-dev=. -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-z,relro CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2

Config options:  LIBIPTC LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH JSON OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS FILE_LOGGING LOG_FILE_APPEND EINTR_CHECK

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV RTA_VIA FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK
```

**Distro:**
 - Name: Debian
 - Version: 9
 - Architecture: x86_64

**Configuration file:**
root@gw:~# cat /etc/keepalived/keepalived.conf
global_defs {
  enable_dbus
}
vrrp_instance eth1_52 {
  interface eth1
  virtual_ipaddress {
    192.168.1.10/24
  }
  priority 100
}

**System Log entries**
In attachment.
[keepalived_2.0.15_sigsegv.txt](https://github.com/acassen/keepalived/files/3116505/keepalived_2.0.15_sigsegv.txt)

**Comment by pqarmitage** [comment] 2019-04-25 11:08
With the config above I get the error message:
`(eth1_52) the virtual router id must be set`
and keepalived terminates.

Could you please provide the actual configuration you are using when the problem occurs.

Further could you please provide a stack backtrace from the coredump produced when keepalived segfaults.

**Comment by pqarmitage** [comment] 2019-04-25 12:01
I have discovered that the configuration you have given above does cause a segfault, although your log file does not show `(eth1_52) the virtual router id must be set`.

Commit 9c39564 resolves the segfault I have identified, but if your configuration does not have a `virtual_router_id nn` entry in the vrrp_instance block, the configuration will not work.

Can you please confirm whether commit 9c39564 resolves your issue.

**Comment by MikhaylovOA** [comment] 2019-04-25 12:18
Thank you for your quick reply.

I was trying to pinpoint this problem so I shrinked configuration as much as possible and accidently deleted virtual_router_id. Sorry.
So this could actually be another problem.

The problem I actually faced was like this (with the same configuration, but with virtual_router_id):
1. Reboot with "enable_dbus" part commented;
2. Uncomment "enable_dbus" and type "systemctl reload keepalived.service";
3. Type "systemctl restart keepalived.service".
After this I saw single SIGSEGV in /tmp/keepalived.log, not looped one like it was with previous issue.

**Comment by MikhaylovOA** [comment] 2019-04-25 12:25
> 
> 
> 
> Further could you please provide a stack backtrace from the coredump produced when keepalived segfaults.

Could you please show (or give me a link) how can I get it?

**Comment by pqarmitage** [comment] 2019-04-25 12:51
On my Debian virtual machine, it looks as though coredumps are not enabled by default.

https://stackoverflow.com/questions/2065912/core-dumped-but-core-file-is-not-in-the-current-directory has a description of what is necessary for coredumps. If you run `ulimit -c` and the output is `0`, then coredumps are disabled. Executing `ulimit -c unlimited` should enable coredumps. Running `cat /proc/sys/kernel/core_pattern` should tell you where core dumps are written. If the output is `core` then keepalived should produce a file `/core.PID`. After the coredump, run the folllowing:
```
gdb PATH_TO_KEEPALIVED PATH_TO_COREFILE
gdb> bt full
```
That should produce a backtrace, which you can then post to the issue report.

**Comment by pqarmitage** [comment] 2019-04-25 16:13
I can't reproduce the segfault, but I have found and resolved three issues related to reloading and DBus. They are now merged so it would be worth trying them to see if they resolve your issue.

**Comment by MikhaylovOA** [comment] 2019-04-26 05:19
Thank you, I will try it.
 
Cannot get coredumps.
Do I need any additional packages for this to work (like keepalived-debuginfo)?

**Comment by pqarmitage** [comment] 2019-04-26 07:06
If there is a package keepalived-debuginfo that that would help with the stack backtrace, but it won't enable coredumps themselves. Unfortunately I don't use Debian, so am not familiar with the specific details of how to enable coredumps. It _might_ help to add the `-m` switch to keepalived.

**Comment by MikhaylovOA** [comment] 2019-04-26 07:54
I cannot reproduce both of my issues on the most recent version, but if I comment physical interface ('interface eth1' part) I get SIGSEGV loop which seems similar to the first one.
Using -m option enabled me to get coredumps. There was lots of them (about 1500), so I only posted the last one.

(gdb) bt full
#0  0x000055d5e18f2ca0 in vrrp_complete_init () at vrrp.c:3372
        e = 0x55d5e3a69d00
        e1 = <optimized out>
        vrrp = 0x55d5e3a6d1e0
        old_vrrp = <optimized out>
        sgroup = <optimized out>
        next = <optimized out>
        vrrp1 = <optimized out>
        max_mtu_len = 0
        have_master = <optimized out>
        have_backup = <optimized out>
        scr = <optimized out>
#1  0x000055d5e18e7385 in start_vrrp (
    prev_global_data=prev_global_data@entry=0x0) at vrrp_daemon.c:565
No locals.
#2  0x000055d5e18e7c85 in start_vrrp_child () at vrrp_daemon.c:1049
        pid = 0
        syslog_ident = <optimized out>
        pid = 0
#3  0x000055d5e18e7d88 in vrrp_respawn_thread (thread=<optimized out>)
    at vrrp_daemon.c:876
No locals.
#4  0x000055d5e191c68d in thread_call (thread=0x55d5e3a68e50)
---Type <return> to continue, or q <return> to quit---
    at scheduler.c:1763
No locals.
#5  process_threads (m=0x55d5e3a68860) at scheduler.c:1811
        thread = 0x55d5e3a68e50
        thread_type = <optimized out>
#6  0x000055d5e191ce91 in launch_thread_scheduler (m=<optimized out>)
    at scheduler.c:1913
No locals.
#7  0x000055d5e18c5582 in keepalived_main (argc=9, argv=0x7ffd64e748b8)
    at main.c:1962
        report_stopped = true
        uname_buf = {sysname = "Linux", '\000' <repeats 59 times>,
          nodename = "GW2", '\000' <repeats 61 times>,
          release = "4.9.0-8-amd64", '\000' <repeats 51 times>,
          version = "#1 SMP Debian 4.9.130-2+st1 (2018-11-16)", '\000' <repeats 24 times>, machine = "x86_64", '\000' <repeats 58 times>,
          domainname = "(none)", '\000' <repeats 58 times>}
        end = 0x7ffd64e740b4 ""
        exit_code = 0
#8  0x00007f691e4472e1 in __libc_start_main ()
   from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#9  0x000055d5e18c343a in _start ()

**Comment by pqarmitage** [comment] 2019-04-26 15:43
I have just pushed some further commits related to reloading and DBus. 

Commit d34da8b resolves the segfault when no interface is specified. Many thanks for the stack backtrace.

**Closed by pqarmitage** 2019-04-26 15:43 UTC

**Comment by skydevil56** [comment] 2019-04-27 06:13
Great thanks for solve bugs.
