### ISSUE TITLE
1.2.20 - mixed v4/6 config worked fine, now segfaults

### ISSUE THREAD

**Issue by SjonHortensius** [acassen/keepalived#303] opened 2016-04-18 11:43 UTC
It seems commit 485847cd30503c1ec2370713c2593a2216f19bb1 broke my configuration; I'm using a pretty simple config where both an ipv4 and ipv6 vip is negotiated via ipv6 vrrp. This has worked fine for years; but keepalived now segfaults immediately

Here is my config
```
vrrp_instance VI_1 {
	state MASTER
	interface eth0
	virtual_router_id 1
	priority 110
	advert_int 1
	smtp_alert
	native_ipv6
	version 3

	authentication {
		auth_type AH
		auth_pass pass
	}

	track_script {
		check_nginx
	}

	unicast_peer {
		2a02:xxxx
	}

	virtual_ipaddress {
		141.xyz/32 dev eth0
		2a02:xyz/128 dev eth0
	}
}
```

My master simply segfaults, slave says this and then segfaults as well
```
Keepalived_vrrp[1635]: Registering Kernel netlink command channel
Keepalived_vrrp[1635]: Registering gratuitous ARP shared channel
Keepalived_vrrp[1635]: Opening file '/etc/keepalived/keepalived.conf'.
Keepalived_vrrp[1635]: (VI_2): address family must match VRRP instance [                141.xyz/32 dev eth0] - ignoring
Keepalived[1492]: pid 1635 exited due to segmentation fault (SIGSEGV).
Keepalived[1492]:   Please report a bug at https://github.com/acassen/keepalived/issues
Keepalived[1492]:   and include this log from when keepalived started, what happened
Keepalived[1492]:   immediately before the crash, and your configuration file.
Keepalived[1492]: VRRP child process(1635) died: Respawning
```

**Comment by gregnetau** [comment] 2016-04-21 03:19
I can confirm I am getting the same issues after attempting to upgrade to 1.2.20.


Additionally, I am getting


Apr 20 20:07:57 sjc-fw2 Keepalived_healthcheckers[19184]: Removing service [240x::e16]:443 from VS [240x::22]:443
Apr 20 20:07:57 sjc-fw2 Keepalived_healthcheckers[19184]: IPVS: Operation not supported with specified address family


Regards,

Greg

________________________________

**Comment by SjonHortensius** [comment] 2016-05-04 08:22
Is this bug missing context or information? Is this maybe a known problem or intended behavior?  Please let us know

**Comment by pqarmitage** [comment] 2016-05-04 10:34
Apologies for the delay in responding. It appears that I am not receiving emails from github at the moment.

Whereas previous versions of keepalived didn't complain about the configuration above, it never actually worked. The VRRPv3 protocol requires VRRP packets to be entirely IPv6 or entirely IPv4; this is both in respect of the source and destination addresses of the packets and the virtual ip addresses contained in the packets. In particular, it is not possible to mix IPv4 and IPv6 virtual IP addresses in a vrrp packet, nor indeed within a VRRP instance (RFC5798 states at 5.2.9 "... that is, IPv4 and IPv6 MUST NOT both be carried in one IPvX Address field").

What happened with keepalived prior to v1.2.20 was that if there was a virtual IP address that didn't match the address family of the virtual router itself, it was silently omitted from any vrrp packets sent. The receiving end should have then rejected the packet due to the packet length being wrong, but there was a bug in that code which in certain instances allowed the packet to be processed, which would appear to have been the case here.

There are two straightforward ways to update the configuration:
1. Create a second vrrp instance, for IPv4, and remove the 141.xyz/32 address from VI_1.
2. Move the 141.xyz/32 into a virtual_address_excluded block within the instance, which means it will be configured on the interface, but excluded from VRRP packets sent.

Clearly the code shouldn't segfault, and I am looking at that now to find the cause and resolve it.

**Comment by pqarmitage** [comment] 2016-05-04 10:38
Re option 2 above, it should be a virtual_**ip**address_excluded block.

**Comment by pqarmitage** [comment] 2016-05-04 10:41
@gregnetau 

Could you please provide a copy of your configuration so that I can attempt to see what is causing the healthcheckers problem.

I think that problem is different from the original problem, so it is probably best to report it as a separate issue.

**Comment by pqarmitage** [comment] 2016-05-04 11:29
The segfault issue is resolved in commit 7484481

**Comment by SjonHortensius** [comment] 2016-05-04 11:30
@pqarmitage thanks for your extensive response. It seems we did indeed used the two bugs combined into a feature. I'll have a look at *virtual_ipaddress_excluded* as that seems the easiest to setup. I'll update this issue when I have results

You were probably not notified of the issue initially because I didn't mention you explicitly expecting @acassen to respond. I'm not sure why he didn't but you might consider requesting co-owner ship of this repo; that 'd result in you getting notifications for all issues as well. You might also want to checkout [your notification settings](https://github.com/settings/notifications)

**Closed** 2016-05-04 12:41 UTC

**Comment by gregnetau** [comment] 2016-06-01 10:09
I have attached the sanitized configuration. 
[keepalived.zip](https://github.com/acassen/keepalived/files/293145/keepalived.zip)

Thanks!

**Comment by SjonHortensius** [comment] 2016-06-01 10:30
@gregnetau; it'd be more useful if you post this in the correct issue: https://github.com/acassen/keepalived/issues/341

**Comment by gregnetau** [comment] 2016-06-01 11:30
Sorry about that, unsure how this happened.
