### ISSUE TITLE
keepalived segmentfault while SSL check

### ISSUE THREAD

**Issue by HW-lj** [acassen/keepalived#1151] opened 2019-03-09 03:17 UTC
# keepalived -v
```Keepalived v2.0.6 (07/23,2018)

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.19.25
Running on Linux 4.19.25-vhulk1901.1.0.h110.aarch64 #1 SMP Tue Feb 12 00:00:00 UTC 2019

configure options: --build=aarch64-Huawei-linux-gnu --host=aarch64-Huawei-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-snmp --enable-snmp-rfc --enable-sha1 --with-init=systemd build_alias=aarch64-Huawei-linux-gnu host_alias=aarch64-Huawei-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fasynchronous-unwind-tables -fstack-clash-protection LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld

Config options:  LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RT SCHED_RESET_ON_FORK
```
The config is as follow:
```! Configuration File for keepalived
  
virtual_server 22.22.60.90 5001 {
    delay_loop 6
    lb_algo rr
    lb_kind DR
    protocol TCP
    alpha
    quorum 1
    hysteresis 0

    real_server 33.33.80.139 5001 {
        weight 1
        SSL_GET {
            url {
                path /
                status_code 200
            }
            connect_port 443
            connect_timeout 1
            retry 1
            delay_before_retry 1
        }
    }
}
```
The coredump is : 
![image](https://user-images.githubusercontent.com/48020967/54065471-6fb3f580-425c-11e9-985a-b46a51012324.png)

Thank you for your time.

**Comment by pqarmitage** [comment] 2019-03-11 16:01
I have tested your configuration on a x86_64 Fedora 26 and 29 systems and cannot reproduce the problem. I see you are using aarch64, and unfortunately I do not have access to such a system.

The call to SSL_CTX_set_verify_depth(SSL_CTX *ctx, int depth) is essentially ctx->param->depth = depth. The segfault suggests that either ctx or ctx->param is NULL, or invalid. The code doesn't check the return values of SSLv23_method(0 or SSL_CTX_new() so it is possible one of those calls is failing (I note that SSLv23_method() is deprecated now, and will update the code accordingly in due course).

Could you try applying the following patch and see if it tells us anything:
```
diff --git a/keepalived/check/check_ssl.c b/keepalived/check/check_ssl.c
index 69498197..35f15563 100644
--- a/keepalived/check/check_ssl.c
+++ b/keepalived/check/check_ssl.c
@@ -81,6 +81,7 @@ build_ssl_ctx(void)
        /* Initialize SSL context for SSL v2/3 */
        ssl->meth = SSLv23_method();
        ssl->ctx = SSL_CTX_new(ssl->meth);
+log_message(LOG_INFO, "ssl->meth %p, ssl->ctx %p", ssl->meth, ssl->ctx);
 
        /* return for autogen context */
        if (!check_data->ssl) {
```

**Comment by HW-lj** [comment] 2019-03-12 02:54
The log is:
`localhost Keepalived_healthcheckers[19942]: ssl->meth 0xffff7fed1818, ssl->ctx (nil)`, 
According to your advice, I find the ssl->ctx is NULL, further, the real reason is SSL_library_init() is missed. And then I‘m sure there are some difference between OPENSSL_init_crypto and ```SSL_library_init();SSL_load_error_strings();``` 
So I loop up some datas about OPENSSL_init_crypto and when  I changed OPENSSL_INIT_NO_LOAD_CRYPTO_STRINGS to  OPENSSL_INIT_LOAD_CRYPTO_STRINGS, the question seems disappear.

**Comment by HW-lj** [comment] 2019-03-12 04:29
I suddenly think of it that could you make without the MACRO HAVE_OPENSSL_INIT_CRYPTO in function build_ssl_ctx  of check_ssl.c to reproduce the problem. Because if I comment as follow:
'''
	/* Library initialization */
//#if HAVE_OPENSSL_INIT_CRYPTO
//	if (!OPENSSL_init_crypto(OPENSSL_INIT_NO_LOAD_CONFIG, NULL))
//		log_message(LOG_INFO, "OPENSSL_init_crypto failed");
//#else
	/* Library initialization */
	SSL_library_init();

	SSL_load_error_strings();
//#endif
'''
Everything works very well

**Comment by pqarmitage** [comment] 2019-03-12 09:26
@HW-lj Many thanks for your work on this. Could you please advise what version the openssl rpm package is that you are using.

SSL_library_init() is deprecated from OpenSSL V1.1.0, so we need to stop using it. The man page for OPENSSL_init_crypto() states that "As of version 1.1.0, OpenSSL will automatically allocate all resources that it needs so no explicit initialisation is required". Could you please try the following (for all of these we do NOT want SSL_library_init() or SSL_load_error_strings()):
1. Don't call OPENSSL_init_crypto() at all.
2. Use OPENSSL_init_ssl() instead of OPENSSL_init_crypto()

When everything works, are you calling OPENSSL_init_crypto() as `OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CRYPTO_STRINGS | OPENSSSL_INIT_NO_LOAD_CONFIG)`
or just as:
`OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CRYPTO_STRINGS)`

Do both of the above options work, or does just one of them? The strange thing about specifying OPENSSL_INIT_LOAD_CRYPTO_STRINGS is that the man page for OPENSSL_init_crypto() states that it is a default option.

Regarding OPENSSL_INIT_NO_LOAD_CONFIG, the man page for OPENSSL_init_crypto() indicates that there has been a change for OpenSSL 1.1.1. For libssl OPENSSL_INIT_LOAD CONFIG is now a default option, but neither it nor OPENSSL_INIT_NO_LOAD_CONFIG is a default option for libcrypto!

**Comment by HW-lj** [comment] 2019-03-12 11:38
Openssl version is 
```
# openssl version
OpenSSL 1.1.1 FIPS  11 Sep 2018
```
And sorry for I wrote something wrong due to my careless.
When everything works, I just call as OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CONFIG, NULL) instead of  OPENSSL_init_crypto(OPENSSL_INIT_NO_LOAD_CONFIG, NULL)  , there is nothing with OPENSSL_INIT_LOAD_CRYPTO_STRINGS!
With this option the loading of OpenSSL configuration files will be suppressed. And you are right, it's not a default option, just as the link says
https://www.openssl.org/docs/man1.1.0/man3/OPENSSL_init_crypto.html. 
At last, sorry for my careless again.

**Comment by pqarmitage** [comment] 2019-03-12 13:07
@HW-lj I have just installed RHEL 8 beta on an x86_64 VM, and I can reproduce the problem you have found. 

Could you please try and see what happens when the call to OPENSSL_init_crypto() is commented out. I have tried it on my RHEL 8 beta system, and it doesn't segfault when OPELSSL_init_crypto() is NOT called; presumably this is because the default option is OPENSSL_INIT_LOAD_CONFIG.

BTW keepalived v2.0.13 detects when the call to SSL_CTX_new() fails (i.e. ssl->ctx is NULL), and doesn't segfault (though SSL_GET won't work though).

What type of system are you running on? It looks a bit like an RHEL 8 beta system, but with a Huawei toolchain.

**Comment by HW-lj** [comment] 2019-03-12 13:24
Yes, your are right. When the call to OPENSSL_init_crypto() is commented out, no segfault would happen, of course, as you mentioned, SSL_GET won't work though. And we just replace OPENSSL_INIT_NO_LOAD_CONFIG with OPENSSL_INIT_LOAD_CONFIG. Everything is ok.
I'm running on EulerOS, which based on Centos indeed.For more detail, you can refer https://developer.huawei.com/ict/en/site-euleros

**Comment by pqarmitage** [comment] 2019-03-12 13:29
I have produced a trivial test program:
```
#include <stdio.h>
#include <openssl/ssl.h>

int main(int argc, char **argv)
{
	const SSL_METHOD *meth;
	SSL_CTX *ctx;

        if (!OPENSSL_init_crypto(OPENSSL_INIT_NO_LOAD_CONFIG, NULL))
                fprintf(stderr, "OPENSSL_init_crypto failed\n");

        /* Initialize SSL context */
        meth = TLS_method();
        if (!(ctx = SSL_CTX_new(meth))) {
                fprintf(stderr, "SSL error: cannot create new SSL context\n");
                return 1;
        }
}
```
With OpenSSL v1.1.0h and v1.1.1b this works without an error. With OpenSSL v1.1.1, as you have, SSL_CTX_new() returns NULL. On this basis, returning NULL is probably a bug introduced around about v1.1.1 and has been fixed by v1.1.1b. Rather than changing keepalived to always read the OpenSSL config, I'll add a configure check to detect the problem, and work around it if it exists. I'll also let RedHat know that there appears to be a problem.

**Comment by pqarmitage** [comment] 2019-03-12 13:33
From my reading of the man pages, if OPENSSL_init_crypto() is NOT called, then everything should be OK and the SSL_GET should work. It is in keepalived v2.0.13, which detects that SSL_CTX_new() returns null, thereby avoiding the segfault, that the subsequent SSL_GET fails. I think the SSL_GET should succeed if OPENSSL_init_crypto() isn't called; if the SSL_GET fails then that looks like another bug in openssl.

**Comment by HW-lj** [comment] 2019-03-12 13:53
emmmm, so it seems obvious that I must do something with openSSL, otherwise SSL_GET would not work correctly.

**Comment by pqarmitage** [comment] 2019-03-12 14:07
Since OpenSSL v1.1.0, it is not necessary to call the init functions - see man page for OPENSSL_init_crypto() - "As of version 1.1.0 OpenSSL will automatically allocate all resources that it needs so no explicit initialisation is required". If we are not setting OPENSSL_INIT_NO_LOAD_CONFIG, and so all the default settings are used, then there is no need to call OPENSSL_init_crypto().

**Comment by pqarmitage** [comment] 2019-03-12 14:10
The trivial test program above succeeds if OPENSSL_init_crypto() is not called, but fails (with OpenSSL v1.1.1) if OPENSSL_init_crypto() is called with OPENSSL_INIT_NO_LOAD_CONFIG.

**Comment by HW-lj** [comment] 2019-03-12 14:14
Do you mean we can just delete
```
if (!OPENSSL_init_crypto(OPENSSL_INIT_NO_LOAD_CONFIG, NULL))
		log_message(LOG_INFO, "OPENSSL_init_crypto failed");
```
And anything would be nice

**Comment by HW-lj** [comment] 2019-03-12 14:25
Just as what you said, when I delete
```
if (!OPENSSL_init_crypto(OPENSSL_INIT_NO_LOAD_CONFIG, NULL))
		log_message(LOG_INFO, "OPENSSL_init_crypto failed");
```
Everything works well, so why not delete it, or do you have some more purpose of calling it

**Comment by pqarmitage** [comment] 2019-03-12 14:27
Yes, we can potentially delete it, but I am assuming that if it is used, it will be more efficient, since OpenSSL will not have to load (unnecessary) config.

What I am thinking (and I'm working on a patch right now) is that if it doesn't work, we won't call it, but if it does, we will. This can be determined by a test at configure time.

**Comment by pqarmitage** [comment] 2019-03-12 15:12
I have merged commit fe6d6ac which should resolve the problem. Please confirm if it resolves the issue for you.

**Comment by HW-lj** [comment] 2019-03-13 03:08
Many thanks for your work on this. I have test the patch you give, in my environment, there are something to do so that it can works well.
```
AS_IF([test .$ac_cv_func_OPENSSL_init_crypto = .yes],
        [
         AC_RUN_IFELSE(
        [AC_LANG_PROGRAM(
                [[#include <openssl/ssl.h>]],
                [[
                      const SSL_METHOD *meth;
                      SSL_CTX *ctx;

                      if (!OPENSSL_init_crypto(OPENSSL_INIT_NO_LOAD_CONFIG, NULL))
                                return 1;

                      /* Initialize SSL context */
                      if ($ac_cv_func_TLS_method = yes)
                          meth = TLS_method();
                      else
                          meth = SSLv23_method();
                      if (!(ctx = SSL_CTX_new(meth)))
                                return 1;
                      return 0;
                    ]])],
                  [openssl_init_no_load_bug=0],
                  [openssl_init_no_load_bug=1],
                  [
                    AC_MSG_WARN([Cannot determine if need to OPENSSL_init_crypto() problem. Assuming yes for safety.])
                    openssl_init_no_load_bug=1
                  ]
         )
        AS_IF([test $openssl_init_no_load_bug -eq 1],
            [AC_DEFINE([HAVE_OPENSSL_INIT_NO_LOAD_CONFIG_BUG], [ 1 ], [Define to 1 if OPENSSL_init_crypto(OPENSSL_INIT_NO_LOAD_CONFIG) bug)])])

        ])
```
I think we should move the judgement of ac_cv_func_TLS_method into the all logic.

**Comment by HW-lj** [comment] 2019-03-13 07:08
BTW, could you observe that whether there is something wrong with log_message in RHEL 8 beta on an x86_64 VM.
In my environment， it seems I should do something, too.
![image](https://user-images.githubusercontent.com/48020967/54259591-43bcab00-45a1-11e9-8229-ba5fbc60a760.png)

**Comment by pqarmitage** [comment] 2019-03-13 09:52
> Many thanks for your work on this. I have test the patch you give, in my environment, there are something to do so that it can works well.
> 
> ```
>                       /* Initialize SSL context */
>                       if ($ac_cv_func_TLS_method = yes)
>                           meth = TLS_method();
>                       else
>                           meth = SSLv23_method();
> ```
> 
> I think we should move the judgement of ac_cv_func_TLS_method into the all logic.

Unfortunately the above is not valid C code, and will fail to compile. Since OPENSSL_init_crypto() and TLS_method() were both introduced in OpenSSL v1.1.0, I decided to take a short cut and assume that TLS_method() existed if OPENSSL_init_crypto() existed.

Commit 178ca08 adds the checking improvements you suggested above, and also updates genhash with the same fixes as SSL_GET.

**Comment by pqarmitage** [comment] 2019-03-13 10:07
> BTW, could you observe that whether there is something wrong with log_message in RHEL 8 beta on an x86_64 VM.
> In my environment， it seems I should do something, too.

When I run your configuration with keepalived v2.0.13, I get the following:
```
Wed Mar 13 10:03:38 2019: Opening file '/home/quentin/keepalived/github.pqa/../utils/configs/1151a.conf'.
Wed Mar 13 10:03:38 2019: Configuration is using : 3973 Bytes
Wed Mar 13 10:03:38 2019: Initializing ipvs
Wed Mar 13 10:03:38 2019: Gained quorum 1+0=1 <= 1 for VS [10.10.10.3]:tcp:1358
Wed Mar 13 10:03:38 2019: Activating healthchecker for service [192.168.200.4]:tcp:1358 for VS [10.10.10.3]:tcp:1358
Wed Mar 13 10:03:38 2019: Activating BFD healthchecker
Wed Mar 13 10:03:43 2019: Check on service [192.168.200.4]:tcp:1358 failed after 1 retries.
Wed Mar 13 10:03:43 2019: Removing service [192.168.200.4]:tcp:1358 to VS [10.10.10.3]:tcp:1358
Wed Mar 13 10:03:43 2019: Lost quorum 1-0=1 > 0 for VS [10.10.10.3]:tcp:1358
```
It would appear that you are using an older version of keepalived, and the problem has since been fixed.

**Comment by HW-lj** [comment] 2019-03-13 12:26
> > BTW, could you observe that whether there is something wrong with log_message in RHEL 8 beta on an x86_64 VM.
> > In my environment， it seems I should do something, too.
> 
> When I run your configuration with keepalived v2.0.13, I get the following:
> 
> ```
> Wed Mar 13 10:03:38 2019: Opening file '/home/quentin/keepalived/github.pqa/../utils/configs/1151a.conf'.
> Wed Mar 13 10:03:38 2019: Configuration is using : 3973 Bytes
> Wed Mar 13 10:03:38 2019: Initializing ipvs
> Wed Mar 13 10:03:38 2019: Gained quorum 1+0=1 <= 1 for VS [10.10.10.3]:tcp:1358
> Wed Mar 13 10:03:38 2019: Activating healthchecker for service [192.168.200.4]:tcp:1358 for VS [10.10.10.3]:tcp:1358
> Wed Mar 13 10:03:38 2019: Activating BFD healthchecker
> Wed Mar 13 10:03:43 2019: Check on service [192.168.200.4]:tcp:1358 failed after 1 retries.
> Wed Mar 13 10:03:43 2019: Removing service [192.168.200.4]:tcp:1358 to VS [10.10.10.3]:tcp:1358
> Wed Mar 13 10:03:43 2019: Lost quorum 1-0=1 > 0 for VS [10.10.10.3]:tcp:1358
> ```
> It would appear that you are using an older version of keepalived, and the problem has since been fixed.
Maybe this is related to the architecture or build environment, because when I changed the position of VS and RS, it works well. So I doubt args‘ sequence is different between ARM64 and X86_64

**Comment by pqarmitage** [comment] 2019-03-13 13:43
I'm not sure which version of keepalived you are using; is it still v2.0.6 or have you updated to v2.0.13. It would be helpful if you could clarify this, since there is a bit of a mismatch in the text being shown.

The log message I have in clear_service_rs() is:
```
                        log_message(LOG_INFO, "%s %sservice %s from VS %s",
                                        stopping ? "Shutting down" : "Removing",
                                        rs->inhibit && !rs->alive ? "(inhibited) " : "",
                                        FMT_RS(rs, vs),
                                        FMT_VS(vs));
```
whereas your original log message was:
`Removing service [10.10.10.3]:tcp:1358 to VS [10.10.10.3]:tcp:1358`
and this appears to be generated by function perform_svr_state() (compare "from" with "to").

The change you have quoted appears not only to have swapped the order of the last two parameters, but also reversed the order of the RS and VS in the text, so the two changes cancel each other out, but also it does not appear to relate to the line of code that is generating the log message you referred to, since it appears to be generated by perform_svr_state(). Further, since it was outputting [10.10.10.3] twice, I am not clear how reversing the order of FMT_RS() and FMT_VS() would change anything.

I have certainly in the past sorted out some of these messages so that the reported VS and RS identifiers make more sense.

I think the best thing would be if you could post a diff (ideally git diff) of the code changes you have made along with either the version of keepalived or the upstream git commit reference to which the changes apply, then I will have a look at what is happening.

**Comment by HW-lj** [comment] 2019-03-13 14:21
wow, you are so careful and nice!
 My version is still 2.0.6.
the config[forgive me for I changed it again :）]
```
! Configuration File for keepalived
  
virtual_server 22.22.60.90 5001 {
    delay_loop 6
    lb_algo rr
    lb_kind DR
    protocol TCP
    quorum 1
    hysteresis 0
    retry 1

    real_server 33.33.80.139 5001 {
        weight 1
        TCP_CHECK {
            connect_port 29
            connect_timeout 1
            delay_before_retry 1
        }
    }
}
```

the git diff
```
[2019-03-13 10:12:54] root@localhost ~/Euler_compile_env/workspace 
# git diff keepalived/check/ipwrapper.c
diff --git a/keepalived/check/ipwrapper.c b/keepalived/check/ipwrapper.c
index 51184ce..4e1d2a4 100644
--- a/keepalived/check/ipwrapper.c
+++ b/keepalived/check/ipwrapper.c
@@ -1247,10 +1247,10 @@ perform_svr_state(bool alive, checker_t *checker)
        if (ISALIVE(rs) == alive)
                return true;
 
-       log_message(LOG_INFO, "%sing service  %s to VS %s"
+       log_message(LOG_INFO, "%sing VS %s=> %s"
                            , alive ? (rs->inhibit) ? "Enabl" : "Add" :
                                      (rs->inhibit) ? "Disabl" : "Remov"
-                          ,FMT_RS(rs, vs),FMT_VS(vs));
+                          ,FMT_VS(vs),FMT_RS(rs, vs));
 
        /* Change only if we have quorum or no sorry server */
        if (vs->quorum_state_up || !vs->s_svr || !ISALIVE(vs->s_svr)) {

```
origin log:
```
Mar 13 10:07:38 localhost Keepalived_healthcheckers[1147]: Registering Kernel netlink command channel
Mar 13 10:07:38 localhost Keepalived_healthcheckers[1147]: Gained quorum 1+0=1 <= 1 for VS [22.22.60.90]:tcp:5001
Mar 13 10:07:45 localhost Keepalived_healthcheckers[1147]: TCP connection to [33.33.80.139]:tcp:5001 timeout.
Mar 13 10:07:45 localhost Keepalived_healthcheckers[1147]: Check on service [33.33.80.139]:tcp:5001 failed after 1 retries.
Mar 13 10:07:45 localhost Keepalived_healthcheckers[1147]: Removing service  [22.22.60.90]:tcp:5001 to VS [22.22.60.90]:tcp:5001
```
when I apply the patch, new log is:
```
Mar 13 10:11:47 localhost systemd[1]: Started LVS and VRRP High Availability Monitor.
Mar 13 10:11:47 localhost Keepalived_healthcheckers[2774]: Registering Kernel netlink command channel
Mar 13 10:11:47 localhost Keepalived_healthcheckers[2774]: Gained quorum 1+0=1 <= 1 for VS [22.22.60.90]:tcp:5001
Mar 13 10:11:48 localhost [/bin/bash]: [2019-03-13 10:11:47 service keepalived restart] return code=[0], execute success by [root(uid=0)] from [pts/1 (9.3.20.202)]
Mar 13 10:11:54 localhost Keepalived_healthcheckers[2774]: TCP connection to [33.33.80.139]:tcp:5001 timeout.
Mar 13 10:11:54 localhost Keepalived_healthcheckers[2774]: Check on service [33.33.80.139]:tcp:5001 failed after 1 retries.
Mar 13 10:11:54 localhost Keepalived_healthcheckers[2774]: Removing VS [22.22.60.90]:tcp:5001=> [33.33.80.139]:tcp:5001
Mar 13 10:11:54 localhost Keepalived_healthcheckers[2774]: Lost quorum 1-0=1 > 0 for VS [22.22.60.90]:tcp:5001
```
forgive my poor description and it's really nice of you (≧∀≦)ゞ!

**Comment by pqarmitage** [comment] 2019-03-13 15:10
OK, I see the real cause of the problem now, and I can see how swapping the order of FMT_VS() and FMT_RS() makes a difference.

The problem is that `FMT_RS()` calls `inet_sockaddrtotrio()` which uses a `static char []` to format the address, protocol and port in, and returns a pointer to the `static char []`. `FMT_VS()`, which is simply a call to `format_vs()`, also calls `inet_sockaddrtotrio()`, but then copies the contents of the returned `static char []` into it's own `static char []`. Therefore, if `FMT_VS()` is called first, and then `FMT_RS()` is called, everything is OK; if `FMT_RS()` is called first, and then `FMT_VS()` is called, `FMT_VS()` calls `format_vs()` which calls `inet_sockaddrtotrio()` and its `static char [],` which `FMT_RS()` is using, gets overwritten and the `char *` returned by `FMT_RS()` has been overwritten.

Since the order of evaluation of parameters for a function call in C is undefined, specifying parameters to `log_message()` (or any other function) in the order `FMT_RS(), FMT_VS()` or `FMT_VS(), FMT_RS() cannot be relied upon, since it is up to the compiler in which order it evaluates them.

That it works with x86_64 but doesn't work with aarch64 is almost certainly due to a difference in compiler implementations. We therefore need a more fundamental change, and also need to check all calls to `FMT_RS()`, `FMT_VS()` and `inet_sockaddrtotrio()` to make sure they are never used in constructing parameters to the same function call.

I will have a look further into this, and provide a patch once I have got it all sorted.

**Comment by HW-lj** [comment] 2019-03-13 15:19
Yes, so great you are! What I can think of is to judge the current arch and then decide to print sequence， a more fundamental function will be a more better solution! (～￣▽￣)～

**Comment by pqarmitage** [comment] 2019-03-13 15:34
Unfortunately determining the current arch will not provide a reliable solution. Since the order of calculating the parameters for a function call is entirely an implementation decision for the compiler, not only might, for example, gcc and clang do it differently for the same architecture, it is also entirely possible that the same compiler might not be consistent in how it does it.

What we will need to do is either move away from function local `static char []` or more likely calculate the parameters before the function call is specified, so that we can do it in a deterministic way.

**Comment by HW-lj** [comment] 2019-03-13 15:39
So rigorous you are! Then look forward to your replyლ(╹◡╹ლ)

**Comment by pqarmitage** [comment] 2019-03-14 15:44
I have been able to reproduce the logging problem on one of my ARMv7 (32 bit) systems and commit 9fe353d resolves the problem.

**Closed by pqarmitage** 2019-03-14 15:44 UTC

**Comment by bdperkin** [comment] 2019-03-14 16:54
Forgive me, but it appears that this commit belongs to a different issue than the one this issue is supposed to address.

**Comment by pqarmitage** [comment] 2019-03-14 17:29
@bdperkin Yes, you are quite right, and it's my fault really. The issue originally just referred to a segfault. In https://github.com/acassen/keepalived/issues/1151#issuecomment-472305390 @HW-lj subsequently added a further issue regarding incorrect logging when a real server was removed. I should have asked him to create a new issue report for that, but unfortunately I didn't do so. Commit 9fe353d deals with the second issue.
