### ISSUE TITLE
restart keepalived donot work,  Can't open PID file /var/run/keepalived.pid (yet?) after start: No such file or directory

### ISSUE THREAD

**Issue by kangqiao-lu** [acassen/keepalived#2402] opened 2024-04-02 07:52 UTC
restart keepalived donot work,  Can't open PID file /var/run/keepalived.pid (yet?) after start: No such file or directory

[root@localhost  ~]# systemctl start keepalived
[root@localhost  ~]# 
[root@localhost  ~]# 
[root@localhost  ~]# 
[root@localhost  ~]# ps aux |grep keepalived
root     450135  0.0  0.0 123016  1408 ?        Ss   15:47   0:00 /usr/sbin/keepalived -D
root     450136  0.0  0.0 144724  3912 ?        S    15:47   0:00 /usr/sbin/keepalived -D
root     450137  0.0  0.0 146748  3288 ?        S    15:47   0:00 /usr/sbin/keepalived -D
root     450504  0.0  0.0 112716   968 pts/2    S+   15:47   0:00 grep --color=auto keepalived
[root@st-mysql-uat-8 ~]# cat /var/run/keepalived.pid 
450135
[root@localhost  ~]# 
[root@localhost  ~]# systemctl restart keepalived
[root@localhost  ~]# ps aux |grep keepalived
root     450135  0.0  0.0 123016  1408 ?        Ss   15:47   0:00 /usr/sbin/keepalived -D
root     450136  0.0  0.0 144724  3912 ?        S    15:47   0:00 /usr/sbin/keepalived -D
root     450137  0.0  0.0 146748  3288 ?        S    15:47   0:00 /usr/sbin/keepalived -D
root     451767  0.0  0.0 112716   972 pts/2    S+   15:47   0:00 grep --color=auto keepalived
[root@localhost  ~]# cat /var/run/keepalived.pid 
cat: /var/run/keepalived.pid: No such file or directory

logmsg:
Apr  2 15:47:47 st-mysql-uat-8 systemd: Stopped LVS and VRRP High Availability Monitor.
Apr  2 15:47:47 st-mysql-uat-8 systemd: Stopping LVS and VRRP High Availability Monitor...
Apr  2 15:47:47 st-mysql-uat-8 systemd: Starting LVS and VRRP High Availability Monitor...
Apr  2 15:47:47 st-mysql-uat-8 Keepalived[451543]: Starting Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2
Apr  2 15:47:47 st-mysql-uat-8 Keepalived[451543]: Opening file '/etc/keepalived/keepalived.conf'.
Apr  2 15:47:47 st-mysql-uat-8 Keepalived[451543]: daemon is already running
Apr  2 15:47:47 st-mysql-uat-8 systemd: Can't open PID file /var/run/keepalived.pid (yet?) after start: No such file or directory
Apr  2 15:47:47 st-mysql-uat-8 systemd: Started LVS and VRRP High Availability Monitor.

keepalived.conf:
vrrp_script chk_mysql {
    script "/etc/keepalived/check_mysql.sh"
    interval 30
}

vrrp_instance VI_1 {
    state BACKUP       
    interface eth0
    virtual_router_id 99
    priority 100
    advert_int 1
    nopreempt          
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    track_script {
        chk_mysql
    }

    virtual_ipaddress {
        192.168.0.200/24 dev eth0 label eth0:1
    }
    notify_master "/etc/keepalived/notify_master.sh"
}

keepalived & system version:
keepalived-1.3.5-19
CentOS Linux release 7.7.1908 (Core)
Linux 3.10.0-514.el7.x86_64

**Comment by pqarmitage** [comment] 2024-04-02 11:01
I have tested _systemctl restart keepalived_ on my CentOS 7 VM and it works fine for me.

There are some strange things about the log output
1. systemd logs "Stopped ..." before it logs "Stopping ..."
2. The new keepalived logs that keepalived is already running.

Point 2 means that keepalived has found an old PID file and the process whose PID is in the file still exists. Each of the keepalived processes (parent process, VRRP process checker process) creates a PID file and each of them is checked. It is presumably the VRRP or checker process that is still running, since systemd complains that /var/run/keepalived.pid does not exist. After keepalived determines another instance of keepalived is still running the new keepalived then exits, which is why the keepalived.pid file does not exist.

Does this problem always happen when you restart keepalived, or is it intermittent? Have you checked the RedHat bugzilla for any relevant keepalived issues on RHEL7?

The interaction between keepalived and systemd has significantly improved since keepalived v1.3.5, as indeed has keepalived itself (there have been over 3000 non merge commits since v1.3.5). In order for us to look at the problem further, you would need to build and install the latest keepalived (i.e. v2.2.8 or later) and observe the problem occurring with that. You would also need to provide the full logs for keepalived since it started, and the relevant systemd logs.

I am closing this issue now, but if you provide the details identified in the previous paragraph and the problem is still occurring with keepalived v2.2.8+ we will reopen the issue.

**Closed by pqarmitage** 2024-04-02 11:01 UTC
