### ISSUE TITLE
CPU scheduling of the called scripts by keepalived  is not synchronized 

### ISSUE THREAD

**Issue by neutrino1** [acassen/keepalived#584] opened 2017-05-08 19:20 UTC
Hi,
Every time when state is changed the  notifyipsec.sh script is executed, the CPU scheduling of th scripts is not controlled by keepalived and multiple notifyipsec.sh scripts are not executed in a Last In Last Out order. The called scripts by keepalived scheduling is not synchronized due to which old/rotten/not-updated  commands are executed.

My Keepalived version is 1.2.15 and I excute it with command  "keepalived -P". The default state of both devices is MASTER with same priority but both machines have two IPs assigned on same ethernet interface i.e eth0 - VIP & eth0:0 1.1.1.4 second machine has eth0:0 1.1.1.5.

During following logs the notifyipsec.sh was executing "ipsec start" in MASTER state and in SLAVE state it execute "ipsec stop".

##TEST:
**Device current state** - SLAVE
**Action** - Plugged out and plug in the ethernet cable multiple times. Usually as soon as the device gets into state FAULT, the cable is plugged in.
**Observation** - On plug out the device get into state FAULT
              On plug in the device gets into state Master/Backup
              If its in state Master and own receving primary master device advert this device change its     state to BACKUP.
              The above can be seen in the following syslogs
#SYSLOG
eth0: Link is up - 1000/Full
May  5 14:36:36 localhost kernel: eth0: Link is up - 1000/Full
May  5 14:36:38 localhost Keepalived_vrrp[29923]: Kernel is reporting: interface eth0 UP
May  5 14:36:38 localhost Keepalived_vrrp[29923]: VRRP_Instance(VI_1) Transition to MASTER STATE
May  5 14:36:39 localhost Keepalived_vrrp[29923]: VRRP_Instance(VI_1) Entering MASTER STATE
May  5 14:36:39 localhost Keepalived_vrrp[29923]: Opening script file /usr/notifyipsec.sh
May  5 14:36:39 localhost Keepalived_vrrp[29923]: VRRP_Instance(VI_1) Received higher prio advert
May  5 14:36:39 localhost Keepalived_vrrp[29923]: VRRP_Instance(VI_1) Entering BACKUP STATE
May  5 14:36:39 localhost Keepalived_vrrp[29923]: Opening script file /usr/notifyipsec.sh

**Problem** - Sometime this SLAVE device has state BACKUP but ipsec is not stopped which is wrong, it occurred because ipsec stop is executed first and ipsec start is executed later on as can be seen in following auth.log but as I told before notifyipsec.sh was executing "ipsec start" in MASTER state and in SLAVE state it execute "ipsec stop". So behaviour is not what was expected. A part from auth.log is given below;

##AUTH.LOG
May  5 14:36:39 localhost sudo:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/echo MASTER
May  5 14:36:39 localhost sudo:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/echo BACKUP
May  5 14:36:39 localhost sudo:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ipsec stop
May  5 14:36:40 localhost sudo:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ipsec start
 
**Conclusion** - Please correct me, as per my understanding the notifyipsec.sh scheduling issue is causing this problem, although keepalive detected and set the VIP correctly but the called scripts are not scheduled as they should be i.e** "notifyipsec.sh MASTER" should had been scheduled first and "notifyipsec.sh SLAVE" afterwards, and ipsec should have stopped.**

**How can I resolve this issue, kindly guide me.**

**Comment by Navjot01** [comment] 2017-05-09 11:24
https://github.com/acassen/keepalived/pull/568

I hope you are talking about this issue, please read the discussion in above pull request

**Comment by pqarmitage** [comment] 2017-05-21 11:01
Closing due to duplicate of #568.

**Closed by pqarmitage** 2017-05-21 11:01 UTC

**Comment by pqarmitage** [comment] 2017-05-22 14:46
Commit 04905cd provides an alternative method to receive notification of events, which will be delivered in the correct order. Please see the comment in pull request #568 for how the mechanism for notifying events via a FIFO work.
