### ISSUE TITLE
Master doesn't send advertisement sometimes

### ISSUE THREAD

**Issue by pelucky** [acassen/keepalived#1157] opened 2019-03-12 05:49 UTC
Hi, all:
We find some strange thing when I used keepalived, we search the issue but can't find answer:

1. We found master(S1) would not send advertisement sometime, after Master_Down_internal(about 3s), backup(S2) become master. After a while, S1 would continue to send advertisement, and become master again.

S1(Master) log is below:
```
Mar 11 16:50:54 Keepalived_vrrp[12253]: VRRP_Instance(vnfvrrp) Received lower prio advert, forcing new election
Mar 11 16:50:54 Keepalived_vrrp[12253]: VRRP_Instance(vnfvrrp) Received lower prio advert, forcing new election
Mar 11 16:50:54 Keepalived_vrrp[12253]: VRRP_Instance(vnfvrrp) Received lower prio advert, forcing new election
Mar 11 16:51:01 Keepalived_vrrp[12253]: VRRP_Instance(vnfvrrp) Received lower prio advert, forcing new election
Mar 11 16:51:01 Keepalived_vrrp[12253]: VRRP_Instance(vnfvrrp) Received lower prio advert, forcing new election
Mar 11 16:51:01 Keepalived_vrrp[12253]: VRRP_Instance(vnfvrrp) Received lower prio advert, forcing new election
Mar 11 16:51:01 Keepalived_vrrp[12253]: VRRP_Instance(vnfvrrp) Received lower prio advert, forcing new election
```

S2(Backup) log is below:

```
Mar 11 16:50:52 Keepalived_vrrp[1753]: VRRP_Instance(vnfvrrp) Transition to MASTER STATE
Mar 11 16:50:53 Keepalived_vrrp[1753]: VRRP_Instance(vnfvrrp) Entering MASTER STATE
Mar 11 16:50:53 Keepalived_vrrp[1753]: Opening script file /home/script/keepalived/notify.sh
Mar 11 16:50:54 Keepalived_vrrp[1753]: VRRP_Instance(vnfvrrp) Received higher prio advert
Mar 11 16:50:54 Keepalived_vrrp[1753]: VRRP_Instance(vnfvrrp) Entering BACKUP STATE
Mar 11 16:50:54 Keepalived_vrrp[1753]: Opening script file /home/script/keepalived/notify.sh
Mar 11 16:50:58 Keepalived_vrrp[1753]: VRRP_Instance(vnfvrrp) Transition to MASTER STATE
Mar 11 16:50:59 Keepalived_vrrp[1753]: VRRP_Instance(vnfvrrp) Entering MASTER STATE
Mar 11 16:50:59 Keepalived_vrrp[1753]: Opening script file /home/script/keepalived/notify.sh
Mar 11 16:51:01 Keepalived_vrrp[1753]: VRRP_Instance(vnfvrrp) Received higher prio advert
Mar 11 16:51:01 Keepalived_vrrp[1753]: VRRP_Instance(vnfvrrp) Entering BACKUP STATE
Mar 11 16:51:01 Keepalived_vrrp[1753]: Opening script file /home/script/keepalived/notify.sh
```

At the same time, we tcpdump vrrp packets in master and backup

S1(Master) tcpdump's result:

```
16:50:46.995034 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:50:47.996116 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:50:48.997217 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:50:52.847968 IP S2 > S1: VRRPv2, Advertisement, vrid 254, prio 50, authtype simple, intvl 1s, length 20
16:50:53.829929 IP S2 > S1: VRRPv2, Advertisement, vrid 254, prio 50, authtype simple, intvl 1s, length 20
16:50:54.481599 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:50:54.482405 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:50:54.484594 IP S2 > S1: VRRPv2, Advertisement, vrid 254, prio 50, authtype simple, intvl 1s, length 20
16:50:54.543309 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:50:59.076677 IP S2 > S1: VRRPv2, Advertisement, vrid 254, prio 50, authtype simple, intvl 1s, length 20
16:50:59.404674 IP S2 > S1: VRRPv2, Advertisement, vrid 254, prio 50, authtype simple, intvl 1s, length 20
16:51:00.359018 IP S2 > S1: VRRPv2, Advertisement, vrid 254, prio 50, authtype simple, intvl 1s, length 20
16:51:01.050623 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:51:01.051588 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:51:01.053921 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:51:01.051618 IP S2 > S1: VRRPv2, Advertisement, vrid 254, prio 50, authtype simple, intvl 1s, length 20
16:51:01.054572 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:51:02.248942 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:51:03.577721 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
```

S2(Backup) tcpdump's result:

```
16:50:46.992217 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:50:47.993308 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:50:48.994394 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:50:52.799917 IP S2 > S1: VRRPv2, Advertisement, vrid 254, prio 50, authtype simple, intvl 1s, length 20
16:50:53.802719 IP S2 > S1: VRRPv2, Advertisement, vrid 254, prio 50, authtype simple, intvl 1s, length 20
16:50:54.478714 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:50:54.478888 IP S2 > S1: VRRPv2, Advertisement, vrid 254, prio 50, authtype simple, intvl 1s, length 20
16:50:54.479518 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:50:54.540455 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:50:58.345509 IP S2 > S1: VRRPv2, Advertisement, vrid 254, prio 50, authtype simple, intvl 1s, length 20
16:50:59.355483 IP S2 > S1: VRRPv2, Advertisement, vrid 254, prio 50, authtype simple, intvl 1s, length 20
16:51:00.356036 IP S2 > S1: VRRPv2, Advertisement, vrid 254, prio 50, authtype simple, intvl 1s, length 20
16:51:01.048542 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:51:01.048687 IP S2 > S1: VRRPv2, Advertisement, vrid 254, prio 50, authtype simple, intvl 1s, length 20
16:51:01.048695 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:51:01.051262 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:51:01.051737 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:51:02.246101 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
16:51:03.574886 IP S1 > S2: VRRPv2, Advertisement, vrid 254, prio 100, authtype simple, intvl 1s, length 20
```

You can find, Master(S1) didn't send any advertisement between 16:50:49 to 16:50:51.
We can't find any strange log in syslog.

This happened in some servers sometimes irregularly.

**So we want to find out how to fix this question**.

2. We set `garp_master_refresh_repeat` and `garp_master_repeat` to 1, but master will always send 5 gratuious ARP at one time, no matter it transfer to master or send gratuious arp periodly.

```shell
11:50:21.691572 A1_MAC > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has A1_IP (ff:ff:ff:ff:ff:ff) tell A1_IP, length 28
11:50:21.691744 A1_MAC > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has A1_IP (ff:ff:ff:ff:ff:ff) tell A1_IP, length 28
11:50:21.691791 A1_MAC > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has A1_IP (ff:ff:ff:ff:ff:ff) tell A1_IP, length 28
11:50:21.691844 A1_MAC > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has A1_IP (ff:ff:ff:ff:ff:ff) tell A1_IP, length 28
11:50:21.691885 A1_MAC > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has A1_IP (ff:ff:ff:ff:ff:ff) tell A1_IP, length 28
```

Version
* Linux HOSTNAME 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux
* Keepalived v1.2.13 (05/28,2014)

Master(S1) config:
```
vrrp_instance vnfvrrp {
    state MASTER
    interface eth1
    garp_master_delay 10
    virtual_router_id 254
    nopreempt
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass XXXXXX
    }
    unicast_peer {
        S2_IP
    }
    notify /home/script/keepalived/notify.sh
    virtual_ipaddress {
        VIP1 dev eth1
    }
    virtual_ipaddress_excluded {
        VIP2 dev eth0
        VIP3 dev eth0
    }
    virtual_routes {
        default via ROUTE dev eth0
    }
}
```

Bachup(S2) config:
```
vrrp_instance vnfvrrp {
	state BACKUP
	interface eth1
	garp_master_delay 10
	virtual_router_id 254
	nopreempt
	priority 50
	advert_int 1
	authentication {
		auth_type PASS
		auth_pass XXXXXX
	}
	unicast_peer {
		S1_IP
	}
	notify /home/script/keepalived/notify.sh
	virtual_ipaddress {
		VIP1 dev eth1
	}
	virtual_ipaddress_excluded {
		VIP2 dev eth0
		VIP3 dev eth0
	}
	virtual_routes {
		default via ROUTE dev eth0
	}
}
```

Hope for reply!

**Comment by pqarmitage** [comment] 2019-03-12 08:00
The version of keepalived is very old (nearly 5 years), and there have been a very large number of fixes, performance enhancements and functionality enhancements since then (over 2,500 commits).

The first thing you need to try is to upgrade to v2.0.13 and s ee if the problem still occurs. You will certainly be able to reduce the number of GARP messages to 1, and stop the GARP repeats. I'm not convinced that it will stop the lack of adverts; that looks more like a network or system issue than a keepalived issue to me. However, with recent versions of keepalived you can increase its realtime scheduling priority, and also lock it into memory in case that might be the cause of the problem.

**Comment by chr4** [comment] 2019-03-18 09:24
Sidequestion: Is there an official repository for Ubuntu/ Debian or linux-amd64 binaries that are maintained from keepalived? 

I also still use `1.3.9` as it's the version shipped with current Ubuntu LTS, and I had no luck finding an official binary distribution of keepalived. Is the recommended way to package and maintain it myself?

**Comment by pqarmitage** [comment] 2019-03-18 12:37
The is a snap of keepalived produced by Ubuntu, and the edge version is currently 2.0.10. I'm not sure why it isn't 2.0.13 since it used to automatically update to the latest version from github.

Alternatively, the simplest thing for you to do is to build keepalived yourself. The INSTALL file has instructions for building and installing.

**Comment by pqarmitage** [comment] 2019-03-19 10:05
@pelucky Is there any update on this, or should we close the issue now?

**Comment by pqarmitage** [comment] 2019-03-25 21:46
Closing due to no update for 14 days. If you have any updates, please post them to this issue, which can be reopened if necessary.

**Closed by pqarmitage** 2019-03-25 21:46 UTC
