### ISSUE TITLE
equal priority advert received from remote host with our IP address

### ISSUE THREAD

**Issue by fansari** [acassen/keepalived#2283] opened 2023-04-06 13:43 UTC
**Describe the bug**
I am not sure whether this is a bug or some misconfiguration.

These warnings come up every few seconds.

```
(VRRP2) WARNING - equal priority advert received from remote host with our IP address.
```

This appears only on the master node and only on the second VRRP instance where IPv6 is configured.

**To Reproduce**
Any steps necessary to reproduce the behaviour:

Configure two VRRP instances: one for IPv4 and one for IPv6.

This appears also when I disable the notify and track scripts.

**Expected behavior**
I expect not to have a flood of warning messages.

**Keepalived version**
```
Keepalived v2.2.4 (08/21,2021)

Copyright(C) 2001-2021 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.14.0
Running on Linux 5.14.0-285.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Mar 7 17:32:48 UTC 2023
Distro: CentOS Stream 9

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/sha
re --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-snmp --enable-snmp-rfc --enable-nftables --disable-iptab
les --enable-sha1 --enable-json --with-init=systemd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CC=gcc CFLAGS=-O2 -flto=auto -ffat-lto-objects -fexcept
ions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m6
4 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annob
in-cc1

Config options:  NFTABLES LVS VRRP VRRP_AUTH VRRP_VMAC JSON OLD_CHKSUM_COMPAT SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 INIT=systemd SYSTEMD_NOTIFY

System options:  VSYSLOG MEMFD_CREATE IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_F
ASTOPEN_NO_COOKIE RTA_VIA FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_AT
TR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_IPVLAN IFLA_LINK_NETNSID GLOB_BRACE GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE VRF SO_MARK
```

**Distro (please complete the following information):**
 - Name: CentOS Stream
 - Version: 9
 - Architecture: x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
keepalived runs directly on the host.

**Configuration file:**
```
global_defs {
    dynamic_interfaces
    enable_script_security
    max_auto_priority
    script_user root
}

vrrp_script keepalived_check {
      script "/usr/local/bin/keepalived/keepalived_check.sh"
      interval 1
      timeout 5
      rise 3
      fall 3
}

vrrp_sync_group VRRP1_2 {
  group {
    VRRP1
    VRRP2
  }

  track_script {
    keepalived_check
  }

  track_interface {
   br_nginx
    dummy0
  }

  notify /usr/local/bin/keepalived/keepalived_notify.sh
}

vrrp_instance VRRP1 {
    state MASTER
    nopreempt

    interface ens18

    virtual_router_id 52

    priority 200

    advert_int 1

    virtual_ipaddress {
        10.xxx.xxx.12/24
    }
}

vrrp_instance VRRP2 {
    state MASTER
    nopreempt

    interface ens18

    virtual_router_id 58

    priority 200

    advert_int 1

    virtual_ipaddress {
        fe80::afff:fe61:12/64
        2xxx:xxxx:xxxx:xxxx::12/64
    }
}
```

**Notify and track scripts**

I get the same behaviour when I disable the notify and track scripts.

**System Log entries**
```
Apr 06 13:32:58 myhost Keepalived[1161749]: Starting Keepalived v2.2.4 (08/21,2021)
Apr 06 13:32:58 myhost Keepalived[1161749]: Running on Linux 5.14.0-285.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Mar 7 17:32:48 UTC 2023 (built for Linux 5.14.0)
Apr 06 13:32:58 myhost Keepalived[1161749]: Command line: '/usr/sbin/keepalived' '--dont-fork' '-D'
Apr 06 13:32:58 myhost Keepalived[1161749]: Opening file '/etc/keepalived/keepalived.conf'.
Apr 06 13:32:58 myhost Keepalived[1161749]: Configuration file /etc/keepalived/keepalived.conf
Apr 06 13:32:58 myhost Keepalived[1161749]: Starting VRRP child process, pid=1161750
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: Registering Kernel netlink reflector
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: Registering Kernel netlink command channel
Apr 06 13:32:58 myhost Keepalived[1161749]: Startup complete
Apr 06 13:32:58 myhost systemd[1]: Started LVS and VRRP High Availability Monitor.
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: (VRRP1) Warning - nopreempt will not work with initial state MASTER - clearing
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: Assigned address 10.xxx.xxx.16 for interface ens18
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: Assigned address fe80::f4b0:afff:fe61:a1e7 for interface ens18
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: (VRRP2) Warning - nopreempt will not work with initial state MASTER - clearing
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: Assigned address 172.18.0.1 for interface br_nginx
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: Assigned address fe80::42:aff:fe76:1162 for interface br_nginx
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: Registering gratuitous ARP shared channel
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: Registering gratuitous NDISC shared channel
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: (VRRP1) removing VIPs.
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: (VRRP2) removing VIPs.
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: VRRP sockpool: [ifindex(  2), family(IPv4), proto(112), fd(14,15)]
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: VRRP sockpool: [ifindex(  2), family(IPv6), proto(112), fd(16,17)]
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: VRRP_Script(keepalived_check) succeeded
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: (VRRP2) Entering BACKUP STATE
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: VRRP_Group(VRRP1_2) Syncing instances to BACKUP state
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: (VRRP1) Entering BACKUP STATE
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: (VRRP1) received lower priority (100) advert from 10.xxx.xxx.17 - discarding
Apr 06 13:32:58 myhost Keepalived_vrrp[1161750]: (VRRP2) received lower priority (100) advert from fe80::4d9:1eff:fe8c:1549 - discarding
Apr 06 13:32:59 myhost Keepalived_vrrp[1161750]: (VRRP1) received lower priority (100) advert from 10.xxx.xxx.17 - discarding
Apr 06 13:32:59 myhost Keepalived_vrrp[1161750]: (VRRP2) received lower priority (100) advert from fe80::4d9:1eff:fe8c:1549 - discarding
Apr 06 13:33:00 myhost Keepalived_vrrp[1161750]: (VRRP1) received lower priority (100) advert from 10.xxx.xxx.17 - discarding
Apr 06 13:33:00 myhost Keepalived_vrrp[1161750]: (VRRP2) received lower priority (100) advert from fe80::4d9:1eff:fe8c:1549 - discarding
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: (VRRP2) Receive advertisement timeout
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: (VRRP1) Receive advertisement timeout
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: (VRRP1) Entering MASTER STATE
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: (VRRP1) setting VIPs.
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: (VRRP1) Sending/queueing gratuitous ARPs on ens18 for 10.xxx.xxx.12
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: Sending gratuitous ARP on ens18 for 10.xxx.xxx.12
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: Sending gratuitous ARP on ens18 for 10.xxx.xxx.12
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: Sending gratuitous ARP on ens18 for 10.xxx.xxx.12
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: Sending gratuitous ARP on ens18 for 10.xxx.xxx.12
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: Sending gratuitous ARP on ens18 for 10.xxx.xxx.12
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: VRRP_Group(VRRP1_2) Syncing instances to MASTER state
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: (VRRP2) Entering MASTER STATE
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: (VRRP2) setting VIPs.
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: (VRRP2) Sending/queueing Unsolicited Neighbour Adverts on ens18 for fe80::afff:fe61:12
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for fe80::afff:fe61:12
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: (VRRP2) Sending/queueing Unsolicited Neighbour Adverts on ens18 for 2xxx.xxxx:xxxx:xxxx::12
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for 2xxx.xxxx:xxxx:xxxx::12
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for fe80::afff:fe61:12
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for 2xxx.xxxx:xxxx:xxxx::12
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for fe80::afff:fe61:12
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for 2xxx.xxxx:xxxx:xxxx::12
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for fe80::afff:fe61:12
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for 2xxx.xxxx:xxxx:xxxx::12
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for fe80::afff:fe61:12
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for 2xxx.xxxx:xxxx:xxxx::12
Apr 06 13:33:01 myhost Keepalived_vrrp[1161750]: (VRRP2) WARNING - equal priority advert received from remote host with our IP address.
Apr 06 13:33:02 myhost Keepalived_vrrp[1161750]: (VRRP2) WARNING - equal priority advert received from remote host with our IP address.
Apr 06 13:33:03 myhost Keepalived_vrrp[1161750]: (VRRP2) WARNING - equal priority advert received from remote host with our IP address.
Apr 06 13:33:04 myhost Keepalived_vrrp[1161750]: (VRRP2) WARNING - equal priority advert received from remote host with our IP address.
Apr 06 13:33:05 myhost Keepalived_vrrp[1161750]: (VRRP2) WARNING - equal priority advert received from remote host with our IP address.
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: (VRRP1) Sending/queueing gratuitous ARPs on ens18 for 10.xxx.xxx.12
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: Sending gratuitous ARP on ens18 for 10.xxx.xxx.12
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: Sending gratuitous ARP on ens18 for 10.xxx.xxx.12
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: Sending gratuitous ARP on ens18 for 10.xxx.xxx.12
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: Sending gratuitous ARP on ens18 for 10.xxx.xxx.12
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: Sending gratuitous ARP on ens18 for 10.xxx.xxx.12
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: (VRRP2) Sending/queueing Unsolicited Neighbour Adverts on ens18 for fe80::afff:fe61:12
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for fe80::afff:fe61:12
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: (VRRP2) Sending/queueing Unsolicited Neighbour Adverts on ens18 for 2xxx.xxxx:xxxx:xxxx::12
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for 2xxx.xxxx:xxxx:xxxx::12
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for fe80::afff:fe61:12
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for 2xxx.xxxx:xxxx:xxxx::12
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for fe80::afff:fe61:12
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for 2xxx.xxxx:xxxx:xxxx::12
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for fe80::afff:fe61:12
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for 2xxx.xxxx:xxxx:xxxx::12
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for fe80::afff:fe61:12
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: Sending unsolicited Neighbour Advert on ens18 for 2xxx.xxxx:xxxx:xxxx::12
Apr 06 13:33:06 myhost Keepalived_vrrp[1161750]: (VRRP2) WARNING - equal priority advert received from remote host with our IP address.
Apr 06 13:33:07 myhost Keepalived_vrrp[1161750]: (VRRP2) WARNING - equal priority advert received from remote host with our IP address.
Apr 06 13:33:08 myhost Keepalived_vrrp[1161750]: (VRRP2) WARNING - equal priority advert received from remote host with our IP address.
Apr 06 13:33:09 myhost Keepalived_vrrp[1161750]: (VRRP2) WARNING - equal priority advert received from remote host with our IP address.
Apr 06 13:33:10 myhost Keepalived_vrrp[1161750]: (VRRP2) WARNING - equal priority advert received from remote host with our IP address.
Apr 06 13:33:11 myhost Keepalived_vrrp[1161750]: (VRRP2) WARNING - equal priority advert received from remote host with our IP address.
Apr 06 13:33:12 myhost Keepalived_vrrp[1161750]: (VRRP2) WARNING - equal priority advert received from remote host with our IP address.
Apr 06 13:33:13 myhost Keepalived_vrrp[1161750]: (VRRP2) WARNING - equal priority advert received from remote host with our IP address.
Apr 06 13:33:14 myhost Keepalived_vrrp[1161750]: (VRRP2) WARNING - equal priority advert received from remote host with our IP address.
Apr 06 13:33:15 myhost Keepalived_vrrp[1161750]: (VRRP2) WARNING - equal priority advert received from remote host with our IP address.
```

**Did keepalived coredump?**

no

**Additional context**

**Comment by pqarmitage** [comment] 2023-04-06 14:26
The `WARNING - equal priority advert received from remote host with our IP address.` message means that the adverts that are being sent (with priority 200) are for some reason being looped back and received by the host.

I think you will need to try some monitoring of the various interfaces (e.g. with wireshark) to see if you can see what is happening with the packets, e.g. are the adverts being sent externally and then some external device is sending them back again, are the packets being looped back in the kernel.

**Comment by fansari** [comment] 2023-04-06 14:52
Something like this?

```
tcpdump -nn -i ens18 host ff02::12
dropped privs to tcpdump
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on ens18, link-type EN10MB (Ethernet), snapshot length 262144 bytes
14:51:06.642878 IP6 fe80::f4b0:afff:fe61:a1e7 > ff02::12: VRRPv3, Advertisement, vrid 58, prio 200, intvl 100cs, length 40
14:51:07.643174 IP6 fe80::f4b0:afff:fe61:a1e7 > ff02::12: VRRPv3, Advertisement, vrid 58, prio 200, intvl 100cs, length 40
14:51:08.643428 IP6 fe80::f4b0:afff:fe61:a1e7 > ff02::12: VRRPv3, Advertisement, vrid 58, prio 200, intvl 100cs, length 40
14:51:09.643694 IP6 fe80::f4b0:afff:fe61:a1e7 > ff02::12: VRRPv3, Advertisement, vrid 58, prio 200, intvl 100cs, length 40
14:51:10.643979 IP6 fe80::f4b0:afff:fe61:a1e7 > ff02::12: VRRPv3, Advertisement, vrid 58, prio 200, intvl 100cs, length 40
14:51:11.644215 IP6 fe80::f4b0:afff:fe61:a1e7 > ff02::12: VRRPv3, Advertisement, vrid 58, prio 200, intvl 100cs, length 40
14:51:12.644511 IP6 fe80::f4b0:afff:fe61:a1e7 > ff02::12: VRRPv3, Advertisement, vrid 58, prio 200, intvl 100cs, length 40
```

**Comment by pqarmitage** [comment] 2023-04-11 08:08
`I see that the first message has the source Mac from the ens18 interface of the host and the second one the interface from the physical host where the VM is running on.`

This means that the host is sending the advert back to the VM, which is the cause of the `(VRRP2) WARNING - equal priority advert received from remote host with our IP address.` messages.

This is outside the scope of keepalived, and unfortunately I don't know what to suggest in terms of configuration changes of the host to stop the adverts being looped back.

**Comment by pqarmitage** [comment] 2023-05-12 13:54
Closing due to no update for over 1 month.

**Closed by pqarmitage** 2023-05-12 13:54 UTC
