### ISSUE TITLE
Tracking script not changing VRRP state to BAD

### ISSUE THREAD

**Issue by solarmon** [acassen/keepalived#2438] opened 2024-07-05 15:01 UTC
**Describe the bug**

Even though the script specified with track_script and vrrp_script returns an exit status of 1, the VRRP node status does not change to BAD.

**To Reproduce**
The script specified with track_script and vrrp_script returns an exit status of 1.

**Expected behavior**
The VRRP status should change to BAD when the  script specified with track_script and vrrp_script returns an exit status of 1

**Keepalived version**
```
Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

Copyright(C) 2001-2017 Alexandre Cassen, <acassen@gmail.com>

Build options:  PIPE2 LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_PREF RTA_VIA FRA_OIFNAME FRA_SUPPRESS_PREFIXLEN FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK LIBIPTC LIBIPSET_DYNAMIC LVS LIBIPVS_NETLINK VRRP VRRP_AUTH VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC FIB_ROUTING INET6_ADDR_GEN_MODE SNMP_V3_FOR_V2 SNMP SNMP_KEEPALIVED SNMP_CHECKER SNMP_RFC SNMP_RFCV2 SNMP_RFCV3 SO_MARK
```

**Distro (please complete the following information):**
 - Name: CentOS
 - Version: 7.9
 - Architecture:  x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
N/A

**Configuration file:**
```
TBC
```

**Notify and track scripts**
```
TBC
```

**System Log entries**
```
TBC
```

**Did keepalived coredump?**
```
No
```

**Additional context**

The keepalived version of 1.3.5 is quite old, so it is possible that this issue has already been identified and resolved. I have tried going through the release notes and other tickets but could not find anything relevant. Apologies if I missed anything obvious.

I noticed that in the generated keepalived.data where check the status of the VRRP cluster, it has:

```
Insecure = yes
```

What does this mean? I don't know if this is related to this issue, but on the node that has this issue it has this, all our other keepalived clusters and nodes have ```Insecure = no``` - so this is somehow different from the others.

The keepalived service has been running for 7 months. I suspect that it has got itself into such a state that it does not change it's VRRP node state regardless of what the tracking script returns; and possibly require a restart to resolve it.

I will try a service restart to see if it resolves the issue, but I would like a root cause for the issue to determine whether this has been fixed in a newer version of keepalived and whether we should spend time and effort to upgraded all our keepalived clusters.

Thank you.

**Comment by pqarmitage** [comment] 2024-07-05 16:08
If a script is insecure keepalived will not run it, which explains why the VRRP instance is not transitioning to FAULT state. The reason why the script is being marked as insecure should be in the log file.

**Closed by pqarmitage** 2024-07-05 16:08 UTC

**Comment by solarmon** [comment] 2024-07-05 16:31
@pqarmitage 

Thanks for the response.

Is the log about the insecure file only on keepalived startup, or will it log the reason every time it tries to run it?

Using `journalctl -xef -u keepalived` I don't see any log to state why the file is considered insecure.

**Comment by pqarmitage** [comment] 2024-07-05 17:05
The log entry should only be on startup.

**Comment by solarmon** [comment] 2024-07-05 17:25
@pqarmitage

Since the keepalived service was started 7 months ago then I won't be able to check the logs for it!

I was going to restart the service anyways, so I will keep a record of it when it starts up.

Note that this node *should* be configured the same as the others, so it shouldn't have different permissions or ownership for this tracking script. 

I did check the permissions and ownership of the script and it doesn't differ from our other working keepalived clusters. If I run it manually it works as expected.

I will provide an update again when I restart the keepalived service.

**Comment by solarmon** [comment] 2024-07-08 19:23
@pqarmitage 

I did the keepalived service restart. This was the only thing that was done.

As I suspected, this resolved the issue. The keepalived logs didn't indicate any scripts that it deemed insecure.

Before the the restart:

Insecure = yes

After restart:

Insecure = no

So I don't know what had caused keepalived to deem one of the scripts to be 'insecure'. I'm not sure whether it is referring to the track script of one of the notify (of state transition) scripts.

**Comment by pqarmitage** [comment] 2024-07-09 08:41
If you don't have any `Insecure = Yes` entries now then all your scripts should be OK. If you have the old keepalived.data it should be clear which script it is referring to (at least it is with recent versions of keepalived).

I don't think there is anything further we can investigate here, since the problem has now resolved itself (it could for example be that the permission or ownership of a directory or file has changed), and also we would need to see the problem in a recent version of keepalived.

**Comment by pqarmitage** [comment] 2024-07-09 15:09
The indentation has been improved since version 1.3.5 so it is now clearer. The `Insecure` applies to the check_heplify script.

CentOS 7 is now EOL (as of 9 days ago), and so even if an update were made to keepalived, there would not be a CentOS 7 build including the update. Furthermore, we (the keepalived maintainers) do not maintain old versions of keepalived; if a problem is found in an old version and it still exists in the current code, we will fix it in the current code; if the problem is fixed in a later version than is currently being used, we will recommend upgrading to a more recent version. The latest version of keepalived still builds on CentOS 7, although support is likely to be removed for such an old kernel soon since there is no longer a non EOL mainstream distro using such an old kernel.

You state:
```
I agree that the script files permissions and security could in theory have changed over time
(since the keepalived service had been started) . But then that suggests maybe the check
for the script security should be done dynamically and not just at the start? (Unless this
behaviour has changed since v1.3.5?).
```
There is an overhead checking the script security every time it is run. checks are made when keepalived starts that only root or the uid/gid can change the script or any part of the path of that script; i.e. no-one other than root (and the configured script user if there is one) can change the script. It is assumed that there is sufficient security relating to a configured script user, since keepalived has been run (or been configured to be run) by root, and therefore the script user is trusted by root. Having established that the script is secure (in the sense that no-one else can modify it), then it would require either root or the script user to modify something for the script no longer to be secure. It is assumed that root and any script user (who has been configured by root) will act sensibly (i.e. not take actions to make the system insecure) and any other assumption would lead to having to accept that anything on the system may not be secure.

There is no way that we can determine whether the script itself does `safe` things; we have to rely on the system administrator knowing what he is doing. Likewise, we have to rely on the system administrator acting properly once keepalived has started running.

**Comment by solarmon** [comment] 2024-07-09 15:28
@pqarmitage 

Thanks for the detailed explanation.

Yes, I'm aware of CentOS 7 is now EOL, which we will be addressing!

I just wanted to to determine whether this issue is likely occur on our other keepalived clusters (also on CentOS 7). If this issue is deemed likely to occur, and if it is fixed in newer versions of keepalived, then I would go down the journey of figuring out how update our keepalived clusters.

Thank you your time to explain what the issue is.
