### ISSUE TITLE
Keepalived v2.0.18 does not work with VRRP devices

### ISSUE THREAD

**Issue by emcepe** [acassen/keepalived#1389] opened 2019-09-18 19:31 UTC
Today I've upgraded all Keepalived v1.4.5 instances to v2.0.18. All work fine but the ones with VRRP devices. Seems it cannot create the needed vrrp interface.

**Error in syslog:**

Sep 18 20:06:13 testsystem Keepalived_vrrp[38745]: Opening file '/etc/keepalived/keepalived.conf'.
Sep 18 20:06:13 testsystem Keepalived_vrrp[38745]: (Line 160) WARNING - interface vrrp.6 for VROUTE nexthop doesn't exist
Sep 18 20:06:13 testsystem Keepalived_vrrp[38745]: (Line 163) WARNING - interface vrrp.6 for VROUTE nexthop doesn't exist
Sep 18 20:06:13 testsystem Keepalived_vrrp[38745]: (Line 164) WARNING - interface vrrp.6 for VROUTE nexthop doesn't exist
Sep 18 20:06:13 testsystem Keepalived_vrrp[38745]: (Line 165) WARNING - interface vrrp.6 for VROUTE nexthop doesn't exist
Sep 18 20:06:13 testsystem Keepalived_vrrp[38745]: (Line 168) WARNING - interface vrrp.6 for VROUTE nexthop doesn't exist
Sep 18 20:06:13 testsystem Keepalived_vrrp[38745]: (Line 169) WARNING - interface vrrp.6 for VROUTE nexthop doesn't exist
Sep 18 20:06:13 testsystem Keepalived_vrrp[38745]: (Line 170) WARNING - interface vrrp.6 for VROUTE nexthop doesn't exist
Sep 18 20:06:13 testsystem Keepalived_vrrp[38745]: (Line 173) WARNING - interface vrrp.6 for VROUTE nexthop doesn't exist
Sep 18 20:06:13 testsystem Keepalived_vrrp[38745]: (Line 176) WARNING - interface vrrp.6 for VROUTE nexthop doesn't exist
Sep 18 20:06:13 testsystem Keepalived_vrrp[38745]: (Line 177) WARNING - interface vrrp.6 for VROUTE nexthop doesn't exist
Sep 18 20:06:13 testsystem Keepalived_vrrp[38745]: (Line 178) WARNING - interface vrrp.6 for VROUTE nexthop doesn't exist
Sep 18 20:06:13 testsystem Keepalived_vrrp[38745]: Non-existent interface specified in configuration
Sep 18 20:06:13 testsystem Keepalived_vrrp[38745]: Stopped - used 0.000000 user time, 0.000000 system time
Sep 18 20:06:13 testsystem Keepalived[38744]: Keepalived_vrrp exited with permanent error CONFIG. Terminating
Sep 18 20:06:13 testsystem Keepalived[38744]: Stopped Keepalived v2.0.18 (07/26,2019)

**config snippet:**

`vrrp_script chk_TEST {`
`        script "/etc/keepalived/health-check.sh TEST 4.5.6.7"`
`        timeout 10`
`        interval 11`
`        fall 1`
`        rise 2`
`}`
`vrrp_instance test {`
`        state MASTER`
`        interface eth4`
`        virtual_router_id 6`
`        use_vmac vrrp.6`
`        priority 150`
`        advert_int 1`
`        smtp_alert`

`        virtual_ipaddress {`
`                10.50.63.23/24 brd 10.50.63.255 dev bond0 label bond0:23`
`        }`

`        virtual_ipaddress {`
`                192.168.253.13/24 brd 192.168.253.255`
`        }`

`        virtual_routes {`
`                src 192.168.253.13 to 192.168.253.3 dev vrrp.6`
`                src 192.168.253.13 to 1.2.3.1 via 192.168.253.3 dev vrrp.6`
`                src 192.168.253.13 to 1.2.3.2 via 192.168.253.3 dev vrrp.6`
`                src 192.168.253.13 to 1.2.3.3 via 192.168.253.3 dev vrrp.6`
`                src 192.168.253.13 to ... via 192.168.253.3 dev vrrp.6`
`                ...`
`        }`
`        track_interface {`
`                dummy6`
`                eth4`
`        }`
`        track_script {`
`                chk_TEST`
`        }`
`        notify_master "/etc/keepalived/vmac.sh master eth4 vrrp/6"`
`        notify_backup "/etc/keepalived/vmac.sh backup eth4 vrrp/6"`
`        version 3`
`}`

**keepalived -v output:**

Keepalived v2.0.18 (07/26,2019)

Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 3.16.72
Running on Linux 3.16.0-10-amd64 #1 SMP Debian 3.16.72-1 (2019-08-13)

configure options: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-dbus --enable-dbus-create-instance --enable-json --enable-bfd build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-z,relro CPPFLAGS=-D_FORTIFY_SOURCE=2

Config options:  LIBIPTC LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH JSON BFD OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS DBUS_CREATE_INSTANCE

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP RTAX_QUICKACK FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL LIBIPTC LIBIPSET_PRE_V7 NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK VRRP_VMAC CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE SO_MARK SCHED_RT SCHED_RESET_ON_FORK

**Distro:**
 - Debian Jessie
 - 8.11 (current patchlevel)
 - x86_64
 - with sysvinit (not using systemd)

**Comment by pqarmitage** [comment] 2019-09-18 20:25
@emcepe A lot has changed between v1.4.5 and v2.0.18, including better verification of configurations. In this case though, the check causing the `WARNING - interface vrrp.6 for VROUTE nexthop doesn't exist` log message is being too strict.

The problem is being caused by configuring virtual routes to use the configured VMAC interfaces. When a virtual route is configured, keepalived is now checking that any interfaces specified in the route exist; however at the time the configuration is read, the VMAC interface doesn't exist.

As a temporary workaround, you could add
```
global_defs {
    dynamic_interfaces
}
```
at the beginning of the configuration, and it will allow the routes to specify interfaces that don't exist when keepalived starts.

I will look at changing the code to allow VMAC interfaces to be specified in virtual routes etc, so that specifying `dynamic_interfaces` is no longer necessary, but that may take a few days.

**Comment by pqarmitage** [comment] 2019-09-18 20:41
@emcepe Although these won't make any difference to how your configuration works, you could make the following simplifications:

- Remove `eth4` from track_interfaces - it is automatically tracked since the vrrp instance is configured on that interface
- Combine the virtual_ipaddress blocks and use + for broadcast address:
```
virtual_ipaddress {
  10.50.63.23/24 brd + dev bond0 label bond0:23
  192.168.253.13/24 brd +
}

**Comment by emcepe** [comment] 2019-09-19 12:01
cool, thank you Quentin, it works.

**Comment by pqarmitage** [comment] 2019-10-09 14:16
@emcepe We have been considering this issue further and the best way to resolve it.

One thing we don't understand is why you need to configure the virtual routes on vrrp.6 instead of configuring them on eth4. Indeed, an explanation of how you are using the virtual routes would be very helpful. I am also not clear why the virtual route
`src 192.168.253.13 to 192.168.253.3 dev vrrp.6`
is needed since the route to 192.168.253.0/24 is automatically added due to the virtual_ipaddress 192.168.253.13/24.

**Comment by pqarmitage** [comment] 2019-10-09 15:42
Would it be possible for you to test it with the virtual routes configured on eth4 rather than vrrp.6. If that works for you then we can avoid having to think about changes to fully support virtual routes on VMACs.

**Comment by emcepe** [comment] 2019-10-11 15:23
Hi Quentin,

sure. I can test it every day between 8pm and 10pm, at all other times its in production.

Maybe I'm able to do it this evening ...

**Comment by pqarmitage** [comment] 2019-10-31 15:38
@emcepe Have you had the opportunity to test this?

**Comment by pqarmitage** [comment] 2019-11-09 10:54
@emcepe Closing this issue due to no update for over one month. If you have any further problems with this please update this issue and it can be reopened if necessary.

**Closed by pqarmitage** 2019-11-09 10:54 UTC
Labels: Awaiting feedback

**Comment by emcepe** [comment] 2019-11-10 11:01
Sorry, I totally forgot to answer you and to test it :-(
I will test it this evening.

**Comment by emcepe** [comment] 2019-11-10 19:35
it seems so that the routes will also work on eth4 instead of vrrp.6

**Comment by pqarmitage** [comment] 2019-11-13 11:21
@emcepe If it works for you I think it is probably safest to configure the routes on eth4, and then the `dynamic_interfaces` keyword is no longer required. Having said that, I think it is better to use `dynamic_interfaces` since then keepalived will continue working if interfaces are removed and recreated.
