### ISSUE TITLE
keepalived 2.0.10 - vrrp_instance entering FAULT state

### ISSUE THREAD

**Issue by stfast** [acassen/keepalived#1110] opened 2019-01-22 12:37 UTC
After upgrade from Fedora 28 (keepalived 1.4.5) to Fedora 29 (keepalived 2.0.10 and compiled keepalived 2.0.11), keepalived does run but it enters a FAULT state. Downgrade to 1.4.5 works
without problem. 

[root@smtp2 SPECS]# keepalived -l -D -n 
Tue Jan 22 13:24:09 2019: Starting Keepalived v1.4.5 (05/26,2018)
Tue Jan 22 13:24:09 2019: WARNING - keepalived was build for newer Linux 4.19.15, running on Linux 4.19.13-300.fc29.x86_64 #1 SMP Sat Dec 29 22:54:28 UTC 2018
Tue Jan 22 13:24:09 2019: Opening file '/etc/keepalived/keepalived.conf'.
Tue Jan 22 13:24:09 2019: Starting Healthcheck child process, pid=66130
Tue Jan 22 13:24:09 2019: Starting VRRP child process, pid=66131
Tue Jan 22 13:24:09 2019: Opening file '/etc/keepalived/keepalived.conf'.
Tue Jan 22 13:24:09 2019: Registering Kernel netlink reflector
Tue Jan 22 13:24:09 2019: Registering Kernel netlink command channel
Tue Jan 22 13:24:09 2019: Registering gratuitous ARP shared channel
Tue Jan 22 13:24:09 2019: Opening file '/etc/keepalived/keepalived.conf'.
Tue Jan 22 13:24:09 2019: vmac: Success creating VMAC interface vrrp.1 for vrrp_instance smtp.vlan1322
Tue Jan 22 13:24:09 2019: vmac: Success creating VMAC interface vrrp.2 for vrrp_instance smtp.vlan235
Tue Jan 22 13:24:09 2019: Using LinkWatch kernel netlink reflector...
Tue Jan 22 13:24:09 2019: VRRP_Instance(smtp.vlan1322) Entering BACKUP STATE
Tue Jan 22 13:24:09 2019: Opening script file /usr/libexec/keepalived/primary-backup.sh
Tue Jan 22 13:24:09 2019: VRRP_Instance(smtp.vlan235.) Entering BACKUP STATE
Tue Jan 22 13:24:09 2019: VRRP sockpool: [ifindex(6), proto(112), unicast(0), fd(10,11)]
Tue Jan 22 13:24:09 2019: Remote SMTP server [127.0.0.1]:25 connected.
Tue Jan 22 13:24:09 2019: Remote SMTP server [127.0.0.1]:25 connected.
Tue Jan 22 13:24:09 2019: SMTP alert successfully sent.
Tue Jan 22 13:24:09 2019: SMTP alert successfully sent.

[root@smtp2 SPECS]# keepalived -l -D -n 
Tue Jan 22 13:25:15 2019: Starting Keepalived v2.0.10 (11/12,2018)
Tue Jan 22 13:25:15 2019: Running on Linux 4.19.13-300.fc29.x86_64 #1 SMP Sat Dec 29 22:54:28 UTC 2018 (built for Linux 4.19.3)
Tue Jan 22 13:25:15 2019: Command line: 'keepalived' '-l' '-D' '-n'
Tue Jan 22 13:25:15 2019: Opening file '/etc/keepalived/keepalived.conf'.
Tue Jan 22 13:25:15 2019: Starting VRRP child process, pid=66591
Tue Jan 22 13:25:15 2019: Registering Kernel netlink reflector
Tue Jan 22 13:25:15 2019: Registering Kernel netlink command channel
Tue Jan 22 13:25:15 2019: Opening file '/etc/keepalived/keepalived.conf'.
Tue Jan 22 13:25:15 2019: Assigned address 10.192.255.2 for interface eth4
Tue Jan 22 13:25:15 2019: Assigned address fe80::215:5dff:fe87:b726 for interface eth4
Tue Jan 22 13:25:15 2019: (smtp.vlan1322): Success creating VMAC interface vrrp.1
Tue Jan 22 13:25:15 2019: (smtp.vlan235): Success creating VMAC interface vrrp.2
Tue Jan 22 13:25:15 2019: VRRP_Group(smtp.): Syncing instances to FAULT state
Tue Jan 22 13:25:15 2019: (smtp.vlan1322) entering FAULT state
Tue Jan 22 13:25:15 2019: (smtp.vlan235) entering FAULT state
Tue Jan 22 13:25:15 2019: Registering gratuitous ARP shared channel
Tue Jan 22 13:25:15 2019: VRRP sockpool: [ifindex(6), family(IPv4), proto(112), unicast(0), fd(10,11)]

**Comment by pqarmitage** [comment] 2019-01-22 12:44
@stfast Could you please provide a copy of your configuration, and also the output of `keepalived -v` so that we can investigate this problem.

**Comment by stfast** [comment] 2019-01-22 14:54
Version:

[root@smtp2 ~]# keepalived -v
Keepalived v2.0.10 (11/12,2018)

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.19.3
Running on Linux 4.19.13-300.fc29.x86_64 #1 SMP Sat Dec 29 22:54:28 UTC 2018

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-snmp --enable-snmp-rfc --enable-sha1 --with-init=systemd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld

Config options:  LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK

Configuration:

[root@smtp2 ~]# cat /etc/keepalived/keepalived.conf
! Configuration File for keepalived

global_defs {
	notification_email {
		sysadmin@mail.com
	}

	enable_script_security
	script_user root

	notification_email_from smtp2@mail.com
	smtp_server localhost4
	smtp_connect_timeout 30

	router_id smtp2
}


vrrp_sync_group smtp { 
	group { 
		smtp.vlan1322 
		smtp.vlan235 
	} 

	notify_master "/usr/libexec/keepalived/primary-backup.sh primary"
	notify_backup "/usr/libexec/keepalived/primary-backup.sh backup"
	notify_fault "/usr/libexec/keepalived/primary-backup.sh fault"
} 


vrrp_instance smtp.vlan1322 {
	state BACKUP
	interface eth4
	virtual_router_id 1
	priority 149
	advert_int 1
	garp_master_delay 1
#
	use_vmac
	vmac_xmit_base
#
	authentication {
		auth_type PASS
		auth_pass *********
	}
	virtual_ipaddress {
		10.192.32.20/28 dev eth1
	}
	smtp_alert
}


vrrp_instance smtp.vlan235 {
	state BACKUP
	interface eth4
	virtual_router_id 2
	priority 149
	advert_int 1
	garp_master_delay 1
#
	use_vmac
	vmac_xmit_base
#
	authentication {
		auth_type PASS
		auth_pass *********
	}
	virtual_ipaddress {
		10.10.10.10/28 dev eth3
	}
	smtp_alert
}

**Comment by pqarmitage** [comment] 2019-01-22 17:37
Sorry to ask again, but could you please also post the output of `ip link show`.

**Comment by pqarmitage** [comment] 2019-01-22 18:12
I'm guessing here at the moment but it could be caused by either eth3 or eth4 being down. Certinaly with v1.4.5 if a virtual_ipaddress was configured on a different interface from the vrrp instance, then keepalived didn't track the state of the interface used by the virutal_ipaddress, and didn't cause the vrrp instance to go to fault state if the interface of the address was down.

That changed with the v2.x.x series of keepalived which by default also tracks the interfaces of the virtual_ipaddresses, and will transition the vrrp instance to fault state if an address interface is down.

If you want to restore the old behaviour, add `no_track` to each virtual_ipaddress entry for which you do not want the vrrp_instance to track the state of the address interface.

If you could confirm whether or not this is the situation in your case it would be very helpful.

**Comment by stfast** [comment] 2019-01-22 20:44
> Sorry to ask again, but could you please also post the output of `ip link show`.

[root@smtp2 ~]# ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:15:5d:87:b7:22 brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:15:5d:87:b7:23 brd ff:ff:ff:ff:ff:ff
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:15:5d:87:b7:24 brd ff:ff:ff:ff:ff:ff
5: eth3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:15:5d:87:b7:25 brd ff:ff:ff:ff:ff:ff
6: eth4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:15:5d:87:b7:26 brd ff:ff:ff:ff:ff:ff
29: vrrp.1@eth4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 00:00:5e:00:01:01 brd ff:ff:ff:ff:ff:ff
30: vrrp.2@eth4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 00:00:5e:00:01:02 brd ff:ff:ff:ff:ff:ff

**Comment by stfast** [comment] 2019-01-22 20:50
Yes, eth3 is down (?! will check hypervisor) and IP jumps to this downed interface in 1.4.5 and works.
More wierd, Interface is down with working IP.

5: eth3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:15:5d:87:b7:25 brd ff:ff:ff:ff:ff:ff

eth3: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 10.10.10.10  netmask 255.255.255.240  broadcast 0.0.0.0
        ether 00:15:5d:87:b7:25  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


[root@smtp2 ~]# ping 10.10.10.10
PING 10.10.10.10 (10.10.10.10) 56(84) bytes of data.
64 bytes from 10.10.10.10: icmp_seq=1 ttl=64 time=0.050 ms
64 bytes from 10.10.10.10: icmp_seq=2 ttl=64 time=0.038 ms
64 bytes from 10.10.10.10: icmp_seq=3 ttl=64 time=0.040 ms

**Comment by pqarmitage** [comment] 2019-01-29 13:19
It appears that keepalived was behaving correctly, and the vrrp instance was down due to the interface a virtual_ipaddress was configured on was down.

I will close this issue now, but if there are any more problems with this the issue can be reopened.

**Closed by pqarmitage** 2019-01-29 13:19 UTC

**Comment by liudonghua123** [comment] 2024-05-13 06:45
> It appears that keepalived was behaving correctly, and the vrrp instance was down due to the interface a virtual_ipaddress was configured on was down.
> 
> I will close this issue now, but if there are any more problems with this the issue can be reopened.

I have the similar issue when using keepalived 2.2.8. I need to use an interface which is on and configured with an ip or I will get `vrrp_instance entering FAULT state` warning or error which the keepalived process don't exit. 

See also https://github.com/acassen/keepalived/issues/2091#issuecomment-2106746525.
