### ISSUE TITLE
Run `notify_master` script right after winning election

### ISSUE THREAD

**Issue by mikaku** [acassen/keepalived#1457] opened 2019-11-25 17:06 UTC
**Is your feature request to resolve a problem or provide enhanced functionality? Please describe.**

Hi,

This is a similar problem than in #950.

I came here because I had recently the same issue (a broken vrrp) with the latest version (2.0.19) in both servers, and with the option `notify_master_rx_lower_pri` set either in the master and backup servers with the hope the master will execute such script and will gain the VIP.

Unfortunately the `notify_master_rx_lower_pri` didn't call the script, so the VIP remains pointing to the backup server.

Moreover, I have the option `nopreempt` in the backup server with the hope it will keep as master even when the master server resumes communication and forces a new election.

This is what happened:

BACKUP
```
Nov 22 12:46:49 backup Keepalived_vrrp[1144]: (VI_1) Receive advertisement timeout
Nov 22 12:46:49 backup Keepalived_vrrp[1144]: (VI_1) Entering MASTER STATE
Nov 22 12:46:49 backup Keepalived_vrrp[1144]: (VI_1) Master received advert from <master_ip> with higher priority 150, ours 50
Nov 22 12:46:49 backup Keepalived_vrrp[1144]: (VI_1) Entering BACKUP STATE
```

Why the backup server enters in the BACKUP STATE if it has set the `nopreempt` option?

MASTER
```
Nov 22 12:46:50 master Keepalived_vrrp[1146]: (VI_1) Received advert from <backup_ip> with lower priority 50, ours 150, forcing new election
```

Why the master server didn't run `notify_master_rx_lower_pri` after gaining the election?

Configuration MASTER
```
global_defs {
   router_id HAP1_L2
   script_user root root
   enable_script_security off
}

vrrp_script chk_haproxy {
   script "/usr/sbin/pidof haproxy"
   interval 2
}

vrrp_instance VI_1 {
   state MASTER
   interface eth0
   virtual_router_id 1
   priority 150
   advert_int 1

   unicast_src_ip <master_ip>
   unicast_peer {
      <backup_ip>
   }

   virtual_ipaddress {
      <vip>
   }
   track_script {
     chk_haproxy
   }

   notify_master "/etc/keepalived/change_to.sh master"
   notify_master_rx_lower_pri "/etc/keepalived/change_to.sh master"

   notify_backup "/etc/keepalived/change_to.sh backup"
   notify_fault "/etc/keepalived/change_to.sh fault"
}
```

Configuration BACKUP
```
   state BACKUP
   priority 50
   nopreempt

   unicast_src_ip <backup_ip>
   unicast_peer {
      <master_ip>
   }
```

**Describe the solution you would like**
By executing the `notify_master` script right after winning the election, it would make sure that VIP points to MASTER.

**Describe alternatives you have considered**
I've been using the relatively new option `notify_master_rx_lower_pri` but it looks like it doesn't work.

**Would the feature request be of benefit only to you, or is it more generally applicable?**
I think that this new feature would benefit to other people suffering from the same problem (see #950).

**Keepalived version**
```
Keepalived v2.0.19 (10/19,2019)

Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 3.10.0
Running on Linux 3.10.0-1062.4.3.el7.x86_64 #1 SMP Wed Nov 13 23:58:53 UTC 2019

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-snmp build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic LDFLAGS=-Wl,-z,relro 

Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_VRRP SNMP_CHECKER

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV6_ADVANCED_API LIBNL1 RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK VRRP_VMAC IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RT SCHED_RESET_ON_FORK
```

**Additional context**
Add any other context about the feature request here.

**Comment by pqarmitage** [comment] 2019-11-25 18:56
If you want to stop the master server taking over from the backup server, you need to set `nopreempt` on the master server rather than the backup server. It is the master server that has to know not to preempt the backup server. You will also need to remove the `state MASTER` statement in the master server configuration, since that is incompatible with `nopreempt` and it turns off `nopreempt` (you can't want to start in state MASTER if you don't want to preempt a lower priority instance).

I have run your configuration, and the notify_master_rx_lower_pri does run the script when the master receives a lower priority advert.

Using the following configuration, which is your master and backup configuration merged, with the nopreempt on the master, removing `state MASTER` from the master configuration, and changing the notify scripts to just log what has been called and to identify whether it is the master or backup logging it (${_INSTANCE}):
```
global_defs {
   router_id HAP1_L2
   script_user root root
   enable_script_security off
}

vrrp_script chk_haproxy {
   script "/usr/sbin/pidof haproxy"
   interval 2
}

vrrp_instance VI_1 {
# @master   state MASTER
@backup    state BACKUP
   interface eth0
   virtual_router_id 1
@master   priority 150
@backup   priority 50
   advert_int 1
@master    nopreempt

@master   unicast_src_ip 10.1.0.1
@backup   unicast_src_ip 10.1.0.3
   unicast_peer {
@master   10.1.0.3
@backup   10.1.0.1
   }

   virtual_ipaddress {
      10.1.0.100
   }
   track_script {
     chk_haproxy
   }

   notify_master "${_PWD}/scripts/notify.sh master ${_INSTANCE}"
   notify_master_rx_lower_pri "${_PWD}/scripts/notify.sh master ${_INSTANCE} rx_lower_pri"

   notify_backup "${_PWD}/scripts/notify.sh backup ${_INSTANCE}"
   notify_fault "${_PWD}/scripts/notify.sh fault ${_INSTANCE}"
}
```

notify.sh just logs when it has been called and the parameters it has been called with:
```
#!/bin/bash

if [[ $# -ge 1 ]]; then
	NAME=$1
else
	NAME=${0##*/}
	NAME=${NAME%.sh}
fi

echo -n "$(date +"%a %b %e %X %Y")": \[$PPID:$$\] >>/tmp/$NAME.log
for i in $(seq 1 $#); do
	echo -n " '$1'" >>/tmp/$NAME.log
	shift
done
echo >>/tmp/$NAME.log

exit 0
```

When the master server is the VRRP master, and I add the following to the backup to stop it receiving adverts:
`iptables -I INPUT -p 112 -j drop`

I get the following master.log entries:
```
Mon Nov 25 18:45:11 2019: [19374:19381] 'master' 'master'
Mon Nov 25 18:45:52 2019: [19388:19479] 'master' 'master' 'rx_lower_pri'
Mon Nov 25 18:45:52 2019: [19374:19480] 'master' 'backup'
Mon Nov 25 18:45:53 2019: [19374:19486] 'master' 'master' 'rx_lower_pri'
Mon Nov 25 18:45:54 2019: [19374:19490] 'master' 'master' 'rx_lower_pri'
Mon Nov 25 18:45:55 2019: [19374:19494] 'master' 'master' 'rx_lower_pri'
Mon Nov 25 18:45:56 2019: [19374:19498] 'master' 'master' 'rx_lower_pri'
Mon Nov 25 18:45:57 2019: [19374:19503] 'master' 'master' 'rx_lower_pri'
Mon Nov 25 18:45:58 2019: [19374:19507] 'master' 'master' 'rx_lower_pri'
Mon Nov 25 18:45:59 2019: [19374:19511] 'master' 'master' 'rx_lower_pri'
Mon Nov 25 18:46:00 2019: [19374:19515] 'master' 'master' 'rx_lower_pri'
Mon Nov 25 18:46:01 2019: [19374:19519] 'master' 'master' 'rx_lower_pri'
Mon Nov 25 18:46:02 2019: [19374:19524] 'master' 'master' 'rx_lower_pri'
Mon Nov 25 18:46:03 2019: [19374:19528] 'master' 'master' 'rx_lower_pri'
Mon Nov 25 18:46:04 2019: [19374:19532] 'master' 'master' 'rx_lower_pri'
Mon Nov 25 18:46:05 2019: [19374:19537] 'master' 'master' 'rx_lower_pri'
```
and for completeness the backup is:
```
Mon Nov 25 18:45:07 2019: [19374:19376] 'backup' 'master'
Mon Nov 25 18:45:12 2019: [19388:19390] 'backup' 'backup'
Mon Nov 25 18:46:05 2019: [19388:19538] 'backup' 'backup'
```
I have the following log entries on the master:
```
Mon Nov 25 18:45:52 2019: (VI_1) Received advert from 10.1.0.3 with lower priority 50, ours 150, forcing new election
Mon Nov 25 18:45:53 2019: (VI_1) Received advert from 10.1.0.3 with lower priority 50, ours 150, forcing new election
Mon Nov 25 18:45:54 2019: (VI_1) Received advert from 10.1.0.3 with lower priority 50, ours 150, forcing new election
Mon Nov 25 18:45:55 2019: (VI_1) Received advert from 10.1.0.3 with lower priority 50, ours 150, forcing new election
Mon Nov 25 18:45:56 2019: (VI_1) Received advert from 10.1.0.3 with lower priority 50, ours 150, forcing new election
Mon Nov 25 18:45:57 2019: (VI_1) Received advert from 10.1.0.3 with lower priority 50, ours 150, forcing new election
Mon Nov 25 18:45:58 2019: (VI_1) Received advert from 10.1.0.3 with lower priority 50, ours 150, forcing new election
Mon Nov 25 18:45:59 2019: (VI_1) Received advert from 10.1.0.3 with lower priority 50, ours 150, forcing new election
Mon Nov 25 18:46:00 2019: (VI_1) Received advert from 10.1.0.3 with lower priority 50, ours 150, forcing new election
Mon Nov 25 18:46:01 2019: (VI_1) Received advert from 10.1.0.3 with lower priority 50, ours 150, forcing new election
Mon Nov 25 18:46:02 2019: (VI_1) Received advert from 10.1.0.3 with lower priority 50, ours 150, forcing new election
Mon Nov 25 18:46:03 2019: (VI_1) Received advert from 10.1.0.3 with lower priority 50, ours 150, forcing new election
Mon Nov 25 18:46:04 2019: (VI_1) Received advert from 10.1.0.3 with lower priority 50, ours 150, forcing new election
Mon Nov 25 18:46:05 2019: (VI_1) Received advert from 10.1.0.3 with lower priority 50, ours 150, forcing new election
```
and on the backup:
```
Mon Nov 25 18:45:52 2019: (VI_1) Receive advertisement timeout
Mon Nov 25 18:45:52 2019: (VI_1) Entering MASTER STATE
Mon Nov 25 18:45:52 2019: (VI_1) setting VIPs.
Mon Nov 25 18:45:52 2019: Sending gratuitous ARP on eth0 for 10.1.0.100
Mon Nov 25 18:45:52 2019: (VI_1) Sending/queueing gratuitous ARPs on eth0 for 10.1.0.100
Mon Nov 25 18:45:57 2019: (VI_1) Sending/queueing gratuitous ARPs on eth0 for 10.1.0.100
Mon Nov 25 18:46:05 2019: (VI_1) Master received advert from 10.1.0.1 with higher priority 150, ours 50
Mon Nov 25 18:46:05 2019: (VI_1) Entering BACKUP STATE
Mon Nov 25 18:46:05 2019: (VI_1) removing VIPs.
```
The above demonstrates that the notify_master_rx_lower_pri script is being called. With the configuration you have provided, I don't think it is possible to to differentiate between the `notify_master` and `notify_master_rx_lower_pri` scripts being called.

**Comment by mikaku** [comment] 2019-11-26 08:16
@pqarmitage,

First of all, thank you very much for your always quick and detailed responses to the people requests. I've been reading a lot of old issues here and I noticed that you put always a lot of effort to make things clear with extensive explaining. I really appreciate that.

> If you want to stop the master server taking over from the backup server, you need to set nopreempt on the master server rather than the backup server. It is the master server that has to know not to preempt the backup server. You will also need to remove the state MASTER statement in the master server configuration, since that is incompatible with nopreempt and it turns off nopreempt (you can't want to start in state MASTER if you don't want to preempt a lower priority instance).

Well this changes it all. I've read multiple times the keepalived documentation regarding the `nopreempt` option, and I completely failed to understand that:

1. Such option must go to the master server.
1. The master server must not contain the statement `state MASTER`.

I think the following paragraph should be rephrased to clear up things better:

```
       # VRRP will normally preempt a lower priority machine when a higher priority
       # machine comes online.  "nopreempt" allows the lower priority machine to
       # maintain the master role, even when a higher priority machine comes back
       # online.
       # NOTE: For this to work, the initial state of this
       # entry must be BACKUP.
       # --
       nopreempt
```

Regarding the notify script, shouldn't appear a similar line in the master server (as it appears in the backup server) when running the `notify_master_rx_lower_pri` script?
```
Mon Nov 25 18:45:52 2019: (VI_1) setting VIPs.
```

I've always believed that this message is shown when keepalived calls the script in the `notify_` options. Is that true?

Besides all this, I'll modify the configuration in both servers to fix the `nopreempt` option. Also, I'll include a log file in the notify scripts to make sure that `notify_master_rx_lower_pri` is working, and what is really failing is my script.

I'll keep you informed.
Again, thanks.

**Comment by pqarmitage** [comment] 2019-11-26 09:33
I will change the wording in keepalived.conf(5) to:
```
    # A higher priority VRRP instance will normally preempt a lower priority instance
    # when it comes online.  "nopreempt" stops the higher priority machine taking
    # over the master role, and allows the lower priority machine to remain as
    # master.
    # NOTE: For this to work, the initial state must not be MASTER.
    # --
    \fBnopreempt\fR
```
Does that seem clearer?

With regard to
`Mon Nov 25 18:45:52 2019: (VI_1) setting VIPs.`
and calling the notify_ scripts, "setting VIPs" is logged when a VRRP instance transitions to master state, and so it will occur at the same time as the `notify_master` script is called. The `notify_master_rx_lower_pri` script is called when the VRRP instance is already master, and so "setting VIPs" will not be logged at that time.

**Comment by mikaku** [comment] 2019-11-26 16:53
> Does that seem clearer?

Yes, it is much clear to me.

> The notify_master_rx_lower_pri script is called when the VRRP instance is already master, and so "setting VIPs" will not be logged at that time.

Understood.

By the way, after applying the changes on `nopreempt` in master and backup servers, they behave exactly the same as in your test. Moreover, today *lucky me* I experienced an unexpected small network outage right after applying the changes and it confirmed that all works perfectly. :smiley: 

Without these changes applied such small network outage would have ruined my VRRP as it did before.

You can close this issue, if I experience again a related issue I'll reopen it.
Thank you very much.

**Closed** 2019-11-26 17:09 UTC

**Comment by catac** [comment] 2019-11-29 10:59
Hello,

I also have an issue really close to this, but I'm already using the `state BACKUP` and `nopreempt` config options and I don't understand why the master still forces reelection.

Here are the logs:
```
## one of the BACKUP instances
Tue Nov 26 15:45:57 2019: Opening file '/etc/keepalived/keepalived.conf'.
Tue Nov 26 15:45:57 2019: (vips) Ignoring track_interface eth0 since own interface
Tue Nov 26 15:45:57 2019: Assigned address 172.16.141.12 for interface eth0
Tue Nov 26 15:45:57 2019: Registering gratuitous ARP shared channel
Tue Nov 26 15:45:57 2019: (vips) removing VIPs.
Tue Nov 26 15:45:57 2019: (vips) Entering BACKUP STATE (init)
Tue Nov 26 15:45:57 2019: VRRP sockpool: [ifindex(2), family(IPv4), proto(112), unicast(1), fd(10,11)]

Thu Nov 28 20:00:33 2019: (vips) Receive advertisement timeout
Thu Nov 28 20:00:33 2019: (vips) Entering MASTER STATE
Thu Nov 28 20:00:33 2019: (vips) using locally configured advertisement interval (5000 milli-sec)
Thu Nov 28 20:00:33 2019: (vips) setting VIPs.
Thu Nov 28 20:00:33 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:33 2019: (vips) Sending/queueing gratuitous ARPs on eth0 for 172.16.141.9
Thu Nov 28 20:00:33 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:33 2019: (vips) Received advert from 172.16.141.11 with lower priority 100, ours 101, forcing new election
Thu Nov 28 20:00:33 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:33 2019: (vips) Sending/queueing gratuitous ARPs on eth0 for 172.16.141.9
Thu Nov 28 20:00:33 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: (vips) Master received advert from 172.16.141.13 with higher priority 102, ours 101
Thu Nov 28 20:00:36 2019: (vips) Entering BACKUP STATE
Thu Nov 28 20:00:36 2019: (vips) removing VIPs.

## initial MASTER instance
Tue Nov 26 15:45:56 2019: Opening file '/etc/keepalived/keepalived.conf'.
Tue Nov 26 15:45:56 2019: Reloading
Tue Nov 26 15:45:56 2019: Opening file '/etc/keepalived/keepalived.conf'.
Tue Nov 26 15:45:56 2019: (vips) Ignoring track_interface eth0 since own interface
Tue Nov 26 15:45:56 2019: Assigned address 172.16.141.13 for interface eth0
Tue Nov 26 15:45:56 2019: (vips) removing VIPs.
Tue Nov 26 15:45:56 2019: (vips) Entering BACKUP STATE (init)
Tue Nov 26 15:45:56 2019: VRRP sockpool: [ifindex(2), family(IPv4), proto(112), unicast(1), fd(10,11)]
Tue Nov 26 15:46:14 2019: (vips) Receive advertisement timeout
Tue Nov 26 15:46:14 2019: (vips) Entering MASTER STATE
Tue Nov 26 15:46:14 2019: (vips) using locally configured advertisement interval (5000 milli-sec)
Tue Nov 26 15:46:14 2019: (vips) setting VIPs.
Tue Nov 26 15:46:14 2019: Sending gratuitous ARP on eth0 for 172.16.141.9

Thu Nov 28 20:00:36 2019: (vips) Received advert from 172.16.141.12 with lower priority 101, ours 102, forcing new election
Thu Nov 28 20:00:36 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Error 105 (No buffer space available) sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: (vips) Sending/queueing gratuitous ARPs on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Error 105 (No buffer space available) sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Error 105 (No buffer space available) sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Error 105 (No buffer space available) sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Error 105 (No buffer space available) sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: (vips) Received advert from 172.16.141.11 with lower priority 100, ours 102, forcing new election
Thu Nov 28 20:00:36 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Error 105 (No buffer space available) sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: (vips) Sending/queueing gratuitous ARPs on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Error 105 (No buffer space available) sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Error 105 (No buffer space available) sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Error 105 (No buffer space available) sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Error 105 (No buffer space available) sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: (vips) Received advert from 172.16.141.12 with lower priority 101, ours 102, forcing new election
Thu Nov 28 20:00:36 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Error 105 (No buffer space available) sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: (vips) Sending/queueing gratuitous ARPs on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Error 105 (No buffer space available) sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Error 105 (No buffer space available) sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Error 105 (No buffer space available) sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:36 2019: Error 105 (No buffer space available) sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:41 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
Thu Nov 28 20:00:41 2019: (vips) Sending/queueing gratuitous ARPs on eth0 for 172.16.141.9
Thu Nov 28 20:00:41 2019: Sending gratuitous ARP on eth0 for 172.16.141.9
```

It's strange also the `Error 105 (No buffer space available) sending gratuitous ARP` messages. I wonder if that is because the VMs are t2 instances...

Here is the config for all 3 instances:
```
global_defs {
  vrrp_version 3
  vrrp_iptables KUBE-KEEPALIVED-VIP
  script_user root root
  enable_script_security
}

vrrp_instance vips {
  state BACKUP
  interface eth0
  virtual_router_id 50
  ##instance1: priority 100
  ##instance2: priority 101
  ##instance3: priority 102

  nopreempt
  advert_int 5
  garp_master_delay 10

  track_interface {
    eth0
  }

  ##instance1:
  unicast_src_ip 172.16.141.11
  unicast_peer {
    172.16.141.12
    172.16.141.13
  }
  ##instance2:
  unicast_src_ip 172.16.141.12
  unicast_peer {
    172.16.141.11
    172.16.141.13
  }
  ##instance3:
  unicast_src_ip 172.16.141.13
  unicast_peer {
    172.16.141.11
    172.16.141.12
  }

  virtual_ipaddress {
    172.16.141.9
  }

  notify_master "/master.sh 172.16.141.9"

}
```

Thanks a lot for your help,
Catalin.

**Comment by pqarmitage** [comment] 2019-11-29 12:55
There seem to be two issues here:

1. A lower priority instance becoming master for a short time when keepalived starts, and then reverting to backup

2. The `Error 105 (No buffer space available)` messages

Point 1 we have seen before in some VM environments, where keepalived doesn't start receiving packets until some seconds after it starts up. It might be that using `vrrp_startup_delay` could help. It could be worth running tcpdump on eth0 in the VM while keepalived is starting to see what is happening.

Point 2. This means that for some reason the VM is not sending the GARP messages, and they are being left on the socket's send queue, which after a bit over 4 hours fills up. I have not seen this before, but I suspect if you run `netstat -anp | grep keepalived` some time after keepalived has started, you will see send-q of one of the sockets gradually growing.

Regarding your configuration, the 
```
  track_interface {
    eth0
  }
```
is superfluous since the interface that the VRRP instance is configured on is tracked by default.

Your overall configuration could be streamlined to the following. `state BACKUP` is removed, since it is superfluous, and you might like to use the `nftables` option rather that `vrrp_iptables`, since it is more efficient, and you don't have to create a table first. If your system names are instance1, instance2 and instance3:
```
global_defs {
  vrrp_version 3
  vrrp_iptables KUBE-KEEPALIVED-VIP
# alternatively:
# nftables
  script_user root root
  enable_script_security
}

vrrp_instance vips {
  interface eth0
  virtual_router_id 50
@instance1 priority 100
@instance2 priority 101
@instance3 priority 102

  nopreempt
  advert_int 5
  garp_master_delay 10

@instance1  unicast_src_ip 172.16.141.11
@instance2  unicast_src_ip 172.16.141.12
@instance3  unicast_src_ip 172.16.141.13
  unicast_peer {
@^instance1    172.16.141.11
@^instance2    172.16.141.12
@^instance3    172.16.141.13
  }

  virtual_ipaddress {
    172.16.141.9
  }

  notify_master "/master.sh 172.16.141.9"
}
```
and exactly the same configuration could be used unaltered on all three systems.

**Comment by catac** [comment] 2019-12-01 21:28
Thanks a lot @pqarmitage for all the explanations. I think I understand now what is happening.

I can reproduce the behaviour like this: let's say current master is the instance with the highest priority. On this instance I run
```
iptables -A OUTPUT -p 112 -o eth0 -j DROP
```
to drop all outgoing vrrp packets. This simulates the case I was experiencing. As the other instances no longer receive the advertisements, one of them becomes master. This means that one of these instance already ran the `notify_master` script and thus, AWS has assigned the VIP to that instance. In the meantime, the first one still thinks it's the master and will try to force reelection, and in the logs we see
```
(vips) Received advert from 172.16.141.11 with lower priority 100, ours 102, forcing new election
```
I was thinking that since we used `nopreemt` this should not happen, but in fact it is normal. When it finally manages to send the messages (drop the iptables rule, or no more buffer error) the others will step down and become backup. However, the first one doesn't notify anymore the master script (because it thinks it was master all the time) and thus, from AWS point of view, the VIP is still associated with the other instance (which doesn't have anymore the VIP).

So, I think the solution is to always set the `notify_master_rx_lower_pri` option to the same script as for the `notify_master`. It will probably call the script several times, but at least, it should be last called by the instance that eventually becomes the master.

Does this make sense? Do you see any better way around this corner case?

**Comment by pqarmitage** [comment] 2019-12-02 07:56
The situation you describe is precisely the reason why I added the `notify_master_rx_lower_pri` functionality. Whether you use the same script as `notify_master` or a different script is down to what you want to achieve, but I can see no reason why you shouldn't use the same script.
