### ISSUE TITLE
IPv6 virtual_route not set

### ISSUE THREAD

**Issue by gurubert** [acassen/keepalived#965] opened 2018-07-27 13:25 UTC
Hi,
we have a vrrp_instance with the following configuration:

…
    virtual_ipaddress_excluded {
    10.25.0.9/29
    2001:67c:2050:204::1/64
    }
    virtual_routes {
    to 80.241.61.64/28 via 10.25.0.10
    to 80.241.60.64/27 via 10.25.0.11
    to 2001:67c:2050:310::/60 via 2001:67c:2050:204::2
    to 2001:67c:2050:320::/60 via 2001:67c:2050:204::3
    }
…

The IPv4 routes are getting set, but the IPv6 routes not. I think this is a timing problem, as these entries are in the logfile:

    Jul 23 13:27:28 gate-1 Keepalived_vrrp[9777]: Netlink: error: No route to host, type=(24), seq=1532345287, pid=0
    Jul 23 13:27:28 gate-1 Keepalived_vrrp[9777]: Netlink: error: No route to host, type=(24), seq=1532345288, pid=0

It looks like it takes to long for 2001:67c:2050:204::1 to come up on the interface so that when keepalived tries to set the routes via 2001:67c:2050:204::2 and 2001:67c:2050:204::3 the kernel has no route to these hosts.

Is there anything we can do here?
keepalived is version 1.3.2 on Debian 9 with kernel 4.9.0-7.

**Comment by pqarmitage** [comment] 2018-07-27 14:17
It must be taking quite a while for 2001:67c:2050:204::1to come up, since keepalived won't attempt to install those routes until it has timed out in backup mode and then is transitioning to master.

If you are specifying `state MASTER` in your configuration, then it might work better without it.

Is keepalived being started at system startup? Can you try manually starting keepalived once 2001:67c:2050:204::1 is up and see if it runs then without an error.

Could you wrap the starting up of keepalived in a script that does something like:
```
ip route get 2001:67c:2050:204::2
while [[ $? -ne 0 ]]; do
    sleep 1
    ip route get 2001:67c:2050:204::2
done

keepalived ...
```

You could try upgrading to the latest version of keepalived, and see if that helps, since it does monitor routes, but I'm not sure it will help in your case.

**Comment by gurubert** [comment] 2018-08-15 14:01
Sorry, I should remember to not open issues before going on vacation…

2001:67c:2050:204::1 is a virtual IP set by keepalived. I cannot delay the startup of keepalived until this IP is set as it is keepalived that sets this IP.

Maybe we need to think "out of the box" here and use a routing protocol and not keepalived for this.

**Comment by pqarmitage** [comment] 2018-08-15 14:37
I'll have a look at the code, but my first thoughts are that this needs virtual addresses being added before virtual routes.

**Comment by pqarmitage** [comment] 2018-08-16 11:14
@gurubert keepalived does add the virtual addresses before virtual routes so that is not the cause of the problem.

I have run keepalived with the configuration extract you have shown above (including in a Debian 9 VM with the same kernel), and with both the current version of keepalived and v1.3.2 I do not experience the problem you are reporting.

In case it is something to do with the routes being added too quickly after the address is added, can you try executing the following script and see what happens:
```
#!/bin/bash

[[ $# -eq 0 ]] && CMD=add || CMD=del

ip -b - <<EOF
	addr $CMD 2001:67c:2050:204::1/64 dev eth0
	route $CMD 2001:67c:2050:310::/60 via 2001:67c:2050:204::2
	route $CMD 2001:67c:2050:320::/60 via 2001:67c:2050:204::3
EOF
```
(to delete the routes and address just run the script and include a parameter on the command line).

**Comment by pqarmitage** [comment] 2018-09-14 10:52
@gurubert Do you have any update on this, or should we close the issue now?

**Comment by pqarmitage** [comment] 2018-09-28 11:15
Closing due to no update for over 1 month. If you have a further update this issue can be reopened.

**Closed by pqarmitage** 2018-09-28 11:15 UTC
