### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by sigxcpu76** [acassen/keepalived#464] opened 2016-11-22 14:31 UTC
I'm using https://github.com/kubernetes/contrib/tree/master/keepalived-vip and keepalived crashes with SIGSEGV. I'm not 100% sure, but the unset "track_interface" can be the problem?

Kernel log:
```
Nov 22 14:30:44 kube-minion-11.sgu kernel: keepalived[5973]: segfault at 0 ip 00007f07bf928e1a sp 00007ffdee5a7548 error 4 in libc-2.23.so[7f07bf7db000+1c0000]
```

```
Starting Keepalived v1.2.24 (10/17,2016)
Opening file '/etc/keepalived/keepalived.conf'.
Starting Healthcheck child process, pid=26
Initializing ipvs
Starting VRRP child process, pid=27
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Opening file '/etc/keepalived/keepalived.conf'.
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Using LinkWatch kernel netlink reflector...
Opening file '/etc/keepalived/keepalived.conf'.
Using LinkWatch kernel netlink reflector...
Opening file '/etc/keepalived/keepalived.conf'.
Got SIGHUP, reloading checker configuration
Initializing ipvs
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Opening file '/etc/keepalived/keepalived.conf'.
Using LinkWatch kernel netlink reflector...
Activating healthchecker for service [172.31.16.135]:80
Activating healthchecker for service [172.31.16.135]:443
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Opening file '/etc/keepalived/keepalived.conf'.
pid 27 exited due to segmentation fault (SIGSEGV).
  Please report a bug at https://github.com/acassen/keepalived/issues
  and include this log from when keepalived started, what happened
  immediately before the crash, and your configuration file.
VRRP child process(27) died: Respawning
```

Configuration generated by the controller:

```
global_defs {
  vrrp_version 3
  vrrp_iptables KUBE-KEEPALIVED-VIP
}

vrrp_instance vips {
  state BACKUP
  interface
  virtual_router_id 50
  priority 99
  nopreempt
  advert_int 1

  track_interface {

  }



  virtual_ipaddress {
    10.129.128.210
  }
}


# Service: default/nginx-ingress
virtual_server 10.129.128.210 80 {
  delay_loop 5
  lvs_sched wlc
  lvs_method NAT
  persistence_timeout 1800
  protocol TCP


  real_server 172.31.16.135 80 {
    weight 1
    TCP_CHECK {
      connect_port 80
      connect_timeout 3
    }
  }

}

# Service: default/nginx-ingress
virtual_server 10.129.128.210 443 {
  delay_loop 5
  lvs_sched wlc
  lvs_method NAT
  persistence_timeout 1800
  protocol TCP


  real_server 172.31.16.135 443 {
    weight 1
    TCP_CHECK {
      connect_port 443
      connect_timeout 3
    }
  }

}
```

**Comment by pqarmitage** [comment] 2016-11-22 16:48
I think the problem is most likely due to the `interface` statement in the `vrrp_instance` block not having an interface name after `interface`. The `interface` keyword expects to be followed by an interface name (see vrrp_int_handler() in keepalived/vrrp/vrrp_parser.c), and will behave randomly it it is missing. v1.3.0 onwards will identify missing keywords, log an error and terminate cleanly.

**Comment by pqarmitage** [comment] 2016-12-05 09:00
Is this problem now resolved?

**Comment by sigxcpu76** [comment] 2016-12-05 09:09
That was the crash cause, indeed. After patching the k8s controller to fill the interface names I've ran into other issues not related to keepalived directly, so it is postponed for now (e.g. calico starts to announce BGP using the VIP on the leader and loses connectivity when the VIP migrates).

**Comment by pqarmitage** [comment] 2016-12-05 09:24
Thanks for the update; I'll close this issue for now.

If further keepalived issues arise, please open a new issue.

**Closed by pqarmitage** 2016-12-05 09:24 UTC
