### ISSUE TITLE
SIGSEGV when stopping

### ISSUE THREAD

**Issue by lasseoe** [acassen/keepalived#1998] opened 2021-09-15 07:43 UTC
**Describe the bug**
If DBus is enabled keepalived SIGSEGV during shutdown, when stopping keepalived, either using systemd stop keepalived or CTRL-C when running in the foreground.

**To Reproduce**
Enable DBus support and stop keeplived.

**Expected behavior**
Not SIGSEGV and stop gracefully :)

**Keepalived version**
```
Keepalived v2.2.4 (08/21,2021)

Copyright(C) 2001-2021 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.10.46
Running on Linux 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03)
Distro: Debian GNU/Linux 11 (bullseye)

configure options: --enable-dbus

Config options:  LIBIPSET_DYNAMIC NFTABLES LVS VRRP VRRP_AUTH VRRP_VMAC OLD_CHKSUM_COMPAT DBUS INIT=systemd SYSTEMD_NOTIFY

System options:  VSYSLOG MEMFD_CREATE IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA IPTABLES NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_IPVLAN IFLA_LINK_NETNSID GLOB_BRACE GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE VRF SO_MARK
```

**Distro (please complete the following information):**
 - Name: Debian
 - Version: 11.0
 - Architecture: x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
VMware

**Configuration file:**
```
global_defs {
  router_id XXXXXX-haproxy01
  enable_dbus
}

vrrp_instance PX1 {
        state MASTER
        interface ens192
        virtual_router_id 51
        priority 101
        advert_int 2
	nopreempt
	unicast_src_ip 172.xx.xx.62
	unicast_peer {
		172.xx.xx.66
	}
        authentication {
              auth_type PASS
              auth_pass xxxxxxxx
        }
        virtual_ipaddress {
              172.xx.xx.67/24
        }
}
```

**Notify and track scripts**
```
None
```

**System Log entries**
```
systemd[1]: Starting LVS and VRRP High Availability Monitor...
Keepalived[2613]: Starting Keepalived v2.2.4 (08/21,2021)
Keepalived[2613]: WARNING - keepalived was built for newer Linux 5.10.46, running on Linux 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03)
Keepalived[2613]: Command line: '/usr/local/sbin/keepalived' '--dont-fork' '-D'
Keepalived[2613]: Opening file '/etc/keepalived/keepalived.conf'.
Keepalived[2613]: Configuration file /etc/keepalived/keepalived.conf
Keepalived[2613]: NOTICE: setting config option max_auto_priority should result in better keepalived performance
Keepalived[2613]: Starting VRRP child process, pid=2614
Keepalived_vrrp[2614]: Registering Kernel netlink reflector
Keepalived_vrrp[2614]: Registering Kernel netlink command channel
Keepalived[2613]: Startup complete
systemd[1]: Started LVS and VRRP High Availability Monitor.
Keepalived_vrrp[2614]: (PX1) Warning - nopreempt will not work with initial state MASTER - clearing
Keepalived_vrrp[2614]: Assigned address 172.xx.0.62 for interface ens192
Keepalived_vrrp[2614]: Assigned address fe80::250:56ff:fe91:b5d2 for interface ens192
Keepalived_vrrp[2614]: Warning - script haproxy is not used
Keepalived_vrrp[2614]: Registering gratuitous ARP shared channel
Keepalived_vrrp[2614]: (PX1) removing VIPs.
Keepalived_vrrp[2614]: (PX1) Entering BACKUP STATE (init)
Keepalived_vrrp[2614]: VRRP sockpool: [ifindex(  2), family(IPv4), proto(112), fd(17,18), unicast, address(172.xx.0.62)]
Keepalived_vrrp[2614]: (PX1) Receive advertisement timeout
Keepalived_vrrp[2614]: (PX1) Entering MASTER STATE
Keepalived_vrrp[2614]: (PX1) setting VIPs.
Keepalived_vrrp[2614]: (PX1) Sending/queueing gratuitous ARPs on ens192 for 172.xx.0.67
Keepalived_vrrp[2614]: Sending gratuitous ARP on ens192 for 172.xx.0.67
Keepalived_vrrp[2614]: Sending gratuitous ARP on ens192 for 172.xx.0.67
Keepalived_vrrp[2614]: Sending gratuitous ARP on ens192 for 172.xx.0.67
Keepalived_vrrp[2614]: Sending gratuitous ARP on ens192 for 172.xx.0.67
Keepalived_vrrp[2614]: Sending gratuitous ARP on ens192 for 172.xx.0.67
Keepalived_vrrp[2614]: (PX1) Sending/queueing gratuitous ARPs on ens192 for 172.xx.0.67
Keepalived_vrrp[2614]: Sending gratuitous ARP on ens192 for 172.xx.0.67
Keepalived_vrrp[2614]: Sending gratuitous ARP on ens192 for 172.xx.0.67
Keepalived_vrrp[2614]: Sending gratuitous ARP on ens192 for 172.xx.0.67
Keepalived_vrrp[2614]: Sending gratuitous ARP on ens192 for 172.xx.0.67
Keepalived_vrrp[2614]: Sending gratuitous ARP on ens192 for 172.xx.0.67
systemd[1]: Stopping LVS and VRRP High Availability Monitor...
Keepalived[2613]: Stopping
Keepalived_vrrp[2614]: (PX1) sent 0 priority
Keepalived_vrrp[2614]: (PX1) removing VIPs.
keepalived[2614]: g_main_loop_quit: assertion 'loop != NULL' failed
Keepalived[2613]: Keepalived_vrrp exited due to segmentation fault (SIGSEGV).
Keepalived[2613]:   Please report a bug at https://github.com/acassen/keepalived/issues
Keepalived[2613]:   and include this log from when keepalived started, a description
Keepalived[2613]:   of what happened before the crash, your configuration file and the details below.
Keepalived[2613]:   Also provide the output of keepalived -v, and whether keepalived is being
Keepalived[2613]:   run in a container or VM.
Keepalived[2613]:   A failure to provide all this information may mean the crash cannot be investigated.
Keepalived[2613]:   If you are able to provide a stack backtrace with gdb that would really help.
Keepalived[2613]:   Source version 2.2.4
Keepalived[2613]:   Built with kernel headers for Linux 5.10.46
Keepalived[2613]:   Running on Linux 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03)
Keepalived[2613]:   Command line: '/usr/local/sbin/keepalived' '--dont-fork' '-D'
Keepalived[2613]:   configure options: --enable-dbus
Keepalived[2613]:   Config options: LIBIPSET_DYNAMIC NFTABLES LVS VRRP VRRP_AUTH VRRP_VMAC OLD_CHKSUM_COMPAT DBUS
Keepalived[2613]:                   INIT=systemd SYSTEMD_NOTIFY
Keepalived[2613]:   System options: VSYSLOG MEMFD_CREATE IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF
Keepalived[2613]:                   FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK
Keepalived[2613]:                   RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA
Keepalived[2613]:                   FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS
Keepalived[2613]:                   LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA IPTABLES NET_LINUX_IF_H_COLLISION
Keepalived[2613]:                   LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS
systemd[1]: keepalived.service: Succeeded.
Keepalived[2613]:                   IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_IPVLAN IFLA_LINK_NETNSID GLOB_BRACE
Keepalived[2613]:                   GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE VRF SO_MARK
Keepalived[2613]: CPU usage (self/children) user: 0.003687/0.004468 system: 0.003687/0.000000
systemd[1]: Stopped LVS and VRRP High Availability Monitor.
Keepalived[2613]: Stopped Keepalived v2.2.4 (08/21,2021)
kernel: [161930.603426] keepalived[2614]: segfault at 0 ip 00007f0f711184d0 sp 00007ffdc62a91c8 error 4 in libgio-2.0.so.0.6600.8[7f0f71031000+110000]
kernel: [161930.603453] Code: 43 01 49 8b 3c c4 48 89 c3 48 85 ff 75 ec 4c 89 e7 e8 14 c4 f1 ff 5b 48 89 ef 5d 41 5c e9 08 c4 f1 ff 0f 1f 84 00 00 00 00 00 <8b> 07 83 f8 ff 74 19 41 54 55 48 89 fd 53 f0 83 2f 01 74 14 5b 5d
```

**Did keepalived coredump?**
```
If so, can you please provide a stacktrace from the coredump, using gdb.
```

**Additional context**

**Comment by pqarmitage** [comment] 2021-09-15 16:38
A quick answer for now is that this appears to be caused by one of the following files missing (I got the same segfault as you without them installed, but after installing them [by installing the debian keepalived package] then the segfault stopped).

I will provide more details later, and I can easily add a patch to stop the segfault.

**Comment by lasseoe** [comment] 2021-09-15 16:52
Yeah one or several of the dbus related vrrp files are likely not installed.  When I do "make install" on Debian and Ubuntu those files are not installed in the correct location where dbus is looking, at least not on my box :)
Been struggling figuring out the right location to install them when they are not provided by a package.
I'm finding it odd that everything gets installed under /usr/local except it's looking for keepalived.conf under /etc/keepalived, shouldn't it also be /usr/local/ ?   I know, different problem from the above really.

**Comment by pqarmitage** [comment] 2021-09-15 18:21
The Debian keepalived package installs them at:
/etc/dbus-1/system.d/org.keepalived.Vrrp1.conf
/usr/share/dbus-1/interfaces/org.keepalived.Vrrp1.Instance.xml
/usr/share/dbus-1/interfaces/org.keepalived.Vrrp1.Vrrp.xml

See [Debian bullseye package listing](https://packages.debian.org/bullseye/amd64/keepalived/filelist) for how I found the file locations.

I simply installed the Debian keepalived package, and then ran keepalived v2.2.4 from where I installed it. You could try installing the Debian keepalived package and then reinstalling the keepalived that you have built.

I'll look into the other issues further when I have a moment.

**Comment by pqarmitage** [comment] 2021-09-16 09:12
The DBus code in keepalived runs in a separate thread (Linux pthread). When the thread starts, it attempts to read "/usr/share/dbus-1/interfaces/org.keepalived.Vrrp1.Vrrp.xml" and "/usr/share/dbus-1/interfaces/org.keepalived.Vrrp1.Instance.xml". If it cannot read either of the files, the thread silently terminates without executing `loop == g_main_loop_new(NULL, false);`.

When keepalived later terminates, if DBus is enabled it calls `dbus_stop()` which in turn calls `g_main_loop_quit(loop)` without checking whether `loop` is not null.

This last problem is very easy to resolve. I will also make keepalived log that it cannot find one of the XML files, which will give the location where it is trying to find the file.

I will also look into whether, if keepalived is installed into /usr/local, then the DBus files should  be installed under that path (as they are now) or whether they should still be installed in /etc/dbus-1/system.d and /usr/share/dbus-1/interfaces.

And finally I will look at whether, if keepalived is installed into /usr/local, then it should look for its configuration file in /usr/local/etc/keepalived. Since that is where keepalived.conf is installed, it would seem appropriate.

**Comment by lasseoe** [comment] 2021-09-16 10:34
Fantastic Quentin :-) 👍 

I firmly believe that if something installs under /usr/local then everyhing should go there and the application(s) should look for their files under /usr/local and not elsewhere, not only does it get confusing it also means you may have conflicts if i.e. in a troubleshooting situation you have both the system provided package installed and the equivalent under /usr/local.

Perhaps first check /usr/local/share/dbus-1 then /usr/share/dbus-1, and /usr/local/etc/dbus-1 then /etc/dbus-1   maybe depending on autoconf options.

**Comment by pqarmitage** [comment] 2021-09-21 18:45
@lasseoe I have merged a series of commits at https://github.com/acassen/keepalived/pull/2002.

These will (inter alia):
1) log if keepalived is unable to open a DBus .xml file
2) Attempts to open the DBus .xml file in the location where they are installed
3) Issue a warning at the end of `make install` if the DBus .conf file is installed in a non-standard location from the point of view of DBus.
4) Stop segfaulting if the DBus thread didn't start
5) Attempt to open the default keepalived.conf in the location where it is installed, and if that is not successful, then attempt to open /etc/keepalived/keepalived.conf.

I tkink that resolves all the issues you have raised. If not please update this issue and I can reopen it.

**Closed by pqarmitage** 2021-09-21 18:45 UTC

**Comment by pqarmitage** [comment] 2021-09-22 18:10
@lasseoe Apologies, it appears that I didn't actually merge the commits yesterday. I have now merged them.

**Comment by lasseoe** [comment] 2021-09-27 11:48
So far it looks promising, not done testing yet but it more or less just works.  Once thing I noticed was that I had to reload dbus.service after adding the include to /etc/dbus-1/system-local.conf

Without restarting or reloading dbus.service this happens:
Sep 27 13:42:40 xxxxx Keepalived_vrrp[22083]: Acquired DBus bus org.keepalived.Vrrp1
Sep 27 13:42:40 xxxxx Keepalived_vrrp[22083]: Lost the name org.keepalived.Vrrp1 on the session bus

And during shutdown of keepalived we get:
 keepalived[22083]: g_hash_table_foreach_remove: assertion 'hash_table != NULL' failed

After reloading dbus.service everything works as advertised.   It may be obvious to some, but not everyone :-)

**Comment by pqarmitage** [comment] 2021-09-27 16:31
@lasseoe Thanks for mentioning about needing to restart dbus. Commit dd16e98 adds that to the warning issued at install time (I haven't merged the commit yet).

Commit 5721b5b should resolve the assert failure (g_hash_table_foreach_remove() was being called when the name was lost, and again on shutdown).
