### ISSUE TITLE
New healthchecker for real_server: local file existence / absence

### ISSUE THREAD

**Issue by libesz** [acassen/keepalived#1495] opened 2020-02-10 10:45 UTC
**Is your feature request to resolve a problem or provide enhanced functionality? Please describe.**
This is an enhanced functionality to resolve a scalability problem.
The requested feature is a new real_server healthchecker, which is checking if a file exists in a configured path, or not. The fact that the file exists, would represent the real_server state. This assumes that an external process does the real healtcheck and creates/deletes the file (as an interface towards keepalived) accordingly.

**Describe the solution you would like**
Assume a configuration where there are X virtual_server and Y real_server configured in a way that behind all X the same set of Y is configured. This happens when keepalived is configured to expose a lot of ports. Assuming the healthcheck of the real_servers are not happening on the exposed application port, but on a common port on the backend server, the very same healthcheck is configured for the real_server as many times as many virtual_server is configured. Example:
```
virtual_server 192.168.10.100 80 {
  real_server 10.0.0.1 30524 {
    HTTP_GET {
      connect_port 30520
      url {
        path /
        status_code 200
      }
    }
  }

  real_server 10.0.0.2 30524 {
    HTTP_GET {
      connect_port 30520
      url {
        path /
        status_code 200
      }
    }
  }
}

virtual_server 192.168.10.100 443 {
  real_server 10.0.0.1 31532 {
    HTTP_GET {
      connect_port 30520
      url {
        path /
        status_code 200
      }
    }
  }

  real_server 10.0.0.2 31532 {
    HTTP_GET {
      connect_port 30520
      url {
        path /
        status_code 200
      }
    }
  }
}
```
Assuming keepalived is configured with 100+ virtual_servers and 100+ real_servers, the HTTP GET checks can easily consume all the ephemeral ports on the host, while only one check would be enough per backend, not per port * per backend. The root cause is that keepalived does create a new TCP+HTTP session for every healtcheck, which leaves a lot of TIME_WAIT ans CLOSE_WAIT sockets behind, eventually consuming all the ephemeral client TCP ports.

The current understanding is that there is no way in keepalived configuration to express the ultimate availability of a real_server IP, regardless of the real_server port. Given that, an alternative solution (for the same configuration) can be to offload the real healthcheck to an external process, living outside of keepalived, and configure keepalived to check a local interface towards the external process. Such external process can use persistent TCP connections for multiple HTTP healthchecks and other techniques to spare ephemeral TCP client ports.
One of the most generic and lightweight interface between keepalived and an external proess could be to check if a file exists, which represents the backend's state. This way a more lightweight healthcheck is performed per port * per backend times from keepalived.
The proposed configuration snippet looks like:
```
virtual_server 192.168.10.100 80 {
  real_server 10.0.0.1 30524 {
    FILE_CHECK {
      path /tmp/10.0.0.1
    }
  }

  real_server 10.0.0.2 30524 {
    FILE_CHECK {
      path /tmp/10.0.0.2
    }
  }
}

virtual_server 192.168.10.100 443 {
  real_server 10.0.0.1 31532 {
    FILE_CHECK {
      path /tmp/10.0.0.1
    }
  }

  real_server 10.0.0.2 31532 {
    FILE_CHECK {
      path /tmp/10.0.0.2
    }
  }
}

```  

**Describe alternatives you have considered**
The alternative solution uses MISC_CHECK to call out to an external process to check the file, like this:
```
    MISC_CHECK {
      misc_path "/bin/busybox test -f /tmp/10.0.0.1"
    }
```
While it works as expected, there is still an unnecessary fork/exec done for every single check. This can be a significant amount assuming the large configurations, explained above. If the file check would be implemented inside keepalived, only the real file access (a single stat syscall) would be needed, without fork/exec. 

**Would the feature request be of benefit only to you, or is it more generally applicable?**
This is a generic feature, with potential performance benefits for anyone, having large homo-gen configurations.

**Keepalived version**
Keepalived v2.0.19 (11/24,2019), git commit v20191114-652-g038556d644

**Additional context**
Add any other context about the feature request here.

**Comment by pqarmitage** [comment] 2020-02-10 14:33
@libesz Rather than the presence or absence of a file, would it work for you if the file contained a number, so the the value could be used for weighting purposes?

My thought is this could work in the same way as `vrrp_track_file`, and so we would already have most of the code in keepalived, and more importantly already tested. The code for `vrrp_track_file` uses `inotify()`, and so there is no polling involved at all.

Could this work for you? If so I will proceed and add FILE_CHECK to work like `vrrp_track_file`, but for health checkers.

**Comment by libesz** [comment] 2020-02-10 15:02
@pqarmitage Thanks for the fast feedback! I was not familiar with `vrrp_track_file` and TBH using only weight 0 (disabled real_server) and 1 (enabled real_server) for my use-case. 😄 Anyway, I would happily change my external healthcheck process to write 0 or 1 into the files, instead of creating and deleting them if FILE_CHECK will be implemented.

**Comment by libesz** [comment] 2020-02-10 15:04
One question though. Will the (initial?) absence of the file be treated as 0 weight?

**Comment by pqarmitage** [comment] 2020-02-10 15:39
Looking at the code for vrrp_track_file, there is a comment `/* The file has disappeared. Treat as though the value is 0 */` so currently, yes, the absence of the file is treated as if the file existed and had weight 0. However, `vrrp_track_file` has an option `init_file [VALUE] [overwrite]` which causes an initial value to be written to the file if it doesn't exist, or if `overwrite` is specified it will write the value even if it exists (see keepalived.conf(5) man page for details).

Note however, that the logic is reversed from what you have suggested. If the weight is configured as 0 (which is what you will need for the FILE_CHECK to be considered to have failed), 0 in the file is the value for success, and any non-zero value means failed.

**Comment by libesz** [comment] 2020-02-11 09:06
I see. I will catch up with any logic when available. And of course I can make sure the files will be all there with a valid value before keepalived is spawned (feels better to not ask keepalived as well to (over)write the same files). Just wanted to double-check.
👍

**Comment by libesz** [comment] 2020-02-17 09:15
@pqarmitage Is there anything I can help with this?

**Comment by pqarmitage** [comment] 2020-02-26 10:37
@libesz I am working on this now. I hope to have something in the next few days.

**Comment by libesz** [comment] 2020-02-26 11:49
Thank you very much! I am all for testing it when becomes available.

**Comment by libesz** [comment] 2020-04-16 10:22
@pqarmitage Sorry for jumping on this 😞 but the workaround which I use so far (MISC_CHECK with test -f, described as alternative solution above) can exhaust the entire pid space on the node in the same large setup, which is similarly bad as exhausting ephemeral sockets.

So if there is any help I can provide to have this feature, please let me know.

**Comment by pqarmitage** [comment] 2020-04-16 14:29
@libesz I am working on this at the moment, and hope to be able to merge a commit by the end of the weekend. Apologies for the delay, but Covid-19 has got in the way!

I am intrigued about MISC_CHECK causing exhaustion of the entire pid space (is this 32768 pids?), and this sounds like something we need to fix too. Could you please provide details of how the problem is being caused - keepalived configuration, MISC_CHECK scripts, description of the environment, relevant output to show what is happening (e.g. keepalived logs, other system logs, output of `ps -ef` or equivalent, etc. I assume the script being run by the MISC checker is not terminating, or it is forking children that don't terminate other wise I can't see how the PID space can become exhausted.

**Comment by libesz** [comment] 2020-04-16 14:57
@pqarmitage Thanks again for the great work, I would really not want to push this, especially in the current situation. Just letting you know I would help if I can.

Will open a new issue with the fork problem details.

**Comment by pqarmitage** [comment] 2020-04-19 08:52
FILE_CHECK code now merged. Note that weights with FILE_CHECK are not fully supported at the moment.

Is there any progress regarding creating an issue re fork problem?

**Closed by pqarmitage** 2020-04-19 08:52 UTC

**Comment by libesz** [comment] 2020-04-19 10:56
Thank you very much @pqarmitage for adding this!
Will create the fork related issue tomorrow. I have to collect enough logs...
