### ISSUE TITLE
real_server FILE_CHECK may treat state: "success" at initialization

### ISSUE THREAD

**Issue by libesz** [acassen/keepalived#1555] opened 2020-04-23 09:04 UTC
**Describe the bug**
The new file_track option for real_server may treat the initial status as "success", regardless of the file content on the first read. In this case, until the first file content change the respective real_server will be enabled in the virtual_server regardless when it is failed in the reality and file content is according to this.

**To Reproduce**
Any steps necessary to reproduce the behaviour:
Configure the following:
```
[...]
track_file TF_local {
 file /tmp/node_status/127.0.0.1
 weight 0
}
[...]
virtual_server 192.168.1.1 30091 {
  delay_loop 5
  inhibit_on_failure
  lvs_sched rr
  lvs_method TUN
  protocol TCP
  real_server 127.0.0.1 30091 {
    lvs_method DR
    FILE_CHECK {
      track_file TF_local
    }
  }
}
[...]
```
If the file content contains 1 (meaning failure), the ipvs will be still programmed to allow traffic towards the real_server.

**Expected behavior**
Initial file reading shall also be effective

**Keepalived version**
Compiled from master branch, containing #1495 

**Distro (please complete the following information):**
 - Name: Alpine
 - Version 3.11
 - Architecture x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details

**Configuration file:**
https://pastebin.com/EMVWFs5X

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
https://pastebin.com/EMVWFs5X

**Did keepalived coredump?**
If so, can you please provide a stacktrace from the coredump, using gdb.

**Additional context**

**Comment by libesz** [comment] 2020-04-23 09:25
I've sent a suspected correction. Not tested with vrrp, only with real_server + FILE_CHECK.

**Comment by pqarmitage** [comment] 2020-04-23 10:09
I have tested a vrrp instance using track_file and it does read the initial state.

I will look at your patch in detail presently. I just wonder if `if (!init)` should be `if (init)`, rather than no check at all. I assume I put that test in for some reason; it might just be that I got it the wrong way around. On the other hand, I don't see that it can do any harm reading all the track files on a reload, and it might be necessary if a new track file is introduced at a reload.

**Comment by libesz** [comment] 2020-04-23 10:15
Thanks for the comment. Yes I also assumed that the check had some intent. Though I agree it may not be harmful to push forward the update. If the state did not change, I guess the next function (update_track_file_status) will early-return, so no unnecessary cycles are burned.

**Comment by pqarmitage** [comment] 2020-04-23 12:39
I have just tested the patch and while it does fix the checkers problem it breaks vrrp instances tracking the file. I have also noticed that the reading of the files occurs AFTER the initial ipvs configuration has been set up, which is too late since it means that the real servers are configured with a non zero weight, and then after reading the track files, the weight is, in your case, set to 0, or alternatively the real server is removed.

**Comment by libesz** [comment] 2020-04-23 13:02
Thanks for the update. So then the initial ipvs configuration shall be altered instead?

**Comment by pqarmitage** [comment] 2020-04-24 09:03
Commit 94ad05a resolves this issue. Many thanks for you help with this.

**Comment by libesz** [comment] 2020-04-27 12:23
Thanks @pqarmitage . Could you please confirm that the `delay_loop` option is not used at all for virtual_servers if only `FILE_CHECK` based checkers are configured for the real_servers?

**Comment by libesz** [comment] 2020-04-27 12:31
Also, I found possibly unitialized data in the logs, created as part of this fix:
```
[...]
2020/04/27 12:26:14.629582 keepalived | ------< Health checkers >------
2020/04/27 12:26:14.629589 keepalived |  [x.x.x.x]:tcp:30091 -> [127.0.0.11]:tcp:30091
2020/04/27 12:26:14.629622 keepalived |    Enabled = yes
2020/04/27 12:26:14.629629 keepalived |    Up = no
2020/04/27 12:26:14.629650 keepalived |    Has run = yes
2020/04/27 12:26:14.629659 keepalived |    Alpha = yes
2020/04/27 12:26:14.629711 keepalived |    Delay loop = 18446744073709551615
2020/04/27 12:26:14.629717 keepalived |    Warmup = 18446744073709551615
2020/04/27 12:26:14.629723 keepalived |    Retries = 4294967295
2020/04/27 12:26:14.629728 keepalived |    Delay before retry = 18446744073709551615
2020/04/27 12:26:14.629765 keepalived |    Retries iterations = 0
2020/04/27 12:26:14.629770 keepalived |    Defailt delay before retry = 1000000
2020/04/27 12:26:14.629784 keepalived |    Log all failures = no
2020/04/27 12:26:14.629824 keepalived |    Keepalive method = FILE_CHECK
2020/04/27 12:26:14.629829 keepalived |      Tracked file = TF_local
[...]
```

**Comment by pqarmitage** [comment] 2020-04-27 13:29
18446744073709551615 = 2^64 - 1 = ULONG_MAX
4294967295 = 2^32 -1 = UINT32_MAX

These values are used to indicate that the parameter has not been configured, and so it is disabled. For a FILE_CHECK checker delay loop, warmup, retries and delay before retry are not relevant and hence aren't set (I think this answers your previous comment as well).

For checkers other than FILE_CHECK, they are all run periodically, and these parameters control the start up delay to running the checker, how many times to retry and interval between retries. For a FILE_CHECK these do not apply since the file is read when keepalived starts, and then the checker on runs when the file is modified.

**Comment by libesz** [comment] 2020-04-27 13:34
Thank you. That confirms all my questions.

**Comment by libesz** [comment] 2020-04-29 09:08
@pqarmitage We are still testing this FILE_CHECK feature. I think there might be still some issues with the (re)initialization. In the test, keepalived got reconfigured:
* one more `track_file` added (initialliy 4, then 5)
* it is referenced by new `real_server`s
* SIGHUP sent

One of the original `real_server`s is dead:
* not sure if it was dead before the SIGHUP, but after that it is
* IPVS is enabled for it in all `virtual_server` after the SIGHUP (not sure if it was enabled before the SIGHUP)

I can send portions of the log and configs, but maybe not all (it is too large) due to the 1000 virtual servers.

**Comment by pqarmitage** [comment] 2020-04-29 11:33
I will have a look into this. If you could send the logs and configs that would be helpful, ideally the full logs and full configs. I suggest you either compress them or send them to me direct via email. Once we track down the problem this issue can be updated with the relevant information.

**Comment by libesz** [comment] 2020-04-29 11:57
Thanks! Sent them in email.

**Comment by libesz** [comment] 2020-05-08 12:51
I tested this issue with the recent source tree (https://github.com/acassen/keepalived/commit/2c65ca8e39ec07bcd365af75a4aea04c62d24291). The issue is still persistent and I found this way to reliably reproduce it:
* Assume we have multiple vs * rs configured with the new file trackers
* At the initial startup, there are inactive rs -es
Config snippet:
```
[...]
track_file TF_0 {
  file /tmp/node_status/10.131.64.80
  weight 0
}
track_file TF_1 {
  file /tmp/node_status/10.131.64.90
  weight 0
}
[...]
virtual_server x.x.x.x 30091 {
  inhibit_on_failure
  lvs_sched rr
  lvs_method TUN
  protocol TCP

  real_server 10.131.64.80 31137 {
    FILE_CHECK { track_file TF_0 }
  }

  real_server 10.131.64.90 31137 {
    FILE_CHECK { track_file TF_1 }
  }
[...]
}
```
Initial ipvs is correct, like:
```
TCP  x.x.x.x:30091 rr
  -> 10.131.64.80:30091           Tunnel  0      0          0
  -> 10.131.64.90:30091           Tunnel  1      0          0
```
* Sending SIGHUP triggers the issue and turns all rs in all vs into active, regardless that the config and the files on the filesystem are not changed meanwhile:
```
TCP  x.x.x.x:30091 rr
  -> 10.131.64.80:30091           Tunnel  1      0          0
  -> 10.131.64.90:30091           Tunnel  1      0          0
```
* The generated logs at SIGHUP time are the following:
```
2020/05/08 12:32:12.272451 keepalived | Reloading
2020/05/08 12:32:12.272470 keepalived | Got SIGHUP, reloading checker configuration
2020/05/08 12:32:12.282692 keepalived | Opening file '/etc/keepalived/keepalived.conf'.
2020/05/08 12:32:12.302975 keepalived | WARNING - virtual server [x.x.x.x]:tcp:30091 and real server [10.131.64.80]:tcp:31137 ports don't match - resetting <-- this is written for all vs * rs
[...]
2020/05/08 12:32:12.357892 keepalived | Reinitializing ipvs
2020/05/08 12:32:12.358465 keepalived | Enabling service [10.131.64.80]:tcp:30091 to VS [x.x.x.x]:tcp:30091 <-- this is written for all vs * rs which was not enabled before the SIGHUP
[...]
```
* This system state remains until any inactive rs goes into active and back to inactive. At that time, the respective rs is corrected. Sending another SIGHUP resets everything into enabled again

I assume the last log (and action) should not happen but could not track down on source level why it is actually happening at SIGHUP time.

Hope this helps.

**Comment by libesz** [comment] 2020-05-08 13:08
I assume the wrong state change is invoked here: https://github.com/acassen/keepalived/blame/2c65ca8e39ec07bcd365af75a4aea04c62d24291/keepalived/check/ipwrapper.c#L915
According to the git message it should solve the issue which we have here :).

**Comment by libesz** [comment] 2020-05-29 13:20
@pqarmitage I did some further investigation on this issue as it still blocks the usage of track files.
I put a breakpoint to https://github.com/acassen/keepalived/blame/2c65ca8e39ec07bcd365af75a4aea04c62d24291/keepalived/check/ipwrapper.c#L915 and found out that indeed it forces the IPVS states to ON on SIGHUP. These are the RS structs at the breakpoint:
```
(gdb) p *new_rs
$21 = {addr = {ss_family = 2, __ss_padding = "u\213\177\000\000\v", '\000' <repeats 111 times>, 
    __ss_align = 0}, weight = 1, effective_weight = 0, iweight = 1, pweight = 1, forwarding_method = 3, 
  u_threshold = 0, l_threshold = 0, inhibit = 1, notify_up = 0x0, notify_down = 0x0, alpha = 0, 
  connection_to = 5000000, delay_loop = 60000000, warmup = 18446744073709551615, retry = 4294967295, 
  delay_before_retry = 18446744073709551615, smtp_alert = 1, alive = false, num_failed_checkers = 0, 
  set = true, reloaded = true, virtualhost = 0x0, track_files = 0x55a216116260}
(gdb) p *old_rs
$22 = {addr = {ss_family = 2, __ss_padding = "u\213\177\000\000\v", '\000' <repeats 111 times>, 
    __ss_align = 0}, weight = 1, effective_weight = 1, iweight = 1, pweight = 0, forwarding_method = 3, 
  u_threshold = 0, l_threshold = 0, inhibit = 1, notify_up = 0x0, notify_down = 0x0, alpha = 0, 
  connection_to = 5000000, delay_loop = 60000000, warmup = 18446744073709551615, retry = 4294967295, 
  delay_before_retry = 18446744073709551615, smtp_alert = 1, alive = false, num_failed_checkers = 1, 
  set = true, reloaded = false, virtualhost = 0x0, track_files = 0x55a2161129c0}
```

As you can see, old_rs shows there is a failed checker, while new_rs shows 0.
Not sure how this `migrate_checkers` function should really behave, but based on this comment:
```
	/* If a checker has failed, set new alpha checkers to be down until
	 * they have run. */
```
 I assume it is not prepared for tracker files yet. I believe track_file does not run such regularly and attempts to update the RS state, so it won't ever trigger the state change to failure again (until RS becomes really available and then fail again).

Can you please advice if this is a correct way of investigating this?
Would it be possible to specialize the behavior of this function in case of the checker itself is a file tracker type?

**Comment by libesz** [comment] 2020-05-29 13:26
Also at the same breakpoint I think the content of the checker itself is the following:
```
(gdb) p *old_checkers_queue
$23 = {head = 0x55a2161130a0, tail = 0x7efd204fc8c0, count = 6, free = 0x55a2144bec37 <free_checker>, 
  dump = 0x55a2144bec39 <dump_checker>}
(gdb) p (checker_t)*0x55a2161130a0
$24 = {free_func = 0x55a216112040, dump_func = 0x0, launch = 0x55a216113220, compare = 0x0, 
  vs = 0x7efd201663a0, rs = 0x7efd204f9a80, data = 0x41, enabled = 65, is_up = false, has_run = false, 
  co = 0x55a216113140, alpha = 370225472, delay_loop = 1, warmup = 94154613744386, retry = 340678582, 
  delay_before_retry = 0, retry_it = 65, default_retry = 0, default_delay_before_retry = 33, 
  log_all_failures = 128}
```

It shows `has_run = false` which also might be part of the problem.

**Comment by pqarmitage** [comment] 2020-05-29 13:28
track_file only runs when the file is written to, i.e. there is no polling involved. This is the beauty of using track_files, they are very efficient since the checker only runs when there is a state change.

Commit 4bdafb6 resolves the issue of a failed track file not leaving the real server down after a reload. I was working on this right now, and the one outstanding issue, which I was going to include in the commit, is dealing with a added track file that is failed when the reload occurs. I will now fix that in a separate commit.

**Comment by libesz** [comment] 2020-05-29 13:35
Thanks! Will be happy to try out the newest commit when merged.

**Comment by pqarmitage** [comment] 2020-05-29 16:19
@libesz Just to confirm that has been merged.

**Comment by pqarmitage** [comment] 2020-05-30 14:41
Commit e27e595 now handles the situation where a track file is added when the configuration is reloaded, and the track file status is down.

**Comment by libesz** [comment] 2020-06-04 09:45
@pqarmitage Sorry for still jumping on this 😄 , but this might be again important.
I tested (with the latest relevant commit) the reload cases and something is suspicious in the logs. When new track file is added and referenced, the following log appears (seemingly) with too much instances:
Two VS with one new RS added to both causes 4 lines of logs instead of two:
```
2020/06/03 15:07:48.673852 keepalived | ([10.176.120.133]:tcp:30091): tracked file TF_0 now FAULT state
2020/06/03 15:07:48.673870 keepalived | ([10.176.120.133]:tcp:30092): tracked file TF_0 now FAULT state
2020/06/03 15:07:48.673883 keepalived | ([10.176.120.133]:tcp:30091): tracked file TF_0 now FAULT state
2020/06/03 15:07:48.673929 keepalived | ([10.176.120.133]:tcp:30092): tracked file TF_0 now FAULT state
```
If I do it with a 500 VS setup, where I add a new file reference (the same for all), it prints 25000 (500*500) logs. I guess the file is evaluated as many times as referred, but then it enumerates all it's references when reloading. When a file represented RS changes the state, the logs are not multiplied as in case of reload.

I did not debug this further, but if not only the logs are printed, real actions done multiple times may be exhaustive.

**Comment by pqarmitage** [comment] 2020-06-11 22:58
Commit 3198d2b resolves the problem of the new track file being processed n^2 times.

**Comment by libesz** [comment] 2020-06-25 13:45
@pqarmitage Back to this topic again. Keepalived version: 2.1.2

We captured an issue, where:
* New track files has been added to the config
* SIGHUP issued
* Meanwhile backends became available (track files updated)
* Keepalived entered master state

And all ipvs is programmed to false after all.

Here are the keepalived logs with some annotations and ipvs state:
```
[...]
2020/06/25 11:17:15.570782 Reload / sending SIGHUP to /usr/sbin/keepalived ...
2020/06/25 11:17:15.570818 Checker started up with 5 nodes
2020/06/25 11:17:15.571635 keepalived | Reloading ...
2020/06/25 11:17:15.571663 keepalived | Opening file '/etc/keepalived/keepalived.conf'.
2020/06/25 11:17:15.571716 keepalived | Reloading
2020/06/25 11:17:15.571768 keepalived | Got SIGHUP, reloading checker configuration
2020/06/25 11:17:15.572020 keepalived | Reloading
2020/06/25 11:17:15.572343 keepalived | Opening file '/etc/keepalived/keepalived.conf'.
2020/06/25 11:17:15.572817 keepalived | Assigned address 169.44.4.228 for interface eth1
2020/06/25 11:17:15.573115 keepalived | Assigned address fe80::446:8fff:fe5a:2eab for interface eth1
2020/06/25 11:17:15.573650 keepalived | (vip-x.x.x.x) removing VIPs.
2020/06/25 11:17:15.573850 keepalived | VRRP sockpool: [ifindex(  3), family(IPv4), proto(112), fd(11,12)]
2020/06/25 11:17:15.579949 keepalived | Opening file '/etc/keepalived/keepalived.conf'.
2020/06/25 11:17:15.580320 keepalived | WARNING - virtual server [x.x.x.x]:tcp:30053 and real server [10.143.159.30]:tcp:32186 ports don't match - resetting
2020/06/25 11:17:15.580418 keepalived | WARNING - virtual server [x.x.x.x]:tcp:30053 and real server [10.143.9.146]:tcp:32186 ports don't match - resetting
2020/06/25 11:17:15.580469 keepalived | WARNING - virtual server [x.x.x.x]:tcp:30053 and real server [10.143.9.193]:tcp:32186 ports don't match - resetting
2020/06/25 11:17:15.580607 keepalived | WARNING - virtual server [x.x.x.x]:tcp:30053 and real server [10.143.9.232]:tcp:32186 ports don't match - resetting
2020/06/25 11:17:15.580650 keepalived | WARNING - virtual server [x.x.x.x]:tcp:30090 and real server [10.143.159.30]:tcp:32226 ports don't match - resetting
2020/06/25 11:17:15.580748 keepalived | WARNING - virtual server [x.x.x.x]:tcp:30090 and real server [10.143.9.146]:tcp:32226 ports don't match - resetting
2020/06/25 11:17:15.580867 keepalived | WARNING - virtual server [x.x.x.x]:tcp:30090 and real server [10.143.9.193]:tcp:32226 ports don't match - resetting
2020/06/25 11:17:15.580934 keepalived | WARNING - virtual server [x.x.x.x]:tcp:30090 and real server [10.143.9.232]:tcp:32226 ports don't match - resetting
2020/06/25 11:17:15.581040 keepalived | Reinitializing ipvs
2020/06/25 11:17:15.581128 keepalived | ([10.143.9.146]:tcp:30053): tracked file TF_1 now FAULT state
2020/06/25 11:17:15.581255 keepalived | ([10.143.9.146]:tcp:30090): tracked file TF_1 now FAULT state
2020/06/25 11:17:15.581315 keepalived | ([10.143.9.193]:tcp:30053): tracked file TF_2 now FAULT state
2020/06/25 11:17:15.581393 keepalived | ([10.143.9.193]:tcp:30090): tracked file TF_2 now FAULT state
2020/06/25 11:17:15.581485 keepalived | ([10.143.9.232]:tcp:30053): tracked file TF_3 now FAULT state
2020/06/25 11:17:15.581510 keepalived | ([10.143.9.232]:tcp:30090): tracked file TF_3 now FAULT state
2020/06/25 11:17:16.573603 Checker identified state change for node 10.143.9.232: true                    <-files are changed to enabled state
2020/06/25 11:17:16.573678 Checker identified state change for node 10.143.9.193: true
2020/06/25 11:17:16.573805 Checker identified state change for node 10.143.9.146: true
2020/06/25 11:17:16.574076 keepalived | ([10.143.9.232]:tcp:30053): tracked file TF_3 leaving FAULT state <- keepalived logs correctly that backends became available
2020/06/25 11:17:16.574127 keepalived | ([10.143.9.232]:tcp:30090): tracked file TF_3 leaving FAULT state
2020/06/25 11:17:16.574175 keepalived | ([10.143.9.193]:tcp:30053): tracked file TF_2 leaving FAULT state
2020/06/25 11:17:16.574184 keepalived | ([10.143.9.193]:tcp:30090): tracked file TF_2 leaving FAULT state
2020/06/25 11:17:16.574246 keepalived | ([10.143.9.146]:tcp:30053): tracked file TF_1 leaving FAULT state
2020/06/25 11:17:16.574265 keepalived | ([10.143.9.146]:tcp:30090): tracked file TF_1 leaving FAULT state
2020/06/25 12:27:04.686540 keepalived | (vip-x.x.x.x) Backup received priority 0 advertisement
2020/06/25 12:27:05.296458 keepalived | (vip-x.x.x.x) Receive advertisement timeout
2020/06/25 12:27:05.296496 keepalived | (vip-x.x.x.x) Entering MASTER STATE
2020/06/25 12:27:05.296503 keepalived | (vip-x.x.x.x) setting VIPs.
2020/06/25 12:27:05.296509 keepalived | Netlink reflector reports IP x.x.x.x added
2020/06/25 12:27:05.296516 keepalived | (vip-x.x.x.x) Sending/queueing gratuitous ARPs on eth1 for x.x.x.x
2020/06/25 12:27:05.296522 keepalived | Sending gratuitous ARP on eth1 for x.x.x.x
2020/06/25 12:27:05.296527 keepalived | Sending gratuitous ARP on eth1 for x.x.x.x
2020/06/25 12:27:05.296532 keepalived | Sending gratuitous ARP on eth1 for x.x.x.x
2020/06/25 12:27:05.296537 keepalived | Sending gratuitous ARP on eth1 for x.x.x.x
2020/06/25 12:27:05.296542 keepalived | Sending gratuitous ARP on eth1 for x.x.x.x

# ipvsadm -ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  x.x.x.x:30053 rr
  -> 10.143.9.146:30053           Tunnel  0      0          0
  -> 10.143.9.193:30053           Tunnel  0      0          0
  -> 10.143.9.232:30053           Tunnel  0      0          0
  -> 10.143.159.30:30053          Tunnel  0      0          0
  -> 127.0.0.11:30053             Route   0      0          0
TCP  x.x.x.x:30090 rr
  -> 10.143.9.146:30090           Tunnel  0      0          0
  -> 10.143.9.193:30090           Tunnel  0      0          0
  -> 10.143.9.232:30090           Tunnel  0      0          0
  -> 10.143.159.30:30090          Tunnel  0      0          0
  -> 127.0.0.11:30090             Route   0      0          0

```

**Comment by pqarmitage** [comment] 2020-06-27 08:56
@libesz I will have a further look at this, but you annotation isn't quite correct. Where you state `<- keepalived logs correctly that backends became available` the log entries are saying that the track_file is not longer in FAULT state; it isn't saying that the real servers have been enabled, that is a different log message.

The transition of the VRRP instance from backup to master seems to be a completely unrelated event, since it occurs approximately 1 hour and 10 minutes after the reload.

In the mean time can you please provide a copy of your configuration so that we can test what is happening.

**Comment by libesz** [comment] 2020-06-29 09:00
@pqarmitage Thanks for the corrections. Here is the original config:
```
global_defs {
    vrrp_mcast_group4 224.0.0.18
}

vrrp_instance vip-x.x.x.x {
    state BACKUP
    interface eth1
    virtual_router_id 117
    priority 100
    nopreempt
    virtual_ipaddress {
        x.x.x.x
    }
}

track_file TF_local {
  file /tmp/node_status/127.0.0.1
  weight 0
}

track_file TF_0 {
  file /tmp/node_status/10.143.159.30
  weight 0
}

virtual_server x.x.x.x 30090 {
  inhibit_on_failure
  lvs_sched rr
  lvs_method TUN
  protocol TCP

  real_server 127.0.0.11 30090 {
    lvs_method DR
    FILE_CHECK { track_file TF_local }
  }

  real_server 10.143.159.30 32226 {
    FILE_CHECK { track_file TF_0 }
  }
}

virtual_server x.x.x.x 30053 {
  inhibit_on_failure
  lvs_sched rr
  lvs_method TUN
  protocol TCP

  real_server 127.0.0.11 30053 {
    lvs_method DR
    FILE_CHECK { track_file TF_local }
  }

  real_server 10.143.159.30 32186 {
    FILE_CHECK { track_file TF_0 }
  }
}
```

And here is the extended one:
```
global_defs {
    vrrp_mcast_group4 224.0.0.18
}

vrrp_instance vip-x.x.x.x {
    state BACKUP
    interface eth1
    virtual_router_id 117
    priority 100
    nopreempt
    virtual_ipaddress {
        x.x.x.x
    }
}

track_file TF_local {
  file /tmp/node_status/127.0.0.1
  weight 0
}

track_file TF_0 {
  file /tmp/node_status/10.143.159.30
  weight 0
}

track_file TF_1 {
  file /tmp/node_status/10.143.9.146
  weight 0
}

track_file TF_2 {
  file /tmp/node_status/10.143.9.193
  weight 0
}

track_file TF_3 {
  file /tmp/node_status/10.143.9.232
  weight 0
}

virtual_server x.x.x.x 30053 {
  inhibit_on_failure
  lvs_sched rr
  lvs_method TUN
  protocol TCP

  real_server 127.0.0.11 30053 {
    lvs_method DR
    FILE_CHECK { track_file TF_local }
  }

  real_server 10.143.159.30 32186 {
    FILE_CHECK { track_file TF_0 }
  }

  real_server 10.143.9.146 32186 {
    FILE_CHECK { track_file TF_1 }
  }

  real_server 10.143.9.193 32186 {
    FILE_CHECK { track_file TF_2 }
  }

  real_server 10.143.9.232 32186 {
    FILE_CHECK { track_file TF_3 }
  }
}

virtual_server x.x.x.x 30090 {
  inhibit_on_failure
  lvs_sched rr
  lvs_method TUN
  protocol TCP

  real_server 127.0.0.11 30090 {
    lvs_method DR
    FILE_CHECK { track_file TF_local }
  }

  real_server 10.143.159.30 32226 {
    FILE_CHECK { track_file TF_0 }
  }

  real_server 10.143.9.146 32226 {
    FILE_CHECK { track_file TF_1 }
  }

  real_server 10.143.9.193 32226 {
    FILE_CHECK { track_file TF_2 }
  }

  real_server 10.143.9.232 32226 {
    FILE_CHECK { track_file TF_3 }
  }
}
```

The change is basically that three new track files are added and all of them referenced in both `virtual_server`s. If that counts, the two `virtual_server`s are swapped in the configuration, but the properties (IP/port) is the same for them. Also maybe this matters: the new track files may or may not already exist at the time of the SIGHUP.

Hope this helps.

**Comment by libesz** [comment] 2020-06-29 13:50
I could reliably reproduce the issue with 30+ seconds delay between the SIGHUP processing and the (new) file state change, which may suggest this is not a timing issue. IPVS left disabled.

**Comment by pqarmitage** [comment] 2020-06-29 13:57
I can see what is going wrong, and at the moment I am trying to track down why it is happening.

After the reload, if you send SIGUSR1 to the parent keepalived process a file /tmp/keepalived_check.data will be written. In there you will be able to see against the new RS that num_failed_checkers = 2, and that is the problem.

**Comment by libesz** [comment] 2020-06-29 14:05
I see, thanks! For me the new RS shows `num failed checkers = 1` right now in the file.

**Comment by libesz** [comment] 2020-07-08 08:52
Is there any more logs or dumps which I could capture about this?

**Comment by pqarmitage** [comment] 2020-07-08 08:55
@libesz I can reproduce the problem and so I have all the information I need.

This issue is going to be quite involved to fix, and I have had some other issues that I needed to resolve. I will have a further look at this in the next few days.

**Comment by libesz** [comment] 2020-07-08 09:06
Thank you @pqarmitage in advance!

**Comment by libesz** [comment] 2020-09-03 13:34
@pqarmitage Sorry, but let me ping this once more. If there is anything what would help to proceed with this, please let me know. I would definitely love to integrate this feature once it is stable.

**Comment by pqarmitage** [comment] 2020-09-03 13:51
@libesz Many apologies for the delay in resolving this. I will aim to have a look at it this weekend when I should have some free time.

**Comment by libesz** [comment] 2020-09-17 13:32
@pqarmitage Thank for all of your efforts.

**Comment by pqarmitage** [comment] 2020-09-18 15:25
@libesz This has been much harder to resolve than I anticipated; I had thought that it was down to the new track_files not being read after a reload, but that wasn't the case, and it was down to a bug in the code relating to alpha mode (sort of) being set, which doesn't make sense for FILE_CHECKers, or indeed any track_file.

As a work around, if you set `alpha false` in each of the FILE_CHECK blocks, then that stops the problem occurring. I will push a patch to resolve this later, so that `alpha false` is not needed, but I want to do some more testing beforehand.

**Comment by pqarmitage** [comment] 2020-09-18 17:26
CORRECTION: setting `alpha false` does not work; it will need to wait for a patch to be pushed. 

The patch so far is:
```
diff --git a/keepalived/check/check_file.c b/keepalived/check/check_file.c
index 90c9556b..6828388d 100644
--- a/keepalived/check/check_file.c
+++ b/keepalived/check/check_file.c
@@ -189,6 +197,9 @@ add_rs_to_track_files(void)
                                 * checked the file, so mark it as run. */
                                new_checker->has_run = true;

+                               /* Clear Alpha mode - we know the state of the checker immediately */
+                               new_checker->alpha = false;
+
                                add_obj_to_track_file(new_checker, tfl, FMT_RS(rs, vs), dump_tracking_rs);
                        }
                }
```

but there is now a problem if the track_file is in a failed state when it is added at a reload.

**Comment by pqarmitage** [comment] 2020-09-20 16:23
@libesz Commit fa143f0 resolves this issue. I have had to alter the way that FILE_CHECKs are handled on reload, but it is now simpler.

Many apologies for this having taken so long.

**Closed by pqarmitage** 2020-09-20 16:23 UTC

**Comment by libesz** [comment] 2020-09-21 06:02
I appreciate all the hard work you made on this @pqarmitage! I try to get back to the testing of this asap and let you know if I see unexpected behavior!
Thanks again!
