### ISSUE TITLE
genhash program outputs a success code when it has failed

### ISSUE THREAD

**Issue by coretemp** [acassen/keepalived#766] opened 2018-01-26 17:34 UTC
```
genhash -s 192.168.122.145 -p 10000 -u / 
```
produces no output with exit status 0. It is my understanding that I requested a MD5 hash, which is non-empty. So, there is a program error, regardless of whether my HTTP endpoint is actually conforming to a standard (wget seems to accept it with some trouble, but not without issues, so I hold the possibility that it's not conforming open).

```
genhash -s 192.168.122.141 -p 10000 -u / # note  192.168.122.141  is invalid on purpose
Cannot send get request to [192.168.122.141]:10000.
```
Compare to `wget` output:
```
wget -O - 192.168.122.145:10000/
--2018-01-26 17:15:55--  http://192.168.122.145:10000/
Connecting to 192.168.122.145:10000... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2018-01-26 17:15:59--  (try: 2)  http://192.168.122.145:10000/
Connecting to 192.168.122.145:10000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10 [text/plain]
Saving to: ‘STDOUT’

-                               0%[                                                ]       0  --.-KB/s               It Works!
-                             100%[===============================================>]      10  --.-KB/s    in 0s

2018-01-26 17:15:59 (501 KB/s) - written to stdout [10/10]
```

**Comment by acassen** [comment] 2018-01-26 20:20
Hi there,

just a quick off-topic consideration here, long time ago I wanted to just remove genhash utility since it is a non sense to provide a dedicated code for it. You can obtain the same hash by piping wget output directly to md5sum, this a single command line :) I think we need to remove this code and just replace it by a simple wget -O | md5sum

for you issue, well, you just dont provide enough infos here... but use wget and md5sum instead of genhash.

regs,
Alexandre

**Comment by pqarmitage** [comment] 2018-01-27 11:09
Yes, I agree it would be a very good idea to get rid of genhash, since having to maintain compatibility between some of the code that is used by both keepalived and genhash can be quite a nuisance.

However, I am getting a discrepancy between the md5sums calculated by genhash and by wget/md5sum:
```
genhash -s 192.168.122.145 -p 10000 -u /
MD5SUM = 69f1ff4f8d3649303782cef07141bc89
```
and
```
wget -nv -O - 192.168.122.145:10000/ | md5sum
2018-01-27 11:08:36 URL:http://192.168.122.145:10000/ [9/9] -> "-" [1]
6610da01ab9963d9489fbdb2cd6051d5  -
```
This is when using the "dummy" http server at https://github.com/acassen/keepalived/issues/765#issuecomment-360852268

I'll have a look to see what is causing the difference.

**Comment by pqarmitage** [comment] 2018-01-27 11:10
I cannot reproduce the problem at https://github.com/acassen/keepalived/issues/766#issue-291975993 . Can you please explain how you cause that to happen.

**Comment by pqarmitage** [comment] 2018-01-27 12:52
I've found the problem with genhash and wget/md5sum producing different md5sums. The problem is twofold: first the script for the "dummy" http server at https://github.com/acassen/keepalived/issues/766#issue-291975993 was appending a `<LF>` character to the string, and so although it was setting the length to 9 bytes, it was sending 10 bytes. This is resolved by adding the `-n` option to the echo command. The second problem is that genhash is not using the Content-Length sent in the http header.

I'll have a look at fixing genhash, and also producing a genhash script that uses wget/md5sum with a view to the C code for genhash being replaced.

**Comment by acassen** [comment] 2018-01-27 17:19
great !
long time ago I used wget+md5sum and get the same hash but cant remind the excct cmdline I used (but quite the same as yours).

**Comment by pqarmitage** [comment] 2018-01-28 12:31
Commit bd5ebf should make genhash exit with code 1 if it encounters an error, and 0 otherwise.

**Closed** 2018-02-05 13:21 UTC
