### ISSUE TITLE
Cant send advert to 10.100.12.60 (Invalid argument)

### ISSUE THREAD

**Issue by snailq** [acassen/keepalived#1771] opened 2020-11-05 12:32 UTC
**Describe what you need help/support for**
Keepalive uses active-active mode, vip1 and vip2

v1 often have problems during the evening peak hours. 
The vrrp advertisement cannot be sent, but it will be sent normally next time soon
As shown in the log below
v2 works normally and has never had a problem.
 No performance issues found, No abnormalities were found in cpu, memory, system log, network card, network card queue, etc.
Because it is an online service, you cannot use tools such as gdb to check the problem, and there is no recurring problem in the same environment
I originally used v1.3.5, but I didn’t search for relevant information using Google. There was only an ipv6 problem, but my version has been upgraded to the latest (v2.1.5), and it still doesn’t solve my problem.
I try to collect the available information,Can help me check where the problem is, thank you very very very very very much！

**Keepalived version**
Keepalived v2.1.5 (07/13,2020)
Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>
Built with kernel headers for Linux 3.10.0
Running on Linux 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017
configure options: --enable-snmp --enable-snmp-vrrp --enable-snmp-rfc --enable-snmp-rfcv2
Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3
System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV6_ADVANCED_API RTA_ENCAP RTA_EXPIRES FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL NET_LINUX_IF_H_COLLISION NET_LINUX_IF_ETHER_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION VRRP_VMAC IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RESET_ON_FORK

**keepalived log**

10.100.12.144
Sep 27 21:19:24 Keepalived_vrrp[27738]: (VI_1) Cant send advert to 10.100.12.60 (Invalid argument)
Sep 27 21:27:42 Keepalived_vrrp[27738]: (VI_1) Cant send advert to 10.100.12.60 (Invalid argument)
Sep 27 21:27:45 Keepalived_vrrp[27738]: (VI_1) Cant send advert to 10.100.12.60 (Invalid argument)
Sep 27 21:27:48 Keepalived_vrrp[27738]: (VI_1) Cant send advert to 10.100.12.60 (Invalid argument)
Sep 27 21:27:49 Keepalived_vrrp[27738]: (VI_1) Received advert from 10.100.12.60 with lower priority 50, ours 100, forcing new election
Sep 27 21:27:49 Keepalived_vrrp[27738]: (VI_1) Cant send advert to 10.100.12.60 (Invalid argument)
Sep 27 21:27:49 Keepalived_vrrp[27738]: (VI_1) Sending/queueing gratuitous ARPs on eth0 for 10.100.12.206
Sep 27 21:27:49 Keepalived_vrrp[27738]: Sending gratuitous ARP on eth0 for 10.100.12.206
Sep 27 21:27:49 Keepalived_vrrp[27738]: Sending gratuitous ARP on eth0 for 10.100.12.206
Sep 27 21:27:49 Keepalived_vrrp[27738]: Sending gratuitous ARP on eth0 for 10.100.12.206
Sep 27 21:27:49 Keepalived_vrrp[27738]: Sending gratuitous ARP on eth0 for 10.100.12.206
Sep 27 21:27:49 Keepalived_vrrp[27738]: Sending gratuitous ARP on eth0 for 10.100.12.206

10.100.12.60
Sep 27 21:27:49 Keepalived_vrrp[28364]: (VI_1) Receive advertisement timeout
Sep 27 21:27:49 Keepalived_vrrp[28364]: (VI_1) Entering MASTER STATE
Sep 27 21:27:49 Keepalived_vrrp[28364]: (VI_1) setting VIPs.
Sep 27 21:27:49 Keepalived_vrrp[28364]: (VI_1) Sending/queueing gratuitous ARPs on eth0 for 10.100.12.206
Sep 27 21:27:49 Keepalived_vrrp[28364]: Sending gratuitous ARP on eth0 for 10.100.12.206
Sep 27 21:27:49 Keepalived_vrrp[28364]: Sending gratuitous ARP on eth0 for 10.100.12.206
Sep 27 21:27:49 Keepalived_vrrp[28364]: Sending gratuitous ARP on eth0 for 10.100.12.206
Sep 27 21:27:49 Keepalived_vrrp[28364]: Sending gratuitous ARP on eth0 for 10.100.12.206
Sep 27 21:27:49 Keepalived_vrrp[28364]: Sending gratuitous ARP on eth0 for 10.100.12.206
Sep 27 21:27:49 Keepalived_vrrp[28364]: Remote SMTP server [10.100.9.128]:25 connected.
Sep 27 21:27:49 Keepalived_vrrp[28364]: SMTP alert successfully sent.
Sep 27 21:27:52 Keepalived_vrrp[28364]: (VI_1) Master received advert from 10.100.12.144 with higher priority 100, ours 50
Sep 27 21:27:52 Keepalived_vrrp[28364]: (VI_1) Entering BACKUP STATE
Sep 27 21:27:52 Keepalived_vrrp[28364]: (VI_1) removing VIPs.
Sep 27 21:27:52 Keepalived_vrrp[28364]: Remote SMTP server [10.100.9.128]:25 connected.
Sep 27 21:27:52 Keepalived_vrrp[28364]: SMTP alert successfully sent.

**strace info**
 sendmsg(12, {msg_name(16)={sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("10.100.12.60")}, msg_iov(1)=[{"E\300\0(\346\344\0\0\377p\0\0\nd\f\220\nd\f<!3d\1\1\3\23\232\nd\f\316"..., 40}], msg_controllen=0, msg_flags=0}, 0) = -1 EINVAL (Invalid argument)
 sendto(3, "<14>Sep 27 00:03:20 Keepalived_v"..., 102, MSG_NOSIGNAL, NULL, 0) = 102

**Distro (please complete the following information):**
 - Name [CentOS release 7.3.1611]
 - Version [ Linux kernel 3.10.0-514.21.1.el7.x86_64]
 - Architecture [x86_64]

**Configuration file:**
global_defs {
   notification_email {
    xx@xx.com
   }
   notification_email_from xxx@xx.cn
   smtp_server xx.xx.xxx
   smtp_connect_timeout 30
   router_id snat01
}
vrrp_instance VI_1 {
    state MASTER
    smtp_alert
    interface eth0
    virtual_router_id 51
    priority 100
    advert_int 3
    authentication {
        auth_type PASS
        auth_pass havip1
    }
    virtual_ipaddress {
        10.100.12.206 dev eth0 label eth0:havip1
    }
    unicast_src_ip 10.100.12.144
    unicast_peer {
            10.100.12.60
    }
}
vrrp_instance VI_2 {
    state BACKUP
    smtp_alert
    interface eth0
    virtual_router_id 52
    priority 50
    advert_int 3
    authentication {
        auth_type PASS
        auth_pass havip2
    }
    virtual_ipaddress {
        10.100.12.84 dev eth0 label eth0:havip2
    }
    unicast_src_ip 10.100.12.144
    unicast_peer {
            10.100.12.60
    }
}

**Comment by pqarmitage** [comment] 2020-11-06 12:46
The strace output appears to show that the data being passed in the sendmsg() call is all valid. From some tests I have done it doesn't produce an error if the unicast_src_ip is deleted, so that isn't the problem.

You state that the problem only occurs with v1, and that v2 doesn't have a problem. I am guessing that 10.100.12.144 is master for v1 and backup for v2, and that 10.100.12.60 is backup for v1 and master for v2. Is that correct? If that is the case, then v2 doesn't have the problem because it is only occurring on 10.100.12.144 and not on 10.100.12.60.

Is there anything in the system log around the time of the `Invalid argument` messages?

At the moment I cannot reproduce the problem, so I can't see what is causing it.

**Comment by snailq** [comment] 2020-11-11 02:53
thank you for your reply！
1.`that 10.100.12.60 is backup for v1 and master for v2. Is that correct?` Yes.
2.ʻIs there anything in the system log around the time of the Invalid argument messages?` The system does not have any other log.
In addition, my monitoring found that every time a problem occurs, the system has tcp timeout,`TcpExt.TCPTimeouts
` `TcpExt.TCPAbortOnTimeout`,but not much
My keepalived is used for intranet NAT traffic, and load traffic is split by default route to two VIPs. I found that when all traffic goes to one server, at peak times, both VIPs will report `nvalid argument`
I did the optimization of the related kernel parameters, but still did not solve the problem

Kernel parameter:
`net.core.rmem_default = 536870912
net.core.wmem_default = 536870912
net.core.rmem_max = 536870912
net.core.wmem_max = 536870912
net.ipv4.tcp_wmem = 40960 873800 268435456
net.ipv4.tcp_rmem = 40960 655360 268435456
net.ipv4.tcp_max_tw_buckets = 55000
net.ipv4.tcp_congestion_control=htcp
net.core.default_qdisc=fq
net.netfilter.nf_conntrack_max = 4194304
net.netfilter.nf_conntrack_tcp_timeout_fin_wait = 30
net.netfilter.nf_conntrack_tcp_timeout_time_wait = 30
net.netfilter.nf_conntrack_tcp_timeout_established = 3600
net.netfilter.nf_conntrack_tcp_timeout_close_wait = 15
net.netfilter.nf_conntrack_tcp_timeout_syn_sent = 30
`

**Comment by snailq** [comment] 2020-11-11 02:54
> The strace output appears to show that the data being passed in the sendmsg() call is all valid. From some tests I have done it doesn't produce an error if the unicast_src_ip is deleted, so that isn't the problem.
> 
> You state that the problem only occurs with v1, and that v2 doesn't have a problem. I am guessing that 10.100.12.144 is master for v1 and backup for v2, and that 10.100.12.60 is backup for v1 and master for v2. Is that correct? If that is the case, then v2 doesn't have the problem because it is only occurring on 10.100.12.144 and not on 10.100.12.60.
> 
> Is there anything in the system log around the time of the `Invalid argument` messages?
> 
> At the moment I cannot reproduce the problem, so I can't see what is causing it.

**Comment by snailq** [comment] 2020-11-11 02:54
> The strace output appears to show that the data being passed in the sendmsg() call is all valid. From some tests I have done it doesn't produce an error if the unicast_src_ip is deleted, so that isn't the problem.
> 
> You state that the problem only occurs with v1, and that v2 doesn't have a problem. I am guessing that 10.100.12.144 is master for v1 and backup for v2, and that 10.100.12.60 is backup for v1 and master for v2. Is that correct? If that is the case, then v2 doesn't have the problem because it is only occurring on 10.100.12.144 and not on 10.100.12.60.
> 
> Is there anything in the system log around the time of the `Invalid argument` messages?
> 
> At the moment I cannot reproduce the problem, so I can't see what is causing it.

thank you for your reply！
1.`that 10.100.12.60 is backup for v1 and master for v2. Is that correct?` Yes.
2.ʻIs there anything in the system log around the time of the Invalid argument messages?` The system does not have any other log.
In addition, my monitoring found that every time a problem occurs, the system has tcp timeout,`TcpExt.TCPTimeouts
` `TcpExt.TCPAbortOnTimeout`,but not much
My keepalived is used for intranet NAT traffic, and load traffic is split by default route to two VIPs. I found that when all traffic goes to one server, at peak times, both VIPs will report `nvalid argument`
I did the optimization of the related kernel parameters, but still did not solve the problem

Kernel parameter:
`net.core.rmem_default = 536870912
net.core.wmem_default = 536870912
net.core.rmem_max = 536870912
net.core.wmem_max = 536870912
net.ipv4.tcp_wmem = 40960 873800 268435456
net.ipv4.tcp_rmem = 40960 655360 268435456
net.ipv4.tcp_max_tw_buckets = 55000
net.ipv4.tcp_congestion_control=htcp
net.core.default_qdisc=fq
net.netfilter.nf_conntrack_max = 4194304
net.netfilter.nf_conntrack_tcp_timeout_fin_wait = 30
net.netfilter.nf_conntrack_tcp_timeout_time_wait = 30
net.netfilter.nf_conntrack_tcp_timeout_established = 3600
net.netfilter.nf_conntrack_tcp_timeout_close_wait = 15
net.netfilter.nf_conntrack_tcp_timeout_syn_sent = 30
`

**Comment by pqarmitage** [comment] 2020-11-14 14:51
You state:
> In addition, my monitoring found that every time a problem occurs, the system has tcp timeout,TcpExt.TCPTimeouts TcpExt.TCPAbortOnTimeout,but not much

This suggests that this is a problem in your network stack rather than a problem with keepalived. With the configuration you have provided keepalived does not use TCP.

**Comment by pqarmitage** [comment] 2020-12-05 09:39
Closing due to no update for 3 weeks. If your problems persist please update this issue and it can be reopened if necessary.

**Closed by pqarmitage** 2020-12-05 09:39 UTC
