### ISSUE TITLE
Keepalived: External VIP(eth1) is not released by stand by VM when keepalived is stopped

### ISSUE THREAD

**Issue by anilkps199** [acassen/keepalived#1205] opened 2019-04-08 11:10 UTC
Hi All,

I ran into an issue with keepalived. 

We have a two rhel7 VMs deployed in Openstack where One VM act as Master and other as backup.

We use keepalived for achieving HA of our application.
We have VIPs configured for both internal(eth0) and external(eth1) interfaces.

We found a strange intermittent issue with VIP assignment while fail over.

During fail over, External VIP is not released by Backup VM and internal VIP is assigned to master VM as expected.
External VIP is 131.160.205.240
Internal VIP is 172.16.100.33

You can see it in below interface details
Server1(standby): ip a s
---------------------------------------------------------
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast state UP qlen 1000
    link/ether fa:16:3e:a3:3a:52 brd ff:ff:ff:ff:ff:ff
    inet 172.16.100.36/24 brd 172.16.100.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:fea3:3a52/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether fa:16:3e:54:8f:f7 brd ff:ff:ff:ff:ff:ff
    inet 131.160.205.242/25 brd 131.160.205.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet 131.160.205.240/32 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:fe54:8ff7/64 scope link
       valid_lft forever preferred_lft forever

Server2(Master): ip a s
---------------------------------------------------------
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast state UP qlen 1000
    link/ether fa:16:3e:47:0c:ea brd ff:ff:ff:ff:ff:ff
    inet 172.16.100.35/24 brd 172.16.100.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.100.33/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:fe47:cea/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether fa:16:3e:d0:32:00 brd ff:ff:ff:ff:ff:ff
    inet 131.160.205.241/25 brd 131.160.205.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:fed0:3200/64 scope link
       valid_lft forever preferred_lft forever

**keepalived configuration of both VMs:**
Server 1: keepalived.conf  is as shown blow
---------------------------------------------------
! Configuration File for keepalived

vrrp_script svc_health_chk {
  script "/opt/myApp/bin/_healthcheck.sh 'KEEPALIVED'"
  interval 40
  fall 2
}

vrrp_instance SVC_EXT {
    state BACKUP
    interface eth1
    virtual_router_id 113
    vrrp_garp_master_delay 10
    vrrp_garp_interval 0.001
    vrrp_garp_master_repeat 100
    priority 99
    nopreempt
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    unicast_src_ip  131.160.205.242
    unicast_peer {
        131.160.205.241
    }
    virtual_ipaddress {
       131.160.205.240
    }
    track_script {
        svc_health_chk
    }
    notify_master  /opt/myApp/bin/configure_master.sh
    notify_backup /opt/myApp/bin/configure_standby.sh
    notify_fault /opt/myApp/bin/configure_fault.sh
}

vrrp_instance SVC_INT {
    state BACKUP
    interface eth0
    virtual_router_id 113
    vrrp_garp_master_delay 10
    vrrp_garp_interval 0.001
    vrrp_garp_master_repeat 100
    priority 99
    nopreempt
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    unicast_src_ip  172.16.100.36
    unicast_peer {
        172.16.100.35
    }
    virtual_ipaddress {
       172.16.100.33
    }
    track_script {
        svc_health_chk
    }
    notify_master  /opt/myApp/bin/configure_master.sh
    notify_backup /opt/myApp/bin/configure_standby.sh
    notify_fault /opt/myApp/bin/configure_fault.sh
}

Server 2: keepalived.conf is as shown blow
-------------------------------------------------------
! Configuration File for keepalived

vrrp_script svc_health_chk {
  script "/opt/myApp/bin/svc_healthcheck.sh 'KEEPALIVED'"
  interval 40
  fall 2
}

vrrp_instance SVC_EXT {
    state BACKUP
    interface eth1
    virtual_router_id 113
    vrrp_garp_master_delay 10
    vrrp_garp_interval 0.001
    vrrp_garp_master_repeat 100
    priority 99
    nopreempt
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    unicast_src_ip  131.160.205.241
    unicast_peer {
        131.160.205.242
    }
    virtual_ipaddress {
       131.160.205.240
    }
    track_script {
        svc_health_chk
    }
    notify_master  /opt/myApp/bin/configure_svc_master.sh
    notify_backup /opt/myApp/bin/configure_svc_standby.sh
    notify_fault /opt/myApp/bin/configure_svc_fault.sh
}

vrrp_instance SVC_INT {
    state BACKUP
    interface eth0
    virtual_router_id 113
    vrrp_garp_master_delay 10
    vrrp_garp_interval 0.001
    vrrp_garp_master_repeat 100
    priority 99
    nopreempt
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    unicast_src_ip  172.16.100.35
    unicast_peer {
        172.16.100.36
    }
    virtual_ipaddress {
       172.16.100.33
    }
    track_script {
        svc_health_chk
    }
    notify_master  /opt/myApp/bin/configure_svc_master.sh
    notify_backup /opt/myApp/bin/configure_svc_standby.sh
    notify_fault /opt/myApp/bin/configure_svc_fault.sh
}

Any help here is appreciated.

Regards,
Anil

**Comment by pqarmitage** [comment] 2019-04-09 10:29
What you have shown looks as though SVC_EXT master is on Server1 and SVC_INT master is on Server2. The main problem is that the VRRP instances have the same priorities on both servers, and so it is indeterminate which will be master and which will be backup. There are a couple of changes you can (should) make to stop this happening.

1. Configure the server you want generally to be master to have higher priorities on its vrrp instances than the backup.
2. Do you need `nopreempt`? This means that once a vrrp instance takes over as master, then it will remain master despite a higher priority instance being available. This will increase the risk of one vrrp instance being master and the other instance being backup on the same server.
3. Configure a vrrp_sync group:
```
vrrp_sync_group SG1 {
    group {
        SVC_INT
        SVC_EXT
    }
}
```
This means that the two vrrp instances will always be in the same state, either both master or both backup, which is what you appear to need for your configuration to work.

As an aside, your configuration is causing a very high number of GARP messages to be sent after a transition to master. Nowadays, unless you have some very defective switches in your network, it shouldn't be necessary to send more than 1 GARP message after transition to master. I woud use the following, unless you know your environment has a problem with very high loss of GARP messages (possibly caused by keepalived being configured to send so many):
```
vrrp_garp_master_delay 0
vrrp_garp_master_repeat 1
```
This will cause just one GARP message to be sent after transition to master.

**Comment by anilkps199** [comment] 2019-04-10 06:36
Hi @pqarmitage 

Thanks for the quick info.

1.Even we require  priorities are same.
2."nopreempt" is required in our case.
3.Can  sync_grp be configured along with the notify scripts ?

Without any election, could see that it's receiving the high prio advt(Note : on both configurations prio are set to same)

**Just some logs :** 
Apr 10 11:30:10 saji_5_4_32-vnflaf-services-0 Keepalived_vrrp[5660]: VRRP_Instance(SVC_EXT) Transition to MASTER STATE
Apr 10 11:30:10 saji_5_4_32-vnflaf-services-0 Keepalived_vrrp[5660]: VRRP_Instance(SVC_INT) Transition to MASTER STATE
Apr 10 11:30:11 saji_5_4_32-vnflaf-services-0 Keepalived_vrrp[5660]: VRRP_Instance(SVC_EXT) Entering MASTER STATE
Apr 10 11:30:11 saji_5_4_32-vnflaf-services-0 Keepalived_vrrp[5660]: VRRP_Instance(SVC_EXT) setting protocol VIPs.
Apr 10 11:30:11 saji_5_4_32-vnflaf-services-0 Keepalived_vrrp[5660]: VRRP_Instance(SVC_EXT) Sending gratuitous ARPs on eth1 for 131.160.205.240
Apr 10 11:30:11 saji_5_4_32-vnflaf-services-0 Keepalived_vrrp[5660]: VRRP_Instance(SVC_INT) Entering MASTER STATE
Apr 10 11:30:11 saji_5_4_32-vnflaf-services-0 Keepalived_vrrp[5660]: VRRP_Instance(SVC_INT) setting protocol VIPs.
Apr 10 11:30:11 saji_5_4_32-vnflaf-services-0 Keepalived_vrrp[5660]: VRRP_Instance(SVC_INT) Sending gratuitous ARPs on eth0 for 172.16.100.33
Apr 10 11:30:16 saji_5_4_32-vnflaf-services-0 Keepalived_vrrp[5660]: VRRP_Instance(SVC_EXT) Sending gratuitous ARPs on eth1 for 131.160.205.240
Apr 10 11:30:16 saji_5_4_32-vnflaf-services-0 Keepalived_vrrp[5660]: VRRP_Instance(SVC_INT) Sending gratuitous ARPs on eth0 for 172.16.100.33
**Apr 10 11:36:48 saji_5_4_32-vnflaf-services-0 Keepalived_vrrp[5660]: VRRP_Instance(SVC_EXT) Received higher prio advert**
Apr 10 11:36:48 saji_5_4_32-vnflaf-services-0 Keepalived_vrrp[5660]: VRRP_Instance(SVC_EXT) Entering BACKUP STATE
Apr 10 11:36:48 saji_5_4_32-vnflaf-services-0 Keepalived_vrrp[5660]: VRRP_Instance(SVC_EXT) removing protocol VIPs

**Comment by pqarmitage** [comment] 2019-04-10 08:25
If you would like us to be able you, you will need to provide more information about what you are trying to achieve operationally, so that we can understand why, for example, you state that you need the priorities to be the same. It is clear that the configuration you have provided above cannot work properly, but without knowing how you want to operate, we are not able to suggests what needs to be changed in your configuration.

Could you please also provide the output of `keepalived -v`, so that we knwo the keepalived setup you are running.

**Comment by anilkps199** [comment] 2019-04-10 11:13
keepalived -v
Keepalived v1.2.13 (06/25,2015)

**Comment by anilkps199** [comment] 2019-04-10 11:18
On observation know could see that , external vip(131.160.205.240) as stated in the above configuration was released and switched to the Backup node, but  when the previous Master vm is back vip is falling back again.
But the internal VIP(172.16.100.33) is not falling back even when the previous master is back.
**It is clear that the configuration you have provided above cannot work properly, but without knowing how you want to operate, we are not able to suggests what needs to be changed in your configuration.**
Please suggest what is wrong with the configuration.

**Comment by pqarmitage** [comment] 2019-04-10 12:29
@anilkps199 

I would say that there are two things wrong with your configuration:
1. You are using the same priorities for the same vrrp instances on server1 as on server2.
2. You are not using vrrp_sync_groups.

However, without knowing exactly what you are wanting to achieve, it isn't possible to be categorical about this.

You are also using an extremely old version of keepalived, and there have been very many bug fixes since v1.2.13. It is strongly recommended that you upgrade to version 2.0.15, even if you have to build it yourself.

**Comment by anilkps199** [comment] 2019-04-11 10:06
Hi @pqarmitage 

Even after changing the priorities , could see that nopreempt is not honoured and vip is falling back to previous master when it is up.
We require the notify/track scripts to be run and sync group is not supported with this configuration

**Comment by pqarmitage** [comment] 2019-04-11 12:22
> Even after changing the priorities , could see that nopreempt is not honoured and vip is falling back to previous master when it is up.

If nopreempt is not working, then you need to upgrade to the current version of keepalived. If you still have the problem, then it can be investigated.

> We require the notify/track scripts to be run and sync group is not supported with this configuration

There should be no issue with notify or track scripts when you are using sync groups. Again, if you are experiencing a problem with that then you need to upgrade to the current version of keepalived.

We are not aware of any issues in recent versions of keepalived in relation to the problems you are experiencing.

**Comment by acassen** [comment] 2019-04-11 12:26
1.2.13 is really way too old. we really strongly encourage you to upgrade. We are not backporting fix, Keepalived devel circle is allways forward. Code in master branch is not bleeding-edge, it is STABLE release widely use now. And if there are some issues with it we are happy to investigate and fix.

**Comment by pqarmitage** [comment] 2019-04-25 10:59
Closing due to no update for over 2 weeks. If you still have the issue with a current version of keepalived please provide further details in this issue report and it can be reopened.

**Closed by pqarmitage** 2019-04-25 10:59 UTC
