### ISSUE TITLE
2.0.7 SIGSEGV on startup

### ISSUE THREAD

**Issue by growler** [acassen/keepalived#1025] opened 2018-10-04 06:12 UTC
```
Opening file '/etc/firewall/keepalived.conf'.
(ha_router_ip) State MASTER must match being address owner
Registering gratuitous ARP shared channel
iptables command not available - can't filter IPv4 VIP address destinations
(ha_router_ip) Entering BACKUP STATE (init)
(ha_router_ip) Entering MASTER STATE
(ha_router_ip) using locally configured advertisement interval (1000 milli-sec)
Keepalived_vrrp exited due to segmentation fault (SIGSEGV).
  Please report a bug at https://github.com/acassen/keepalived/issues
  and include this log from when keepalived started, a description
  of what happened before the crash, your configuration file and the details below.
  Also provide the output of keepalived -v, what Linux distro and version
  you are running on, and whether keepalived is being run in a container or VM.
  A failure to provide all this information may mean the crash cannot be investigated.
  If you are able to provide a stack backtrace with gdb that would really help.
  Source version 2.0.7
  Built with kernel headers for Linux 4.17.6
  Running on Linux 4.18.0-0.bpo.1-amd64 #1 SMP Debian 4.18.6-1~bpo9+1 (2018-09-13)
  Command line: '/usr/sbin/keepalived' '-l' '-n' '-i' 'master' '-f' '/etc/firewall/keepalived.conf'
  configure options: --enable-vrrp --disable-lvs --enable-sha1 --enable-snmp-vrrp --prefix=/usr
                     --sysconfdir=/etc --mandir=/usr/share/man --localstatedir=/var
                     --with-kernel-dir=/usr/include/linux
  Config options: VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_VRRP
  System options: PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES
                  RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID
                  RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE
                  RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE
                  FRA_DPORT_RANGE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA
                  NETINET_LINUX_IF_ETHER_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION VRRP_VMAC
                  SOCK_NONBLOCK SOCK_CLOEXEC O_PATH INET6_ADDR_GEN_MODE SO_MARK SCHED_RT
                  SCHED_RESET_ON_FORK
VRRP child process(14) died: Respawning
```

Configuration:

```
global_defs {

@master router_id firewall-main
@backup router_id firewall-backup

        vrrp_version 3
        vrrp_strict

        enable_script_security
        script_user root

}

static_ipaddress {
@master A.A.A.251/24 dev eth0 scope global
@backup A.A.A.252/24 dev eth0 scope global
}

vrrp_instance ha_router_ip {
        interface eth0

@master mcast_src_ip A.A.A.251/24
@backup mcast_src_ip A.A.A.252/24

@master state MASTER
@backup state BACKUP
@master priority 200
@backup priority 100

        virtual_router_id 14
        virtual_ipaddress {
            A.A.A.253/24 dev eth0
            B.B.B.254/24 dev eth1
            C.C.C.240/24 dev eth2
        }
        virtual_routes {
            default via C.C.C.254 dev eth2
        }
        notify /etc/notify-keepalive-state
}
```

I'm running keepalived in a container with no IP addresses assigned, so I'm trying to make keepalive first setup static_ipaddress and then use it. If I set ip addresses before starting keepalived, it works fine. If I remove mcast_src_ip, keepalived doesn't crash, but immediately transit into FAIL mode due to ip addresses absent. There might be some race here since IP addresses are assigned by keepalived, but probably after vrrp_instance starts. I guess there is some configuration option for synchronisation but I failed to find one.

**Comment by pqarmitage** [comment] 2018-10-04 09:32
I've just pushed a commit which for me resolves the problem. The backtrace you have provided shows that what I observed is the same problem as you have. The issue is when the default route is added. The RTM_NEWLINK message does not have a RTA_DST field for a default route, but the code was expecting there always to be an RTA_DST. The clue is in the address 0x4 passed as addr1 to compare_addr().

**Comment by pqarmitage** [comment] 2018-10-04 09:34
The reason it works fine after keepalived is respawned is that the default route, which was added during the first time keepalived ran, is still configured, and so when keepalived attempts to add it when it is respawned, since the route exists, no RTM_NEWLINK message is sent to keepalived.

I'll merge the commit once the Travis-CI builds have completed.

**Comment by growler** [comment] 2018-10-04 09:38
wow, that was quick
thank you!

**Comment by pqarmitage** [comment] 2018-10-04 09:39
Commit 069a039 is now merged and should resolve the problem.

**Closed by pqarmitage** 2018-10-04 09:39 UTC

**Comment by growler** [comment] 2018-10-04 10:14
works like a charm, thank you!
