### ISSUE TITLE
/usr/bin/killall -0 haproxy track scripts fails with "no process found"

### ISSUE THREAD

**Issue by johannbg** [acassen/keepalived#1420] opened 2019-11-05 10:10 UTC
Fedora/Kernel 5.3.8-300.fc31.x86_64/keepalived-2.0.18-2.fc31.x86_64...

When testing the haproxy track script it always exits with "no process found" ( on Fedora31 anyway ) which kinda makes that test useless since keepalived will never notice the failed state of haproxy thus never change state when haproxy is down. 

This can be easily duplicate via "sudo -u haproxy  /usr/bin/killall -0 haproxy" which results in on affected system "haproxy: no process found" output

Now I personally I blame the kernel/cgroups for this change in behaviour since I dont have much time to track this down but ymmv 

For systemd based system much *smarter* way to check if service is running is using "systemctl is-active --quiet <service>"  command as in systemctl is-active --quiet haproxy which returns an exit code 0 if active and non-zero otherwise and I would suggest reference for track script in documentation for type services be changed to systemctl is-active --quiet <service> for linux distributions  /usr/bin/systemctl is-active --quiet <service> || <command to execute if service exist with non-zero exit code )

The following check_haproxy vrrp_script would then be recommended to look like this on a systemd based systems.

vrrp_script check_haproxy {
      script  "systemctl is-active --quiet haproxy"
      ...
}
...
track_script {
       check_haproxy
}

**Comment by pqarmitage** [comment] 2019-11-05 14:09
I think you are indicating that the script not running is a Fedora issue, not a keepalived issue; is that correct? I will try this on Fedora 31 once I have installed it.

A better way to check the state of haproxy would be to use the `track_process` feature, which is much more efficient that using a track_script, and detects a process disappearing as soon as it happens.

**Comment by pqarmitage** [comment] 2019-11-05 16:51
The error message from killall on Fedora 31 is incorrect. On Fedora 32 (Rawhide), when I try doing the same thing the error message is `haproxy(15849): Operation not permitted`, which is correct.

The problem with what you are trying to do is that the parent haproxy **process** is owned by **root**, and the haproxy **user** does not have permission to send signals to processes owned by root - see the following `ps -ef` output:
```
root       15849       1  0 15:47 ?        00:00:00 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid
haproxy    15850   15849  0 15:47 ?        00:00:03 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid
```

killall is provided by the psmisc package, which is version 23.1 on Fedora 31 and 23.2 plus some upstream patches on Fedora 32.  I have built the Fedora 32 source code for killall on Fedora31, and it then correctly reports `Operation not permitted`, so it looks like a killall issue.

**Comment by pqarmitage** [comment] 2019-11-05 16:52
BTW I have SELinux in enforcing mode, so it appears not to be related to that.

**Comment by johannbg** [comment] 2019-11-05 17:00
killall/permission issue which you dont have with systemctl is-active --quiet <service>

**Comment by pqarmitage** [comment] 2019-11-05 20:13
I have filed a bug against Fedora at https://bugzilla.redhat.com/show_bug.cgi?id=1768993

If you want to use killall then you need to upgrade the psmisc package to v23.2 or later.

**Comment by johannbg** [comment] 2019-11-05 20:25
Just one note before we close this is it to be expected that observed difference in track process vs track script in which using track process does not result in keepalive entering BACKUP STATE while the track script does once the haproxy went back online?

**Comment by pqarmitage** [comment] 2019-11-05 20:28
track_process should behave in a similar way to your track_scripts, and the vrrp instance should transition to backup state if the process is running. I am looking at the problem now, and will update this issue once I have more information. I would like to keep this issue open until I have resolved the problem.

**Comment by pqarmitage** [comment] 2019-11-07 00:24
Using the following configuration:
```
vrrp_track_process haproxy {
process haproxy
quorum 1
delay 2
}

vrrp_instance VI_1 {
    interface eth0
    state BACKUP
    virtual_router_id 253
    version 3
    priority 240
    advert_int 1
    use_vmac
    virtual_ipaddress {
      10.2.0.100/32
      10.2.0.101/32
    }
    track_process {
	haproxy
    }
}
```
this is working exactly as I would expect. `systemctl stop haproxy` makes the vrrp instance go to fault state after a two second delay, and `systemctl start haproxy` makes the vrrp instance go to backup state immediately.

**Comment by johannbg** [comment] 2019-11-07 06:21
Hmm maybe the difference is that I have two v1 ipv4 and v2 ipv6 I'll test that to see if I can trigger it. I rewrote the spec file in fedora and yesterday and submitted it which enabled nftables and update the component latest release then finally the rh employee woke up and update the component so I test on .18 and .19 to see if this has been fixed already aswell as nftables

**Comment by johannbg** [comment] 2019-11-07 08:21
Can trigger this just with ipv4 ( VI1_ ) using this config

global_defs {
   vrrp_version 3
   enable_script_security
   script_user haproxy
   notification_email {
        lbadm@foo.com
   }

   notification_email_from instance@foo.com
   smtp_server 127.0.0.1
   smtp_connect_timeout 30
   router_id LBCL01

}

vrrp_track_process haproxy {
  process haproxy
  quorum 1
  delay 2
}

vrrp_instance VI_1 {
    interface enp6s0
    virtual_router_id 50
    garp_master_delay 5
    priority 249
    advert_int 5
    use_vmac

    virtual_ipaddress {
        IPv4-Address dev enp6s0 # test01
        IPv4-Address dev enp6s0 # test02
        IPv4-Address dev enp6s0 # test03
        IPv4-Address dev enp6s0 # test04
    }

    track_process {
      haproxy
    }

    nopreempt
}

**Comment by pqarmitage** [comment] 2019-11-07 08:33
Can you please provide a copy of the logs showing the problem occurring.

**Comment by johannbg** [comment] 2019-11-07 08:41
Nov 07 08:14:14  systemd[1]: Starting LVS and VRRP High Availability Monitor...
Nov 07 08:14:14  Keepalived[45859]: Starting Keepalived v2.0.18 (07/26,2019)
Nov 07 08:14:14  Keepalived[45859]: Running on Linux 5.3.8-300.fc31.x86_64 #1 SMP Tue Oct 29 14:28:41 UTC 2019 (built for Linux 5.3.0)
Nov 07 08:14:14  Keepalived[45859]: Command line: '/usr/sbin/keepalived' '-D'
Nov 07 08:14:14  Keepalived[45859]: Opening file '/etc/keepalived/keepalived.conf'.
Nov 07 08:14:14  systemd[1]: keepalived.service: Can't open PID file /run/keepalived.pid (yet?) after start: No such file or directory
Nov 07 08:14:14  Keepalived[45860]: Starting VRRP child process, pid=45861
Nov 07 08:14:14  Keepalived_vrrp[45861]: Registering Kernel netlink reflector
Nov 07 08:14:14  Keepalived_vrrp[45861]: Registering Kernel netlink command channel
Nov 07 08:14:14  Keepalived_vrrp[45861]: Opening file '/etc/keepalived/keepalived.conf'.
Nov 07 08:14:14  Keepalived_vrrp[45861]: Assigned address 193.4.58.198 for interface enp6s0
Nov 07 08:14:14  systemd[1]: Started LVS and VRRP High Availability Monitor.
Nov 07 08:14:15  Keepalived_vrrp[45861]: (VI_1): Success creating VMAC interface vrrp.50
Nov 07 08:14:15  Keepalived_vrrp[45861]: NOTICE: setting sysctl net.ipv4.conf.default.rp_filter from 0 to 1
Nov 07 08:14:15  Keepalived_vrrp[45861]: NOTICE: setting sysctl net.ipv4.conf.all.rp_filter from 1 to 0
Nov 07 08:14:15  systemd-networkd[417]: vrrp.50: Gained carrier
Nov 07 08:14:15  Keepalived_vrrp[45861]: Registering gratuitous ARP shared channel
Nov 07 08:14:15  Keepalived_vrrp[45861]: (VI_1) Entering BACKUP STATE (init)
Nov 07 08:14:15  Keepalived_vrrp[45861]: VRRP sockpool: [ifindex(28), family(IPv4), proto(112), unicast(0), fd(11,12)]
Nov 07 08:14:15  systemd-udevd[45858]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Nov 07 08:14:15  systemd-udevd[45858]: Using default interface naming scheme 'v243'.
Nov 07 08:14:33  haproxy[45852]: [WARNING] 310/081433 (45852) : Exiting Master process...
Nov 07 08:14:33  haproxy[45852]: [ALERT] 310/081433 (45852) : Current worker #1 (45853) exited with code 143 (Terminated)
Nov 07 08:14:33  haproxy[45852]: [WARNING] 310/081433 (45852) : All workers exited. Exiting... (0) 
Nov 07 08:14:33  systemd[1]: Stopping HAProxy Load Balancer...
Nov 07 08:14:33  systemd[1]: haproxy.service: Succeeded.
Nov 07 08:14:33  systemd[1]: Stopped HAProxy Load Balancer.
Nov 07 08:14:35  Keepalived_vrrp[45861]: Quorum lost for tracked process haproxy
Nov 07 08:14:35  Keepalived_vrrp[45861]: (VI_1) Entering FAULT STATE
Nov 07 08:14:52  systemd[1]: Starting HAProxy Load Balancer...
Nov 07 08:14:52  haproxy[45871]: Available polling systems :
Nov 07 08:14:52  haproxy[45871]:       epoll : pref=300,  test result OK
Nov 07 08:14:52  haproxy[45871]:        poll : pref=200,  test result OK
Nov 07 08:14:52  haproxy[45871]:      select : pref=150,  test result FAILED
Nov 07 08:14:52  haproxy[45871]: Total: 3 (2 usable), will use epoll.
Nov 07 08:14:52  haproxy[45871]: Available filters :
Nov 07 08:14:52  haproxy[45871]:         [SPOE] spoe
Nov 07 08:14:52  haproxy[45871]:         [COMP] compression
Nov 07 08:14:52  haproxy[45871]:         [CACHE] cache
Nov 07 08:14:52  haproxy[45871]:         [TRACE] trace
Nov 07 08:14:52  haproxy[45871]: Using epoll() as the polling mechanism.
Nov 07 08:14:52  haproxy[45871]: [NOTICE] 310/081452 (45871) : New worker #1 (45872) forked
Nov 07 08:14:52  systemd[1]: Started HAProxy Load Balancer.
Nov 07 08:14:52  haproxy[45871]: [WARNING] 310/081452 (45872) : Health check for server netdisco.isnic.is_https_backend/netdisco02 succeeded, reason: Layer4 check passed, check duration: 0ms, status: 3/3 UP. 
Nov 07 08:36:02  systemd[1]: Starting dnf makecache...
Nov 07 08:36:02  dnf[45880]: Metadata cache refreshed recently.
Nov 07 08:36:03  systemd[1]: dnf-makecache.service: Succeeded.
Nov 07 08:36:03  systemd[1]: Started dnf makecache.

**Comment by johannbg** [comment] 2019-11-07 08:47
Updated to keepalived-2.0.19-1.fc31.x86_64 and it's still present.

**Comment by pqarmitage** [comment] 2019-11-07 09:20
I have just tested this using the keepalived-2.0.18-2 rpm and haproxy-2.0.7-2, using the default haproxy configuration and your keepalived configuration, and track_process is working fine for me.

The one difference is I am not getting any of the following log messages:
```
Nov 07 08:14:52 haproxy[45871]: Available polling systems :
Nov 07 08:14:52 haproxy[45871]: epoll : pref=300, test result OK
Nov 07 08:14:52 haproxy[45871]: poll : pref=200, test result OK
Nov 07 08:14:52 haproxy[45871]: select : pref=150, test result FAILED
Nov 07 08:14:52 haproxy[45871]: Total: 3 (2 usable), will use epoll.
Nov 07 08:14:52 haproxy[45871]: Available filters :
Nov 07 08:14:52 haproxy[45871]: [SPOE] spoe
Nov 07 08:14:52 haproxy[45871]: [COMP] compression
Nov 07 08:14:52 haproxy[45871]: [CACHE] cache
Nov 07 08:14:52 haproxy[45871]: [TRACE] trace
Nov 07 08:14:52 haproxy[45871]: Using epoll() as the polling mechanism.
```
which is presumably due to your haproxy configuration being different. Could you please therefore provide a copy of your haproxy configuration.

If I still can't reproduce your problem then, we will need to try something much simpler such as tracking process `sleep` and executing `sleep 20` and see what happens.

**Comment by johannbg** [comment] 2019-11-07 09:28
It's pretty basic but since you mentioned haproxy I'm going to disable the nbproc,nbthread, cpu-map entry's which would be the only likely suspect afaikt.

`#==========================================#
#                                          #
# * * * HAProxy Global Configuration * * * # 
#                                          #   
#==========================================#

global
    log         127.0.0.1 local2
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     32768
    nbproc      1   
    nbthread    2   
    cpu-map     auto:1/1-2 0-1 
    user        haproxy
    group       haproxy
    daemon
    stats socket /var/lib/haproxy/stats user haproxy group haproxy mode 0640 level operator
    tune.bufsize 32768
    tune.ssl.default-dh-param 4096
    ssl-default-bind-ciphers EECDH+AESGCM:EDH+AESGCM
    ssl-default-bind-options ssl-min-ver TLSv1.2 ssl-max-ver TLSv1.3 no-tls-tickets
    ssl-default-server-ciphers EECDH+AESGCM:EDH+AESGCM
    ssl-default-server-options ssl-min-ver TLSv1.2 ssl-max-ver TLSv1.3 no-tls-tickets
    debug

#===========================================#
#                                           #   
# * * * HAProxy Default Configuration * * * # 
#                                           #
#===========================================#

defaults
    log         global
    mode        http
    option      httplog
    option      log-health-checks
    option      log-separate-errors
    option      dontlognull
    option      splice-auto
    option      socket-stats
    retries     3   
    option      redispatch
    maxconn     10000
    timeout     connect         5s
    timeout     client          60s 
    timeout     server          450s
#    errorfile 400 /etc/haproxy/errors/400.http
#    errorfile 403 /etc/haproxy/errors/403.http
#    errorfile 408 /etc/haproxy/errors/408.http
#    errorfile 500 /etc/haproxy/errors/500.http
#    errorfile 502 /etc/haproxy/errors/502.http
#    errorfile 503 /etc/haproxy/errors/503.http
#    errorfile 504 /etc/haproxy/errors/504.http


#===========================================#
#                                           #
# * * * * * * * * Statistic * * * * * * * * # 
#                                           #   
#===========================================#


listen stats
    bind  ipv4-address,ipv6-address
    stats enable
    stats hide-version
    stats refresh 30s 
    stats show-node
    stats auth <username>:<very secret password>
    stats uri /lb_stats
`

**Comment by johannbg** [comment] 2019-11-07 09:31
Disabling
    nbproc      1
    nbthread    2
    cpu-map     auto:1/1-2 0-1
 
Did not change anything

**Comment by johannbg** [comment] 2019-11-07 09:42
Output from "systemctl restart keepalived && sleep 20 && sleep 20" with sleep as tracking process ( the same thing happens the instance does not come back up again )

Nov 07 09:39:29  systemd[1]: Starting LVS and VRRP High Availability Monitor...
Nov 07 09:39:29  Keepalived[46575]: Starting Keepalived v2.0.19 (10/19,2019)
Nov 07 09:39:29  Keepalived[46575]: Running on Linux 5.3.8-300.fc31.x86_64 #1 SMP Tue Oct 29 14:28:41 UTC 2019 (built for Linux 5.3.6) 
Nov 07 09:39:29  Keepalived[46575]: Command line: '/usr/sbin/keepalived' '-D'
Nov 07 09:39:29  Keepalived[46575]: Opening file '/etc/keepalived/keepalived.conf'.
Nov 07 09:39:29  systemd[1]: keepalived.service: Can't open PID file /run/keepalived.pid (yet?) after start: No such file or directory
Nov 07 09:39:29  Keepalived[46576]: Starting VRRP child process, pid=46577
Nov 07 09:39:29  Keepalived_vrrp[46577]: Registering Kernel netlink reflector
Nov 07 09:39:29  Keepalived_vrrp[46577]: Registering Kernel netlink command channel
Nov 07 09:39:29  Keepalived_vrrp[46577]: Opening file '/etc/keepalived/keepalived.conf'.
Nov 07 09:39:29  Keepalived_vrrp[46577]: Assigned address ipv4-address for interface enp6s0
Nov 07 09:39:29  systemd[1]: Started LVS and VRRP High Availability Monitor.
Nov 07 09:39:29  Keepalived_vrrp[46577]: (VI_1): Success creating VMAC interface vrrp.50
Nov 07 09:39:29  Keepalived_vrrp[46577]: NOTICE: setting sysctl net.ipv4.conf.default.rp_filter from 0 to 1
Nov 07 09:39:29  Keepalived_vrrp[46577]: NOTICE: setting sysctl net.ipv4.conf.all.rp_filter from 1 to 0
Nov 07 09:39:29  systemd-networkd[417]: vrrp.50: Gained carrier
Nov 07 09:39:29  Keepalived_vrrp[46577]: Registering gratuitous ARP shared channel
Nov 07 09:39:29  Keepalived_vrrp[46577]: (VI_1) Entering BACKUP STATE (init)
Nov 07 09:39:29  Keepalived_vrrp[46577]: VRRP sockpool: [ifindex(36), family(IPv4), proto(112), unicast(0), fd(11,12)]
Nov 07 09:39:29  systemd-udevd[46573]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Nov 07 09:39:29  systemd-udevd[46573]: Using default interface naming scheme 'v243'.
Nov 07 09:39:51  Keepalived_vrrp[46577]: Quorum lost for tracked process sleep
Nov 07 09:39:51  Keepalived_vrrp[46577]: (VI_1) Entering FAULT STATE

**Comment by johannbg** [comment] 2019-11-07 09:44
I'm just going to build a fresh minimal image via mkosi and test this since this is working for you ( are you using F31 or F32 or some other distro )  and not for me ( then it's either something I'm doing or perhaps not installed or something )

**Comment by pqarmitage** [comment] 2019-11-07 09:49
I have recently being testing on an F31 VM, but I have also tested on F32 on a physical machine, and the development and initial testing is currently done on an F26 system.

**Comment by johannbg** [comment] 2019-11-07 10:11
You should upgrade F26 to the latest when you have the time ;) 
dnf update
dnf upgrade --refresh
dnf install dnf-plugin-system-upgrade
dnf system-upgrade download --releasever=31
dnf system-upgrade reboot
dnf repoquery --unsatisfied
dnf repoquery --duplicated
dnf list extras
dnf clean all

Could you pull the latest branch to your private keepalive repo I'm going to make the pull request there ( full filling what I mentioned long time ago but forgot ) with the mkosi addition which should make your life a bit easier generating images for testing keepalived on multiple disributions even  ;)

**Comment by pqarmitage** [comment] 2019-11-07 10:18
My github repo at <http://github.com/pqarmitage/keepalived> branch updates is fully up-to-date, and branch master is also now up-to-date. They should be the same as <http://github.com/acassen/keepalived>.

There is debugging support that can be enabled and turned on provide more information about what is happening with track_process, so if your latest testing doesn't work I can post details about how to use it.

**Comment by zeylos** [comment] 2019-11-07 17:55
Hi there,

I'm experimenting the same issue on Debian buster
```
root@xxx:~ # cat /etc/debian_version
10.1
root@xxx:~ # keepalived -v
Keepalived v2.0.19 (10/19,2019)
```
My configuration for this vrrp looks like that
```
vrrp_track_process chk_memcached {
  process "memcached"
  quorum 2
  delay 2
}
...
track_process {
    chk_memcached
}
```
When I down one instance, state doesn't go to FAULT, however if I reload keepalived :
```
Nov  7 18:25:49 Keepalived_vrrp[25596]: Reloading
Nov  7 18:25:49 Keepalived_vrrp[25596]: Opening file '/etc/keepalived/keepalived.conf'.
...
Nov  7 18:25:49 Keepalived_vrrp[25596]: (XXX) entering FAULT state (tracked process chk_memcached quorum not achieved)
Nov  7 18:25:49 Keepalived_vrrp[25596]: (XXX) entering FAULT state
```
Then again if I start it up again nothing happens but if I reload : 
```
Nov  7 18:26:42 Keepalived_vrrp[25596]: Reloading
Nov  7 18:26:42 Keepalived_vrrp[25596]: Opening file '/etc/keepalived/keepalived.conf'.
...
Nov  7 18:26:42 Keepalived_vrrp[25596]: (XXX) Entering BACKUP STATE (init)
```
I may provide more debug if you teach me how to do so.

Regards,

**Comment by pqarmitage** [comment] 2019-11-07 18:51
When using debug options I find it much easier to make keepalived log to files rather than syslog. To enable this option, add the `--enable-log-file` option when running configure.

The build with track_process debugging run configure with the `--enable-track-process-debug` option as well, and then rebuild keepalived. Then, when you run keepalived, add the `--debug=Ov` command line option to enable track_process logging in the vrrp process, and add the `-g/tmp/keepalived.log -G --flush-log-file` command line options to log to /tmp/keepalived*.log (separate files for the parent process and the vrrp, checker and bfd child processes), not to write to syslog (`-G` option), and (optionally) `--flush-log-file` to ensure that log entries aren't buffered.

The above will log all received process events to the /tmp/keepalived_vrrp.log file. It may be necessary to add some more debugging in the check_process() function in keepalived/core/track_process.c to log what is read from /proc/PID/cmdline and /proc/PID/comm. With the configuration above, it will be the comm entries that are of interest, rather than the cmdline entries.

**Comment by pqarmitage** [comment] 2019-11-08 09:46
@zeylos Could you please provide the full output of `keepalived -v` so that I can see what system and configure options you have. I can then ensure that my setup is the same as yours.

I have installed Debian Buster, built the latest keepalived and using the configuration above at https://github.com/acassen/keepalived/issues/1420#issuecomment-550973789 (albeit using sleep rather than memcached) it works for me as expected.

Could you please try replacing the line
`process "memcached"`
with
`process sleep`
and see what happens when you run a could of sleep processes from the command line. It that works as expected, then we will know we need to look more closely at what memcached is doing, otherwise we will need to investigate the differences between my setup and yours.

**Comment by zeylos** [comment] 2019-11-08 09:49
@pqarmitage Sorry didn't have time to debug just yet, just a quick reply for the `keepalived -v`
```
Keepalived v2.0.19 (10/19,2019)

Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.19.67
Running on Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20)

configure options: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fdebug-prefix-map=/keepalived=. -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-z,relro CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2

Config options:  LIBIPTC LIBIPSET_DYNAMIC NFTABLES LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK
```

I'll test the sleeps this afternoon.

**Comment by zeylos** [comment] 2019-11-08 14:08
@pqarmitage Exactly the same thing is happening with sleep process.
```
vrrp_track_process sleep {
   process "sleep"
   quorum 1
   delay 2
}
vrrp_instance TST {
    state BACKUP
    interface ens18
    virtual_router_id 162
    priority 100
    advert_int 1
    virtual_ipaddress {
        ip.ip.ip.ip dev ens18 label ens18_test
    }
    track_process {
       sleep
    }
}
```
I tried :
- `sleep 10` then reload :
```
Nov 08 15:04:58 emzprdbdd03 Keepalived_vrrp[25596]: (TST) Entering BACKUP STATE (init)
Nov 08 15:05:02 emzprdbdd03 Keepalived_vrrp[25596]: (TST) Entering MASTER STATE
```
Not going in fault state after the sleep
- reload, then `sleep 10` :
```
Nov 08 15:04:05 emzprdbdd03 Keepalived_vrrp[25596]: (TST) entering FAULT state (tracked process sleep quorum not achieved)
Nov 08 15:04:05 emzprdbdd03 Keepalived_vrrp[25596]: (TST) entering FAULT state
```
No state changes when I start the `sleep`.

**Comment by pqarmitage** [comment] 2019-11-08 14:11
The next step is to run it with track_process debugging turned on. I'm just adding some extra diagnostics which should help, and I hope to be able to push the updated code in the next half hour or so.

**Comment by pqarmitage** [comment] 2019-11-08 14:47
@zeylos I have now merge commit ea57afb which enables some more detailed diagnostics of what is happening with track-process.

Instructions for building with it are at https://github.com/acassen/keepalived/issues/1420#issuecomment-551213631. Use `--enable-log-file --enable-track-process-debug` configure options, the same as before. When running keepalived specify the following runtime options to keepalived: `--debug=Av`. The system logs of identifiers Keepalived, Keepalived_vrrp and systemd should then provide good information as to what is happening.

**Comment by zeylos** [comment] 2019-11-08 16:02
@pqarmitage well just tried on a fresh empty buster with your version, works as expected.
Also tried with the same .deb as the one that fails on the other vm, works too. Looks like the problem comes from the system, will try to deploy an even vm and see what happens.

**Comment by pqarmitage** [comment] 2019-11-08 16:11
@zeylos I'm just trying the new diagnostics on a Fedora 32 system where it has worked before and it is not working now. With both of us looking at it let's hope we manage to get to the bottom of this. :)

**Comment by zeylos** [comment] 2019-11-08 16:27
@pqarmitage well it's working too so this very virtual machine is the issue ... Gonna compile the debug version on it, didn't want to do it because some production is running on it but well, gotta debug :D.

> With both of us looking at it let's hope we manage to get to the bottom of this. :)
sure thing ^^

**Comment by pqarmitage** [comment] 2019-11-08 16:31
I have discovered the problem. If the pid is greater than 32768 then it doesn't form the filename of /proc/PID/comm or /proc/PID/cmdline correctly, and this is caused by the %hd in /proc/%hd/comm and /proc/%hd/cmdline in check_process() in keepalived/core/track_process.c.

It is only very recently that I have had a system running for any appreciable amount of time where /proc/sys/kernel/pid_max was greater than 32768 (VMs I use for testing don't stay spun up for very long, and it is only in a relatively recent version of Fedora that /proc/sys/kernel/pid_max has been increased to 4194304.

Changing the `%hd`s to %d appears to resolve the problem, but I will do a little more testing before I push a commit.

**Comment by zeylos** [comment] 2019-11-08 16:35
Doesn't seems to be the same problem here, tried with my memcacheds, pid before stop `14837`; pid after restart `26852`, still no state change.
I'm compiling the debug version right now.

**Comment by zeylos** [comment] 2019-11-08 16:52
Ok so i compiled with debug and well, it worked... So I reinstalled my previous version.
It's working too.......
(╯°□°）╯~ ┻━┻

**Comment by pqarmitage** [comment] 2019-11-08 17:07
Something else you could try is to specify `full_command` in the vrrp_track_process block. You would then need to change the `process` line to match the output of /proc/PID/cmdline. It might make a difference, or it might not.

**Comment by zeylos** [comment] 2019-11-08 17:19
When adding `full_command` + giving cmdline to the processline the vrrp is always in FAULT state. Also tried with sleep10, no luck either, I may be doing something wrong.
It's working on this node without  `full_command` thought, I tried on another node of the cluster and I happen to have the bug there, however I can't really play with this one because it has an important production VIP.
Pids definitly aren't my problem
```
pidof memcached
25955 3661
```
There is something going on but I can't put the finger on it ...
I'll continue my testing on Tuesday, I guess I'll report if I find something interesting.
@pqarmitage thank you A LOT for your time today, very appreciated.

**Comment by pqarmitage** [comment] 2019-11-09 10:28
@johannbg Commit 23a5b81 should fix your problem with track_process. There was a problem with PIDs > 32767, and Fedora 31 increased the pid_max value from 32768 to 4194304 (it was actually the upgrade of systemd to version 243 that made the change). I can see from your log entries above that your PIDs have exceeded 32768.

@zeylos Commit 887d2e6 adds yet more track_process debugging output, so it would be helpful if you could pull the latest code before you do more testing on Tuesday.

**Comment by pqarmitage** [comment] 2019-11-16 12:07
@zeylos For using the full_command option, changing the vrrp_track_process block to:
```
vrrp_track_process sleep {
   process /bin/sleep
   quorum 1
   delay 2
   full_command
}
```
and executing `/bin/sleep 20` works for me.

Do you still have any problems or can we close this issue now?

**Comment by zeylos** [comment] 2019-11-18 10:49
@pqarmitage Can't reproduce after re-installing, also my binaries aren't using the same libraries as on the broken one ... No idea what happened with my first install thought and I can't really reproduce the installation so I guess we can close this.
I'll report if I'm seeing the same behavior again.

Again, thanks for your time.

**Closed** 2019-11-18 11:33 UTC
