### ISSUE TITLE
Can't reuse vmac interfaces

### ISSUE THREAD

**Issue by andempsey** [acassen/keepalived#449] opened 2016-11-03 15:58 UTC
I'm not sure if this an artefact from the implementation that we use here but if you use an rfc interface and then reload the config the rfc interface wont be reused and the code will actually create a new rfc interface.
The cause of this, as far as I can see, is because the interface already exists when we try to recreate it we get an error saying the device is busy. After that we don't attach the interface to the vrrp group so when we next try to use the interface we have to create a new interface in the vrrp.N style.
I've attached a patch file with a suggested solution for comment.

Cheers,
Anthony
[refactor_vmac_add_code.txt](https://github.com/acassen/keepalived/files/569472/refactor_vmac_add_code.txt)

**Comment by pqarmitage** [comment] 2016-11-04 14:39
Anthony,

You've found a rather larger problem than is apparent at first glance, since the same VRID can be used on different interfaces (and on the same interface with both IPv4 and IPv6). This means that the `memcmp` in `netlink_link_add_vmac()` is insufficient on its own, and it also needs to check that the interface matches. However, in vrrp_complete_instance(), under the comment `/* Set a default interface name for the vmac if needed */`, it actually does rather more than the comment says, and for all VMACs, it checks if a matching VMAC interface already exists (matching meaning same MAC address i.e. address family and VRID matches, and the same underlying interface), and if so sets that as the VMAC interface for the VRRP instance. I'm about to provide a patch that will overwrite the configured VMAC name if necessary  and I've also added a check that a configured VMAC name isn't the name of an existing non-VMAC interface.

This means that in `netlink_link_add_vmac()`, 

Towards the end of the reload process, clear_diff_vrrp() seeks to delete any old vrrp instances and VMACs that are no longer used, but again the comparison is based on the VMAC name, rather than the interface, address family and VRID. This needs another patch which I'll provide

I think this whole problem will also occur if keepalived terminates abnormally, and is then restarted with a different config. Unfortunately it isn't safe in that case for keepalived to remove any VMACs with a VRRP MAC address, since they may belong to another running instance of keepalived (we are aware of people who run more than one instance, and the `instance` configuration keyword is designed to support this). However, keepalived should certainly find any matching VMACs (based on interface and MAC address) and use them, or alternatively issue a warning.

I've submitted a pull request for a couple of patches, the first of which incorporates the essence of your patch, and between the two patches I think the further issues identified above are also resolved.

I now am finding that on a reload, the IP addresses of any interfaces in master state are being lost. I get error messages like:
```
ip address 10.1.4.248/32 dev vrrp4.5, no longer exist
VRRP_Instance(VI_24) setting protocol VIPs.
Netlink: error: No such device, type=(20), seq=1478268966, pid=0
```
Do you experience a similar problem?

**Comment by pqarmitage** [comment] 2016-11-04 22:39
I've found the cause of the problem above. The comparison of address to determine that an address no exists wasn't working. I've now merged a commit to resolve it.

**Closed by pqarmitage** 2016-11-04 22:39 UTC
