### ISSUE TITLE
IVPS not initialized

### ISSUE THREAD

**Issue by juanvasquezreyes** [acassen/keepalived#1553] opened 2020-04-21 16:12 UTC
Not sure if I'm getting crazy, when I start the service using "systemctl start keepalived"
the healthchecks doesnt work getting this error "Keepalived_healthcheckers[3327]: WEB socket bind failed. Rescheduling"

But when I manually run it like this: /usr/sbin/keepalived -nldD -f /etc/keepalived/keepalived.conf
everything works perfect

So, I checked the logs and the only difference I found was that using the service I dont see the message "Initializing ipvs" as I do when I manually run it

So I'm thinking that IPVS is not being initialized when running the service, I'm using v1.3.5 keepalived version

**Comment by pqarmitage** [comment] 2020-04-21 21:50
Closing since duplicate of #1552.

**Closed by pqarmitage** 2020-04-21 21:50 UTC
