### ISSUE TITLE
Repeating "Received advert with lower priority 103, ours 104, forcing new election" 

### ISSUE THREAD

**Issue by robertitox** [acassen/keepalived#1705] opened 2020-07-29 02:59 UTC
Dear people, I have a Debian 10.4 server with keepalived 1:2.0.10-1.

The master switches to slave several times a day, and squid process is alive from some days, it never comes down.

These are the messages received at master node:

ul 27 20:18:27 proxy-master Keepalived_vrrp[2590]: (VI_1) Received advert from 172.18.88.143 with lower priority 103, ours 104, forcingnew election
Jul 27 20:55:48 proxy-master Keepalived_vrrp[2590]: (VI_1) Receivedadvert from 172.18.88.143 with lower priority 103, ours 104, forcing new election
Jul 27 21:00:59 proxy-master Keepalived_vrrp[2590]: (VI_1) Received advert from 172.18.88.143 with lower priority 103, ours 104, forcing new election

And these are the keepalived configuration at both nodes:

MASTER

global_defs {
   notification_email {
     dat@color.gob.ar
   }
   enable_script_security
   script_user root root
   notification_email_from keepalived@color.gob.ar
   smtp_server 172.18.88.14
   smtp_connect_timeout 30
   smtp_helo_name proxy-master.color.gob.ar
   }

vrrp_script chk_proxy {
      script "/usr/bin/killall -0 squid"
      interval 2
      weight 3
}

vrrp_instance VI_1 {
      interface ens32
      state MASTER
      virtual_router_id 51
      priority 101          # 101 on proxy-master, 100 on proxy-slave
      smtp_alert
      virtual_ipaddress {
           172.18.88.141
      }
      track_script {
           chk_proxy
      }
}

SLAVE

global_defs {
   notification_email {
     dat@color.gob.ar
   }
   enable_script_security
   script_user root root
   notification_email_from keepalived@color.gob.ar
   smtp_server 172.18.88.14
   smtp_connect_timeout 30
   smtp_helo_name proxy-slave.color.gob.ar
}

vrrp_script chk_proxy {
      script "/usr/bin/killall -0 squid"
      interval 2
      weight 3
}

vrrp_instance VI_1 {
      interface ens32
      state BACKUP
      virtual_router_id 51
      priority 100          # 100 on proxy-slave, 101 on proxy-master
      smtp_alert
      virtual_ipaddress {
           172.18.88.141
      }
      track_script {
           chk_proxy
      }
}

Please can you help me to find a solution? What can be the cause of my problem?

Special thanks!!!

**Comment by pqarmitage** [comment] 2020-07-29 08:57
@robertitox You state `The master switches to slave several times a day` but it appears from the log that actually the backup is switching to master state; it is only when an instance is in master state that that it can send an advert.

The more interesting logs in this case would be the logs on the backup system since the issue is, why is the backup switching to master state occasionally. This almost always is caused by a network problem and adverts sent by the master not being received by the backup instance. There have been quite a number of issues like this where users resolved the problem by changing some of their network hardware even though they had not previously been aware of a network issue.

Since the adverts have priority 103 and 104 it is evident that the chk_proxy script is succeeding, since the priorities both have the weight 3 added to them.

My first approach to diagnosing this problem would be to run tcpdump on both the master and backup systems to capture the raw VRRP traffic to a file. When you then get an occurrence of the backup instance becoming master you can look at the captured dumps to see what was happening with the adverts.

The only comment I have about your configurations is that I would use `track_process` to monitor the squid process, rather than a `track_script`. track_process is much more efficient for doing this than a track_script, and it is precisely what track_process is designed for.

**Comment by robertitox** [comment] 2020-07-29 13:00
Dear Quentin, thanks a lot for your help.

It's correct, Backup node claims to be master for any reason I don't know
at the moment....so I will use tcpdump as you said.

I'm using keepalived from Debian 10 repository and the version is old, so
do you suggest downloading the Debian testing version or installing the
newest tar.gz package??? This behaviour may be a bug from my keepalived
version???

Special thanks again!!!

**Comment by pqarmitage** [comment] 2020-07-29 14:30
I don't think your keepalived version should be the cause of the problem, but as you say v2.0.10 is quite old. The version in Debian testing appears to be v2.0.19 which isn't very recent either, so if you do upgrade version I would recommend updating to v2.1.5.

**Comment by robertitox** [comment] 2020-07-29 15:27
Thanks a lot!!!

**Comment by robertitox** [comment] 2020-08-01 02:00
Dear Quentin, I've realized that backup node switches to master between 21
hs and 23 hs everyday. Maybe a network problem as you said, and maybe a
network micro failure.

I have defined:

advert_int 3

Should I change this value to 10 in orden to avoid network micro failures?

Because advert_int is the time that backup node waits for master
notification.

Thanks a lot sgain!!!

**Comment by pqarmitage** [comment] 2020-08-01 10:12
@robertitox Strictly speaking, since you are using VRRPv2, the backup waits for (3 * advert_int + (256 - priority) / 256) seconds before taking over as master. If you change the advert_int to 10, the backup will wait for 30.8 seconds without receiving an advert before it takes over as master, and you may well find this delay too long. Further, whether increasing the advert interval (or more to the point the delay before a backup takes over as master) stops the backup becoming master while the master is still running depends on the nature of the network problem you are experiencing. However you change the advert interval it will still need only 3 consecutive missed adverts for the backup to become master.

The reality is that keepalived, or more specifically VRRP, can only work reliably if the network between the various systems running keepalived is itself reliable, and it appears that intermittent problems of a backup instance becoming master when the master is still running are quite a good way of identifying that there are network problems.

Unfortunately the only way to really resolve your issue is to resolve your network problem which is presumably something you need to do anyway. Are you able to identify anything that happens on your network between 21.00 and 23.00 hrs?

**Comment by robertitox** [comment] 2020-08-01 17:56
Dear Quentin, I understand what You Say.

So I Will try yo identify the network problem between those hours.

Thanks a lot for your useful help !!!

**Comment by Napsty** [comment] 2020-08-19 09:15
This is a very interesting finding. I experienced an issue with a Keepalived setup between two nodes in two different availability zones inside AWS Frankfurt on August 8th. 

Master logs:

```
Aug 08 21:01:15 dnsmaster Keepalived_vrrp[8947]: VRRP_Instance(VI_1) Received advert with lower priority 102, ours 103, forcing new election
Aug 08 21:01:16 dnsmaster Keepalived_vrrp[8947]: VRRP_Instance(VI_1) Received advert with lower priority 102, ours 103, forcing new election 
```

Backup logs:

```
Aug 08 21:01:16 dnsmaster2 Keepalived_vrrp[876]: VRRP_Instance(VI_1) Entering MASTER STATE
Aug 08 21:01:16 dnsmaster2 Keepalived_vrrp[876]: Opening script file /etc/keepalived/master.sh
Aug 08 21:01:16 dnsmaster2 Keepalived_vrrp[876]: VRRP_Instance(VI_1) Received advert with higher priority 103, ours 102
Aug 08 21:01:16 dnsmaster2 Keepalived_vrrp[876]: VRRP_Instance(VI_1) Entering BACKUP STATE 
```

The interesting case is that, same as @robertitox describes, the master did not switch back to MASTER. It did not even switch to BACKUP when the backup node became MASTER.
As this happened inside AWS, I have no control over the network. It is very likely that something (outage between AZs?) has happened in that particular second on August 8th.
Documented this in detail here: https://www.claudiokuenzler.com/blog/986/powerdns-master-slave-replication-stopped-working-aws-elastic-ip-gone

Is there a (config) way to make Keepalived pro-actively check the current priorities and initiate a STATE CHANGE when the master is not detected anymore? In this scenario, the instance VI_1 was running without a MASTER for 10 days.

**Comment by pqarmitage** [comment] 2020-08-19 13:33
> The interesting case is that, same as @robertitox describes, the master did not switch back to MASTER. It did not even switch to BACKUP when the backup node became MASTER.

The master node correctly remained MASTER throughout; since the advert that it received had a lower priority it discarded the advert.

>Is there a (config) way to make Keepalived pro-actively check the current priorities and initiate a STATE CHANGE when the master is not detected anymore? In this scenario, the instance VI_1 was running without a MASTER for 10 days.

I am not clear why you state that VI_1 was running without a MASTER for 10 days. From the logs you have provided dnsmaster remained the master for VI_1 throughout.

The problem that happens when a backup instance misses 3 consecutive adverts (as is presumably the case that happened at Aug 08 21:01:16) is that when it becomes master it sends gratuitous ARP messages for the VIPs, thereby causing switches etc to update their ARP caches, and so although dnsmaster2 reverted to backup state, any devices caching ARP information will retain the ARP information that dnsmaster2 sent. You don't say whether you are using VMACs or not; if you are using VMACs then this is less of an issue since the MAC address for the VIPs does not change whereas if you are not using VMACs the cached MAC address for the VIPs will be dnsmaster2's MAC address. There is still a problem even if using VMACs if switches update which interface the VMAC MAC address is on.

In order to resolve these issues I added some additional functionality to keepalived. As can be seen from the logs
>VRRP_Instance(VI_1) Received advert with higher priority 103, ours 102
VRRP_Instance(VI_1) Entering BACKUP STATE 

if a master instance (in this case dnsmaster2) receives a higher priority advert it simply reverts to being backup, but due to the gratuitous ARP messages it will have sent, the ARP caches will be wrong. Adding `vrrp_higher_prio_send_advert` to the `global_defs` section of your config will mean that dns_master will discover that there was a lower priority master, and that can trigger it to send its own gratuitious ARP messages. To make dnsmaster then send gratuitous ARP messages (so that the ARP caches are updated), you need to set `garp_lower_prio_repeat 1` (or however many ARP messages you want sent) in the VRRP instance block.

So, to sumarise:
1. Add `vrrp_higher_prio_send_advert` to the `global_defs` block, or `higher_prio_send_advert` to the VRRP instance
2. Add `garp_lower_prio_repeat 1` (or whatever value > 0 that you want) to the VRRP instance
3. Ensure that `vrrp_lower_prio_no_advert` is NOT set in `global_defs` and `lower_prio_no_advert` is NOT set on the VRRP instance.

**Comment by pqarmitage** [comment] 2020-08-19 13:34
Closing this issue now since no update regarding the original problem for over 2 weeks. If the problem still persists, please update this issue and it can be reopened if necessary.

**Closed by pqarmitage** 2020-08-19 13:34 UTC
