### ISSUE TITLE
lvs_sync_daemon with multiple vrrp instances

### ISSUE THREAD

**Issue by boudekerk** [acassen/keepalived#418] opened 2016-09-06 15:20 UTC
Hi,

we have been using a configuration with two independent vrrp_instances, something like:

```
global_defs {
...
}
vrrp_instance VI_1 {
...
    lvs_sync_daemon_interface eth1
    virtual_router_id 10
    priority 100
...
}
vrrp_instance VI_2 {
...
    lvs_sync_daemon_interface eth1
    virtual_router_id 20
    priority 50
...
}
```

These two instances need to failover independently, if everything is functioning different servers will be MASTER for different instances (the priorities are reversed on the other node, everything else is equal). In the log we currently get the message that  lvs_sync_daemon_interface is deprecated and that lvs_sync_daemon in the global config should be used.

The issue is that that setting requires us to specify a vrrp_instance, of which we have multiple.

When I tested with adding `lvs_sync_daemon eth1 VI_1`, on first glance everything seemed to work like we're used to, but somehow it doesn't feel right to specify one specific instance when there are multiple equal ones.

Could someone please clarify what the proper configuration should be here?

Thanks.

Kind regards,
Bartosz

**Comment by pqarmitage** [comment] 2016-09-27 07:27
First of all, apologies for the delay in responding.

My understanding is that the lvs_sync_daemon is a system-wide entity, so on any system there is one of:
i) No lvs sync daemon running
ii) The lvs sync daemon is running in backup mode
iii) The lvs sync daemon is running in master mode

There therefore cannot be different states for lvs sync daemon relating to different interfaces. So while your VI_1 and VI_2 vrrp instances can fail over independently, there can only be one decision for what state the lvs sync daemon should be in.

For the above reasons I decided to change the way the lvs sync daemon is configured, in an attempt to more closely mirror how the sync daemon works.

One enhancement could be that one might want a system to be sync daemon master only if both VI_1 and VI_2 are vrrp masters, but then should the other system be the complement of that, i.e. sync daemon master if either VI_1 or VI_2 is a vrrp master?

If I've got this wrong, and there can be multiple lvs sync daemons on a system in different states, and potentially on different interfaces, then let me know and I'll investigate further. The only way I can see this working, though, is if real servers can be assigned to different sync daemon instances, but I don't see any ipvsadm configuration options to support that.

**Comment by jwalzer** [comment] 2016-10-13 13:15
@pqarmitage You're right so far. The Kernel never supported more than one Instance of the Sync daemon. So the implementation of this option in the vrrp-instance has been questionable in keepalived since. I much support your chance to move this into the global config as long as the kernel isn't supporting multiple instances.

Even worse: I'm not even sure if the sync daemon is namespace-aware.

Also: Whats missing is an kernelpatch that would allow the sync-daemon to work in a mixed mode. 
- Accept new sessions via multicast like a backup-mode does
- Send out new sessions it established like master-mode does

This would enable real Active/Active setups (even with more than 2 Nodes) using Anycast.

**Comment by yctn** [comment] 2017-03-02 10:43
any news on this issue? cause if the implementation of the Sync deamon have been questionable ever since  cause im having the same issue here.

**Comment by pqarmitage** [comment] 2017-03-02 10:57
The kernel only supports one instance of the sync daemon, so there is nothing more that keepalived can do.

It would need a patch to the kernel to add the ability to support multiple sync daemons. If there is sufficient interest in that I will consider investigating its feasibility.

**Comment by yctn** [comment] 2017-03-06 11:03
@pqarmitage are you reachable on gitter/irc?

i assume there is sufficient interest in that. cause since the sync daemon only support one instance ur limited in what you can do with keepalived for example:

If i understand correctly currently it can only be master state or backups state which means oure senario is already broken now

we have 2 load balacers and 8 vips. 4 master and 4 backups in one keepalived. other keepalived is exacly the opposite. 4 master 4 backups. this way we allways have 8 vips online even if one load balacers goes offline. and regarding keepalived this works just fine. only the ipvs sync is not fully working. since the implementation of the kernel does not support this.

**Comment by pqarmitage** [comment] 2017-03-06 12:55
@yctn I'm not on gitter or irc unfortunately.

I think there might be a way of achieving what you want to do, but I haven't tested it. I also think that at the moment keepalived won't support this, but first it needs to be tested to endure that the ip_vs side works.

With ipvsadm you can setup one master daemon and one backup daemon concurrently on the same system. The sync-daemons may need to have different syncids. When you are running normally, each system would have one master and one backup. If one keepalived instance fails, and the other takes over then all the connections will be synchronised on the new master. When the failed keepalived instance restarts it will bring up a sync daemon in backup mode, and so it will learn all the connections from the master. When the previously failed instance becomes master for 4 of the vips, then the connections should already be in the ipvs connection table, and it just needs a sysnc daemon running in master mode.

Are you able to test this scenario manually? If you can and it works, then I will look at the necessary changes in keepalived. What it needs is that whenever there is a vrrp instance in backup mode it needs to run a backup sync daemon, and whenever there is an instance in master mode it needs to run a master daemon.

**Comment by yctn** [comment] 2017-03-06 15:45
@pqarmitage i think i can test this senario manualy. cause i have 2 spare loadbalacers i can use to test this. but i think im gonna need a little help testing cause i dont know how i should configure the ipvsadm in master mode or in backups mode. maby you could join gitter/irc/skype or some other chat utilitie that you would prefer. cause else this is going to get a Realy long issue.

**Comment by pqarmitage** [comment] 2017-03-06 21:23
@yctn To configure ipvs sync, you need to do the following:
On one system do:
```
ipvsadm --start-daemon master --syncid 1
ipvsadm --start-daemon backup --syncid 2
```
and on the other system:
```
ipvsadm --start-daemon backup --syncid 1
ipvsadm --start-daemon master --syncid 2
```
To stop the daemons:
```
ipvsadm --stop-daemon master
ipvsadm --stop-daemon backup
```

I hope that helps.

Re gitter/irc/skype or some other chat utility, I have never used these and I think the learning curve would just take too long. I think we're not too far aware from knowing where we want to go with this, providing the testing works OK.

**Comment by pqarmitage** [comment] 2017-03-31 23:18
@jwalzer I can confirm that ipvs is network namespace aware.

**Closed** 2019-03-26 13:04 UTC
