### ISSUE TITLE
VRRP IPv6 use_vmac disable: dont_track_primary not working

### ISSUE THREAD

**Issue by louis-oui** [acassen/keepalived#1892] opened 2021-04-15 08:26 UTC
**Describe the bug**
On VRRP IPv6  with use_vmac disabled, dont_track_primary does not work. Interface down causes FAULT state on instance and then on group.

**To Reproduce**
Machine1 ens4 <-> Machine1 ens4
Machine1 ens5 <-> Machine2 ens5

Machine 1:
```
ip -6 addr add fd00::300:3/64 dev ens4
ip -6 addr add fd00::200:3/64 dev ens5
```

Machine 2:
```
ip -6 addr add fd00::300:4/64 dev ens4
ip -6 addr add fd00::200:4/64 dev ens5
```

Both machines at the same time:
```
ifconfig ens4 up
ifconfig ens5 up
killall keepalived
sleep 2
cat>/etc/keepalived/keepalived.conf <<\EOF
global_defs
{
router_id router
dynamic_interfaces
}

vrrp_sync_group group {
group {
vrrp
vrrp2
}
}

vrrp_instance vrrp {
version 3
state BACKUP
interface ens4

garp_master_delay 5

virtual_router_id 15

priority 200
advert_int 1.0

virtual_ipaddress {
fd00::300:1/64
}

preempt_delay 0
}

vrrp_instance vrrp2 {
version 3
state BACKUP
interface ens5

garp_master_delay 5

virtual_router_id 15

priority 200
advert_int 1.0

virtual_ipaddress {
fd00::200:1/64
}
dont_track_primary
preempt_delay 0
}
EOF

ip -6 add show ens4 | grep 300:4 && sed -e 's|priority 200|priority 150|g' -i /etc/keepalived/keepalived.conf
keepalived -D
sleep 10
ip a show ens4
sleep 10
ip -6 add show ens4 | grep 300:3 && ifconfig ens5 down
sleep 2
ip a show ens4
```

**Expected behavior**
ens5 down on machine1 does not cause FAULT state on vrrp2 machine2 instance.
Virtual address remains on ens4 machine1.

**Keepalived version**
```
Keepalived v2.2.2 (04/10,2021), git commit v2.2.2-27-g475d1bd9

Copyright(C) 2001-2021 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.15.18
Running on Linux 4.15.0-123-generic #126-Ubuntu SMP Wed Oct 21 09:40:11 UTC 2020
Distro: Ubuntu 18.04 LTS

configure options: CFLAGS=-g -O0 --prefix=/usr --sysconfdir=/etc --with-extra-cflags=-I/usr/include/libnl3 --with-extra-ldflags= --disable-lvs --with-init=systemd --host=x86_64-linux-gnu hou

Config options:  VRRP VRRP_AUTH VRRP_VMAC OLD_CHKSUM_COMPAT INIT=systemd SYSTEMD_NOTIFY

System options:  VSYSLOG MEMFD_CREATE IPV4_DEVCONF RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SK

```

**Distro (please complete the following information):**
 - Name ubuntu
 - Version 18.04
 - Architecture x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
none

**Configuration file:**
see to reproduce

**Notify and track scripts**
none

**System Log entries**
machine1
```
root@ubuntu:~/keepalived# journalctl _PID=$(pgrep keepalived | tail -n1)
-- Logs begin at Fri 2020-10-23 11:17:41 UTC, end at Thu 2021-04-15 08:17:01 UTC. --
Apr 15 08:13:56 ubuntu Keepalived_vrrp[13539]: Registering Kernel netlink reflector
Apr 15 08:13:56 ubuntu Keepalived_vrrp[13539]: Registering Kernel netlink command channel
Apr 15 08:13:56 ubuntu Keepalived_vrrp[13539]: (vrrp) the first IPv6 VIP address should be link local
Apr 15 08:13:56 ubuntu Keepalived_vrrp[13539]: Assigned address fe80::e56:39ff:feb3:bd01 for interface ens4
Apr 15 08:13:56 ubuntu Keepalived_vrrp[13539]: (vrrp2) the first IPv6 VIP address should be link local
Apr 15 08:13:56 ubuntu Keepalived_vrrp[13539]: Assigned address fe80::e56:39ff:feb3:bd02 for interface ens5
Apr 15 08:13:56 ubuntu Keepalived_vrrp[13539]: Registering gratuitous NDISC shared channel
Apr 15 08:13:56 ubuntu Keepalived_vrrp[13539]: (vrrp) removing VIPs.
Apr 15 08:13:56 ubuntu Keepalived_vrrp[13539]: (vrrp2) removing VIPs.
Apr 15 08:13:56 ubuntu Keepalived_vrrp[13539]: (vrrp) Entering BACKUP STATE (init)
Apr 15 08:13:56 ubuntu Keepalived_vrrp[13539]: (vrrp2) Entering BACKUP STATE (init)
Apr 15 08:13:56 ubuntu Keepalived_vrrp[13539]: VRRP sockpool: [ifindex(  3), family(IPv6), proto(112), fd(13,14)]
Apr 15 08:13:56 ubuntu Keepalived_vrrp[13539]: VRRP sockpool: [ifindex(  4), family(IPv6), proto(112), fd(15,16)]
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: (vrrp2) Receive advertisement timeout
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: (vrrp) Receive advertisement timeout
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: (vrrp) Entering MASTER STATE
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: (vrrp) setting VIPs.
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: (vrrp) Sending/queueing Unsolicited Neighbour Adverts on ens4 for fd00::300:1
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens4 for fd00::300:1
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens4 for fd00::300:1
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens4 for fd00::300:1
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens4 for fd00::300:1
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens4 for fd00::300:1
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: VRRP_Group(group) Syncing instances to MASTER state
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: (vrrp2) Entering MASTER STATE
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: (vrrp2) setting VIPs.
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: (vrrp2) Sending/queueing Unsolicited Neighbour Adverts on ens5 for fd00::200:1
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:13:59 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:14:04 ubuntu Keepalived_vrrp[13539]: (vrrp) Sending/queueing Unsolicited Neighbour Adverts on ens4 for fd00::300:1
Apr 15 08:14:04 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens4 for fd00::300:1
Apr 15 08:14:04 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens4 for fd00::300:1
Apr 15 08:14:04 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens4 for fd00::300:1
Apr 15 08:14:04 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens4 for fd00::300:1
Apr 15 08:14:04 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens4 for fd00::300:1
Apr 15 08:14:04 ubuntu Keepalived_vrrp[13539]: (vrrp2) Sending/queueing Unsolicited Neighbour Adverts on ens5 for fd00::200:1
Apr 15 08:14:04 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:14:04 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:14:04 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:14:04 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:14:04 ubuntu Keepalived_vrrp[13539]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:14:16 ubuntu Keepalived_vrrp[13539]: Netlink reports ens5 down
Apr 15 08:14:16 ubuntu Keepalived_vrrp[13539]: Netlink reflector reports IP fd00::200:1 removed from ens5
Apr 15 08:14:16 ubuntu Keepalived_vrrp[13539]: (vrrp2) Entering BACKUP STATE
Apr 15 08:14:16 ubuntu Keepalived_vrrp[13539]: (vrrp2): send advert error 22 (Invalid argument)
Apr 15 08:14:16 ubuntu Keepalived_vrrp[13539]: (vrrp2) sent 0 priority
Apr 15 08:14:16 ubuntu Keepalived_vrrp[13539]: (vrrp2) removing VIPs.
Apr 15 08:14:16 ubuntu Keepalived_vrrp[13539]: (vrrp) Entering BACKUP STATE
Apr 15 08:14:16 ubuntu Keepalived_vrrp[13539]: (vrrp) sent 0 priority
Apr 15 08:14:16 ubuntu Keepalived_vrrp[13539]: (vrrp) removing VIPs.
Apr 15 08:14:16 ubuntu Keepalived_vrrp[13539]: Deassigned address fe80::e56:39ff:feb3:bd02 from interface ens5
Apr 15 08:14:16 ubuntu Keepalived_vrrp[13539]: (vrrp2) Entering FAULT STATE
Apr 15 08:14:16 ubuntu Keepalived_vrrp[13539]: VRRP_Group(group) Syncing instances to FAULT state
```
machine2
```
-- Logs begin at Fri 2020-10-23 11:17:41 UTC, end at Thu 2021-04-15 08:17:01 UTC. --
Apr 15 08:13:57 ubuntu Keepalived_vrrp[8092]: Registering Kernel netlink reflector
Apr 15 08:13:57 ubuntu Keepalived_vrrp[8092]: Registering Kernel netlink command channel
Apr 15 08:13:57 ubuntu Keepalived_vrrp[8092]: (vrrp) the first IPv6 VIP address should be link local
Apr 15 08:13:57 ubuntu Keepalived_vrrp[8092]: Assigned address fe80::e56:39ff:fe79:1901 for interface ens4
Apr 15 08:13:57 ubuntu Keepalived_vrrp[8092]: (vrrp2) the first IPv6 VIP address should be link local
Apr 15 08:13:57 ubuntu Keepalived_vrrp[8092]: Assigned address fe80::e56:39ff:fe79:1902 for interface ens5
Apr 15 08:13:57 ubuntu Keepalived_vrrp[8092]: Registering gratuitous NDISC shared channel
Apr 15 08:13:57 ubuntu Keepalived_vrrp[8092]: (vrrp) removing VIPs.
Apr 15 08:13:57 ubuntu Keepalived_vrrp[8092]: (vrrp2) removing VIPs.
Apr 15 08:13:57 ubuntu Keepalived_vrrp[8092]: (vrrp) Entering BACKUP STATE (init)
Apr 15 08:13:57 ubuntu Keepalived_vrrp[8092]: (vrrp2) Entering BACKUP STATE (init)
Apr 15 08:13:57 ubuntu Keepalived_vrrp[8092]: VRRP sockpool: [ifindex(  8), family(IPv6), proto(112), fd(13,14)]
Apr 15 08:13:57 ubuntu Keepalived_vrrp[8092]: VRRP sockpool: [ifindex(  9), family(IPv6), proto(112), fd(15,16)]
Apr 15 08:14:16 ubuntu Keepalived_vrrp[8092]: (vrrp) Backup received priority 0 advertisement
Apr 15 08:14:17 ubuntu Keepalived_vrrp[8092]: (vrrp) Receive advertisement timeout
Apr 15 08:14:19 ubuntu Keepalived_vrrp[8092]: (vrrp2) Receive advertisement timeout
Apr 15 08:14:19 ubuntu Keepalived_vrrp[8092]: (vrrp2) Entering MASTER STATE
Apr 15 08:14:19 ubuntu Keepalived_vrrp[8092]: (vrrp2) setting VIPs.
Apr 15 08:14:19 ubuntu Keepalived_vrrp[8092]: (vrrp2) Sending/queueing Unsolicited Neighbour Adverts on ens5 for fd00::200:1
Apr 15 08:14:19 ubuntu Keepalived_vrrp[8092]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:14:19 ubuntu Keepalived_vrrp[8092]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:14:19 ubuntu Keepalived_vrrp[8092]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:14:19 ubuntu Keepalived_vrrp[8092]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:14:19 ubuntu Keepalived_vrrp[8092]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:14:19 ubuntu Keepalived_vrrp[8092]: VRRP_Group(group) Syncing instances to MASTER state
Apr 15 08:14:19 ubuntu Keepalived_vrrp[8092]: (vrrp) Entering MASTER STATE
Apr 15 08:14:19 ubuntu Keepalived_vrrp[8092]: (vrrp) setting VIPs.
Apr 15 08:14:19 ubuntu Keepalived_vrrp[8092]: (vrrp) Sending/queueing Unsolicited Neighbour Adverts on ens4 for fd00::300:1
Apr 15 08:14:19 ubuntu Keepalived_vrrp[8092]: Sending unsolicited Neighbour Advert on ens4 for fd00::300:1
Apr 15 08:14:19 ubuntu Keepalived_vrrp[8092]: Sending unsolicited Neighbour Advert on ens4 for fd00::300:1
Apr 15 08:14:19 ubuntu Keepalived_vrrp[8092]: Sending unsolicited Neighbour Advert on ens4 for fd00::300:1
Apr 15 08:14:19 ubuntu Keepalived_vrrp[8092]: Sending unsolicited Neighbour Advert on ens4 for fd00::300:1
Apr 15 08:14:19 ubuntu Keepalived_vrrp[8092]: Sending unsolicited Neighbour Advert on ens4 for fd00::300:1
Apr 15 08:14:24 ubuntu Keepalived_vrrp[8092]: (vrrp2) Sending/queueing Unsolicited Neighbour Adverts on ens5 for fd00::200:1
Apr 15 08:14:24 ubuntu Keepalived_vrrp[8092]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:14:24 ubuntu Keepalived_vrrp[8092]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:14:24 ubuntu Keepalived_vrrp[8092]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:14:24 ubuntu Keepalived_vrrp[8092]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1
Apr 15 08:14:24 ubuntu Keepalived_vrrp[8092]: Sending unsolicited Neighbour Advert on ens5 for fd00::200:1

```

**Did keepalived coredump?**
none

**Additional context**
none

**Comment by louis-oui** [comment] 2021-04-15 10:47
It seems that https://github.com/acassen/keepalived/pull/1466/commits/9cef8085b5b7c6073a592488c29670bb55097497 has fixed IPv4 with vmac disabled but not IPv6

**Comment by louis-oui** [comment] 2021-04-19 16:34
In IPv6 case, link local is deassignated from ens5. down_instance(vrrp) is called at keepalived_netlink.c:1131

**Comment by louis-oui** [comment] 2021-04-19 16:54
down_instance(vrrp) is called there
					     if (ifp == (
#ifdef _HAVE_VRRP_VMAC_
							 vrrp->family == AF_INET ? VRRP_CONFIGURED_IFP(vrrp) :
#endif
							 vrrp->ifp) &&
						 vrrp->family == ifa->ifa_family &&
						 vrrp->saddr.ss_family != AF_UNSPEC &&
						 (!vrrp->saddr_from_config || is_tracking_saddr)) {
						down_instance(vrrp);
						vrrp->saddr.ss_family = AF_UNSPEC;
					}
				}

**Comment by louis-oui** [comment] 2021-04-19 17:17
Fix https://github.com/acassen/keepalived/pull/1896

**Comment by pqarmitage** [comment] 2021-04-19 18:00
Please see my comment against PR #1896. If there is no IPv6 address on the interface then keepalived cannot send adverts using an address that has been deleted.

**Comment by louis-oui** [comment] 2021-04-20 10:41
Hi @pqarmitage,

thank you for noticing me the different behaviours on IPv4 / IPv6 when link is set down. IPv6 addresses are flushed at link down, by default, whereas IPv4 one are kept.

There is a sysctl parameter to override that behaviour from kernel 4.6 : https://serverfault.com/a/843754 . To keep the IPv6 addresses at link down:
`echo 1 >/proc/sys/net/ipv6/conf/<interface>/keep_addr_on_down`

My tests showed that, with this setting, IPv6 addresses are kept except the link local address.

Another PR suggestion https://github.com/acassen/keepalived/pull/1898

**Comment by pqarmitage** [comment] 2021-04-26 08:43
I have added comments against your patch in PR #1898.

So far as I understand it you want to allow keepalived to continue sending VRRP adverts when its interface is down, using an IPv6 source address that has been deleted from the interface that the adverts are being sent on. We cannot allow that since we cannot send using a source address that is no longer configured on the system.

**Comment by louis-oui** [comment] 2021-04-26 11:05
Hi @pqarmitage,

the use-case is the same as https://github.com/acassen/keepalived/issues/1465 but with IPv4. I would like a direct link with a vrrp instance between the nodes to avoid having two MASTERs. This instance is a sync group.

On IPv4, dont_track_primary is configured on the direct link instance. If link state is down on ha link interface (because of other node down or link down), it avoids having the sync group into FAULT state on remaining or both nodes (depending on the case).

On IPv6, dont_track_primary is defeated because removing the link local address causes the FAULT state.

> So far as I understand it you want to allow keepalived to continue sending VRRP adverts when its interface is down, using an IPv6 source address that has been deleted from the interface that the adverts are being sent on. We cannot allow that since we cannot send using a source address that is no longer configured on the system.

We cannot send a VRRP advert via a down interface but we allow no FAULT state on IPv4 with dont_track_primary. Having no source address (because no more IPv6 link local) does not change anything. IPv6 link local will be added back when the interface goes back up and then VRRP advert will be sent normally.

> for IPv6 the kernel does not allow sending from an IP address that is not configured (but I may be wrong here).

I replied here: https://github.com/acassen/keepalived/pull/1898#discussion_r620193669

**Comment by pqarmitage** [comment] 2021-04-27 11:09
@louis-oui I have done some further testing and there is a difference between a link being administratively down (i.e. `ip link set ens5 down`) and a link being down due to it physically not being connected to another device. Therefore using `ip link set ens5 down` (or the obsolete `ifconfig ens5 down`) is not representative of the scenario you describe of not wanting to go to fault state if the other machine is rebooted.

With keepalived running, if you execute `ip link set ens5 down` then you will get EINVAL (error 22) returned from calling sendmsg(), since the link local address has been removed. However, if I simply disconnect the network cable from the interface, then although the interface is reported as down, the IPv6 addresses are not removed from the interface, sendmsg() does not return an error and with `dont_track_primary` configured the vrrp_instance remains in master state.

**Comment by louis-oui** [comment] 2021-04-27 15:47
Thank you @pqarmitage for the tests. It would be good if keepalived supports no FAULT state on IPv6 admin down with dont_track_primary. Then the behavior would be consistent with IPv4.

**Comment by pqarmitage** [comment] 2021-04-27 17:49
Keepalived does support no FAULT state on IPv6 admin down with dont_track_primary, and I give an example below. What keepalived cannot do is continue as master when there is no IPv6 address configured on the interface that it can use to send adverts.

In your keepalived configuration, add:
```
static_ipaddress {
        fd00::200:101/64 dev ens5
}
```
and also add `mcast_src_ip fd00::200:101` to the `vrrp_instance vrrp2` block.
Execute `echo 1 >/proc/sys/net/ipv6/conf/ens5/keep_addr_on_down`, then you will find that the vrrp instance will remain as master after `ip link set ens5 down` is executed (the `echo 1 >/proc/sys/net/ipv6/conf/ens5/keep_addr_on_down` command could be done in a `startup_script` and keep_addr_on_down could be set back to 0 in a `shutdown_script`). An easier solution would be to make the vrrp2 instance use IPv4 rather than IPv6; from your description of what you want to achieve I think that would work.

This shows that keepalived behaves consistently between IPv4 and IPv6, and that if a suitable address remains then keepalived will not go to fault state on interface down if `dont_track_primary` is configured.

The problem with this under normal circumstances is that since the interface is administratively down, both machines would want to become master. However, since you have the sync group, then vrrp_instance vrrp will control which instance is master.

I think what we need to do is enhance `dont_track_primary` so that if can differentiate between an interface being administratively down and the interface actually being down (e.g. network cable disconnected). Clearly keepalived will need to continue working as now, but there should be an option like `dont_track_primary real` which means that the vrrp instance will go to fault state if the interface is administratively down, but it won't go to fault state for a genuine network fault.

**Comment by louis-oui** [comment] 2021-04-28 08:24
> An easier solution would be to make the vrrp2 instance use IPv4 rather than IPv6

I agree with you. It is an easier solution.

> Clearly keepalived will need to continue working as now, but there should be an option like dont_track_primary real which means that the vrrp instance will go to fault state if the interface is administratively down, but it won't go to fault state for a genuine network fault.

I am wondering which use case would need to differentiate the admin_down state from the operational down state.
My opinion is that the patch is not complex. Even IPv4 dont_track_primary is a better option, it could benefit to keepalived users that configure IPv6 dont_track_primary without being aware of all those subtleties.

**Comment by pqarmitage** [comment] 2021-05-01 08:10
I will add the following to the keepalived.conf(5) man page:
```
    # Note: when using IPv6, setting the interface administratively down, e.g.
    #   'ip link set IF down' will by default cause all IPv6 addresses to be
    #   deleted from the interface, and consequently the VRRP instance will
    #   go to fault state due to the addresses being deleted. Setting sysctl
    #   net.ipv6.conf.IF.keep_addr_on_down to 1 will allow non link-local addresses
    #   to remain when the interface is downed.
```

**Comment by pqarmitage** [comment] 2021-05-03 16:45
Closing this issue, since keepalived is working as intended.

**Closed by pqarmitage** 2021-05-03 16:45 UTC
