### ISSUE TITLE
segfault once smtp_alert is set

### ISSUE THREAD

**Issue by Cugar15** [acassen/keepalived#336] opened 2016-05-19 12:33 UTC
Hi,

 I was trying to enable email notification. However, keepalived starts segfaulting in a loop..
If the smtp_alert statement is not present, everything seems to be normal.
Attached, you find:
1) Config
2) syslog with -D
3) backtrace

Hope this helps...
Cheers

```
global_defs {
    notification_email {
          my-email@doamin.de
        }
    notification_email_from keepalived_eb1@domain.de
    smtp_server localhost
}

vrrp_script chk_nginx {
    script "pidof nginx"
    interval 2
}

vrrp_instance VI_1 {
    interface eth0
    state BACKUP
    priority 100
    advert_int 5
    virtual_router_id 33
    unicast_src_ip xxxxxxxxxx
    unicast_peer {
        yyyyyyyyyyy
    }

#Need to look at this
    authentication {
        auth_type PASS
        auth_pass 192837465
    }

    track_script {
        chk_nginx
    }

    notify /etc/keepalived/backup.sh
    smtp_alert
    debug
}

```
```
May 19 14:18:11 178 Keepalived[29291]: Starting Keepalived v1.2.20 (05/15,2016)
May 19 14:18:11 178 Keepalived[29292]: Starting Healthcheck child process, pid=29294
May 19 14:18:11 178 Keepalived_healthcheckers[29294]: Initializing ipvs 2.6
May 19 14:18:11 178 Keepalived[29292]: Starting VRRP child process, pid=29295
May 19 14:18:11 178 Keepalived_healthcheckers[29294]: Setting base index for eth0 to ifi_index 2
May 19 14:18:11 178 Keepalived_healthcheckers[29294]: Registering Kernel netlink reflector
May 19 14:18:11 178 Keepalived_healthcheckers[29294]: Registering Kernel netlink command channel
May 19 14:18:11 178 Keepalived_healthcheckers[29294]: Opening file '/etc/keepalived/keepalived.conf'.
May 19 14:18:11 178 Keepalived_vrrp[29295]: Setting base index for eth0 to ifi_index 2
May 19 14:18:11 178 Keepalived_vrrp[29295]: Registering Kernel netlink reflector
May 19 14:18:11 178 Keepalived_vrrp[29295]: Registering Kernel netlink command channel
May 19 14:18:11 178 Keepalived_vrrp[29295]: Registering gratuitous ARP shared channel
May 19 14:18:11 178 Keepalived_vrrp[29295]: Opening file '/etc/keepalived/keepalived.conf'.
May 19 14:18:11 178 Keepalived_vrrp[29295]: Truncating auth_pass to 8 characters
May 19 14:18:11 178 kernel: [1928552.155449] show_signal_msg: 36 callbacks suppressed
May 19 14:18:11 178 kernel: [1928552.155455] keepalived[29295]: segfault at 7472 ip 00007f026fe66b92 sp 00007ffebdd49b90 error 4 in libc-2.13.so[7f026fe2f000+184000]
May 19 14:18:11 178 Keepalived_healthcheckers[29294]: Using LinkWatch kernel netlink reflector...
May 19 14:18:11 178 Keepalived[29292]: pid 29295 exited due to segmentation fault (SIGSEGV).
May 19 14:18:11 178 Keepalived[29292]:   Please report a bug at https://github.com/acassen/keepalived/issues
May 19 14:18:11 178 Keepalived[29292]:   and include this log from when keepalived started, what happened
May 19 14:18:11 178 Keepalived[29292]:   immediately before the crash, and your configuration file.
May 19 14:18:11 178 Keepalived[29292]: VRRP child process(29295) died: Respawning
May 19 14:18:11 178 Keepalived[29292]: Starting VRRP child process, pid=29312
May 19 14:18:11 178 Keepalived_vrrp[29312]: Setting base index for eth0 to ifi_index 2
May 19 14:18:11 178 Keepalived_vrrp[29312]: Registering Kernel netlink reflector
May 19 14:18:11 178 Keepalived_vrrp[29312]: Registering Kernel netlink command channel
May 19 14:18:11 178 Keepalived_vrrp[29312]: Registering gratuitous ARP shared channel
May 19 14:18:11 178 Keepalived_vrrp[29312]: Opening file '/etc/keepalived/keepalived.conf'.
May 19 14:18:11 178 Keepalived_vrrp[29312]: Truncating auth_pass to 8 characters
May 19 14:18:11 178 kernel: [1928552.213966] keepalived[29312]: segfault at 7472 ip 00007f026fe66b92 sp 00007ffebdd49b20 error 4 in libc-2.13.so[7f026fe2f000+184000]
May 19 14:18:11 178 Keepalived[29292]: pid 29312 exited due to segmentation fault (SIGSEGV).
May 19 14:18:11 178 Keepalived[29292]:   Please report a bug at https://github.com/acassen/keepalived/issues
May 19 14:18:11 178 Keepalived[29292]:   and include this log from when keepalived started, what happened
May 19 14:18:11 178 Keepalived[29292]:   immediately before the crash, and your configuration file.
May 19 14:18:11 178 Keepalived[29292]: VRRP child process(29312) died: Respawning
May 19 14:18:11 178 Keepalived[29292]: Starting VRRP child process, pid=29313

```

```
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/sbin/keepalived...done.
[New LWP 30155]

warning: Can't read pathname for load map: Input/output error.
Core was generated by `/usr/local/sbin/keepalived -D'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fdce0e55b92 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by pqarmitage** [comment] 2016-05-19 13:28
I'm not sure why commenting out the smtp_alert statement stops the seg fault, but it does that for me too.

The problem is actually with the debug statement, which expects in integer between 0 and 4 as a parameter. Changing the line to be
`debug 3`
stops the segfault.

Unfortunately, although the config parser seems to correctly parse any valid configuration, it isn't so good at detecting an invalid configuration, and will often segfault if a parameter is expected but is missing in the config. At some point I'm going to have a look at the parser to attempt to fix these problems.

In this instance, the output from gdb wasn't so helpful, since it was in a library function when it segfaulted. What would be helpful is if you posted the output from the bt command in gbd, since that will give us a stack backtrace.

Are you happy to close this issue report now?

**Comment by Cugar15** [comment] 2016-05-19 13:41
Hi,

   sure, I will close this issue. Just FYI, my intend is to help to get
this software stable and provide you guys enough pointers so you are able
to continue your great job.

I have 2 requests though:

1) I'm not familiar with gdb. Can you pls add to this thread how to
generate the backtrace?
    That will be certainly helpful / at least for me

2) The synopsis for the debug statement was taken out of:
    doc/keepalived.conf.SYNOPSIS

    I might be worth while to add the that there is a debug level.. this is
seems to be missing there:
     debug                                       # Debug level

Thanks for your support!!


2016-05-19 15:28 GMT+02:00 pqarmitage <notifications@github.com>:

**Closed** 2016-05-19 13:42 UTC

**Comment by pqarmitage** [comment] 2016-05-19 14:01
Many thanks for your issue reports, they are much appreciated, and indeed are helping keepalived improve.

To generate the stack backtrace in gdb at the gdb prompt, enter 'bt'. e.g.
(gdb) `bt`

I'll update keepalived.SYNOPSIS to correctly document the debug entry.

**Comment by Cugar15** [comment] 2016-05-19 14:12
Thanks... I'm still not clear about gdb - I was using:
   gdb /usr/local/sbin/keepalived -D core.dump
but I guess, I will figure this out...

Sorry to bother - I'm trying that keepalived sends me an email - without success. My smtp port is not standard 25. Is it possible to spec in the configfile:

smtp_server localhost:1234

The configfile is parsed ok - no segfautl :). However, it's not sending email on a state transition...
Did I understand this feature wrongly?

Cheers!

**Comment by pqarmitage** [comment] 2016-05-19 15:09
When you are analysing a core dump, you don't specify the command line of the program to gdb, so the syntax is
`gdb /usr/local/sbin/keepalived core.dump`

gdb should then give you a prompt:
`(gdb)`
and at that prompt, you type:
`bt`

I'll see if I can add an option for specifying the smtp_server port.

**Comment by pqarmitage** [comment] 2016-05-19 15:49
I've added an optional parameter to smtp_server, for specifying the port. The syntax is:
`smtp_server localhost port`

It wouldn't work using a ':' if the smtp_server were specified with an IPv6 address.

**Comment by Cugar15** [comment] 2016-05-19 16:01
ahh - thanks for the gdb pointer! Now it's clear...

For smpt, I was wondering about the following:
Usually, from what I know, the following minimum information is needed to make smpt work:

server, port, email (account) and respective password

without this information, you can only use an open relay smtp server - or i.e localhost, which is configured to send email without authentication...

Not sure how keepalived is dealing with email....

Cheers and thanks again...

**Comment by Cugar15** [comment] 2016-05-20 12:46
Verified that the new option to specify a port for smtp_server works:

smtp_server localhost port

Thanks!
