### ISSUE TITLE
Healthcheck child process(1547) died: Respawning(CentOS7.3-keepalived1.4.2)

### ISSUE THREAD

**Issue by yuweiming2016** [acassen/keepalived#910] opened 2018-06-11 12:20 UTC
i try to install keepalived1.4.2 in centos7.3. when i start it ,the error message can't stop.
the message as follow:
![image](https://user-images.githubusercontent.com/22490427/41230944-2179e15e-6db4-11e8-97e6-8e5839105a87.png)
![image](https://user-images.githubusercontent.com/22490427/41230970-354bfc94-6db4-11e8-9372-23d9d8739525.png)

![image](https://user-images.githubusercontent.com/22490427/41230798-af6dc0b2-6db3-11e8-904d-09929c44763c.png)
and the config file as follow:
![image](https://user-images.githubusercontent.com/22490427/41230879-ece75a34-6db3-11e8-8e13-9a6f8482ffe2.png)
[messages.zip](https://github.com/acassen/keepalived/files/2089883/messages.zip)

it is a real bug or just my problem?

**Comment by yuweiming2016** [comment] 2018-06-11 13:29
by the way,the configuare result as follow:
![image](https://user-images.githubusercontent.com/22490427/41234298-5ba988e8-6dbe-11e8-83c0-606dbdda462e.png)

and make result have an warnning:
![image](https://user-images.githubusercontent.com/22490427/41234376-936a16da-6dbe-11e8-84f0-e3fbd56c9731.png)

**Comment by pqarmitage** [comment] 2018-06-11 13:38
I can reproduce the problem. I think it is caused by all the entries in the notification_email being commented out. Can you try commenting out the `notification_email {` and the following '}' lies as well.

**Comment by pqarmitage** [comment] 2018-06-11 13:42
The warnings are due to the version of gcc you have being oldish and it not being so good at detecting the initialisation of variables within conditions. More recent versions of gcc do not report these warning.

**Comment by pqarmitage** [comment] 2018-06-11 14:10
This issue was fixed by commit 707e213, which was first included in keepalvied v1.4.4. If you are upgrading keepalived you may as will upgrade to 1.4.5 or even v2.0.2.

**Closed by pqarmitage** 2018-06-11 14:10 UTC

**Comment by yuweiming2016** [comment] 2018-06-11 14:14
@pqarmitaoge ,it works for me! thanks you very much
