### ISSUE TITLE
Problem with use_vmac option in keepalived 1.3.2 on Debian Stretch

### ISSUE THREAD

**Issue by florentfillion** [acassen/keepalived#1040] opened 2018-10-18 17:27 UTC
Hi all,

I'm using keepalived version 1.3.2 in Debian Stretch to achieve VRRP functionality with two routers, one in MASTER mode and another in BACKUP mode.

I have a problem with use_vmac option.
When use_vmac option is disabled, it's works good, only MASTER router receive network traffic with virtual IP address. The BACKUP router is in standby and doesn't receive network traffic.

However when use_vmac option is enabled, BOTH routers (MASTER AND BACKUP) receive network traffic via the virtual IP address.
The virtual IP address is not assigned on the VMAC interface on BACKUP router (fortunately) but it also seems be active : VMAC interface and physical interface on BACKUP router receive network traffic but only the MASTER router handle it.
The network traffic is sent to both routers which is useless for the BACKUP router because that consume bandwidth.

My VRRP configuration is it correct ? Or is it a know issue ?
Thanks for your help.

Here is my VRRP and network configuration on both routers :

#################
# MASTER ROUTER #
#################
# ifconfig
ens256: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.1.1.2  netmask 255.128.0.0  broadcast 10.127.255.255
        ether 00:50:56:8c:3d:88  txqueuelen 1000  (Ethernet)
        RX packets 1681  bytes 172338 (168.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 21655  bytes 1285146 (1.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vrrp12: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.1.1.1  netmask 255.128.0.0  broadcast 0.0.0.0
        ether 00:00:5e:00:01:0c  txqueuelen 1000  (Ethernet)
        RX packets 76  bytes 5856 (5.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 20  bytes 840 (840.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

# ip route
10.0.0.0/9 dev ens256 proto kernel scope link src 10.1.1.2
10.0.0.0/9 dev vrrp12 proto kernel scope link src 10.1.1.1

# keepalived.conf :
global_defs {
        notification_email {
                XXXX
        }
        notification_email_from XXXXX
        smtp_server XXXXXX XXX
        smtp_connect_timeout 30
        router_id RTR-01
}

vrrp_instance XXX {
        state MASTER
        interface ens256
        virtual_router_id 12
        priority 200
        advert_int 1
        #nopreempt
        #smtp_alert
        use_vmac vrrp12
        vmac_xmit_base
        authentication {
                auth_type PASS
                auth_pass XXX
        }
        virtual_ipaddress {
                10.1.1.1/9
        }
        notify "/etc/keepalived/vrrp-state.sh"
        notify_master "/etc/keepalived/vmac_tweak.sh vrrp12"
}

#################
# BACKUP ROUTER #
#################
# ifconfig
ens256: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.1.1.3  netmask 255.128.0.0  broadcast 10.127.255.255
        ether 00:50:56:8c:77:c8  txqueuelen 1000  (Ethernet)
        RX packets 16777  bytes 1008482 (984.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 77  bytes 5762 (5.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vrrp12: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 00:00:5e:00:01:0c  txqueuelen 1000  (Ethernet)
        RX packets 1271  bytes 116842 (114.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 30  bytes 1260 (1.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

# ip route
10.0.0.0/9 dev ens256 proto kernel scope link src 10.1.1.3

# keepalived.conf :
global_defs {
        notification_email {
                XXXXXX
        }
        notification_email_from XXXXX
        smtp_server XXXXX XXX
        smtp_connect_timeout 30
        router_id RTR-02
}

vrrp_instance XXX {
        state BACKUP
        interface ens256
        virtual_router_id 12
        priority 100
        advert_int 1
        #nopreempt
        #smtp_alert
        use_vmac vrrp12
        vmac_xmit_base
        authentication {
                auth_type PASS
                auth_pass XXX
        }
        virtual_ipaddress {
                10.1.1.1/9
        }
        notify "/etc/keepalived/vrrp-state.sh"
        notify_master "/etc/keepalived/vmac_tweak.sh vrrp12"
}

The vmac_tweak.sh script contains these sysctl options :
net.ipv4.conf.$1.arp_filter = 0
net.ipv4.conf.$1.accept_local = 1
net.ipv4.conf.$1.rp_filter = 0

I also created a file /etc/sysctl.d/vrrp.conf which these sysctl options :
net.ipv4.conf.all.arp_ignore = 1
net.ipv4.conf.all.arp_ignore = 1
net.ipv4.conf.all.arp_filter = 0
net.ipv4.conf.ens256.arp_filter = 1

**Comment by acassen** [comment] 2018-10-18 18:52
Hi, release 1.3.2 is deprecated, please consider upgrading to the last stable release available on website or pull current master branch on git repo.

regs,
Alexandre

**Comment by pqarmitage** [comment] 2018-10-18 23:12
A few pointers that may help you (they apply to both v1.3.2 and the latest version):

1. keepalived sets arp_ignore, arp_filter, accept_local and rp_filter as needed, so you don't need to use scripts to do it.
2. Try without `vmac_xmit_base`
3. Since ens256 has ip address 10.1.1.n/9, the subnet already exists, so the virtual_ipaddress should not duplicate the subnet, and should be 10.1.1.1/32 (/32 is the default so it can be omitted). I remember that getting this wrong used to cause problems, but I think more recent versions of keepalived don't have the same problem. 
4. Using `ip addr show` and `ip link show`, possibly with the `-d` option gives more useful information than ifconfig.
5. Executing `kill -USR1 $(cat /var/run/keepalived.pid)` will create a file /tmp/keepalived.data, which will show the state of the vrrp process. It can be worth doing this on both the master and backup systems to see what they are doing.
6. If the address 10.1.1.1 is not configured on the backup system, it shouldn't be receiving packets addressed to 10.1.1.1. If it is receiving packets addressed to 10.1.1.1 when the address is not configured on the system, then it would appear to be more likely that it is a kernel issue; keepalived manages the addresses, it doesn't otherwise control what is received on the system.

There have been over 1500 non merge commits since v1.3.2. We just can't remember what fixes have been included in that number of commits, but certainly a large number of issues have been resolved in the latest version compared to v1.3.2. It is always worth upgrading to the latest version.

**Comment by florentfillion** [comment] 2018-10-19 09:16
Thank you for your response.

I applied the pointers 2 and 3, no changes.
I will try to install the latest stable version.
The latest version is 2.0.7, is it compatible and stable for my linux kernel version ? (Debian Stretch)

uname -a : 
Linux RTR-01 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

**Comment by pqarmitage** [comment] 2018-10-19 09:53
We aim to support all kernel versions back to at least 2.6.15, so as far as is known keepalived should be stable on a 4.9 kernel.

**Comment by florentfillion** [comment] 2018-10-26 15:21
Hi, after applied the pointers 1,2,3 and installed the latests versions (2.0.7 and then 2.0.8), same problem, the BACKUP router receives packets addresses to 10.1.1.1 and others (any traffic passing through MASTER router).
Note that when keepalived process starts on the BACKUP router, the line "(GEST) removing VIPs." doesn't appear in journalctl (GEST is the instance which using use_vmac option).
When use_vmac option is disable, "(GEST) removing VIPs." appears in journalctl on the BACKUP router (see the journalctl result in attached file).

       +==========+                                                  +===========+
        | Router 1(RTR-01) |----------VMware ESXi----------| Router 2(RTR-02) |
       +==========+                                                   +==========+
                10.1.1.2                                    |                                 10.1.1.3
                MASTER                                 VIP                               BACKUP	
                                                           10.1.1.1
                                                                |
                                                                |
                                                                |
                                                                |
                                                        +======+
                                                        | VM test 1 |
							| 10.1.1.20  |
                                                        +======+

In attached file, the result of traffic capture when "VM test 1" runs ping to 10.1.1.1.
As you can see, the BACKUP router also receives icmp packet and transmits it to MASTER router, that cause duplicate traffic (ICMP request/reply are sent twice when use_vmac enable).

See also network configuration (ip -d addr show, ...) and keepalived.data file of both routers in attached files.

Regards,

[journalctl.txt](https://github.com/acassen/keepalived/files/2519737/journalctl.txt)
[keepalived-conf.txt](https://github.com/acassen/keepalived/files/2519738/keepalived-conf.txt)
[keepalived-data.txt](https://github.com/acassen/keepalived/files/2519739/keepalived-data.txt)
[network-conf.txt](https://github.com/acassen/keepalived/files/2519740/network-conf.txt)
[ping-capture.txt](https://github.com/acassen/keepalived/files/2519741/ping-capture.txt)

**Comment by pqarmitage** [comment] 2018-10-26 19:33
The difference in the journal between non vmac mode and vmac mode is that when you use vmac mode, you get the following log entry:
`oct. 26 14:52:59 RTR-02 kernel: device ens256 entered promiscuous mode`
I don't know why this is happening, but my guess is that because ens256 is in promiscuous mode, RTR-02 receives the ICMP echo request to 10.1.1.1, and it then forwards the packet to 10.1.1.1.

Do you know what is setting ens256 to promiscuous mode? I don't observe that on my systems. If you try the following commands on RTR-02 to manually create a vmac interface, can you check the journal to see if the interface is being set to promiscuous mode (and also post the output of the `ip -d link show test-promisc` command:
```
ip link add link ens256 test-promisc type macvlan mode private
ip link set test-promisc up
sleep 1
ip -d link show ens256
ip link del test-promisc
```

You could try manually turning off promiscuous mode on ens256:
`ip link set ens256 promisc off`
and see if that stops RTR-02 forwarding the ICMP echo requests to RTR-01

You could try, without running keepalived, manually creating and configuring the macvlan interfaces on RTR-01 and RTR-02 to match the configuration that keepalived creates, and see if you get the duplicate ICMP echo replies.

If you can provide the contents of each file in /proc/sys/net/ipv4/conf/all and /proc/sys/net/ipv4/conf/ens256 and /proc/sys/net/ipv4/conf/vrrp12 (when you are using a vmac) then we might be able to see something.

At [https://askubuntu.com/questions/430355/configure-a-network-interface-into-promiscuous-mode](https://askubuntu.com/questions/430355/configure-a-network-interface-into-promiscuous-mode) it states that VMware always sets virtual interfaces to promiscuous mode, and so that might be the cause of the problem.

**Comment by pqarmitage** [comment] 2018-11-02 16:14
@florentfillion Do you have any updates on this or can we close the issue?

**Comment by pqarmitage** [comment] 2018-11-19 12:32
Closing due to no response for over 2 weeks. If you have any updates on this issue, please add them to this issue report and we can reopen the issue if necessary.

**Closed by pqarmitage** 2018-11-19 12:32 UTC
